// Арабский
const ar = {
    'mainBlock#1': 'الاستفادة من الاستثمار في العملات المشفّرة بسهولة ',
    'mainBlock#2': 'وأمان وسرعة',
    'mainBlock#3': 'انضم إلى فعاليات طرح عملاتنا الرمزية المؤمَّنة للبيع',

    'icoInfo#1': 'نقبل ما يلي:',
    'icoInfo#2': 'الحد الأقصى: 21 مليون دولار',
    'icoInfo#3': 'مرحلتا الحد الأدنى:',
    'icoInfo#4': 'يتم توقيع اتفاقات التسجيل مع ',

    'menu#1': 'المستند التقني ',
    'menu#2': 'العرض التقديمي',
    'menu#3': 'نظرة عامة ',
    'menu#4': 'النموذج المالي ',
    'menu#5': 'المستندات القانونية',
    'menu#6': 'AR',
    'menu#7': 'المنتج',
    'menu#8': 'تفاصيل حدث البيع',
    'menu#9': 'فريق العمل',
    'menu#10': 'المستندات العامة',
    'menu#11': 'اختبار الإصدار الأساسي للمنتج ',

    'mailForm#1': 'Wrong email',
    'mailForm#2': 'sending ..',
    'mailForm#3': 'Already was or is not valid, try again',
    'mailForm#4': 'Your email has been sent successfully',
    'mailForm#5': 'an error occurred, try again',
    'mailForm#6': 'GDRP Сompliance',
    'mailForm#7': 'Personal data provided via Subscription form and KYC procedure will be collected in the full compliance with GDRP',
    'mailForm#8': 'The Data Protection Officer  of the project is  Mrs. Sofja Pevzner-Belositski. Contact details: dpo@cindx.io. Any data subject may, at any time, contact Data Protection Officer of directly with any request related to data protection.',
    'mailForm#9': 'Your personal data provided via Subscription form and KYC procedure will be shared to our partners:',
    'mailForm#10': 'ICO Promo',
    'mailForm#11': 'Privacy Policy',
    'mailForm#12': 'Sum & Substance',
    'mailForm#13': 'By default, the personal data provided by subscriber are kept by CINDX, ICO Promo and Sum & Substance for 5 years after registration of subscriber in the system',
    'mailForm#14': 'If you do not agree to this privacy policy, please do not use our site.',
    'mailForm#15': 'By using our site, you consent to the collection and use of information by us. Owing to the global nature of the internet infrastructure, the information you provide may be transferred in transit to countries outside the European Economic Area that do not have similar protections in place regarding your data and its use as set out in this policy.',
    'mailForm#16': 'However, we have taken the steps outlined above to try to improve the security of your information. By submitting your information you consent to these transfers',
    'mailForm#17': 'I agree to process my',
    'mailForm#18': 'personal data',
    'mailForm#19': 'Security Token Sale Starts with',
    'mailForm#20': '25% BONUS',
    'mailForm#21': 'Get it before everyone else does',
    'mailForm#22': 'Token sale starts in',
    'mailForm#23': 'Start from $1',
    'mailForm#24': '1$ later',
    'mailForm#25': 'عنوان بريدك الإلكتروني ',
    'mailForm#26': 'الانضمام إلى فعاليات الطرح الأولي ',
    'mailForm#27': 'AGREE & SUBMIT',

    'progressBarSale#1': 'مكافآت البيع ',
    'progressBarSale#2': 'CINX في',
    'progressBarSale#3': 'الطرح الأولي',
    'progressBarSale#4': 'تخفيض السعر',
    'progressBarSale#5': '26 أغسطس',
    'progressBarSale#6': '17 سبتمبر',
    'progressBarSale#7': '8 أكتوبر',
    'progressBarSale#8': '22 أكتوبر',
    'progressBarSale#9': '6 نوفمبر',
    'progressBarSale#10': '19 نوفمبر',
    'progressBarSale#11': '3 ديسمبر',
    'progressBarSale#12': '17 ديسمبر',

    'cryptoAssetsManagement#1.1': 'تُعد CIDNX مركزًا لإدارة سندات العملات المشفّرة. نحرص على حل المشكلات التي يواجهها المستثمرون والمتداولون والمطوّرون ',
    'cryptoAssetsManagement#1.2': '',
    'cryptoAssetsManagement#2': 'CINDX.MARKETPLACE للمستثمرين ',
    'cryptoAssetsManagement#3': 'لا تقلق بشأن مدى معرفتك وخبراتك، فخبراء تداول العملات المشفّرة هنا لمساعدتك',
    'cryptoAssetsManagement#4': 'تحكّم في أموالك المشفّرة، واضمن وجود عملاتك بحوزتك في جميع الأوقات',
    'cryptoAssetsManagement#5': 'لن تدفع إلا عندما تربح، فسيتم تحصيل الرسوم المطلوبة منك إذا حقّقت محفظتك الاستثمارية أرباحًا فقط',
    'cryptoAssetsManagement#6': 'اختبار الإصدار الأساسي للمنتج ',
    'cryptoAssetsManagement#7': 'CINDX.TERMINAL للمتداولين ',
    'cryptoAssetsManagement#8': 'إذا كنت متداولاً ناجحًا، فيمكنك جذب رؤوس الأموال بدون الاضطرار إلى الاستثمار في التسويق ',
    'cryptoAssetsManagement#9': 'سنزوّدك بمنصة ومتجر للتطبيقات وسوق وغيرها من الأدوات المتطوّرة لمساعدتك على التداول بنجاح ',
    'cryptoAssetsManagement#10': 'تساعدك CINDX على تحويل سُمعتك وخبراتك إلى نقود. ونضمن شفافية سجل التداول الخاص بك وتأثيرك في هذا المجال. ',
    'cryptoAssetsManagement#11': 'CINDX.TALK وCINDX.HUB وCINDX.DAO',
    'cryptoAssetsManagement#12': 'CINDX.Talk - إحدى شبكات التواصل الاجتماعي التي تمنحك مكافأة في حالة إضافة محتوى مفيد ',
    'cryptoAssetsManagement#13': 'CINDX.Hub - تشتمل أدواتنا على "ملف المورّد"، بالإضافة إلى مركز لاختبار برامج الأطراف الثالثة ودمجها ',
    'cryptoAssetsManagement#14': 'CINDX.dao - أداة تسمح لك بتطبيق نظام تصويت لمجتمع المستخدمين استنادًا إلى قواعد تنظيمية ذاتية لامركزية',

    'teamLegal#1': 'لدينا فريق عمل رائع ومستشارون قانونيون محترفون ',
    'teamLegal#2': '',
    'teamLegal#3': 'CRYPTOCURRENCY EXCHANGE LICENSE',
    'teamLegal#4': 'FINANCIAL INSTITUTION LICENSE',
    'teamLegal#5': 'CRYPTO WALLET LICENSE',
    'teamLegal#6': 'WHITEPAPER',
    'teamLegal#7': 'PRESENTATION',
    'teamLegal#8': 'ONE PAGER',
    'teamLegal#9': 'FINANCIAL MODEL',
    'teamLegal#10': 'LEGAL DOCS',

    'roadmap#1': 'خارطة الطريق ',
    'roadmap#2': 'سيناريو',
    'roadmap#3': 'We are building the base for the CINDX platform. At this step, the Minimum Viable Product (MVP) is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform.',
    'roadmap#4': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be  going through some alterations to add functionalities.  ',
    'roadmap#5': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services.      ',
    'roadmap#6': 'At this stage, the CINDX.market and CINDX.trade components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. ',
    'roadmap#7': 'CINDX.talk will have public and private channels. At this stage, the content will  be able to be  separated. ',
    'roadmap#8': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade is an extremely flexible system of order execution and risk management. The Vendor’s market will appear; however, at this point, the Vendor’s market will only contain applications developed by CINDX and its partners.  ',
    'roadmap#9': 'A tokenized rating system will be added in the final version of CINDX.talk, as well as a new type of product: “algorithmic trading”. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders.   ',
    'roadmap#10': 'We are building the base for the CINDX platform. At this step, the MVP is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform. ',
    'roadmap#11': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be going through some alterations to add functionalities.  ',
    'roadmap#12': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services. Another new component, CINDX.hub, will enable Vendors to develop applications that will analyze the market data that CINDX provides. ',
    'roadmap#13': 'At this stage, the CINDX.market and CINDX.trade components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. An SDK for developers will be released. This should simplify application development and implementation for CINDX.  ',
    'roadmap#14': 'CINDX.talk will have public and private channels. At this stage, the content will be able to be separated. CINDX.hub will integrate Github, which will simplify application development even more.',
    'roadmap#15': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade will be an extremely flexible system of order execution and risk management. CINDX.hub will have a full-scale editor for trading strategies with a testing system based on historical market data.',
    'roadmap#16': 'A tokenized rating system  CINDX.talk will be added in the final version of CINDX.talk. This will provide a system of assessment for CINDX community trading experts. “Algorithmic trading” will also be added. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders. A high-grade platform for a code audit will be created. ',
    'roadmap#17': 'We are building the base for the CINDX platform. At this step, the MVP is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform.',
    'roadmap#18': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be  going through some alterations to add functionalities. ',
    'roadmap#19': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services. Another new component,  CINDX.hub, will enable Vendors to develop applications that will analyze the market data that CINDX provides. The team will develop CINDX.dao, a component that acts as a system for the platform’s revenue distribution to its token holders.       ',
    'roadmap#20': 'At this stage, the CINDX.market and CINDX.trade  components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. An SDK for developers will be released. This should simplify application and implementation development for CINDX.  ',
    'roadmap#21': 'CINDX.talk will have public and private channels. At this stage the content can be separated. CINDX.hub will integrate Github which will simplify application development even more.',
    'roadmap#22': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade will be an extremely flexible system of order execution and risk management. CINDX.hub has a full-scale editor for trading strategies with a testing system based on historical market data. CINDX.dao will receive a voting system for token holders. ',
    'roadmap#23': 'A tokenized rating system CINDX.talk will be added in the final version of CINDX.talk. This will provide a system of assessment for CINDX community trading experts. “Algorithmic trading” will also be added. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders. A high-grade platform for a code audit will be created. ',

    'problemSolving#1': 'الوقت ',
    'problemSolving#2': 'الثقة ',
    'problemSolving#3': 'الحيرة ',
    'problemSolving#4': 'لديّ بعض المال الذي أريد استثماره في مجال العملات المشفّرة ولكني لا أملك الوقت اللازم لإجراء الأبحاث الأساسية والاتصال بالمتداولين المحترفين لإدارة محفظتي الاستثمارية',
    'problemSolving#5': 'لطالما غمرني شعور بعدم الارتياح عند تصوُّر فكرة قيام شخص آخر بإدارة أموالي لتحقيق أرباح منها',
    'problemSolving#6': 'أعتقد أن تقنيات تداول العملات المشفّرة صعبة الاستخدام. لذا، لا يسعني فهم كيف يمكنني تداول عملاتي',
    'problemSolving#7': 'تزوّد CINDX عملاءها بإمكانية الوصول إلى متداولين ذوي تصنيفات عالية وجديرين بالثقة ',
    'problemSolving#8': 'لن تفترق عن أموالك أبدًا مع منصة CINDX ',
    'problemSolving#9': 'ستحقق الربح دائمًا مع أفضل المتداولين في السوق',
    'problemSolving#10': 'يتم تصنيف المتداولين على منصة CINDX وفقًا لسجّل صفقات التداول الناجحة لديهم. اختر المتداول الذي يلبي احتياجاتك بسرعة',
    'problemSolving#11': 'يسمح لك نظامنا اللامركزي وميزة العقود الذكية لدينا بإدارة أموالك بدون نقلها إلى أحد المتداولين',
    'problemSolving#12': 'يحظى كل مستثمر على منصة CINDX بفرصة إدارة أمواله بواسطة أكثر المتداولين نجاحًا في السوق',
    'problemSolving#13': 'ما أنواع المشكلات التي تحلها CINDX؟?',
    'problemSolving#14': 'اختبار الإصدار الأساسي للمنتج ',

    'howCindxWorks#1': 'المستثمرون ',
    'howCindxWorks#2': 'المتداولون ',
    'howCindxWorks#3': 'المورّدون ',
    'howCindxWorks#4': 'يعملون على زيادة أرباحهم من العملات المشفّرة من خلال الاستعانة بمهارات إدارة المحافظ الاستثمارية التي يتمتع بها أفضل المتداولين',
    'howCindxWorks#5': 'يربحون عمولات من المستثمرين وفقًا لأدائهم وإستراتيجيات التداول الخاصة بهم',
    'howCindxWorks#6': 'يبيعون أدوات متطوّرة للتداول، مثل روبوتات التداول والتطبيقات المصغّرة للأخبار',
    'howCindxWorks#7': 'تجمع العمولات ورسوم الاشتراك',
    'howCindxWorks#8': 'أريد الانضمام إلى منصة CINDX بالاستعانة بسندات العملات المشفّرة التي أريد تداولها',
    'howCindxWorks#9': 'أريد الانضمام إلى منصة CINDX لتقديم خبرتي في التداول التي ستفيد المستثمرين',
    'howCindxWorks#10': 'أريد الانضمام إلى منصة CINDX لتقديم تطبيقات التداول التي ستساعد المستثمرين',
    'howCindxWorks#11': 'نحن هنا لجعل تجربة التداول سهلة وآمنة ومربحة',
    'howCindxWorks#12': 'كيف تعمل منصة CINDX بإيجاز ',

    'marketAnalytics#1': 'تحليلات السوق ',
    'marketAnalytics#2': 'السندات العالمية الخاضعة للإدارة ',
    'marketAnalytics#3': 'الاستثمار ',
    'marketAnalytics#4': 'نمو رأس المال ',
    'marketAnalytics#5': 'منذ عام 2000، نما سوق إدارة الثروات العالمية بنسبة تزيد عن 250%.',
    'marketAnalytics#6': ' ويُعد هذا النمو نتيجة التحسينات المستمرة في أدوات السوق والتطوير العام لبِنى السوق.',
    'marketAnalytics#7': 'على الرغم من النمو الهائل الذي شهده سوق العملات المشفّرة في عام 2017، لا يزال هذا المجال في طور النشوء.',
    'marketAnalytics#8': 'فلقد بلغت القيمة السوقية الإجمالية 600 مليار دولار في نهاية عام 2017، أي ما يعادل 1% فقط من إجمالي القيمة السوقية لقطاع إدارة الثروات.',
    'marketAnalytics#9': 'المستند التقني ',
    'marketAnalytics#10': 'العرض التقديمي',
    'marketAnalytics#11': 'نظرة عامة ',
    'marketAnalytics#12': 'النموذج المالي ',
    'marketAnalytics#13': 'المستندات القانونية',
    'marketAnalytics#14': 'إحصائيات عامة ',
    'marketAnalytics#15': '25 محفظة محتملة على شبكة البلوك تشين',
    'marketAnalytics#16': '',
    'marketAnalytics#17': '200000 معاملة محتملة كل يوم',
    'marketAnalytics#18': '',
    'marketAnalytics#19': 'أكثر من 225 شريكًا محتملاً، ونصيب كل منهم من 3 إلى 5 مليارات دولار',
    'marketAnalytics#20': '',

    'tokenSaleDetails#1': 'تخصيص العملات الرمزية ',
    'tokenSaleDetails#2': 'فريق العمل ',
    'tokenSaleDetails#3': 'المكافآت ',
    'tokenSaleDetails#4': 'المستشارون',
    'tokenSaleDetails#5': 'الاحتياطي ',
    'tokenSaleDetails#6': 'مِنَح مجتمع المستخدمين ',
    'tokenSaleDetails#7': 'دعم سيولة العملات الرمزية',
    'tokenSaleDetails#8': 'التوفّر للبيع ',
    'tokenSaleDetails#9': 'اسم العملة الرمزية: CINX',
    'tokenSaleDetails#10': 'تاريخ بدء الطرح الأولي للعملات الرمزية: 26 أغسطس 2018',
    'tokenSaleDetails#11': 'الإصدار الكلي من العملات الرمزية: 51500000 عملة CINX ',
    'tokenSaleDetails#12': 'السعر لكل عملة رمزية: دولار واحد',
    'tokenSaleDetails#13': 'CINXO = عملة CINX واحدة',
    'tokenSaleDetails#14': 'الحد الأدنى للاستثمار: ما يعادل 50 دولارًا ',
    'tokenSaleDetails#15': 'المستند التقني ',
    'tokenSaleDetails#16': 'العرض التقديمي',
    'tokenSaleDetails#17': 'نظرة عامة ',
    'tokenSaleDetails#18': 'النموذج المالي ',
    'tokenSaleDetails#19': 'المستندات القانونية ',
    'tokenSaleDetails#20': 'استخدام العائدات ',
    'tokenSaleDetails#21': '21% التسويق والعلاقات العامة ',
    'tokenSaleDetails#22': '41% الأبحاث والتطوير ',
    'tokenSaleDetails#23': '28 العمليات % ',
    'tokenSaleDetails#24': '7% المصروفات القانونية',
    'tokenSaleDetails#25': '3% مكافأة المتداولين ',
    'tokenSaleDetails#26': 'صفقات العملات الرمزية ',
    'tokenSaleDetails#27': 'بيع العملات الرمزية ',
    'tokenSaleDetails#28': 'مكافآت الطرح الأولي للعملات الرمزية ',
    'tokenSaleDetails#29': '26 أغسطس - 16 سبتمبر - 25 ٪ مكافأة',
    'tokenSaleDetails#30': '17 سبتمبر - 7 أكتوبر - مكافأة 20 ٪',
    'tokenSaleDetails#31': 'مكافآت البيع الرئيسي للعملات الرمزية ',
    'tokenSaleDetails#32': 'من 8 أكتوبر إلى 21 أكتوبر: مكافأة بنسبة 17%',
    'tokenSaleDetails#33': 'من 22 أكتوبر إلى 4 نوفمبر: مكافأة بنسبة 15%',
    'tokenSaleDetails#34': 'من 5 نوفمبر إلى 18 نوفمبر: مكافأة بنسبة 13%',
    'tokenSaleDetails#35': 'من 19 نوفمبر إلى 2 ديسمبر: مكافأة بنسبة 10%',
    'tokenSaleDetails#36': 'من 3 ديسمبر إلى 16 ديسمبر: مكافأة بنسبة 5%',
    'tokenSaleDetails#37': ' من 17 ديسمبر إلى 26 ديسمبر: لا توجد مكافأة ',
    'tokenSaleDetails#38': 'شراء العملات الرمزية ',
    'tokenSaleDetails#39': 'تفاصيل بيع العملات الرمزية ',
    'tokenSaleDetails#40': 'During the token sale, investors purchase utility tokens – options [CINXO], which give them the right to receive security tokens [CINX] in the future.',
    'tokenSaleDetails#41': 'Security tokens [CINX] will be issued and distributed following the prospect of emission published on the website of FSA of Estonia https://www.fi.ee/ and cindx.io after the end of the token sale, but no later than Q1 2019.',
    'tokenSaleDetails#42': 'The holder of [CINXO] tokens has the right but no obligation to exchange options for security tokens with a ratio of 1:1 after completing the KYC procedure with identification signature, address confirmation and supply of other documents (see the KYC diagram).',
    'tokenSaleDetails#43': 'Tokens [CINXO] grant the same rights as security tokens apart from the right to participate in revenue distribution with a lock-up and voting on the platform.',

    'legalSchedule#1': 'جدول الإجراءات القانونية ',
    'legalSchedule#2': 'RECEIVED LICENSE (FVR000110) TO EXCHANGE VIRTUAL CURRENCY TO FIAT SERVICES',
    'legalSchedule#3': 'APPLIED FOR TRADEMARK REGISTRATION IN ESTONIA AND EU',
    'legalSchedule#4': 'LICENSE FFA000254 FOR OPERATING AS A FINANCIAL INSTITUTION',
    'legalSchedule#5': 'RECEIVED LICENSE FFA000254 FOR OPERATING AS A FINANCIAL INSTITUTION',
    'legalSchedule#6': 'WORKED OUT PROSPECTUS IN ACCORDANCE WITH ESTONIAN LAW',
    'legalSchedule#7': 'CLAIMED FSA LICENSE (ESTONIAN FINANCIAL SUPERVISION AUTHORITY)',
    'legalSchedule#8': 'RECEIVED LICENSE FOR PROVIDING A VIRTUAL CURRENCY WALLET SERVICE',
    'legalSchedule#9': 'REGISTERED UNDER EXEMPTION D IN SEC',
    'legalSchedule#10': 'APPOINTED A PERSONAL DATA MANAGER TO MEET GDPR REQUIREMENTS',
    'legalSchedule#11': 'RECEIVED THE FSA LICENSE',
    'legalSchedule#12': 'REGISTERED THE PROSPECTUS EU 809-2004',
    'legalSchedule#13': 'ISSUED CINX SECURITY TOKENS',

    'feedbackProject#1': 'ملاحظات على مشروعنا ',
    'feedbackProject#2': 'فال جيرديس ',
    'feedbackProject#3': 'مدير المنتجات ',
    'feedbackProject#4': 'يتحدّث فال جيرديس، مدير منتجات CINDX، عن الأعضاء الأساسيين بفريق العمل ودور الخبرات المتعددة التي يتمتع بها هذا الفريق في المساعدة على تطوير المشروع الذي يمكنه تغيير المجال المالي بطريقة كبيرة ',
    'feedbackProject#5': 'دينيس إسكينازي ',
    'feedbackProject#6': 'مدير تسويق المنتجات ',
    'feedbackProject#7': 'يشرح دينيس إسكينازي، مدير تسويق منتجات CINDX، سبب انضمامه إلى CINDX ',
    'feedbackProject#8': 'فيليب ستايهيلين ',
    'feedbackProject#9': 'مستشار ',
    'feedbackProject#10': 'يشرح فيليب ستايهيلين، أحد مستشاري مشروع CINDX، كيف يمكن للتطوّر الحادث في قطاع العملات المشفّرة أن يساعد المستثمرين المبتدئين ويتحدّث عن الطفرة التي أعدّها مشروع CINDX لسوق العملات المشفّرة',
    'feedbackProject#11': 'أندرزيج سيكوفلاز ',
    'feedbackProject#12': 'أخصائي تسويق ',
    'feedbackProject#13': 'يتحدّث أندرزيج سيكوفلاز، مدير التسويق في CINDX، عن سبب إيمانه بنجاح المشروع ',
    'feedbackProject#14': 'أوستن كيم',
    'feedbackProject#15': 'يتحدّث أوستن كيم، أحد مستشاري مشروع CINDX، عن دور منصة CINDX في تبسيط تجربة تداول العملات المشفّرة لتحقيق الربح وجعلها أكثر ذكاءً ',
    'feedbackProject#16': 'أماربريت سينغ ',
    'feedbackProject#17': 'يشرح أماربريت سينغ، أحد مستشاري مشروع CINDX، دور منصة CINDX في رأب الفجوة بين المستثمرين والمتداولين ',
    'feedbackProject#18': 'كيث تياري ',
    'feedbackProject#19': 'يصف كيث تياري، أحد مستشاري مشروع CINDX، مزايا منصة CINDX',
    'feedbackProject#20': 'منصور رسولوف ',
    'feedbackProject#21': 'مدير مجتمع المستخدمين ',
    'feedbackProject#22': 'يشرح منصور رسولوف، مدير مجتمع مستخدمي CINDX، السبب وراء قراره بأن يصبح جزءًا من فريق عمل CINDX ',
    'feedbackProject#23': 'سادي هاتون ',
    'feedbackProject#24': 'تشرح سادي هاتون، أحد مستشاري مشروع CINDX، أوجه الاختلاف بين منصة CINDX ومنصات التداول الآلية الأخرى ',
    'feedbackProject#25': 'غراهام دوغارت ',
    'feedbackProject#26': 'يتحدّث غراهام دوغارت، أحد مستشاري مشروع CINDX، عن مواطن قوة منصة CINDX',
    'feedbackProject#27': 'ألينا فاردانيان ',
    'feedbackProject#28': 'مديرة المحتوى ',
    'feedbackProject#29': 'تتحدّث ألينا فاردانيان، مديرة المحتوى على منصة CINDX، عن روح الفريق وما تحبه بشأن وظيفتها ',
    'feedbackProject#30': 'بوغدان فيدور ',
    'feedbackProject#31': 'مستشار CINDX ',
    'feedbackProject#32': 'يشرح بوغدان فيدور، أحد مستشاري مشروع CINDX أوجه الاختلاف بين مشروع CINDX والمشروعات الأخرى للطرح الأولي للعملات ',
    'feedbackProject#33': 'جايسون كينغ ',
    'feedbackProject#34': 'يشرح جايسون كينغ، كبير المسؤولين التجاريين، مايجذبه لمشروع CINDX ويتحدّث عن المزايا المهمة للمشروع ',

    'mediaNews#1': 'وسائط الإعلام ',
    'mediaNews#2': 'الأخبار ',
    // Media
    'mediaNews#1_1': 'CINDX Aims to Democratize the Modern Financial System',
    'mediaNews#1_2': 'Even as investors in the cryptocurrency space recognize that they are at the forefront of a new financial revolution, adoption by the general populace is yet to occur. While 3rd parties are slowly entering the space in the form of hedge funds and other investors, very few individuals seem to have taken the step to invest in cryptocurrencies on their own.',
    'mediaNews#1_3': 'CINDX Announces Plans For ICO Pre-Sale Amidst Release Of Revolutionary Crypto Trading Hub That Allows Users To Follow Expert Traders',
    'mediaNews#1_4': 'CINDX takes its business seriously with particular attention and cares to legal matters and has taken great pains to ensure that CINDX is as compliant as possible with global regulations.',
    'mediaNews#1_5': 'How CINDX is Democratizing the Modern Financial System',
    'mediaNews#1_6': 'CINDX is a new platform that is making crypto trading easier, more secure, and more accessible. With this platform, it’s possible to have your funds traded without high fees or minimum investments, with the added security and transparency of blockchain technology.',
    'mediaNews#1_7': 'CINDX is making crypto trading easier, more secure, and more accessible.',
    'mediaNews#1_8': 'Cryptocurrency and blockchain technology have been slated as powerful tools capable of fueling a global financial revolution. There are myriad opportunities to invest in the crypto space, and yet, very few individuals have undertaken the steps necessary to invest.',
    'mediaNews#1_9': 'CINDX Announces Plans Release Of Revolutionary Crypto Trading Hub',
    'mediaNews#1_10': 'The CINDX platform creates a complete ecosystem for cryptocurrency trading that is favorable to all the participants of the market and offers solutions to existing pain points.',
    'mediaNews#1_11': 'CINDX Announces Plans For ICO Pre-Sale',
    'mediaNews#1_12': 'CINDX made headlines this week with the announcement that they will be opening their ICO Pre-Sale in late August after investors interest in the ICO peaks to new levels.',
    'mediaNews#1_13': 'CINDX Will Be Opening ICO Pre-Sale in late August',
    'mediaNews#1_14': 'The CINDX Crypto trading platform has a myriad of features and benefits that haven’t been seen in other platforms to date.',
    'mediaNews#1_15': '5 Tips from CINDX Crypto Assets Management Hub: How to Avoid Being Cheated',
    'mediaNews#1_16': 'The team behind the CINDX crypto assets management hub has created a helpful set of guidelines on how not to become victims of unfair play, so you can learn what should be primarily taken into account when evaluating ICOs before investing in them.',
    'mediaNews#1_17': 'CINDX Crypto Asset Management Hub Adopts Bancor Protocol',
    'mediaNews#1_18': 'CINDX is delighted to announce that a number of new integrations with top industry players are underway, each of which will make the life of the users of the platform easier and richer. These new integrations include the decision to adopt the Bancor protocol to provide continuous liquidity for the CINDX platform.',
    // News
    'mediaNews#2_1': 'CINDX meets Ian Balina',
    'mediaNews#2_2': 'CINDX pitch to the one of the TOP10 crypto gurus in the world in the Cryptobazar event.',
    'mediaNews#2_3': 'CINDX took part in Moscow ICO Summit 2018',
    'mediaNews#2_4': 'CINDX team introduced the project to the Russian crypto community during ICO Summit event.',
    'mediaNews#2_5': 'How CINDX is ensuring legal compliance',
    'mediaNews#2_6': 'Our company is registered in Estonia. Why? The answer is simple — the authorities of Estonia have created a strong and innovative legal infrastructure...',
    'mediaNews#2_7': 'Keith Teare Co-founder of Accelerated Digital Ventures and Founding Shareholder in TechCrunch',
    'mediaNews#2_8': 'We continue to introduce CINDX advisers, find out what they...',
    'mediaNews#2_9': 'Meet world\'s first financial crypto social network',
    'mediaNews#2_10': 'Every day our team takes one more step on the way to creation and start...',
    'mediaNews#2_11': 'Denis Eskenazi CINDX Product Marketing Director',
    'mediaNews#2_12': 'We continue to tell about the CINDX team and each team member’s professional experience. Please, read about Denis Eskenazi...',
    'mediaNews#2_13': 'CINDX crypto currency exchange license',
    'mediaNews#2_14': 'Our company in Estonia has received Crypto Currency Exchange License. This allows CINDX to provide fiat-to-crypto exchange services. This licence is issued...',
    'mediaNews#2_15': 'Austin Kimm Co-founder of Crypterium & CINDS Adviser',
    'mediaNews#2_16': 'We continue to introduce CINDX advisers, find out what they are proud...',
    'mediaNews#2_17': 'The strategic meeting of the international CINDX team',
    'mediaNews#2_18': 'Every day our team takes one more step on the way to creation and start of the CINDX platform. Our work...',
    'mediaNews#2_19': 'Artur Shamalov CINDX Investment Director',
    'mediaNews#2_20': 'We continue to introduce the CINDX team. Our next article is about Artur Shamalov, a skilled...',
    'mediaNews#2_21': 'The issuance of CINX tokens',
    'mediaNews#2_22': 'The issuance of CINX tokens will be carried out according to the license of The Estonian Financial Supervisory Authority (EFSA). What is a token...',
    'mediaNews#2_23': '"Amarpreet Singh Co-Founding Member of Malta Blockchain Association & CINDX adviser"',
    'mediaNews#2_24': 'We at CINDX are incredibly proud to present our advisers, tell the world about their achievements and why they have decided to become a part of the CINDX...',
    'mediaNews#2_25': 'CINDX meets Vangoo Capital Partners Fund',
    'mediaNews#2_26': 'Today we have welcomed Kevin Shang from Vangoo Capital Partners and his colleagues in our office. We have discussed business partnership opportunities in order to attract investors from the Asian region.',
    'mediaNews#2_27': '"Mofassair Hossain CINDX Chief Marketing Officer."',
    'mediaNews#2_28': 'We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly excited about...',
    'mediaNews#2_29': 'How CINDX ensures safety for its users - KYC',
    'mediaNews#2_30': 'Every crypto enthusiast knows that a KYC procedure is necessary in order to protect investors against fraudulent actions of the third...',
    'mediaNews#2_31': 'Philip Staehelin 25 Years of Consulting and Entrepreneurial Experience',
    'mediaNews#2_32': 'We continue our regular series of articles dedicated to introducing CINDX advisers. The next item is about Philip Staehelin.',
    'mediaNews#2_33': 'CINDX meets 9coin Digital Asses Exchange',
    'mediaNews#2_34': 'The CINDX team continues active work on building relationships with various international companies. One of the most important directions of business...',
    'mediaNews#2_35': 'Jason King Interim Chief Commercial Officer',
    'mediaNews#2_36': 'The core of any great project is always people who make the unique idea come true. We would like to tell about...',
    'mediaNews#2_37': 'CINDX Presents the project during RICLUB private investors meeting',
    'mediaNews#2_38': 'CINDX has successfully passed the due diligence procedure requested by RICLub and was one of the few projects...',
    'mediaNews#2_39': 'Sofja Pevzner CINDX Personal Data Officer',
    'mediaNews#2_40': 'We continue to introduce our team and tell about what inspires our colleagues to work with CINDX. Please read about...',
    'mediaNews#2_41': 'Tyler Sanford 8+ years digital marketing in Yelp, Zenefits',
    'mediaNews#2_42': 'We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become a part of the CINDX team. In this...',
    'mediaNews#2_43': 'CINDX - Key points to observe',
    'mediaNews#2_44': 'The CINDX project is a valuable business venture with the features that are critically relevant for its participants. In this article we talk about Strengths...',
    'mediaNews#2_45': 'Airat Shayhulov CINDX Head of Quantitative Research.',
    'mediaNews#2_46': 'In “TEAM” series of the articles, we tell about people who every day participates in the creation...',
    'mediaNews#2_47': 'CINDX license of the financial consultant',
    'mediaNews#2_48': 'CINDX has obtained a termless operating licence (the FFA 000254 license) that gives the right to operate as a financial institution...',
    'mediaNews#2_49': '"Graham Doggart 20 Years of Enterprise Development and Fintech Marketing Compliance"',
    'mediaNews#2_50': 'We continue our regular series of articles dedicated to introducing CINDX advisers. The next item...',
    'mediaNews#2_51': 'CINDX continues the roadshow in China!',
    'mediaNews#2_52': 'The CINDX team is glad to announce participation as a Golden Sponsor of Borderless Blockchain Technology Summit 2018, which...',
    'mediaNews#2_53': 'Ibraghim Haniev CINDX Tech Lead',
    'mediaNews#2_54': 'Get to know more about the CINDX team! The core of any great project is always people who make the unique ideas come true...',
    'mediaNews#2_55': 'Sadie Hutton 25 Years in Senior Management and Management Consulting',
    'mediaNews#2_56': 'Like any global project, we understand the importance of professional help and advice. We continue to tell the stories of...',
    'mediaNews#2_57': 'CINDX.talk - a service that will help people become wiser in taking financial decisions',
    'mediaNews#2_58': 'The current digital-world related to the crypto industry is getting crowded with mind-charming digital solutions...',
    'mediaNews#2_59': '"Val Jerdes CINDX Product Director"',
    'mediaNews#2_60': 'We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly...',
    'mediaNews#2_61': 'Bogdan Fiedur Blockchain and cryptocurrency expert, investor, entrepreneur',
    'mediaNews#2_62': 'We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become...',
    'mediaNews#2_63': 'Welcome to CINX Token Distribution – it’s not an ICO; it’s an STO',
    'mediaNews#2_64': 'In this article, we want to make it clear why CINDX chose to hold a Security Token Offering (STO) instead of an Initial...',
    'mediaNews#2_65': 'CINDX celebrates the “AA” Rating from Top ICO List Audit!',
    'mediaNews#2_66': 'The results of CINDX’s sincerity to make meaningful changes in people’s ambitions via a unique business model just got appreciated...',
    'mediaNews#2_67': 'CINDX Weekly digest (30.07.18 - 05.08.18)',
    'mediaNews#2_68': 'The CINDX team is very excited to share the results of our work for the last week 30.07.18 - 05.08.18!',
    'mediaNews#2_69': 'Virtual Currency Wallet Services',
    'mediaNews#2_70': 'CINDX believes that being fluent in legal issues and having a clean, confident and clear legal status is of utmost importance. At the moment, CINDX is going...',
    'mediaNews#2_71': 'How CINDX Influences Crypto Trading',
    'mediaNews#2_72': 'How to master the crypto market movements and turn them in one’s favor? This is where CINDX’s effective business model comes into play. Learn more about CINDX on our Medium!',
    'mediaNews#2_73': 'CINDX Weekly digest (06.08.18 - 12.08.18)',
    'mediaNews#2_74': 'CINDX continues its regular column - Weekly Digest. We are excited to share the recent achievements of our project! Enjoy your time reading!',
    'mediaNews#2_75': 'CINDX gets 5.0 rating on TrackICO!',
    'mediaNews#2_76': 'CINDX continues getting approval from the largest and the most credible rating services. The week has hardly passed after...',
    'mediaNews#2_77': '"David Gutierrez Investment Relations Officer"',
    'mediaNews#2_78': 'CINDX is very serious about taking people on crew and proud to introduce them. This article is dedicated to David Gutierrez, CINDX Investment Relations Officer',
    'mediaNews#2_79': 'ICObench gives 4.8 to CINDX',
    'mediaNews#2_80': 'The CINDX project has already gained the highest mark of  ‘AA’ from Top ICO List and got a 5.0 rating from TrackICO. Now, we are proud to share...',
    'mediaNews#2_81': 'Dip your Toe in Crypto',
    'mediaNews#2_82': 'It is never late to change your mind. It’s no surprise that Wall Street bankers change their minds in favour of crypto. Enjoy reading CINDX review on the current market situation!',
    'mediaNews#2_83': 'Yuriy Avdeev, CEO of the CINDX project',
    'mediaNews#2_84': 'Enjoy reading what inspired Yuriy Avdeev to create a project that will help all participants of the crypto market to be profitably engaged - CINDX.',
    'mediaNews#2_85': 'Weekly digest (13.08.18 - 19.08.18)',
    'mediaNews#2_86': 'CINDX continues its regular Weekly Digest column. We are excited to share our project’s progress and the most recent achievements! We are glad to remind you that CINDX security token Pre-sale starts this Sunday. Don\'t miss!',

    'teamAdvisersPartners#1': 'فريق عمل يضم أكثر من 50 عضوًا',
    'teamAdvisersPartners#2': 'المستشارون',
    'teamAdvisersPartners#3': 'شركاؤنا ',
    // teamInfo
    'teamAdvisersPartners#4': 'يوري أفديف',
    'teamAdvisersPartners#5': 'الرئيس التنفيذي',
    'teamAdvisersPartners#6': '13 عامًا من الخبرة في مجال إدارة المشروعات',
    'teamAdvisersPartners#7': '9 مشروعات استثمارية',
    'teamAdvisersPartners#8': '2 مليون دولار نظير إدارة العملات المشفّرة',
    'teamAdvisersPartners#9': 'فال جيرديس',
    'teamAdvisersPartners#10': 'مدير المنتجات',
    'teamAdvisersPartners#11': '20 عامًا من الخبرة في مجال إدارة المشروعات',
    'teamAdvisersPartners#12': '3 صفقات ناجحة لمنتجات',
    'teamAdvisersPartners#13': 'الحصول على 4 أضعاف العائدات للمحافظ الاستثمارية',
    'teamAdvisersPartners#14': 'مفسّر حسين',
    'teamAdvisersPartners#15': 'كبير مسؤولي التسويق',
    'teamAdvisersPartners#16': 'مستثمر ومستشار في أكثر من 15 عملية طرح أولي للعملات',
    'teamAdvisersPartners#17': 'أحد كبار المستشارين في ICO Bench',
    'teamAdvisersPartners#18': 'عضو في GBAP',
    'teamAdvisersPartners#19': 'أرتور شمالوف',
    'teamAdvisersPartners#20': 'مدير الاستثمارات',
    'teamAdvisersPartners#21': '15 عامًا من الخبرة في مجال إدارة المشروعات',
    'teamAdvisersPartners#22': '5000 عميل على mixcart.ru',
    'teamAdvisersPartners#23': 'قامت mail.ru بالاستثمار في dc-daily.ru',
    'teamAdvisersPartners#24': 'دينيس إسكينازي',
    'teamAdvisersPartners#25': 'مدير تسويق المنتجات ',
    'teamAdvisersPartners#26': '7 أعوام من الخبرة في مجال إدارة المشروعات',
    'teamAdvisersPartners#27': 'جمع 2 مليون دولار للعملاء',
    'teamAdvisersPartners#28': '10 أعوام من الخبرة في مجال العلامات التجارية',
    'teamAdvisersPartners#29': 'إبراهيم حنيف',
    'teamAdvisersPartners#30': 'المسؤول التقني',
    'teamAdvisersPartners#31': '6 أعوام من الخبرة في مجال إدارة المشروعات',
    'teamAdvisersPartners#32': 'أكثر من 200 موقع تم تطويره',
    'teamAdvisersPartners#33': 'التركيز على مجال أمان المعلومات',
    'teamAdvisersPartners#34': 'Airat Shaikhulov',
    'teamAdvisersPartners#35': 'Head of Quantitative Research',
    'teamAdvisersPartners#36': 'Dr of science at MSU',
    'teamAdvisersPartners#37': 'Aton-line navigator developer',
    'teamAdvisersPartners#38': 'Head of algorithmic trading',
    'teamAdvisersPartners#39': 'صوفيا بيفزنر',
    'teamAdvisersPartners#40': 'مسؤولة البيانات الشخصية',
    'teamAdvisersPartners#41': '5 أعوام من الخبرة في مجال إدارة المشروعات',
    'teamAdvisersPartners#42': 'حاصلة على ترخيص بالعمل في مكتب مكافحة غسيل الأموال في إستونيا',
    'teamAdvisersPartners#43': '8 أعوام من الخبرة في العمل في الشؤون القانونية',
    'teamAdvisersPartners#44': 'ديف جوتيريز',
    'teamAdvisersPartners#45': 'مسؤول العلاقات الاستثمارية',
    'teamAdvisersPartners#46': '5 أعوام من الخبرة في مجال تأجير الطائرات',
    'teamAdvisersPartners#47': '3 أعوام من الخبرة في وكالات الاستثمار',
    'teamAdvisersPartners#48': 'عامان من الخبرة في مجال الاستثمار في الخارج',
    'teamAdvisersPartners#49': 'جيلينا كارزيتسكايا',
    'teamAdvisersPartners#50': 'مسؤولة الامتثال',
    'teamAdvisersPartners#51': 'حاصلة على شهادات عديدة في القانون',
    'teamAdvisersPartners#52': 'مزاولة القضاء منذ عام 1997',
    'teamAdvisersPartners#53': 'العمل في المجالات القانونية: القانون الدولي',
    'teamAdvisersPartners#54': 'وانغ دونغ',
    'teamAdvisersPartners#55': 'متخصّص في سوق البلوك تشين الصيني ',
    'teamAdvisersPartners#56': '3 أعوام من الخبرة في مجال php/JavaScript',
    'teamAdvisersPartners#57': '5 أعوام من الخبرة في مجال SEO/SMM/دعم الإعلام',
    'teamAdvisersPartners#58': 'عامان من الخبرة في مجال تطوير البلوك تشين وبيع العملات الرمزية في الصين',
    // advisers
    'teamAdvisersPartners#59': 'كيث تياري ',
    'teamAdvisersPartners#60': 'مؤسس شركة Accelerated Digital Ventures ورئيس مجلس إدارتها التنفيذي',
    'teamAdvisersPartners#61': 'مستشار لدى ICOBox وCrypterium وEnergiMine وما إلى ذلك.',
    'teamAdvisersPartners#62': 'مساهم مؤسّس في TechCrunch',
    'teamAdvisersPartners#63': 'أنا الرئيس التنفيذي لمجلس الإدارة ورئيس لجنة الاستثمار في شركة Accelerated Digital Ventures، وهي إحدى الشركات الاستثمارية في المملكة المتحدة. وُلِدتُ ونشأت في المملكة المتحدة. ',
    'teamAdvisersPartners#64': 'وأسّست في السابق شركة Archimedes Labs في بالو ألتو بكاليفورنيا وكنت شريكًا فيها. أحب العمل مع المؤسّسين والفِرَق والمصمّمين والمهندسين لإنشاء منتجات مثيرة',
    'teamAdvisersPartners#65': 'ورواية القصص الشيّقة وتحويلها إلى واقع. نجحت في تأسيس الكثير من الشركات وشاركت في تأسيس بعض منها منذ بداية ثمانينيات القرن العشرين. تم بيع بعض هذه الشركات بنجاح، بينما طرح بعضها الآخر أسهمه للاكتتاب العام. بالإضافة إلى ذلك، تم تقدير قيمة اثنتين من شركاتي بما يزيد عن مليار دولار. لطالما انصب تركيزي على اتجاهات حدوث التغيير. ففي ثمانينيات القرن العشرين، قادت الشبكات وقواعد البيانات دفة التغيير. وكان الاتصال بالإنترنت هو موضوع الساعة خلال الفترة بين 1994 و1998. واحتلّت خدمات الويب والمحتوى وتطبيقات المستهلكين على الأجهزة الجوّالة مكانة مهمة خلال الفترة بين 1998 و2010. ويتجه التركيز على تقنية البلوك تشين منذ عام 2017 حتى الآن.',
    'teamAdvisersPartners#66': 'االحياة المهنية والمشروعات: Tech Crunch وAccelerated Digital Ventures وcScape وEasyNet وCyberia وRealNames وVenture Network وICOBox وCrypterium وR/Block وFluz وEnergiMine وArchimedes Labs وCINDX',
    'teamAdvisersPartners#67': 'أوستن كيم',
    'teamAdvisersPartners#68': 'الرئيس التنفيذي لشركة International Financial Services',
    'teamAdvisersPartners#69': 'أكثر من 30 عامًا من الخبرة في مجال الخدمات المالية',
    'teamAdvisersPartners#70': 'أسّس شركات بقيمة 500 مليون دولار',
    'teamAdvisersPartners#71': 'أنا رئيس تنفيذي يتمتع بخبرة عالية مُثبَتة بالنتائج في مجال توفير الخدمات المالية، مع التركيز بشكلٍ خاص على تأسيس شركات التأمين في الأسواق النامية، حيث نجحت في بناء شركات تزيد قيمتها حاليًا عن 500 مليون دولار. عملتُ في الآونة الأخيرة في روسيا (10 سنوات)، كما أني شغلت أدوار أخرى في قطاعات مختلفة بخلاف التأمين ككبير مديرين، بما في ذلك الرئيس التنفيذي لمنصة Workle، وهي أكبر منصة توظيف لمبيعات الإنترنت في روسيا، وعملتُ أيضًا في مناصب إدارية كُبرى ومتنوّعة في شركات ناشئة تعمل في مجال التقنيات المالية، مثل Crypterium، الذي يُعد أول بنك رقمي للعملات المشفّرة في العالم. الحياة المهنية والمشروعات: Aviva وCommercial Union UK وReinaissance Insurance وKimm Health & Leisure Ltd وWorkle وCrypterium وCryptoIndex وCINDX',
    'teamAdvisersPartners#72': '',
    'teamAdvisersPartners#73': '',
    'teamAdvisersPartners#74': 'فيليب ستايهيلين ',
    'teamAdvisersPartners#75': '25 عامًا من الخبرة في مجال الاستشارات وإدارة المشروعات',
    'teamAdvisersPartners#76': 'نجح أثناء مسيرته القيادية في تحقيق 500 مليون دولار بالاستعانة بأنظمة الدفع البديلة',
    'teamAdvisersPartners#77': 'قدّم خدمات إرشادية لأكثر من 200 شركة ناشئة من 20 دولة',
    'teamAdvisersPartners#78': 'أنا قائد شغوف بالابتكار ويرتكز عملي على الجمع بين التفاؤل والمنهج الواقعي العقلاني. وأحاول دائمًا العثور على الفرص في المناطق التي لا يرى أحدٌ أي أمل فيها. بعبارة أخرى، نجحت في مناسبات عديدة في استغلال قدراتي "لرؤية الأمور بشكلٍ مختلف" و"تحقيق الأهداف المنشودة" في بيئات المؤسسات ومجال تقديم الاستشارات والشركات الناشئة، مما أدّى بالتالي إلى مساعدتي على العمل بزوايا جديدة وتشجيعي على تطبيق أفكار لم يتطرّق إليها أحد من قبل. يستند مصدر إلهامي إلى العثور على الحلول اللازمة للتصدّي للتحديات المختلفة. الحياة المهنية والمشروعات: Roland Berger وDot Glasses وTransparency International وStartupYard وBethereum وGjirafa Inc وAccenture وCINDX',
    'teamAdvisersPartners#79': '',
    'teamAdvisersPartners#80': '',
    'teamAdvisersPartners#81': '',
    'teamAdvisersPartners#82': 'أماربريت سينغ ',
    'teamAdvisersPartners#83': 'كبير المستشارين بمؤسسة Global Blockchain Foundation',
    'teamAdvisersPartners#84': 'خبرة من العمل في Microsoft والبنك الدولي وAirbus',
    'teamAdvisersPartners#85': 'عضو في المجلس الاستشاري لعدد من مشروعات البلوك تشين',
    'teamAdvisersPartners#86': 'يتميز أماربريت بأنه شغوف بالتقنيات والعالم الرقمي، كما أنه يتمتع بأعوام من الخبرة المهنية في القطاع التقني والعمليات وتقديم الاستشارات والحلول المُبتكَرة. بالإضافة إلى ذلك، حاز أماربريت على اعتماد Microsoft وAWS بصفته متخصصًا في الشبكة السحابية. يتميز أماربريت أيضًا بمهاراته المتنوّعة والمرونة وقدراته التحليلية الممتازة ومهاراته الإستراتيجية والقيادية، كما أنه يبرع عند العمل ضمن فريق. التخصّصات: الاستشارات التكنولوجية والعمليات والحوسبة السحابية والتقنيات المالية والابتكارات وتخطيط موارد المؤسسات والتعلّم الآلي وإدارة الحسابات وتطوير أعمال الشركاء وتطوير الشركات ووضع إستراتيجياتها. يتمتع أماربريت سينغ أيضًا بخلفية مهنية وتعليمية متنوّعة. حاز أماربريت على درجة الماجيستير ثلاث مرات، وعاش وعمل ودرس في عدة بلدان، مثل الهند وسنغافورة وفرنسا والصين وجنوب أفريقيا وكوريا وكندا. الحياة المهنية والمشروعات: Microsoft والبنك الدولي وAirbus وTokenAsia Platform وGOeurika وCINDX',
    'teamAdvisersPartners#87': '',
    'teamAdvisersPartners#88': '',
    'teamAdvisersPartners#89': '',
    'teamAdvisersPartners#90': '',
    'teamAdvisersPartners#91': 'تايلر سانفورد',
    'teamAdvisersPartners#92': '8 أعوام من الخبرة في مجال التسويق الرقمي في Yelp وZenefits',
    'teamAdvisersPartners#93': '12 عملية من عمليات الطرح الأولي للعملة وجمع ما يزيد عن 225 مليون دولار',
    'teamAdvisersPartners#94': 'من المستخدمين الأوائل لتقنية البلوك تشين',
    'teamAdvisersPartners#95': 'لقد ساعدتني نشأتي كرياضي من خلال منحي مجموعة المهارات التي أهّلتني للتفوّق في حياتي الشخصية والمهنية. لقد حالفني الحظ حقًا عند رؤية ثمار الجهد الذي بذلته، كما أني حرصت على تعلّم الدروس المُستفادة من الإنجازات والكبوات التي ترافق جميع المسارات المهنية. بالإضافة إلى ذلك، أشجّع نفسي دائمًا على المضي قُدُمًا ومواصلة تنمية مواهبي وتوسيع مداركي في جميع جوانب العمل. لا أستسلم لأي تحدٍ مهما كان صعبًا، فمبدأي في الحياة يتلخّص في التغلّب على العقبات التي تقف في طريق تحقيق أهدافي. الحياة المهنية والمشروعات: IPG Holdings وDataBlockChain وTraXion by Puma Technologies وELYSIAN وEtherinc وFTEC Foundation وCINDX',
    'teamAdvisersPartners#96': '',
    'teamAdvisersPartners#97': '',
    'teamAdvisersPartners#98': '',
    'teamAdvisersPartners#99': '',
    'teamAdvisersPartners#100': 'Philip Staehelin',
    'teamAdvisersPartners#101': '25 years of consulting and entrepreneurial experience',
    'teamAdvisersPartners#102': '$500m alternative payments business under leadership',
    'teamAdvisersPartners#103': '200+ startups from 20 countries mentored',
    'teamAdvisersPartners#104': 'I\'m an innovator and a leader who blends contagious optimism with pragmatic realism. I find opportunity where others see none.',
    'teamAdvisersPartners#105': 'I\'ve leveraged my ability to "see things differently" and "make things happen" in corporate, consulting and start-up environments - all giving me broad new perspectives that provide fodder for new transformative ideas.',
    'teamAdvisersPartners#106': 'Finding solutions to hard challenges is what gets me out of bed in the morning.',
    'teamAdvisersPartners#107': 'Career and projects: BCG, Spectacler, Transparency International, StartupYard, Bethreum, Gjirafa Inc, Direct People, CINDX',
    'teamAdvisersPartners#108': 'Senior Adviser of Global Blockchain Foundation',
    'teamAdvisersPartners#109': 'Experience in Microsoft, The World Bank and Airbus',
    'teamAdvisersPartners#110': 'Advisery Board Member of Blockchain projects',
    'teamAdvisersPartners#111': 'Technology/Digital enthusiast and a seasoned professional with years of experience in Tech industry – operations, consulting and innovation.',
    'teamAdvisersPartners#112': 'He is a certified Cloud (Microsoft and AWS) specialist. Known for versatility and flexibility. Excellent analytic, strategic, leadership skills and a team player at its best.',
    'teamAdvisersPartners#113': 'Specialties: Technology Consulting, Operations, Cloud Computing, Fintech, Innovation, ERP, Machine Learning, Account Management, Partner Development, Business Development and Strategy',
    'teamAdvisersPartners#114': 'Amarpreet Singh has a very diversified work and educational background. He holds three Masters degrees and has lived/worked/studied in India, Singapore, France, China, South Africa, Korea, Canada.',
    'teamAdvisersPartners#115': 'Career and projects: Microsoft, The World Bank, Airbus, TokenAsia Platform, GOeurika, CINDX',
    'teamAdvisersPartners#116': 'Tyler Sanford',
    'teamAdvisersPartners#117': '8 Years Digital Marketing in Yelp and Zenefits',
    'teamAdvisersPartners#118': '12 ICO’s over $225M raised',
    'teamAdvisersPartners#119': 'Early adopter of blockchain',
    'teamAdvisersPartners#120': 'Growing up as an Athlete has given me a skill set that I\'ve been able to apply to my careers and personal life.',
    'teamAdvisersPartners#121': 'I have been very fortunate to see the results of going that extra mile, while learning to deal with the highs and lows that go along with all professional careers.',
    'teamAdvisersPartners#122': 'I\'m an extremely self-motivated individual, always looking to continue my growth of knowledge and talents in all aspects of business.',
    'teamAdvisersPartners#123': 'Always up for a challenge, my motivation comes from overcoming obstacles to reach my goals',
    'teamAdvisersPartners#124': 'Career and projects: IPG Holdings, DataBlockChain, TraXion by Puma Technologies, ELYSIAN, Etherinc, FTEC Foundation,  CINDX',
    'teamAdvisersPartners#125': 'بوغدان فيدور ',
    'teamAdvisersPartners#126': 'خبير ومستثمر ورائد أعمال في مجال البلوك تشين والعملات المشفّرة',
    'teamAdvisersPartners#127': 'مؤسس مشارك لشركة bitJob ورئيس Blockchainexperts.io',
    'teamAdvisersPartners#128': 'مستشار في مجال الطرح الأولي للعملات وخبير لدى ICOBench',
    'teamAdvisersPartners#129': 'يُعد بوغدان فيدور واحدًا من المطوّرين المميزين لميزة العقود الذكية، كما أنه مستثمر شغوف بالعملات المشفّرة ورائد أعمال ورئيس منصة http://blockchainexperts.io. يتمتع بوغدان بخبرة تزيد عن 20 عامًا في مجال تقنية المعلومات، وتحديدًا في إنشاء مواقع التجارة الإلكترونية، وقد شارك في تطوير أدوات البلوك تشين خلال السنوات الثلاث الماضية. بالإضافة إلى ذلك، فإنه يعمل كمستشار في مجال الطرح الأولي للعملات ونجح في إطلاق 20 حدثًا من أحداث الطرح الأولي للعملات حتى الآن، كما أنه يقدّم عروضًا تقديمية ووِرَش عمل حول تقنية البلوك تشين وبرمجة العقود الذكية في نطاق مجتمعه المحلي المعني بالعملات المشفّرة في وينيبيغ. يركز بوغدان الآن على مجال البلوك تشين ويقدم خدماته الاستشارية لخبراء البلوك تشين ويفيدهم بمعارفه. أسّس بوغدان مؤخرًا منصة Bitjob، وهي منصة مستقلة قائمة على تقنية البلوك تشين مخصّصة للطلاب، وشارك أيضًا في عدد من مشروعات الطرح الأولي للعملات كعضو في الفِرَق المنفّذة لهذه المشروعات، مثل PayPie.com. الحياة المهنية والمشروعات: US Blockchain Association وTuurnt وTrends Project وBiNeuro وZichain وGraphen Tech وCyClean وSwachhcoin وCINDX',
    'teamAdvisersPartners#130': '',
    'teamAdvisersPartners#131': '',
    'teamAdvisersPartners#132': '',
    'teamAdvisersPartners#133': 'غراهام دوغارت ',
    'teamAdvisersPartners#134': '20 عامًا من الخبرة في مجال تطوير المؤسسات وامتثال تسويق التقنيات المالية',
    'teamAdvisersPartners#135': 'نفّذ حملات بقيمة 100 مليون دولار',
    'teamAdvisersPartners#136': 'مستشار لأكثر من 10 مشروعات في مجال البلوك تشين لهذا العام',
    'teamAdvisersPartners#137': 'أعمل كرئيس مجلس إدارة مشروع Stealth Cryptocurrency Project، كما أني شاركت في تأسيس Dynamic Abundance، وهي إحدى الشركات الاستشارية العاملة في مجال البلوك تشين والتقنيات المالية منذ عام 2012، وأشغل أيضًا منصب المسؤول عن وضع الإستراتيجيات فيها. يتمثّل تخصصي في إنشاء وإنهاء تنفيذ عروض العملات الرمزية، كما أني عملت على عدد كبير من مشروعات البلوك تشين والعملات المشفّرة والطرح الأولي للعملات على الصعيد الدولي. وعلى مدار ما يزيد عن 20 عامًا، نجحت في تقديم استشارات في مجالات إدارة التقنيات والامتثال القانوني والمالي وعلاقات المستثمرين، بالإضافة إلى وضع إستراتيجيات النمو وتصميم وتأليف عدد كبير من المواد. الحياة المهنية والمشروعات: Stealth Cryptocurrency Project وDynamic Abundance وELYSIAN وFox Trading FX وProfede وWorltdopoly وCINDX',
    'teamAdvisersPartners#138': '',
    'teamAdvisersPartners#139': '',
    'teamAdvisersPartners#140': '',
    'teamAdvisersPartners#141': 'سادي هاتون ',
    'teamAdvisersPartners#142': '25 عامًا من الخبرة في الإدارة العليا ومجال الاستشارات الإدارية',
    'teamAdvisersPartners#143': 'نجحت في جمع تبرّعات بعدة ملايين من الدولارات من خلال حملات بقيمة 75 مليون جنيه إسترليني',
    'teamAdvisersPartners#144': 'مستشارة الطرح الأولي للعملات لثمانية مشروعات',
    'teamAdvisersPartners#145': 'نجحت في تأسيس إحدى الشركات الاستشارية العاملة في مجال تقنيات البلوك تشين، وتُعرَف باسم Dynamic Abundance. أفضّل المنهج "العملي" ويستند تخصّصي في الأساس إلى تحليل عمليات الطرح الأولي للعملات وجميع الجوانب المتعلّقة بها وإدارة المشروعات. ونظرًا لأن مهاراتي تعتمد أساسًا على إدارة الشركات وتنميتها، فيمكنني القول إن عملي يتلخّص في إدارة أي مشروع بدءًا من مرحلة وضعه وحتى تنفيذه. وبوجهٍ عام، أحب حل المشكلات وأتعامل مع أي مشروع أعمل به وكأنه مشروعي الأول والأخير. فأنا أسعى للفوز دائمًا! على مدار ما يزيد عن 20 عامًا من الخبرة في مجال الإدارة، نجحت في تكوين شبكة قوية من العلاقات. وحاليًا، أعمل في مجال تقديم الاستشارات المالية والتقنية والتسويقية وتلك المتعلّقة بالمبيعات وضمان الجودة لصالح المشروعات رفيعة المستوى القائمة على تقنية البلوك تشين. الحياة المهنية والمشروعات: Dynamic Abundance وELYSIAN وWorldopoly وConfidential ICO وFox Trading FX وProfede وMarket Digital وCINDX',
    'teamAdvisersPartners#146': '',
    'teamAdvisersPartners#147': '',
    'teamAdvisersPartners#148': '',
    'teamAdvisersPartners#149': 'جايسون كينغ ',
    'teamAdvisersPartners#150': '20 عامًا من الخبرة في شغل المناصب التنفيذية',
    'teamAdvisersPartners#151': 'أدار عمليات تجارية في 30 دولة',
    'teamAdvisersPartners#152': 'مسؤول عن بيانات الأرباح والخسارة بقيم تتعدّى 500 مليون دولار',
    'teamAdvisersPartners#153': 'عمل جايسون كينغ لما يصل إلى 20 عامًا تقريبًا كمسؤول تنفيذي في مجال التكنولوجيا والوسائط والاتصالات، وشارك في وضع عدد من الصفقات التجارية والتفاوض لتحقيق أرباح وبناء الأسواق وتأهيل المؤسسات للنجاح ولعب دور الوسيط في جميع ما سبق أيضًا.عزّزت العديد من التحدّيات التي واجهها جايسون من مهاراته في إعادة البناء والتغيير، مما أدّى بالتالي إلى تكوين الفِرَق المناسبة لتحقيق أكثر الأهداف ربحية.يتمتع جايسون بخبرة واسعة في مجالات مختلفة، بما في ذلك إدارة الأعمال والعمليات والتخطيط الإستراتيجي والتمويل والعملات المشفّرة وقطاع تقنية البلوك تشين.',
    'teamAdvisersPartners#154': '',
    'teamAdvisersPartners#155': '',
    'teamAdvisersPartners#156': '',
    'teamAdvisersPartners#157': 'موتي بير ',
    'teamAdvisersPartners#158': 'مؤسس مشارك لوكالة Blonde 2.0، إحدى وكالات العلاقات العامة الحائزة على جوائز',
    'teamAdvisersPartners#159': 'مؤسس العديد من الشركات في قطاعي الأمان والشؤون المالية.',
    'teamAdvisersPartners#160': 'يُعد موتي أحد القادة المتميزين في مجال العلاقات العامة لقطاعات مثل تقنية البلوك تشين والعملات المشفّرة والشركات الناشئة والعملات الافتراضية.',
    'teamAdvisersPartners#161': 'أسّس موتي العديد من الشركات في قطاعي الأمان والشؤون المالية. ويتمتع بخبرة قِوامها أعوام طويلة من العمل كمدير لصناديق التحوّط وصناديق استثمار الأموال، كما أنه حاصل على درجة الماجيستير في إدارة الأعمال وتحديدًا في قطاع الشؤون المالية والتسويق من جامعة مانشيستر ودرجة البكالوريوس في إدارة الأعمال من جامعة فيرلاي ديكينسون. شارك موتي كرئيس تنفيذي في تأسيس وكالة Blonde 2.0 العالمية للعلاقات العامة، وهي إحدى وكالات العلاقات العامة الحائزة على جوائز، والتي لقّبتها Forbes بإحدى الوكالات الناشئة "ذات النفوذ القوي" على المستوى القومي. وباعتبار موتي رئيسًا تنفيذيًا مشاركًا لوكالة Blonde 2.0، فهو مسؤول عن التعامل مع جوانب العلاقات العامة، بالإضافة إلى جانبي وضع الإستراتيجيات وإدارة الأزمات. تضّم Blonde 2.0 فريقًا مؤلَّفًا من 35 عضوًا محترفًا، وتُعد واحدة من الوكالات المتميزة في مجال العلاقات العامة لقطاعات مثل تقنية البلوك تشين والعملات المشفّرة والشركات الناشئة والعملات الافتراضية.',
    'teamAdvisersPartners#162': '',
    'teamAdvisersPartners#163': '',
    'teamAdvisersPartners#164': 'ليونارد غرايفير',
    'teamAdvisersPartners#165': 'شريك في كلٍ من Greenberg وWhitcombe وTakeuchi',
    'teamAdvisersPartners#166': 'مثّل ما يزيد عن 400 شركة ناشئة',
    'teamAdvisersPartners#167': 'نجح في جمع أكثر من 18 مليون دولار أمريكي لشركته الناشئة عندما كان طالبًا في كلية الحقوق',
    'teamAdvisersPartners#168': 'وُلِد ليونارد غرايفير في الاتحاد السوفيتي وانتقل إلى الولايات المتحدة مع والديه عندما كان طفلاً صغيرًا. أنشأ ليونارد أثناء دراسته في كلية الحقوق شركة ناشئة ونجح في جمع ما يزيد عن 18 مليون دولار أمريكي لتمويلها. لم تستمر هذه الشركة، ولكن منذ ذلك الحين، ساعد ليونارد أكثر من 400 شركة ناشئة. بوجهٍ عام، يتمتع ليونارد بما يزيد عن 10 أعوام من الخبرة في مجال التمويل بالعملات الافتراضية ووضع هياكل الصناديق الاستثمارية وإجراءات بذل العناية الواجبة (أي ما يمثّل كلاً من الصناديق الاستثمارية والشراكات المحدودة). ينصح ليونارد جميع رواد الأعمال بالسعي وراء النجاح فيما يثير اهتماماتهم بدلاً من الاكتفاء بالسير وراء الاتجاهات السائدة.نجح ليونارد في تكوين شبكة من العلاقات المهنية القوية مع أصحاب العديد من الصناديق الاستثمارية الدولية.',
    'teamAdvisersPartners#169': '',
    'teamAdvisersPartners#170': '',

    'joinTokenPreSale#1': 'الانضمام إلى فعاليات الطرح الأولي للعملات الرمزية ',
    'joinTokenPreSale#2': 'الانضمام إلى فعاليات الطرح الأولي ',
    'joinTokenPreSale#3': 'اختبار الإصدار الأساسي للمنتج ',
    'joinTokenPreSale#4': 'المركز الرئيسي ',
    'joinTokenPreSale#5': 'Harjumaa, Erika 14,',
    'joinTokenPreSale#6': 'Talinn, 10416, Estonia',
    'joinTokenPreSale#7': 'الاستفسارات المتعلّقة بالأعمال | hello@cindx.io',
    'joinTokenPreSale#8': 'Legal Disclaimer',
    'joinTokenPreSale#9': 'التطوير والتسويق',
    'joinTokenPreSale#10': 'Presnenskaya naberezhnaya, 8 building 1,',
    'joinTokenPreSale#11': 'Moscow, 123112, Russia',
    'joinTokenPreSale#12': 'الوظائف | انضم إلى فريقنا |',
}

export default ar