const en = {
    'mainBlock#1': 'Make Your Crypto Investments',
    'mainBlock#2': 'Easy, Secure and Fast.',
    'mainBlock#3': 'Join Our Security Token Sale',

    'icoInfo#1': 'We accept:',
    'icoInfo#2': 'Hard Cap:',
    'icoInfo#3': 'Soft Cap Milestone:',
    'icoInfo#4': 'Listing Agreements are Signed With:',

    'menu#1': 'WHITEPAPER',
    'menu#2': 'PRESENTATION',
    'menu#3': 'ONE PAGER',
    'menu#4': 'FINANCIAL MODEL',
    'menu#5': 'LEGAL DOCS',
    'menu#6': 'EN',
    'menu#7': 'Product',
    'menu#8': 'Sale Details',
    'menu#9': 'Team',
    'menu#10': 'Public Docs',
    'menu#11': 'Test MVP',

    'mailForm#1': 'Wrong email',
    'mailForm#2': 'sending ..',
    'mailForm#3': 'Already was or is not valid, try again',
    'mailForm#4': 'Your email has been sent successfully',
    'mailForm#5': 'an error occurred, try again',
    'mailForm#6': 'GDRP Сompliance',
    'mailForm#7': 'Personal data provided via Subscription form and KYC procedure will be collected in the full compliance with GDRP',
    'mailForm#8': 'The Data Protection Officer  of the project is  Mrs. Sofja Pevzner-Belositski. Contact details: dpo@cindx.io. Any data subject may, at any time, contact Data Protection Officer of directly with any request related to data protection.',
    'mailForm#9': 'Your personal data provided via Subscription form and KYC procedure will be shared to our partners:',
    'mailForm#10': 'ICO Promo',
    'mailForm#11': 'Privacy Policy',
    'mailForm#12': 'Sum & Substance',
    'mailForm#13': 'By default, the personal data provided by subscriber are kept by CINDX, ICO Promo and Sum & Substance for 5 years after registration of subscriber in the system',
    'mailForm#14': 'If you do not agree to this privacy policy, please do not use our site.',
    'mailForm#15': 'By using our site, you consent to the collection and use of information by us. Owing to the global nature of the internet infrastructure, the information you provide may be transferred in transit to countries outside the European Economic Area that do not have similar protections in place regarding your data and its use as set out in this policy.',
    'mailForm#16': 'However, we have taken the steps outlined above to try to improve the security of your information. By submitting your information you consent to these transfers',
    'mailForm#17': 'I agree to process my',
    'mailForm#18': 'personal data',
    'mailForm#19': 'Security Token Sale Starts with',
    'mailForm#20': '25% BONUS',
    'mailForm#21': 'Get it before everyone else does',
    'mailForm#22': 'Token sale starts in',
    'mailForm#23': 'Start from $1',
    'mailForm#24': '1$ later',
    'mailForm#25': 'Your Email',
    'mailForm#26': 'JOIN PRE-SALE',
    'mailForm#27': 'AGREE & SUBMIT',

    'progressBarSale#1': 'Bonuses',
    'progressBarSale#2': 'in CINX',
    'progressBarSale#3': 'Pre-Sale',
    'progressBarSale#4': 'Sale',
    'progressBarSale#5': 'Aug 26',
    'progressBarSale#6': 'Sep 17',
    'progressBarSale#7': 'Oct 8',
    'progressBarSale#8': 'Oct 22',
    'progressBarSale#9': 'Nov 6',
    'progressBarSale#10': 'Nov 19',
    'progressBarSale#11': 'Dec 3',
    'progressBarSale#12': 'Dec 17',

    'cryptoAssetsManagement#1.1': 'CINDX is a Crytpto Asset Management Hub. We solve the problems of investors,',
    'cryptoAssetsManagement#1.2': 'traders and developers',
    'cryptoAssetsManagement#2': 'СINDX.MARKETPLACE FOR INVESTORS',
    'cryptoAssetsManagement#3': 'Don’t worry about your knowledge and experience – the experts of crypto trading are here to help you',
    'cryptoAssetsManagement#4': 'Control your currency: your coins are kept in your wallet at all times',
    'cryptoAssetsManagement#5': 'Only pay if you earn: you will only be charged fees if your portfolio makes money',
    'cryptoAssetsManagement#6': 'TEST MVP',
    'cryptoAssetsManagement#7': 'CINDX.TRADE FOR TRADERS',
    'cryptoAssetsManagement#8': 'You can attract capital with $0 marketing costs',
    'cryptoAssetsManagement#9': 'We provide you with Terminal, App Store, marketplace and other advanced tools to succeed in trading.',
    'cryptoAssetsManagement#10': 'CINDX helps to monetize your reputation and expertise. Your trade history and influence are transparent.',
    'cryptoAssetsManagement#11': 'CINDX.TALK, CINDX.HUB & CINDX.DAO',
    'cryptoAssetsManagement#12': 'CINDX.talk - a social network with a reward for useful content',
    'cryptoAssetsManagement#13': 'CINDX.hub - the component includes a vendor’s account, as well as a hub for testing and integrating third-party software',
    'cryptoAssetsManagement#14': 'CINDX.dao - a component that allows you to implement a voting system for the community based on decentralised autonomous organisation rules',

    'teamLegal#1': 'We Нave a Great Team and a Best-in-class',
    'teamLegal#2': 'Legal and Regulatory Organizational Framework',
    'teamLegal#3': 'CRYPTOCURRENCY EXCHANGE LICENSE',
    'teamLegal#4': 'FINANCIAL INSTITUTION LICENSE',
    'teamLegal#5': 'CRYPTO WALLET LICENSE',
    'teamLegal#6': 'WHITEPAPER',
    'teamLegal#7': 'PRESENTATION',
    'teamLegal#8': 'ONE PAGER',
    'teamLegal#9': 'FINANCIAL MODEL',
    'teamLegal#10': 'LEGAL DOCS',

    'roadmap#1': 'Roadmap',
    'roadmap#2': 'SCENARIO',
    'roadmap#3': 'We are building the base for the CINDX platform. At this step, the Minimum Viable Product (MVP) is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform.',
    'roadmap#4': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be  going through some alterations to add functionalities.  ',
    'roadmap#5': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services.      ',
    'roadmap#6': 'At this stage, the CINDX.market and CINDX.trade components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. ',
    'roadmap#7': 'CINDX.talk will have public and private channels. At this stage, the content will  be able to be  separated. ',
    'roadmap#8': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade is an extremely flexible system of order execution and risk management. The Vendor’s market will appear; however, at this point, the Vendor’s market will only contain applications developed by CINDX and its partners.  ',
    'roadmap#9': 'A tokenized rating system will be added in the final version of CINDX.talk, as well as a new type of product: “algorithmic trading”. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders.   ',
    'roadmap#10': 'We are building the base for the CINDX platform. At this step, the MVP is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform. ',
    'roadmap#11': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be going through some alterations to add functionalities.  ',
    'roadmap#12': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services. Another new component, CINDX.hub, will enable Vendors to develop applications that will analyze the market data that CINDX provides. ',
    'roadmap#13': 'At this stage, the CINDX.market and CINDX.trade components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. An SDK for developers will be released. This should simplify application development and implementation for CINDX.  ',
    'roadmap#14': 'CINDX.talk will have public and private channels. At this stage, the content will be able to be separated. CINDX.hub will integrate Github, which will simplify application development even more.',
    'roadmap#15': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade will be an extremely flexible system of order execution and risk management. CINDX.hub will have a full-scale editor for trading strategies with a testing system based on historical market data.',
    'roadmap#16': 'A tokenized rating system  CINDX.talk will be added in the final version of CINDX.talk. This will provide a system of assessment for CINDX community trading experts. “Algorithmic trading” will also be added. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders. A high-grade platform for a code audit will be created. ',
    'roadmap#17': 'We are building the base for the CINDX platform. At this step, the MVP is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform.',
    'roadmap#18': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be  going through some alterations to add functionalities. ',
    'roadmap#19': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services. Another new component,  CINDX.hub, will enable Vendors to develop applications that will analyze the market data that CINDX provides. The team will develop CINDX.dao, a component that acts as a system for the platform’s revenue distribution to its token holders.       ',
    'roadmap#20': 'At this stage, the CINDX.market and CINDX.trade  components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. An SDK for developers will be released. This should simplify application and implementation development for CINDX.  ',
    'roadmap#21': 'CINDX.talk will have public and private channels. At this stage the content can be separated. CINDX.hub will integrate Github which will simplify application development even more.',
    'roadmap#22': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade will be an extremely flexible system of order execution and risk management. CINDX.hub has a full-scale editor for trading strategies with a testing system based on historical market data. CINDX.dao will receive a voting system for token holders. ',
    'roadmap#23': 'A tokenized rating system CINDX.talk will be added in the final version of CINDX.talk. This will provide a system of assessment for CINDX community trading experts. “Algorithmic trading” will also be added. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders. A high-grade platform for a code audit will be created. ',

    'problemSolving#1': 'Time',
    'problemSolving#2': 'Trust',
    'problemSolving#3': 'Uncertainty',
    'problemSolving#4': 'I have some money to put in the crypto game, but don’t have the time to research and contact professional traders to manage my portfolio',
    'problemSolving#5': 'I have always felt uncomfortable with the idea of handing my money over to someone else to make a profit',
    'problemSolving#6': 'The technology surrounding crypto trading is not user-friendly. I cant figure out how to trade my coins',
    'problemSolving#7': 'CINDX provides the access to rated and trustworthy traders',
    'problemSolving#8': 'On CINDX  platform, your funds will never leave your wallet',
    'problemSolving#9': 'You earn right along with the best traders on the market',
    'problemSolving#10': 'Traders on CINDX are rated according to their history of trading success. Choose the trader that’s right for you quickly',
    'problemSolving#11': 'Our decentralized system and smart contracts allow your funds to be managed without being transferred to another trader',
    'problemSolving#12': 'Every investor in CINDX has the opportunity to have their funds managed by the most succesful traders on the market',
    'problemSolving#13': 'What kinds of problems does CINDX solve for investors?',
    'problemSolving#14': 'TEST MVP',

    'howCindxWorks#1': 'Investors',
    'howCindxWorks#2': 'Traders',
    'howCindxWorks#3': 'Vendors',
    'howCindxWorks#4': 'increase their crypto earnings with the portfolio management skills of top traders',
    'howCindxWorks#5': 'earn commissions from the investors that follow them based on their performance and trade strategy',
    'howCindxWorks#6': 'sell advanced trading tools, like trade robots and news widgets.',
    'howCindxWorks#7': 'collects commissions and subscription fees',
    'howCindxWorks#8': 'I’m joining CINDX with crypto assets that  I want to be traded',
    'howCindxWorks#9': 'I’m joining CINDX with trading expertise that will benefit investors',
    'howCindxWorks#10': 'Im joining CINDX with trading apps that will help investors',
    'howCindxWorks#11': 'We’re here to make trading easy, secure, and profitable',
    'howCindxWorks#12': 'In a Nutshell: How CINDX Works',

    'marketAnalytics#1': 'Market Analytics',
    'marketAnalytics#2': 'Global AUM',
    'marketAnalytics#3': 'Investment',
    'marketAnalytics#4': 'Structure of investment',
    'marketAnalytics#5': 'Since 2000, the global trust management market has grown by more than 250%.',
    'marketAnalytics#6': 'This is the result of constant improvements in market tools and the general development of market structuring.',
    'marketAnalytics#7': 'Despite the explosive growth of the cryptocurrency market in 2017, the industry is still in its infancy.',
    'marketAnalytics#8': 'The total market capitalization was $600 billion at the end of 2017 — just 1% of the trust management industry total market capitalization.',
    'marketAnalytics#9': 'WHITEPAPER',
    'marketAnalytics#10': 'PRESENTATION',
    'marketAnalytics#11': 'ONE PAGER',
    'marketAnalytics#12': 'FINANCIAL MODEL',
    'marketAnalytics#13': 'LEGAL DOCS',
    'marketAnalytics#14': 'Geographic Scope',
    'marketAnalytics#15': '25 million potential',
    'marketAnalytics#16': 'blockchain wallets',
    'marketAnalytics#17': '200,000 potential',
    'marketAnalytics#18': 'transactions every day',
    'marketAnalytics#19': 'More than 225 potential',
    'marketAnalytics#20': 'partners, each with $3-5 billion',

    'tokenSaleDetails#1': 'Token Allocation',
    'tokenSaleDetails#2': 'Team',
    'tokenSaleDetails#3': 'Bounty',
    'tokenSaleDetails#4': 'Advisers',
    'tokenSaleDetails#5': 'Reserve',
    'tokenSaleDetails#6': 'Traders Recruitment Program',
    'tokenSaleDetails#7': 'Token Liquidity Support',
    'tokenSaleDetails#8': 'Available for Sale',
    'tokenSaleDetails#9': 'Token Name:',
    'tokenSaleDetails#10': 'Token Pre-Sale start:',
    'tokenSaleDetails#11': 'Total Emission:',
    'tokenSaleDetails#12': 'Price Per Token:',
    'tokenSaleDetails#13': 'Minimal Investment:',
    'tokenSaleDetails#14': '$ 50 equivalent',
    'tokenSaleDetails#15': 'WHITEPAPER',
    'tokenSaleDetails#16': 'PRESENTATION',
    'tokenSaleDetails#17': 'ONE PAGER',
    'tokenSaleDetails#18': 'FINANCIAL MODEL',
    'tokenSaleDetails#19': 'LEGAL DOCS',
    'tokenSaleDetails#20': 'Use of Proceeds',
    'tokenSaleDetails#21': 'Marketing and PR 21%',
    'tokenSaleDetails#22': 'Research and Development 41%',
    'tokenSaleDetails#23': 'Operations 28%',
    'tokenSaleDetails#24': 'Legal expenses 7%',
    'tokenSaleDetails#25': 'Community Grants 3%',
    'tokenSaleDetails#26': 'Token Deals',
    'tokenSaleDetails#27': 'Token Sale:',
    'tokenSaleDetails#28': 'Token Pre-Sale Bonuses:',
    'tokenSaleDetails#29': 'Aug 26 - Sep 16 - 25% Bonus',
    'tokenSaleDetails#30': 'Sep 17 - Oct 7 - 20% Bonus',
    'tokenSaleDetails#31': 'Token Main Sale Bonuses:',
    'tokenSaleDetails#32': 'Oct 8 - Oct 21 - 17% Bonus',
    'tokenSaleDetails#33': 'Oct 22 - Nov 4 - 15% Bonus',
    'tokenSaleDetails#34': 'Nov 6 - Nov 18 - 13% Bonus',
    'tokenSaleDetails#35': 'Nov 19 - Dec 2 - 10% Bonus',
    'tokenSaleDetails#36': 'Dec 3 - Dec 16 - 5% Bonus',
    'tokenSaleDetails#37': 'Dec 17 - Dec 26 - 0% Bonus',
    'tokenSaleDetails#38': 'buy tokens',
    'tokenSaleDetails#39': 'Token Sale Details',
    'tokenSaleDetails#40': 'During the token sale, investors purchase utility tokens – options [CINXO], which give them the right to receive security tokens [CINX] in the future.',
    'tokenSaleDetails#41': 'Security tokens [CINX] will be issued and distributed following the prospect of emission published on the website of FSA of Estonia https://www.fi.ee/ and cindx.io after the end of the token sale, but no later than Q1 2019.',
    'tokenSaleDetails#42': 'The holder of [CINXO] tokens has the right but no obligation to exchange options for security tokens with a ratio of 1:1 after completing the KYC procedure with identification signature, address confirmation and supply of other documents (see the KYC diagram).',
    'tokenSaleDetails#43': 'Tokens [CINXO] grant the same rights as security tokens apart from the right to participate in revenue distribution with a lock-up and voting on the platform.',

    'legalSchedule#1': 'Legal Schedule',
    'legalSchedule#2': 'RECEIVED LICENSE (FVR000110) TO EXCHANGE VIRTUAL CURRENCY TO FIAT SERVICES',
    'legalSchedule#3': 'APPLIED FOR TRADEMARK REGISTRATION IN ESTONIA AND EU',
    'legalSchedule#4': 'LICENSE FFA000254 FOR OPERATING AS A FINANCIAL INSTITUTION',
    'legalSchedule#5': 'RECEIVED LICENSE FFA000254 FOR OPERATING AS A FINANCIAL INSTITUTION',
    'legalSchedule#6': 'WORKED OUT PROSPECTUS IN ACCORDANCE WITH ESTONIAN LAW',
    'legalSchedule#7': 'CLAIMED FSA LICENSE (ESTONIAN FINANCIAL SUPERVISION AUTHORITY)',
    'legalSchedule#8': 'RECEIVED LICENSE FOR PROVIDING A VIRTUAL CURRENCY WALLET SERVICE',
    'legalSchedule#9': 'REGISTERED UNDER EXEMPTION D IN SEC',
    'legalSchedule#10': 'APPOINTED A PERSONAL DATA MANAGER TO MEET GDPR REQUIREMENTS',
    'legalSchedule#11': 'RECEIVED THE FSA LICENSE',
    'legalSchedule#12': 'REGISTERED THE PROSPECTUS EU 809-2004',
    'legalSchedule#13': 'ISSUED CINX SECURITY TOKENS',

    'feedbackProject#1': 'Feedback On Our Project',
    'feedbackProject#2': 'Val Jerdes',
    'feedbackProject#3': 'Product Director',
    'feedbackProject#4': 'Val Jerdes, CINDX Product Director talks about the key team members and how their expertise will help develop the project that can change the game of finance in a significant way',
    'feedbackProject#5': 'Denis Eskenazi',
    'feedbackProject#6': 'Product Marketing Director',
    'feedbackProject#7': 'Denis Eskenazi, CINDX Product Marketing Director explains why he has joined CINDX',
    'feedbackProject#8': 'Philip Staehelin',
    'feedbackProject#9': 'Adviser',
    'feedbackProject#10': 'Philip Staehelin, Adviser of CINDX project, explains how the cryptocurrency revolution can help even inexperienced investors and tells about the breakthrough that CINDX project prepared for the crypto market',
    'feedbackProject#11': 'Andrzej Cichowlaz',
    'feedbackProject#12': 'Marketing Specialist',
    'feedbackProject#13': 'Andrzej Cichowlaz, CINDX Marketing Manager tells why he believes in the project`s success',
    'feedbackProject#14': 'Austin Kimm',
    'feedbackProject#15': 'Austin Kimm, Adviser of CINDX project tells how CINDX makes trading cryptocurrency for profit simple and smart',
    'feedbackProject#16': 'Amarpreet Singh',
    'feedbackProject#17': 'Amarpreet Singh, CINDX Adviser explains how CINDX platform can bridge the gap between investors and traders',
    'feedbackProject#18': 'Keith Teare',
    'feedbackProject#19': 'Keith Teare, CINDX Adviser describes advantages of CINDX platform',
    'feedbackProject#20': 'Mansur Rasulov',
    'feedbackProject#21': 'Community Lead',
    'feedbackProject#22': 'Mansur Rasulov, CINDX Community Lead explains why he decided to become a part of CINDX team',
    'feedbackProject#23': 'Sadie Hutton',
    'feedbackProject#24': 'Sadie Hutton, CINDX Adviser explains how CINDX plantform is different from other automated trading platforms',
    'feedbackProject#25': 'Graham Doggart',
    'feedbackProject#26': 'Graham Doggart, CINDX Adviser talks about strengths of CINDX platform',
    'feedbackProject#27': 'Alina Vardanian',
    'feedbackProject#28': 'Content Manager',
    'feedbackProject#29': 'Alina Vardanian, CINDX Content Manager talks about the team spirit and what she loves about her job',
    'feedbackProject#30': 'Bogdan Fiedur',
    'feedbackProject#31': 'CINDX Advisor',
    'feedbackProject#32': 'Bogdan Fiedur, CINDX Advisor, explains how the CINDX project differs from other ICO projects',
    'feedbackProject#33': 'Jason King',
    'feedbackProject#34': 'Jason King, Chief Commercial Officer, explains what attracts him to CINDX and talks about crucial advantages of the project',

    'mediaNews#1': 'Media',
    'mediaNews#2': 'News',
    // Media
    'mediaNews#3': 'CINDX Aims to Democratize the Modern Financial System',
    'mediaNews#4': 'Even as investors in the cryptocurrency space recognize that they are at the forefront of a new financial revolution, adoption by the general populace is yet to occur. While 3rd parties are slowly entering the space in the form of hedge funds and other investors, very few individuals seem to have taken the step to invest in cryptocurrencies on their own.',
    'mediaNews#5': 'CINDX Announces Plans For ICO Pre-Sale Amidst Release Of Revolutionary Crypto Trading Hub That Allows Users To Follow Expert Traders',
    'mediaNews#6': 'CINDX takes its business seriously with particular attention and cares to legal matters and has taken great pains to ensure that CINDX is as compliant as possible with global regulations.',
    'mediaNews#7': 'How CINDX is Democratizing the Modern Financial System',
    'mediaNews#8': 'CINDX is a new platform that is making crypto trading easier, more secure, and more accessible. With this platform, it’s possible to have your funds traded without high fees or minimum investments, with the added security and transparency of blockchain technology.',
    'mediaNews#9': 'CINDX is making crypto trading easier, more secure, and more accessible.',
    'mediaNews#10': 'Cryptocurrency and blockchain technology have been slated as powerful tools capable of fueling a global financial revolution. There are myriad opportunities to invest in the crypto space, and yet, very few individuals have undertaken the steps necessary to invest.',
    'mediaNews#11': 'CINDX Announces Plans Release Of Revolutionary Crypto Trading Hub',
    'mediaNews#12': 'The CINDX platform creates a complete ecosystem for cryptocurrency trading that is favorable to all the participants of the market and offers solutions to existing pain points.',
    'mediaNews#13': 'CINDX Announces Plans For ICO Pre-Sale',
    'mediaNews#14': 'CINDX made headlines this week with the announcement that they will be opening their ICO Pre-Sale in late August after investors interest in the ICO peaks to new levels.',
    'mediaNews#15': 'CINDX Will Be Opening ICO Pre-Sale in late August',
    'mediaNews#16': 'The CINDX Crypto trading platform has a myriad of features and benefits that haven’t been seen in other platforms to date.',
    'mediaNews#17': '5 Tips from CINDX Crypto Assets Management Hub: How to Avoid Being Cheated',
    'mediaNews#18': 'The team behind the CINDX crypto assets management hub has created a helpful set of guidelines on how not to become victims of unfair play, so you can learn what should be primarily taken into account when evaluating ICOs before investing in them.',
    // News
    'mediaNews#19': 'CINDX meets Ian Balina',
    'mediaNews#20': 'CINDX pitch to the one of the TOP10 crypto gurus in the world in the Cryptobazar event.',
    'mediaNews#21': 'CINDX took part in Moscow ICO Summit 2018',
    'mediaNews#22': 'CINDX team introduced the project to the Russian crypto community during ICO Summit event.',
    'mediaNews#23': 'How CINDX is ensuring legal compliance',
    'mediaNews#24': 'Our company is registered in Estonia. Why? The answer is simple — the authorities of Estonia have created a strong and innovative legal infrastructure...',
    'mediaNews#25': 'Keith Teare Co-founder of Accelerated Digital Ventures and Founding Shareholder in TechCrunch',
    'mediaNews#26': 'We continue to introduce CINDX advisers, find out what they...',
    'mediaNews#27': 'Meet world\'s first financial crypto social network',
    'mediaNews#28': 'Every day our team takes one more step on the way to creation and start...',
    'mediaNews#29': 'Denis Eskenazi CINDX Product Marketing Director',
    'mediaNews#30': 'We continue to tell about the CINDX team and each team member’s professional experience. Please, read about Denis Eskenazi...',
    'mediaNews#31': 'CINDX crypto currency exchange license',
    'mediaNews#32': 'Our company in Estonia has received Crypto Currency Exchange License. This allows CINDX to provide fiat-to-crypto exchange services. This licence is issued...',
    'mediaNews#33': 'Austin Kimm Co-founder of Crypterium & CINDS Adviser',
    'mediaNews#34': 'We continue to introduce CINDX advisers, find out what they are proud...',
    'mediaNews#35': 'The strategic meeting of the international CINDX team',
    'mediaNews#36': 'Every day our team takes one more step on the way to creation and start of the CINDX platform. Our work...',
    'mediaNews#37': 'Artur Shamalov CINDX Investment Director',
    'mediaNews#38': 'We continue to introduce the CINDX team. Our next article is about Artur Shamalov, a skilled...',
    'mediaNews#39': 'The issuance of CINX tokens',
    'mediaNews#40': 'The issuance of CINX tokens will be carried out according to the license of The Estonian Financial Supervisory Authority (EFSA). What is a token...',
    'mediaNews#41': '"Amarpreet Singh Co-Founding Member of Malta Blockchain Association & CINDX adviser"',
    'mediaNews#42': 'We at CINDX are incredibly proud to present our advisers, tell the world about their achievements and why they have decided to become a part of the CINDX...',
    'mediaNews#43': 'CINDX meets Vangoo Capital Partners Fund',
    'mediaNews#44': 'Today we have welcomed Kevin Shang from Vangoo Capital Partners and his colleagues in our office. We have discussed business partnership opportunities in order to attract investors from the Asian region.',
    'mediaNews#45': '"Mofassair Hossain CINDX Chief Marketing Officer."',
    'mediaNews#46': 'We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly excited about...',
    'mediaNews#47': 'How CINDX ensures safety for its users - KYC',
    'mediaNews#48': 'Every crypto enthusiast knows that a KYC procedure is necessary in order to protect investors against fraudulent actions of the third...',
    'mediaNews#49': 'Philip Staehelin 25 Years of Consulting and Entrepreneurial Experience',
    'mediaNews#50': 'We continue our regular series of articles dedicated to introducing CINDX advisers. The next item is about Philip Staehelin.',
    'mediaNews#51': 'CINDX meets 9coin Digital Asses Exchange',
    'mediaNews#52': 'The CINDX team continues active work on building relationships with various international companies. One of the most important directions of business...',
    'mediaNews#53': 'Jason King Interim Chief Commercial Officer',
    'mediaNews#54': 'The core of any great project is always people who make the unique idea come true. We would like to tell about...',
    'mediaNews#55': 'CINDX Presents the project during RICLUB private investors meeting',
    'mediaNews#56': 'CINDX has successfully passed the due diligence procedure requested by RICLub and was one of the few projects...',
    'mediaNews#57': 'Sofja Pevzner CINDX Personal Data Officer',
    'mediaNews#58': 'We continue to introduce our team and tell about what inspires our colleagues to work with CINDX. Please read about...',
    'mediaNews#59': 'Tyler Sanford 8+ years digital marketing in Yelp, Zenefits',
    'mediaNews#60': 'We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become a part of the CINDX team. In this...',
    'mediaNews#61': 'CINDX - Key points to observe',
    'mediaNews#62': 'The CINDX project is a valuable business venture with the features that are critically relevant for its participants. In this article we talk about Strengths...',
    'mediaNews#63': 'Airat Shayhulov CINDX Head of Quantitative Research.',
    'mediaNews#64': 'In “TEAM” series of the articles, we tell about people who every day participates in the creation...',
    'mediaNews#65': 'CINDX license of the financial consultant',
    'mediaNews#66': 'CINDX has obtained a termless operating licence (the FFA 000254 license) that gives the right to operate as a financial institution...',
    'mediaNews#67': '"Graham Doggart 20 Years of Enterprise Development and Fintech Marketing Compliance"',
    'mediaNews#68': 'We continue our regular series of articles dedicated to introducing CINDX advisers. The next item...',
    'mediaNews#69': 'CINDX continues the roadshow in China!',
    'mediaNews#70': 'The CINDX team is glad to announce participation as a Golden Sponsor of Borderless Blockchain Technology Summit 2018, which...',
    'mediaNews#71': 'Ibraghim Haniev CINDX Tech Lead',
    'mediaNews#72': 'Get to know more about the CINDX team! The core of any great project is always people who make the unique ideas come true...',
    'mediaNews#73': 'Sadie Hutton 25 Years in Senior Management and Management Consulting',
    'mediaNews#74': 'Like any global project, we understand the importance of professional help and advice. We continue to tell the stories of...',
    'mediaNews#75': 'CINDX.talk - a service that will help people become wiser in taking financial decisions',
    'mediaNews#76': 'The current digital-world related to the crypto industry is getting crowded with mind-charming digital solutions...',
    'mediaNews#77': '"Val Jerdes CINDX Product Director"',
    'mediaNews#78': 'We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly...',
    'mediaNews#79': 'Bogdan Fiedur Blockchain and cryptocurrency expert, investor, entrepreneur',
    'mediaNews#80': 'We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become...',
    'mediaNews#81': 'Welcome to CINX Token Distribution – it’s not an ICO; it’s an STO',
    'mediaNews#82': 'In this article, we want to make it clear why CINDX chose to hold a Security Token Offering (STO) instead of an Initial...',
    'mediaNews#83': 'CINDX celebrates the “AA” Rating from Top ICO List Audit!',
    'mediaNews#84': 'The results of CINDX’s sincerity to make meaningful changes in people’s ambitions via a unique business model just got appreciated...',
    'mediaNews#85': 'CINDX Weekly digest (30.07.18 - 05.08.18)',
    'mediaNews#86': 'The CINDX team is very excited to share the results of our work for the last week 30.07.18 - 05.08.18!',
    'mediaNews#87': 'Virtual Currency Wallet Services',
    'mediaNews#88': 'CINDX believes that being fluent in legal issues and having a clean, confident and clear legal status is of utmost importance. At the moment, CINDX is going...',
    'mediaNews#89': 'How CINDX Influences Crypto Trading',
    'mediaNews#90': 'How to master the crypto market movements and turn them in one’s favor? This is where CINDX’s effective business model comes into play. Learn more about CINDX on our Medium!',
    'mediaNews#91': 'CINDX Weekly digest (06.08.18 - 12.08.18)',
    'mediaNews#92': 'CINDX continues its regular column - Weekly Digest. We are excited to share the recent achievements of our project! Enjoy your time reading!',
    'mediaNews#93': 'CINDX gets 5.0 rating on TrackICO!',
    'mediaNews#94': 'CINDX continues getting approval from the largest and the most credible rating services. The week has hardly passed after...',
    'mediaNews#95': '"David Gutierrez Investment Relations Officer"',
    'mediaNews#96': 'CINDX is very serious about taking people on crew and proud to introduce them. This article is dedicated to David Gutierrez, CINDX Investment Relations Officer',
    'mediaNews#97': 'ICObench gives 4.8 to CINDX',
    'mediaNews#98': 'The CINDX project has already gained the highest mark of  ‘AA’ from Top ICO List and got a 5.0 rating from TrackICO. Now, we are proud to share...',

    'teamAdvisersPartners#1': 'Team of 50+ Members',
    'teamAdvisersPartners#2': 'Advisers',
    'teamAdvisersPartners#3': 'Our Partners',
    // teamInfo
    'teamAdvisersPartners#4': 'Yuriy Avdeev',
    'teamAdvisersPartners#5': 'Chief Executive Officer',
    'teamAdvisersPartners#6': '13 years in entrepreneurship',
    'teamAdvisersPartners#7': '9 ventures',
    'teamAdvisersPartners#8': '$2m for crypto management',
    'teamAdvisersPartners#9': 'Val Jerdes',
    'teamAdvisersPartners#10': 'Product Director',
    'teamAdvisersPartners#11': '20 years in entrepreneurship',
    'teamAdvisersPartners#12': '3 successful exits',
    'teamAdvisersPartners#13': '4x returns for portfolios',
    'teamAdvisersPartners#14': 'Mofassair Hossain',
    'teamAdvisersPartners#15': 'Chief Marketing Officer',
    'teamAdvisersPartners#16': 'Investor and Adviser of 15+ ICOs',
    'teamAdvisersPartners#17': 'Top Adviser at ICO Bench',
    'teamAdvisersPartners#18': 'GBAP Member',
    'teamAdvisersPartners#19': 'Artur Shamalov',
    'teamAdvisersPartners#20': 'Investment Director',
    'teamAdvisersPartners#21': '15 years in entrepreneurship',
    'teamAdvisersPartners#22': '5000 clients of mixcart.ru',
    'teamAdvisersPartners#23': 'mail.ru invested in dc-daily.ru',
    'teamAdvisersPartners#24': 'Denis Eskenazi',
    'teamAdvisersPartners#25': 'Product Marketing Director',
    'teamAdvisersPartners#26': '7 years in entrepreneurship',
    'teamAdvisersPartners#27': '$2m attracted for clients',
    'teamAdvisersPartners#28': '10 years in branding',
    'teamAdvisersPartners#29': 'Ibraghim Haniev',
    'teamAdvisersPartners#30': 'Tech Lead',
    'teamAdvisersPartners#31': '6 years in entrepreneurship',
    'teamAdvisersPartners#32': '200+ developed site',
    'teamAdvisersPartners#33': 'Information Security focus',
    'teamAdvisersPartners#34': '',
    'teamAdvisersPartners#35': '',
    'teamAdvisersPartners#36': '',
    'teamAdvisersPartners#37': '',
    'teamAdvisersPartners#38': '',
    'teamAdvisersPartners#39': '',
    'teamAdvisersPartners#40': '',
    'teamAdvisersPartners#41': '',
    'teamAdvisersPartners#42': '',
    'teamAdvisersPartners#43': '',
    'teamAdvisersPartners#44': '',
    'teamAdvisersPartners#45': '',
    'teamAdvisersPartners#46': '',
    'teamAdvisersPartners#47': '',
    'teamAdvisersPartners#48': '',
    'teamAdvisersPartners#49': '',
    'teamAdvisersPartners#50': '',
    'teamAdvisersPartners#51': '',
    'teamAdvisersPartners#52': '',
}

export default en
