// Английский
const en = {
    'mainBlock#1': 'Make Your Crypto Investments',
    'mainBlock#2': 'Easy, Secure and Fast.',
    'mainBlock#3': 'Join Our Security Token Sale',

    'icoInfo#1': 'We accept:',
    'icoInfo#2': 'Hard Cap:',
    'icoInfo#3': 'Soft Cap Milestone:',
    'icoInfo#4': 'Listing Agreements are Signed With:',

    'menu#1': 'WHITEPAPER',
    'menu#2': 'PRESENTATION',
    'menu#3': 'ONE PAGER',
    'menu#4': 'FINANCIAL MODEL',
    'menu#5': 'LEGAL DOCS',
    'menu#6': 'EN',
    'menu#7': 'Product',
    'menu#8': 'Sale Details',
    'menu#9': 'Team',
    'menu#10': 'Public Docs',
    'menu#11': 'Test MVP',

    'mailForm#1': 'Wrong email',
    'mailForm#2': 'sending ..',
    'mailForm#3': 'Already was or is not valid, try again',
    'mailForm#4': 'Your email has been sent successfully',
    'mailForm#5': 'an error occurred, try again',
    'mailForm#6': 'GDRP Сompliance',
    'mailForm#7': 'Personal data provided via Subscription form and KYC procedure will be collected in the full compliance with GDRP',
    'mailForm#8': 'The Data Protection Officer  of the project is  Mrs. Sofja Pevzner-Belositski. Contact details: dpo@cindx.io. Any data subject may, at any time, contact Data Protection Officer of directly with any request related to data protection.',
    'mailForm#9': 'Your personal data provided via Subscription form and KYC procedure will be shared to our partners:',
    'mailForm#10': 'ICO Promo',
    'mailForm#11': 'Privacy Policy',
    'mailForm#12': 'Sum & Substance',
    'mailForm#13': 'By default, the personal data provided by subscriber are kept by CINDX, ICO Promo and Sum & Substance for 5 years after registration of subscriber in the system',
    'mailForm#14': 'If you do not agree to this privacy policy, please do not use our site.',
    'mailForm#15': 'By using our site, you consent to the collection and use of information by us. Owing to the global nature of the internet infrastructure, the information you provide may be transferred in transit to countries outside the European Economic Area that do not have similar protections in place regarding your data and its use as set out in this policy.',
    'mailForm#16': 'However, we have taken the steps outlined above to try to improve the security of your information. By submitting your information you consent to these transfers',
    'mailForm#17': 'I agree to process my',
    'mailForm#18': 'personal data',
    'mailForm#19': 'Security Token Sale Starts with',
    'mailForm#20': '25% BONUS',
    'mailForm#21': 'Get it before everyone else does',
    'mailForm#22': 'Token sale starts in',
    'mailForm#23': 'Start from $1',
    'mailForm#24': '1$ later',
    'mailForm#25': 'Your Email',
    'mailForm#26': 'BUY CINX TOKENS',
    'mailForm#27': 'AGREE & SUBMIT',

    'progressBarSale#1': 'Bonuses',
    'progressBarSale#2': 'in CINX',
    'progressBarSale#3': 'Pre-Sale',
    'progressBarSale#4': 'Sale',
    'progressBarSale#5': 'Aug 26',
    'progressBarSale#6': 'Sep 17',
    'progressBarSale#7': 'Oct 8',
    'progressBarSale#8': 'Oct 22',
    'progressBarSale#9': 'Nov 6',
    'progressBarSale#10': 'Nov 19',
    'progressBarSale#11': 'Dec 3',
    'progressBarSale#12': 'Dec 17',

    'cryptoAssetsManagement#1.1': 'CINDX is a Сrypto Asset Management Hub. We solve the problems of investors,',
    'cryptoAssetsManagement#1.2': 'traders and developers',
    'cryptoAssetsManagement#2': 'СINDX.MARKETPLACE FOR INVESTORS',
    'cryptoAssetsManagement#3': 'Don’t worry about your knowledge and experience – the experts of crypto trading are here to help you',
    'cryptoAssetsManagement#4': 'Control your currency: your coins are kept in your wallet at all times',
    'cryptoAssetsManagement#5': 'Only pay if you earn: you will only be charged fees if your portfolio makes money',
    'cryptoAssetsManagement#6': 'TEST MVP',
    'cryptoAssetsManagement#7': 'CINDX.TRADE FOR TRADERS',
    'cryptoAssetsManagement#8': 'You can attract capital with $0 marketing costs',
    'cryptoAssetsManagement#9': 'We provide you with Terminal, App Store, marketplace and other advanced tools to succeed in trading.',
    'cryptoAssetsManagement#10': 'CINDX helps to monetize your reputation and expertise. Your trade history and influence are transparent.',
    'cryptoAssetsManagement#11': 'CINDX.TALK, CINDX.HUB & CINDX.DAO',
    'cryptoAssetsManagement#12': 'CINDX.talk - a social network with a reward for useful content',
    'cryptoAssetsManagement#13': 'CINDX.hub - the component includes a vendor’s account, as well as a hub for testing and integrating third-party software',
    'cryptoAssetsManagement#14': 'CINDX.dao - a component that allows you to implement a voting system for the community based on decentralised autonomous organisation rules',

    'teamLegal#1': 'We Нave a Great Team and a Best-in-class',
    'teamLegal#2': 'Legal and Regulatory Organizational Framework',
    'teamLegal#3': 'CRYPTOCURRENCY EXCHANGE LICENSE',
    'teamLegal#4': 'FINANCIAL INSTITUTION LICENSE',
    'teamLegal#5': 'CRYPTO WALLET LICENSE',
    'teamLegal#6': 'WHITEPAPER',
    'teamLegal#7': 'PRESENTATION',
    'teamLegal#8': 'ONE PAGER',
    'teamLegal#9': 'FINANCIAL MODEL',
    'teamLegal#10': 'LEGAL DOCS',

    'roadmap#1': 'Roadmap',
    'roadmap#2': 'SCENARIO',
    'roadmap#3': 'We are building the base for the CINDX platform. At this step, the Minimum Viable Product (MVP) is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform.',
    'roadmap#4': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be  going through some alterations to add functionalities.  ',
    'roadmap#5': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services.      ',
    'roadmap#6': 'At this stage, the CINDX.market and CINDX.trade components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. ',
    'roadmap#7': 'CINDX.talk will have public and private channels. At this stage, the content will  be able to be  separated. ',
    'roadmap#8': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade is an extremely flexible system of order execution and risk management. The Vendor’s market will appear; however, at this point, the Vendor’s market will only contain applications developed by CINDX and its partners.  ',
    'roadmap#9': 'A tokenized rating system will be added in the final version of CINDX.talk, as well as a new type of product: “algorithmic trading”. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders.   ',
    'roadmap#10': 'We are building the base for the CINDX platform. At this step, the MVP is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform. ',
    'roadmap#11': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be going through some alterations to add functionalities.  ',
    'roadmap#12': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services. Another new component, CINDX.hub, will enable Vendors to develop applications that will analyze the market data that CINDX provides. ',
    'roadmap#13': 'At this stage, the CINDX.market and CINDX.trade components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. An SDK for developers will be released. This should simplify application development and implementation for CINDX.  ',
    'roadmap#14': 'CINDX.talk will have public and private channels. At this stage, the content will be able to be separated. CINDX.hub will integrate Github, which will simplify application development even more.',
    'roadmap#15': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade will be an extremely flexible system of order execution and risk management. CINDX.hub will have a full-scale editor for trading strategies with a testing system based on historical market data.',
    'roadmap#16': 'A tokenized rating system  CINDX.talk will be added in the final version of CINDX.talk. This will provide a system of assessment for CINDX community trading experts. “Algorithmic trading” will also be added. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders. A high-grade platform for a code audit will be created. ',
    'roadmap#17': 'We are building the base for the CINDX platform. At this step, the MVP is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform.',
    'roadmap#18': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be  going through some alterations to add functionalities. ',
    'roadmap#19': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services. Another new component,  CINDX.hub, will enable Vendors to develop applications that will analyze the market data that CINDX provides. The team will develop CINDX.dao, a component that acts as a system for the platform’s revenue distribution to its token holders.       ',
    'roadmap#20': 'At this stage, the CINDX.market and CINDX.trade  components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. An SDK for developers will be released. This should simplify application and implementation development for CINDX.  ',
    'roadmap#21': 'CINDX.talk will have public and private channels. At this stage the content can be separated. CINDX.hub will integrate Github which will simplify application development even more.',
    'roadmap#22': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade will be an extremely flexible system of order execution and risk management. CINDX.hub has a full-scale editor for trading strategies with a testing system based on historical market data. CINDX.dao will receive a voting system for token holders. ',
    'roadmap#23': 'A tokenized rating system CINDX.talk will be added in the final version of CINDX.talk. This will provide a system of assessment for CINDX community trading experts. “Algorithmic trading” will also be added. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders. A high-grade platform for a code audit will be created. ',

    'problemSolving#1': 'Time',
    'problemSolving#2': 'Trust',
    'problemSolving#3': 'Uncertainty',
    'problemSolving#4': 'I have some money to put in the crypto game, but don’t have the time to research and contact professional traders to manage my portfolio',
    'problemSolving#5': 'I have always felt uncomfortable with the idea of handing my money over to someone else to make a profit',
    'problemSolving#6': 'The technology surrounding crypto trading is not user-friendly. I cant figure out how to trade my coins',
    'problemSolving#7': 'CINDX provides the access to rated and trustworthy traders',
    'problemSolving#8': 'On CINDX  platform, your funds will never leave your wallet',
    'problemSolving#9': 'You earn right along with the best traders on the market',
    'problemSolving#10': 'Traders on CINDX are rated according to their history of trading success. Choose the trader that’s right for you quickly',
    'problemSolving#11': 'Our decentralized system and smart contracts allow your funds to be managed without being transferred to another trader',
    'problemSolving#12': 'Every investor in CINDX has the opportunity to have their funds managed by the most succesful traders on the market',
    'problemSolving#13': 'What Kinds of Problems Does CINDX Solve for Investors?',
    'problemSolving#14': 'TEST MVP',

    'howCindxWorks#1': 'Investors',
    'howCindxWorks#2': 'Traders',
    'howCindxWorks#3': 'Vendors',
    'howCindxWorks#4': 'increase their crypto earnings with the portfolio management skills of top traders',
    'howCindxWorks#5': 'earn commissions from the investors that follow them based on their performance and trade strategy',
    'howCindxWorks#6': 'sell advanced trading tools, like trade robots and news widgets.',
    'howCindxWorks#7': 'collects commissions and subscription fees',
    'howCindxWorks#8': 'I’m joining CINDX with crypto assets that  I want to be traded',
    'howCindxWorks#9': 'I’m joining CINDX with trading expertise that will benefit investors',
    'howCindxWorks#10': 'Im joining CINDX with trading apps that will help investors',
    'howCindxWorks#11': 'We’re here to make trading easy, secure, and profitable',
    'howCindxWorks#12': 'In a Nutshell: How CINDX Works',

    'marketAnalytics#1': 'Market Analytics',
    'marketAnalytics#2': 'Global AUM',
    'marketAnalytics#3': 'Investment',
    'marketAnalytics#4': 'Structure of investment',
    'marketAnalytics#5': 'Since 2000, the global trust management market has grown by more than 250%.',
    'marketAnalytics#6': 'This is the result of constant improvements in market tools and the general development of market structuring.',
    'marketAnalytics#7': 'Despite the explosive growth of the cryptocurrency market in 2017, the industry is still in its infancy.',
    'marketAnalytics#8': 'The total market capitalization was $600 billion at the end of 2017 — just 1% of the trust management industry total market capitalization.',
    'marketAnalytics#9': 'WHITEPAPER',
    'marketAnalytics#10': 'PRESENTATION',
    'marketAnalytics#11': 'ONE PAGER',
    'marketAnalytics#12': 'FINANCIAL MODEL',
    'marketAnalytics#13': 'LEGAL DOCS',
    'marketAnalytics#14': 'Geographic Scope',
    'marketAnalytics#15': '25 million potential',
    'marketAnalytics#16': 'clients',
    'marketAnalytics#17': '200,000 potential',
    'marketAnalytics#18': 'transactions every day',
    'marketAnalytics#19': 'More than 225 potential',
    'marketAnalytics#20': 'partners, each with $3-5 billion',

    'tokenSaleDetails#1': 'Token Allocation',
    'tokenSaleDetails#2': 'Team',
    'tokenSaleDetails#3': 'Bounty',
    'tokenSaleDetails#4': 'Advisers',
    'tokenSaleDetails#5': 'Reserve',
    'tokenSaleDetails#6': 'Traders Recruitment Program',
    'tokenSaleDetails#7': 'Token Liquidity Support',
    'tokenSaleDetails#8': 'Available for Sale',
    'tokenSaleDetails#9': 'Token Name:',
    'tokenSaleDetails#10': 'Token Pre-Sale start:',
    'tokenSaleDetails#11': 'Total Emission:',
    'tokenSaleDetails#12': 'Price Per Token:',
    'tokenSaleDetails#13': 'Minimal Investment:',
    'tokenSaleDetails#14': '$ 50 equivalent',
    'tokenSaleDetails#15': 'WHITEPAPER',
    'tokenSaleDetails#16': 'PRESENTATION',
    'tokenSaleDetails#17': 'ONE PAGER',
    'tokenSaleDetails#18': 'FINANCIAL MODEL',
    'tokenSaleDetails#19': 'LEGAL DOCS',
    'tokenSaleDetails#20': 'Use of Proceeds',
    'tokenSaleDetails#21': 'Marketing and PR 21%',
    'tokenSaleDetails#22': 'Research and Development 41%',
    'tokenSaleDetails#23': 'Operations 28%',
    'tokenSaleDetails#24': 'Legal expenses 7%',
    'tokenSaleDetails#25': 'Community Grants 3%',
    'tokenSaleDetails#26': 'Token Deals',
    'tokenSaleDetails#27': 'Token Sale:',
    'tokenSaleDetails#28': 'Token Pre-Sale Bonuses:',
    'tokenSaleDetails#29': 'Aug 26 - Sep 16 - 25% Bonus',
    'tokenSaleDetails#30': 'Sep 17 - Oct 7 - 20% Bonus',
    'tokenSaleDetails#31': 'Token Main Sale Bonuses:',
    'tokenSaleDetails#32': 'Oct 8 - Oct 21 - 17% Bonus',
    'tokenSaleDetails#33': 'Oct 22 - Nov 4 - 15% Bonus',
    'tokenSaleDetails#34': 'Nov 6 - Nov 18 - 13% Bonus',
    'tokenSaleDetails#35': 'Nov 19 - Dec 2 - 10% Bonus',
    'tokenSaleDetails#36': 'Dec 3 - Dec 16 - 5% Bonus',
    'tokenSaleDetails#37': 'Dec 17 - Dec 26 - 0% Bonus',
    'tokenSaleDetails#38': 'buy tokens',
    'tokenSaleDetails#39': 'Token Sale Details',
    'tokenSaleDetails#40': 'During the token sale, investors purchase utility tokens – options [CINXO], which give them the right to receive security tokens [CINX] in the future.',
    'tokenSaleDetails#41': 'Security tokens [CINX] will be issued and distributed following the prospect of emission published on the website of FSA of Estonia https://www.fi.ee/ and cindx.io after the end of the token sale, but no later than Q1 2019.',
    'tokenSaleDetails#42': 'The holder of [CINXO] tokens has the right but no obligation to exchange options for security tokens with a ratio of 1:1 after completing the KYC procedure with identification signature, address confirmation and supply of other documents (see the KYC diagram).',
    'tokenSaleDetails#43': 'Tokens [CINXO] grant the same rights as security tokens apart from the right to participate in revenue distribution with a lock-up and voting on the platform.',

    'legalSchedule#1': 'Legal Schedule',
    'legalSchedule#2': 'RECEIVED LICENSE (FVR000110) TO EXCHANGE VIRTUAL CURRENCY TO FIAT SERVICES',
    'legalSchedule#3': 'APPLIED FOR TRADEMARK REGISTRATION IN ESTONIA AND EU',
    'legalSchedule#4': 'RECEIVED LICENSE (FFA000254) FOR OPERATING AS A FINANCIAL INSTITUTION',
    'legalSchedule#5': 'RECEIVED LICENSE FFA000254 FOR OPERATING AS A FINANCIAL INSTITUTION',
    'legalSchedule#6': 'WORKED OUT PROSPECTUS IN ACCORDANCE WITH ESTONIAN LAW',
    'legalSchedule#7': 'CLAIMED FSA LICENSE (ESTONIAN FINANCIAL SUPERVISION AUTHORITY)',
    'legalSchedule#8': 'RECEIVED LICENSE FOR PROVIDING A VIRTUAL CURRENCY WALLET SERVICE',
    'legalSchedule#9': 'REGISTERED UNDER EXEMPTION D IN SEC',
    'legalSchedule#10': 'APPOINTED A PERSONAL DATA MANAGER TO MEET GDPR REQUIREMENTS',
    'legalSchedule#11': 'RECEIVED THE FSA LICENSE',
    'legalSchedule#12': 'REGISTERED THE PROSPECTUS EU 809-2004',
    'legalSchedule#13': 'ISSUED CINX SECURITY TOKENS',

    'feedbackProject#1': 'Feedback On Our Project',
    'feedbackProject#2': 'Val Jerdes',
    'feedbackProject#3': 'Product Director',
    'feedbackProject#4': 'Val Jerdes, CINDX Product Director talks about the key team members and how their expertise will help develop the project that can change the game of finance in a significant way',
    'feedbackProject#5': 'Denis Eskenazi',
    'feedbackProject#6': 'Product Marketing Director',
    'feedbackProject#7': 'Denis Eskenazi, CINDX Product Marketing Director explains why he has joined CINDX',
    'feedbackProject#8': 'Philip Staehelin',
    'feedbackProject#9': 'Adviser',
    'feedbackProject#10': 'Philip Staehelin, Adviser of CINDX project, explains how the cryptocurrency revolution can help even inexperienced investors and tells about the breakthrough that CINDX project prepared for the crypto market',
    'feedbackProject#11': 'Andrzej Cichowlaz',
    'feedbackProject#12': 'Marketing Specialist',
    'feedbackProject#13': 'Andrzej Cichowlaz, CINDX Marketing Manager tells why he believes in the project`s success',
    'feedbackProject#14': 'Austin Kimm',
    'feedbackProject#15': 'Austin Kimm, Adviser of CINDX project tells how CINDX makes trading cryptocurrency for profit simple and smart',
    'feedbackProject#16': 'Amarpreet Singh',
    'feedbackProject#17': 'Amarpreet Singh, CINDX Adviser explains how CINDX platform can bridge the gap between investors and traders',
    'feedbackProject#18': 'Keith Teare',
    'feedbackProject#19': 'Keith Teare, CINDX Adviser describes advantages of CINDX platform',
    'feedbackProject#20': 'Mansur Rasulov',
    'feedbackProject#21': 'Community Lead',
    'feedbackProject#22': 'Mansur Rasulov, CINDX Community Lead explains why he decided to become a part of CINDX team',
    'feedbackProject#23': 'Sadie Hutton',
    'feedbackProject#24': 'Sadie Hutton, CINDX Adviser explains how CINDX plantform is different from other automated trading platforms',
    'feedbackProject#25': 'Graham Doggart',
    'feedbackProject#26': 'Graham Doggart, CINDX Adviser talks about strengths of CINDX platform',
    'feedbackProject#27': 'Alina Vardanian',
    'feedbackProject#28': 'Content Manager',
    'feedbackProject#29': 'Alina Vardanian, CINDX Content Manager talks about the team spirit and what she loves about her job',
    'feedbackProject#30': 'Bogdan Fiedur',
    'feedbackProject#31': 'CINDX Advisor',
    'feedbackProject#32': 'Bogdan Fiedur, CINDX Advisor, explains how the CINDX project differs from other ICO projects',
    'feedbackProject#33': 'Jason King',
    'feedbackProject#34': 'Jason King, Chief Commercial Officer, explains what attracts him to CINDX and talks about crucial advantages of the project',

    'mediaNews#1': 'Media',
    'mediaNews#2': 'News',
    // Media
    'mediaNews#1_1': 'CINDX Aims to Democratize the Modern Financial System',
    'mediaNews#1_2': 'Even as investors in the cryptocurrency space recognize that they are at the forefront of a new financial revolution, adoption by the general populace is yet to occur. While 3rd parties are slowly entering the space in the form of hedge funds and other investors, very few individuals seem to have taken the step to invest in cryptocurrencies on their own.',
    'mediaNews#1_3': 'CINDX Announces Plans For ICO Pre-Sale Amidst Release Of Revolutionary Crypto Trading Hub That Allows Users To Follow Expert Traders',
    'mediaNews#1_4': 'CINDX takes its business seriously with particular attention and cares to legal matters and has taken great pains to ensure that CINDX is as compliant as possible with global regulations.',
    'mediaNews#1_5': 'How CINDX is Democratizing the Modern Financial System',
    'mediaNews#1_6': 'CINDX is a new platform that is making crypto trading easier, more secure, and more accessible. With this platform, it’s possible to have your funds traded without high fees or minimum investments, with the added security and transparency of blockchain technology.',
    'mediaNews#1_7': 'CINDX is making crypto trading easier, more secure, and more accessible.',
    'mediaNews#1_8': 'Cryptocurrency and blockchain technology have been slated as powerful tools capable of fueling a global financial revolution. There are myriad opportunities to invest in the crypto space, and yet, very few individuals have undertaken the steps necessary to invest.',
    'mediaNews#1_9': 'CINDX Announces Plans Release Of Revolutionary Crypto Trading Hub',
    'mediaNews#1_10': 'The CINDX platform creates a complete ecosystem for cryptocurrency trading that is favorable to all the participants of the market and offers solutions to existing pain points.',
    'mediaNews#1_11': 'CINDX Announces Plans For ICO Pre-Sale',
    'mediaNews#1_12': 'CINDX made headlines this week with the announcement that they will be opening their ICO Pre-Sale in late August after investors interest in the ICO peaks to new levels.',
    'mediaNews#1_13': 'CINDX Will Be Opening ICO Pre-Sale in late August',
    'mediaNews#1_14': 'The CINDX Crypto trading platform has a myriad of features and benefits that haven’t been seen in other platforms to date.',
    'mediaNews#1_15': '5 Tips from CINDX Crypto Assets Management Hub: How to Avoid Being Cheated',
    'mediaNews#1_16': 'The team behind the CINDX crypto assets management hub has created a helpful set of guidelines on how not to become victims of unfair play, so you can learn what should be primarily taken into account when evaluating ICOs before investing in them.',
    'mediaNews#1_17': 'CINDX Crypto Asset Management Hub Adopts Bancor Protocol',
    'mediaNews#1_18': 'CINDX is delighted to announce that a number of new integrations with top industry players are underway, each of which will make the life of the users of the platform easier and richer. These new integrations include the decision to adopt the Bancor protocol to provide continuous liquidity for the CINDX platform.',
    // News
    'mediaNews#2_1': 'CINDX meets Ian Balina',
    'mediaNews#2_2': 'CINDX pitch to the one of the TOP10 crypto gurus in the world in the Cryptobazar event.',
    'mediaNews#2_3': 'CINDX took part in Moscow ICO Summit 2018',
    'mediaNews#2_4': 'CINDX team introduced the project to the Russian crypto community during ICO Summit event.',
    'mediaNews#2_5': 'How CINDX is ensuring legal compliance',
    'mediaNews#2_6': 'Our company is registered in Estonia. Why? The answer is simple — the authorities of Estonia have created a strong and innovative legal infrastructure...',
    'mediaNews#2_7': 'Keith Teare Co-founder of Accelerated Digital Ventures and Founding Shareholder in TechCrunch',
    'mediaNews#2_8': 'We continue to introduce CINDX advisers, find out what they...',
    'mediaNews#2_9': 'Meet world\'s first financial crypto social network',
    'mediaNews#2_10': 'Every day our team takes one more step on the way to creation and start...',
    'mediaNews#2_11': 'Denis Eskenazi CINDX Product Marketing Director',
    'mediaNews#2_12': 'We continue to tell about the CINDX team and each team member’s professional experience. Please, read about Denis Eskenazi...',
    'mediaNews#2_13': 'CINDX crypto currency exchange license',
    'mediaNews#2_14': 'Our company in Estonia has received Crypto Currency Exchange License. This allows CINDX to provide fiat-to-crypto exchange services. This licence is issued...',
    'mediaNews#2_15': 'Austin Kimm Co-founder of Crypterium & CINDS Adviser',
    'mediaNews#2_16': 'We continue to introduce CINDX advisers, find out what they are proud...',
    'mediaNews#2_17': 'The strategic meeting of the international CINDX team',
    'mediaNews#2_18': 'Every day our team takes one more step on the way to creation and start of the CINDX platform. Our work...',
    'mediaNews#2_19': 'Artur Shamalov CINDX Investment Director',
    'mediaNews#2_20': 'We continue to introduce the CINDX team. Our next article is about Artur Shamalov, a skilled...',
    'mediaNews#2_21': 'The issuance of CINX tokens',
    'mediaNews#2_22': 'The issuance of CINX tokens will be carried out according to the license of The Estonian Financial Supervisory Authority (EFSA). What is a token...',
    'mediaNews#2_23': '"Amarpreet Singh Co-Founding Member of Malta Blockchain Association & CINDX adviser"',
    'mediaNews#2_24': 'We at CINDX are incredibly proud to present our advisers, tell the world about their achievements and why they have decided to become a part of the CINDX...',
    'mediaNews#2_25': 'CINDX meets Vangoo Capital Partners Fund',
    'mediaNews#2_26': 'Today we have welcomed Kevin Shang from Vangoo Capital Partners and his colleagues in our office. We have discussed business partnership opportunities in order to attract investors from the Asian region.',
    'mediaNews#2_27': '"Mofassair Hossain CINDX Chief Marketing Officer."',
    'mediaNews#2_28': 'We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly excited about...',
    'mediaNews#2_29': 'How CINDX ensures safety for its users - KYC',
    'mediaNews#2_30': 'Every crypto enthusiast knows that a KYC procedure is necessary in order to protect investors against fraudulent actions of the third...',
    'mediaNews#2_31': 'Philip Staehelin 25 Years of Consulting and Entrepreneurial Experience',
    'mediaNews#2_32': 'We continue our regular series of articles dedicated to introducing CINDX advisers. The next item is about Philip Staehelin.',
    'mediaNews#2_33': 'CINDX meets 9coin Digital Asses Exchange',
    'mediaNews#2_34': 'The CINDX team continues active work on building relationships with various international companies. One of the most important directions of business...',
    'mediaNews#2_35': 'Jason King Interim Chief Commercial Officer',
    'mediaNews#2_36': 'The core of any great project is always people who make the unique idea come true. We would like to tell about...',
    'mediaNews#2_37': 'CINDX Presents the project during RICLUB private investors meeting',
    'mediaNews#2_38': 'CINDX has successfully passed the due diligence procedure requested by RICLub and was one of the few projects...',
    'mediaNews#2_39': 'Sofja Pevzner CINDX Personal Data Officer',
    'mediaNews#2_40': 'We continue to introduce our team and tell about what inspires our colleagues to work with CINDX. Please read about...',
    'mediaNews#2_41': 'Tyler Sanford 8+ years digital marketing in Yelp, Zenefits',
    'mediaNews#2_42': 'We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become a part of the CINDX team. In this...',
    'mediaNews#2_43': 'CINDX - Key points to observe',
    'mediaNews#2_44': 'The CINDX project is a valuable business venture with the features that are critically relevant for its participants. In this article we talk about Strengths...',
    'mediaNews#2_45': 'Airat Shayhulov CINDX Head of Quantitative Research.',
    'mediaNews#2_46': 'In “TEAM” series of the articles, we tell about people who every day participates in the creation...',
    'mediaNews#2_47': 'CINDX license of the financial consultant',
    'mediaNews#2_48': 'CINDX has obtained a termless operating licence (the FFA 000254 license) that gives the right to operate as a financial institution...',
    'mediaNews#2_49': '"Graham Doggart 20 Years of Enterprise Development and Fintech Marketing Compliance"',
    'mediaNews#2_50': 'We continue our regular series of articles dedicated to introducing CINDX advisers. The next item...',
    'mediaNews#2_51': 'CINDX continues the roadshow in China!',
    'mediaNews#2_52': 'The CINDX team is glad to announce participation as a Golden Sponsor of Borderless Blockchain Technology Summit 2018, which...',
    'mediaNews#2_53': 'Ibraghim Haniev CINDX Tech Lead',
    'mediaNews#2_54': 'Get to know more about the CINDX team! The core of any great project is always people who make the unique ideas come true...',
    'mediaNews#2_55': 'Sadie Hutton 25 Years in Senior Management and Management Consulting',
    'mediaNews#2_56': 'Like any global project, we understand the importance of professional help and advice. We continue to tell the stories of...',
    'mediaNews#2_57': 'CINDX.talk - a service that will help people become wiser in taking financial decisions',
    'mediaNews#2_58': 'The current digital-world related to the crypto industry is getting crowded with mind-charming digital solutions...',
    'mediaNews#2_59': '"Val Jerdes CINDX Product Director"',
    'mediaNews#2_60': 'We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly...',
    'mediaNews#2_61': 'Bogdan Fiedur Blockchain and cryptocurrency expert, investor, entrepreneur',
    'mediaNews#2_62': 'We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become...',
    'mediaNews#2_63': 'Welcome to CINX Token Distribution – it’s not an ICO; it’s an STO',
    'mediaNews#2_64': 'In this article, we want to make it clear why CINDX chose to hold a Security Token Offering (STO) instead of an Initial...',
    'mediaNews#2_65': 'CINDX celebrates the “AA” Rating from Top ICO List Audit!',
    'mediaNews#2_66': 'The results of CINDX’s sincerity to make meaningful changes in people’s ambitions via a unique business model just got appreciated...',
    'mediaNews#2_67': 'CINDX Weekly digest (30.07.18 - 05.08.18)',
    'mediaNews#2_68': 'The CINDX team is very excited to share the results of our work for the last week 30.07.18 - 05.08.18!',
    'mediaNews#2_69': 'Virtual Currency Wallet Services',
    'mediaNews#2_70': 'CINDX believes that being fluent in legal issues and having a clean, confident and clear legal status is of utmost importance. At the moment, CINDX is going...',
    'mediaNews#2_71': 'How CINDX Influences Crypto Trading',
    'mediaNews#2_72': 'How to master the crypto market movements and turn them in one’s favor? This is where CINDX’s effective business model comes into play. Learn more about CINDX on our Medium!',
    'mediaNews#2_73': 'CINDX Weekly digest (06.08.18 - 12.08.18)',
    'mediaNews#2_74': 'CINDX continues its regular column - Weekly Digest. We are excited to share the recent achievements of our project! Enjoy your time reading!',
    'mediaNews#2_75': 'CINDX gets 5.0 rating on TrackICO!',
    'mediaNews#2_76': 'CINDX continues getting approval from the largest and the most credible rating services. The week has hardly passed after...',
    'mediaNews#2_77': '"David Gutierrez Investment Relations Officer"',
    'mediaNews#2_78': 'CINDX is very serious about taking people on crew and proud to introduce them. This article is dedicated to David Gutierrez, CINDX Investment Relations Officer',
    'mediaNews#2_79': 'ICObench gives 4.8 to CINDX',
    'mediaNews#2_80': 'The CINDX project has already gained the highest mark of  ‘AA’ from Top ICO List and got a 5.0 rating from TrackICO. Now, we are proud to share...',
    'mediaNews#2_81': 'Dip your Toe in Crypto',
    'mediaNews#2_82': 'It is never late to change your mind. It’s no surprise that Wall Street bankers change their minds in favour of crypto. Enjoy reading CINDX review on the current market situation!',
    'mediaNews#2_83': 'Yuriy Avdeev, CEO of the CINDX project',
    'mediaNews#2_84': 'Enjoy reading what inspired Yuriy Avdeev to create a project that will help all participants of the crypto market to be profitably engaged - CINDX.',
    'mediaNews#2_85': 'Weekly digest (13.08.18 - 19.08.18)',
    'mediaNews#2_86': 'CINDX continues its regular Weekly Digest column. We are excited to share our project’s progress and the most recent achievements! We are glad to remind you that CINDX security token Pre-sale starts this Sunday. Don\'t miss!',
    'mediaNews#2_87': 'Dip your Toe in Crypto',
    'mediaNews#2_88': "It is never late to change your mind. It’s no surprise that Wall Street bankers change their minds in favour of crypto. Enjoy reading CINDX review on the current market situation!",
    'mediaNews#2_89': 'Yuriy Avdeev, CEO of the CINDX project',
    'mediaNews#2_90': 'Enjoy reading what inspired Yuriy Avdeev to create a project that will help all participants of the crypto market to be profitably engaged - CINDX.',
    'mediaNews#2_91': 'Weekly digest (13.08.18 - 19.08.18)',
    'mediaNews#2_92': 'CINDX continues its regular Weekly Digest column. We are excited to share our project’s progress and the most recent achievements! We are glad to remind you that CINDX security token Pre-sale starts this Sunday. Don"t miss',

    'teamAdvisersPartners#1': 'Team of 50+ Members',
    'teamAdvisersPartners#2': 'Advisers',
    'teamAdvisersPartners#3': 'Our Partners',
    // teamInfo
    'teamAdvisersPartners#4': 'Yuriy Avdeev',
    'teamAdvisersPartners#5': 'Chief Executive Officer',
    'teamAdvisersPartners#6': '13 years in entrepreneurship',
    'teamAdvisersPartners#7': '9 ventures',
    'teamAdvisersPartners#8': '$2m for crypto management',
    'teamAdvisersPartners#9': 'Val Jerdes',
    'teamAdvisersPartners#10': 'Product Director',
    'teamAdvisersPartners#11': '20 years in entrepreneurship',
    'teamAdvisersPartners#12': '3 successful exits',
    'teamAdvisersPartners#13': '4x returns for portfolios',
    'teamAdvisersPartners#14': 'Mofassair Hossain',
    'teamAdvisersPartners#15': 'Chief Marketing Officer',
    'teamAdvisersPartners#16': 'Investor and Adviser of 15+ ICOs',
    'teamAdvisersPartners#17': 'Top Adviser at ICO Bench',
    'teamAdvisersPartners#18': 'GBAP Member',
    'teamAdvisersPartners#19': 'Artur Shamalov',
    'teamAdvisersPartners#20': 'Investment Director',
    'teamAdvisersPartners#21': '15 years in entrepreneurship',
    'teamAdvisersPartners#22': '5000 clients of mixcart.ru',
    'teamAdvisersPartners#23': 'mail.ru invested in dc-daily.ru',
    'teamAdvisersPartners#24': 'Denis Eskenazi',
    'teamAdvisersPartners#25': 'Product Marketing Director',
    'teamAdvisersPartners#26': '7 years in entrepreneurship',
    'teamAdvisersPartners#27': '$2m attracted for clients',
    'teamAdvisersPartners#28': '10 years in branding',
    'teamAdvisersPartners#29': 'Ibraghim Haniev',
    'teamAdvisersPartners#30': 'Tech Lead',
    'teamAdvisersPartners#31': '6 years in entrepreneurship',
    'teamAdvisersPartners#32': '200+ developed site',
    'teamAdvisersPartners#33': 'Information Security focus',
    'teamAdvisersPartners#34': 'Airat Shaikhulov',
    'teamAdvisersPartners#35': 'Head of Quantitative Research',
    'teamAdvisersPartners#36': 'Dr of science at MSU',
    'teamAdvisersPartners#37': 'Aton-line navigator developer',
    'teamAdvisersPartners#38': 'Head of algorithmic trading',
    'teamAdvisersPartners#39': 'Sofja Pevzner',
    'teamAdvisersPartners#40': 'Personal Data Officer',
    'teamAdvisersPartners#41': '5 years in entrepreneurship',
    'teamAdvisersPartners#42': 'Permisson of estonian AML office',
    'teamAdvisersPartners#43': '8 years of legal work expirience',
    'teamAdvisersPartners#44': 'Dave Gutierrez',
    'teamAdvisersPartners#45': 'Investment Relations Officer',
    'teamAdvisersPartners#46': '5 years in aircraft leasing',
    'teamAdvisersPartners#47': '3 years in investment promotion',
    'teamAdvisersPartners#48': '2 years in russian deals abroad',
    'teamAdvisersPartners#49': 'Jelena Karzetskaja',
    'teamAdvisersPartners#50': 'Compliance Adviser',
    'teamAdvisersPartners#51': 'holds several degrees in law',
    'teamAdvisersPartners#52': 'judicial practice since 1997',
    'teamAdvisersPartners#53': 'legal spheres: international law',
    'teamAdvisersPartners#54': 'Wang Dong',
    'teamAdvisersPartners#55': 'Specialist in Chinese market',
    'teamAdvisersPartners#56': '3 years in php/ JavaScript',
    'teamAdvisersPartners#57': '5 years in SEO/SMM/media buyer',
    'teamAdvisersPartners#58': '2 years in token sale in China',
    // advisers
    'teamAdvisersPartners#59': 'Keith Teare',
    'teamAdvisersPartners#60': 'Founder and Executive Chairman at Accelerated Digital Ventures',
    'teamAdvisersPartners#61': 'Adviser to ICOBox, Crypterium, EnergiMine, etc.',
    'teamAdvisersPartners#62': 'Founding shareholder of TechCrunch',
    'teamAdvisersPartners#63': 'I am Executive Chairman and Chair of the Investment Committee at Accelerated Digital Ventures - a UK Venture Company. I was born and raised in the UK.',
    'teamAdvisersPartners#64': 'Previously I was founder and a partner at Archimedes Labs in Palo Alto, California. I love working with founders, teams, designers and engineers to create products, tell stories, and turn them into reality. I have founded or co-founded many companies myself since the early 1980s. Some were successfully sold, others IPO\'d.',
    'teamAdvisersPartners#65': 'Two of my companies were Unicorns - valued by others at more than $1 billion. I have always focused on the point at which change is happening. In the 1980\'s networking and databases. In the 1994-1998 period, Internet Access. From 1998-2010 - Web Services and Content, Mobile Consumer Applications and since 2017 Blockchain.',
    'teamAdvisersPartners#66': 'Career and projects: Tech Crunch, Accelerated Digital Ventures, cScape, EasyNet, Cyberia,  RealNames, Venture Network, ICOBox, Crypterium,  R/Block, Fluz, EnergiMine, Archimedes Labs  and CINDX',
    'teamAdvisersPartners#67': 'Austin Kimm',
    'teamAdvisersPartners#68': 'International Financial Services CEO',
    'teamAdvisersPartners#69': '30+ years of financial service experience',
    'teamAdvisersPartners#70': 'Created companies with a worth of $500m',
    'teamAdvisersPartners#71': 'Experienced results proven financial services CEO with a particular focus on building insurance businesses in developing markets where I have successfully built companies with a current valuation in excess $500m, most recently in Russia (10 years), as well as other non insurance senior management roles, including CEO of Russia\'s largest internet sales employment platform, Workle, and a wide range of fintech start up C level positions including Crypterium, the world\'s first digital cryptobank.',
    'teamAdvisersPartners#72': 'Most recently in Russia (10 years), as well as other non insurance senior management roles, including CEO of Russia\'s largest internet sales employment platform, Workle, and a wide range of fintech start up C level positions including Crypterium, the world\'s first digital cryptobank.',
    'teamAdvisersPartners#73': 'Career and projects: Aviva, Commercial Union UK, Reinaissance Insurance, Kimm Health & Leisure Ltd, Workle, Crypterium, CryptoIndex, CINDX',
    'teamAdvisersPartners#74': 'Philip Staehelin',
    'teamAdvisersPartners#75': '25 years of consulting and entrepreneurial experience',
    'teamAdvisersPartners#76': '$500m alternative payments business under leadership',
    'teamAdvisersPartners#77': '200+ startups from 20 countries mentored',
    'teamAdvisersPartners#78': 'I\'m an innovator and a leader who blends contagious optimism with pragmatic realism. I find opportunity where others see none.',
    'teamAdvisersPartners#79': 'I\'ve leveraged my ability to "see things differently" and "make things happen" in corporate, consulting and start-up environments - all giving me broad new perspectives that provide fodder for new transformative ideas.',
    'teamAdvisersPartners#80': 'Finding solutions to hard challenges is what gets me out of bed in the morning.',
    'teamAdvisersPartners#81': 'Career and projects: BCG, Spectacler, Transparency International, StartupYard, Bethreum, Gjirafa Inc, Direct People, CINDX',
    'teamAdvisersPartners#82': 'Amarpreet Singh',
    'teamAdvisersPartners#83': 'Senior Adviser of Global Blockchain Foundation',
    'teamAdvisersPartners#84': 'Experience in Microsoft, The World Bank and Airbus',
    'teamAdvisersPartners#85': 'Advisery Board Member of Blockchain projects',
    'teamAdvisersPartners#86': 'Technology/Digital enthusiast and a seasoned professional with years of experience in Tech industry – operations, consulting and innovation.',
    'teamAdvisersPartners#87': 'He is a certified Cloud (Microsoft and AWS) specialist. Known for versatility and flexibility. Excellent analytic, strategic, leadership skills and a team player at its best.',
    'teamAdvisersPartners#88': 'Specialties: Technology Consulting, Operations, Cloud Computing, Fintech, Innovation, ERP, Machine Learning, Account Management, Partner Development, Business Development and Strategy',
    'teamAdvisersPartners#89': 'Amarpreet Singh has a very diversified work and educational background. He holds three Masters degrees and has lived/worked/studied in India, Singapore, France, China, South Africa, Korea, Canada.',
    'teamAdvisersPartners#90': 'Career and projects: Microsoft, The World Bank, Airbus, TokenAsia Platform, GOeurika, CINDX',
    'teamAdvisersPartners#91': 'Tyler Sanford',
    'teamAdvisersPartners#92': '8 Years Digital Marketing in Yelp and Zenefits',
    'teamAdvisersPartners#93': '12 ICO’s over $225M raised',
    'teamAdvisersPartners#94': 'Early adopter of blockchain',
    'teamAdvisersPartners#95': 'Growing up as an Athlete has given me a skill set that I\'ve been able to apply to my careers and personal life.',
    'teamAdvisersPartners#96': 'I have been very fortunate to see the results of going that extra mile, while learning to deal with the highs and lows that go along with all professional careers.',
    'teamAdvisersPartners#97': 'I\'m an extremely self-motivated individual, always looking to continue my growth of knowledge and talents in all aspects of business.',
    'teamAdvisersPartners#98': 'Always up for a challenge, my motivation comes from overcoming obstacles to reach my goals',
    'teamAdvisersPartners#99': 'Career and projects: IPG Holdings, DataBlockChain, TraXion by Puma Technologies, ELYSIAN, Etherinc, FTEC Foundation,  CINDX',
    'teamAdvisersPartners#100': 'Philip Staehelin',
    'teamAdvisersPartners#101': '25 years of consulting and entrepreneurial experience',
    'teamAdvisersPartners#102': '$500m alternative payments business under leadership',
    'teamAdvisersPartners#103': '200+ startups from 20 countries mentored',
    'teamAdvisersPartners#104': 'I\'m an innovator and a leader who blends contagious optimism with pragmatic realism. I find opportunity where others see none.',
    'teamAdvisersPartners#105': 'I\'ve leveraged my ability to "see things differently" and "make things happen" in corporate, consulting and start-up environments - all giving me broad new perspectives that provide fodder for new transformative ideas.',
    'teamAdvisersPartners#106': 'Finding solutions to hard challenges is what gets me out of bed in the morning.',
    'teamAdvisersPartners#107': 'Career and projects: BCG, Spectacler, Transparency International, StartupYard, Bethreum, Gjirafa Inc, Direct People, CINDX',
    'teamAdvisersPartners#108': 'Senior Adviser of Global Blockchain Foundation',
    'teamAdvisersPartners#109': 'Experience in Microsoft, The World Bank and Airbus',
    'teamAdvisersPartners#110': 'Advisery Board Member of Blockchain projects',
    'teamAdvisersPartners#111': 'Technology/Digital enthusiast and a seasoned professional with years of experience in Tech industry – operations, consulting and innovation.',
    'teamAdvisersPartners#112': 'He is a certified Cloud (Microsoft and AWS) specialist. Known for versatility and flexibility. Excellent analytic, strategic, leadership skills and a team player at its best.',
    'teamAdvisersPartners#113': 'Specialties: Technology Consulting, Operations, Cloud Computing, Fintech, Innovation, ERP, Machine Learning, Account Management, Partner Development, Business Development and Strategy',
    'teamAdvisersPartners#114': 'Amarpreet Singh has a very diversified work and educational background. He holds three Masters degrees and has lived/worked/studied in India, Singapore, France, China, South Africa, Korea, Canada.',
    'teamAdvisersPartners#115': 'Career and projects: Microsoft, The World Bank, Airbus, TokenAsia Platform, GOeurika, CINDX',
    'teamAdvisersPartners#116': 'Tyler Sanford',
    'teamAdvisersPartners#117': '8 Years Digital Marketing in Yelp and Zenefits',
    'teamAdvisersPartners#118': '12 ICO’s over $225M raised',
    'teamAdvisersPartners#119': 'Early adopter of blockchain',
    'teamAdvisersPartners#120': 'Growing up as an Athlete has given me a skill set that I\'ve been able to apply to my careers and personal life.',
    'teamAdvisersPartners#121': 'I have been very fortunate to see the results of going that extra mile, while learning to deal with the highs and lows that go along with all professional careers.',
    'teamAdvisersPartners#122': 'I\'m an extremely self-motivated individual, always looking to continue my growth of knowledge and talents in all aspects of business.',
    'teamAdvisersPartners#123': 'Always up for a challenge, my motivation comes from overcoming obstacles to reach my goals',
    'teamAdvisersPartners#124': 'Career and projects: IPG Holdings, DataBlockChain, TraXion by Puma Technologies, ELYSIAN, Etherinc, FTEC Foundation,  CINDX',
    'teamAdvisersPartners#125': 'Bogdan Fiedur',
    'teamAdvisersPartners#126': 'Blockchain and cryptocurrency expert, investor, entrepreneur',
    'teamAdvisersPartners#127': 'Co-Founder of bitJob and President of Blockchainexperts.io',
    'teamAdvisersPartners#128': 'ICO Adviser, ICOBench Expert',
    'teamAdvisersPartners#129': 'Bogdan Fiedur is a smart contract developer, crypto-investor, entrepreneur and President of http://blockchainexperts.io . He has over 20 years of IT experience in building e-commerce websites and has been involved in blockchain development during last 3 years.',
    'teamAdvisersPartners#130': 'He is also an ICO adviser working with 20 successful ICOs to date and deeply involved in offering presentation and workshops on blockchain and smart contract programming in his local crypto community of Winnipeg.',
    'teamAdvisersPartners#131': 'Bogdan now focuses on the Blockchain industry and offers advice, consulting services and connections to Blockchain experts. Most recently Bogdan has co-founded ‘Bitjob’, a freelancer blockchain platform for students and participated in several ICO projects as a team member. e.g. PayPie.com.',
    'teamAdvisersPartners#132': 'Career and projects: US Blockchain Association, Tuurnt, Trends Project, BiNeuro, Zichain, Graphen Tech, CyClean, Swachhcoin, CINDX',
    'teamAdvisersPartners#133': 'Graham Doggart',
    'teamAdvisersPartners#134': '20 years of enterprise development, fintech marketing compliance',
    'teamAdvisersPartners#135': 'Executed campaigns with a worth of $100m',
    'teamAdvisersPartners#136': 'Adviser for 10+ blockchain projects this year',
    'teamAdvisersPartners#137': 'I am chairman of a Stealth Cryptocurrency Project and co-founder and lead strategist at Dynamic Abundance, a Blockchain and Fintech Advisery since 2012.',
    'teamAdvisersPartners#138': 'I specialise in the structuring and packaging of token offerings and have worked with numerous blockchain, cryptocurrency and ICO projects internationally.',
    'teamAdvisersPartners#139': 'For more than 20 years I have provided tech management consultation, legal and financial compliance advice, growth strategies, investor relations, as well as design and authorship of materials.',
    'teamAdvisersPartners#140': 'Career and projects: Stealth Cryptocurrency Project, Dynamic Abundance, ELYSIAN, Fox Trading FX, Profede, Worltdopoly, CINDX',
    'teamAdvisersPartners#141': 'Sadie Hutton',
    'teamAdvisersPartners#142': '25 years in senior management and management consulting',
    'teamAdvisersPartners#143': 'Multimillion-dollar fundraiser with campaigns with a worth of £75m',
    'teamAdvisersPartners#144': 'ICO Adviser of 8 projects',
    'teamAdvisersPartners#145': 'I am the founder of Dynamic Abundance, a blockchain advisery.',
    'teamAdvisersPartners#146': 'Preferring a “hands-on” approach, I am a specialist in ICO analysis, project management, all key aspects of the ICO process. I am skilled in business management and growth, which enable me to see a project from inception through to delivery. I am a problem solver by nature, and I take any project I am involved with personally. I like to win!',
    'teamAdvisersPartners#147': 'With over 20 years of management experience I built up a powerful network, I actively advise on finance, tech, sales, marketing and quality assurance for high-level blockchain projects.',
    'teamAdvisersPartners#148': 'Career and projects: Dynamic Abundance, ELYSIAN, Worldopoly, Confidential ICO,  Fox Trading FX, Profede, Market Digital, CINDX',
    'teamAdvisersPartners#149': 'Jason King',
    'teamAdvisersPartners#150': '20 years of excecutive experience',
    'teamAdvisersPartners#151': 'Led businesses operations in 30 countries',
    'teamAdvisersPartners#152': 'Responsible over $500m P&L',
    'teamAdvisersPartners#153': 'For almost 20 years, Jason has been a senior technology, media and telecoms executive involved in structuring and brokering commercial deals, negotiating wins, building markets and positioning organizations for success.',
    'teamAdvisersPartners#154': 'The core theme in his career has been to successfully drive business restructuring, transformation and turnaround programs - by leading the right people and teams towards the most profitable goals.',
    'teamAdvisersPartners#155': 'In addition to his interests in private equity and startup companies, Jason has worked in various groups including Deutsche Telekom, Telenor and UPC Liberty Global and Veon.',
    'teamAdvisersPartners#156': 'Jason has either worked or has led business directly in over 30 countries and has previously held commercial P&L responsibilities in the $500M-$1B range.',
    'teamAdvisersPartners#157': 'Motti Peer',
    'teamAdvisersPartners#158': 'Co-founder of Blonde 2.0, award-winning global PR agency',
    'teamAdvisersPartners#159': 'Founder of various companies in the security and finance sectors',
    'teamAdvisersPartners#160': 'Motti is one of the leading forces in PR for Blockchain and Crypto, startups, VCs.',
    'teamAdvisersPartners#161': 'Motti founded various companies in the security and finance sectors. He has many years of experience as a money and hedge fund manager and holds an MBA in Finance and Marketing from Manchester University and a BA in Business Management from Fairleigh Dickinson University',
    'teamAdvisersPartners#162': 'He is a Co-CEO of Blonde 2.0, an award-winning global PR agency also named as one the startup nation’s “Movers and Shakers” on Forbes. As Co-CEO of Blonde 2.0, he is responsible for handling the Public Relations aspects, along with strategy and crisis management.',
    'teamAdvisersPartners#163': 'With a team of 35 professionals, Blonde 2.0 is one of the leading forces in PR for Blockchain and Crypto, startups, VCs.',
    'teamAdvisersPartners#164': 'Leonard Grayver',
    'teamAdvisersPartners#165': 'Сhair of Greenberg Whitcombe Takeuchi Gibson & Grayver LLP',
    'teamAdvisersPartners#166': 'Represented and advised a number of successful ICOs',
    'teamAdvisersPartners#167': 'Has substantial experience in venture capital fund formation',
    'teamAdvisersPartners#168': 'Leonard Grayver was born in USSR, moved to US with his parents as a kid. While in Law school Leonard created a start-up and successfully raised more than 18 mln USD for financing.',
    'teamAdvisersPartners#169': 'Start-up has not survived but since then Leonard has helped more than 400 start-ups',
    'teamAdvisersPartners#170': 'Overall Leonard has more than 10 years of experience with VC financing, fund structuring, due diligence (representing both funds and LPs). His advise to all entrepreneurs - do not follow trends, follow your interests.',

    'joinTokenPreSale#1': 'Join Token Pre-Sale Now!',
    'joinTokenPreSale#2': 'JOIN PRE-SALE',
    'joinTokenPreSale#3': 'TEST MVP',
    'joinTokenPreSale#4': 'Head Office',
    'joinTokenPreSale#5': 'Harjumaa, Erika 14,',
    'joinTokenPreSale#6': 'Talinn, 10416, Estonia',
    'joinTokenPreSale#7': 'Business inquiries | hello@cindx.io',
    'joinTokenPreSale#8': 'Legal Disclaimer',
    'joinTokenPreSale#9': 'Development and Marketing',
    'joinTokenPreSale#10': 'Presnenskaya naberezhnaya, 8 building 1,',
    'joinTokenPreSale#11': 'Moscow, 123112, Russia',
    'joinTokenPreSale#12': 'Careers | Join our team',
}

export default en
