// Испанский
const es = {
    'mainBlock#1': 'Inversión fácil,',
    'mainBlock#2': 'rápida y segura en criptomonedas',
    'mainBlock#3': 'Apúntese a nuestra venta de tokens de seguridad',

    'icoInfo#1': 'Aceptamos:',
    'icoInfo#2': 'Límite estricto:',
    'icoInfo#3': 'Hitos de límite flexible:',
    'icoInfo#4': 'Los acuerdos de venta se firman con',

    'menu#1': 'DOCUMENTO TÉCNICO',
    'menu#2': 'PRESENTACIÓN',
    'menu#3': 'RESUMEN',
    'menu#4': 'MODELO FINANCIERO',
    'menu#5': 'DOCUMENTACIÓN LEGAL',
    'menu#6': 'ES',
    'menu#7': 'Producto',
    'menu#8': 'Detalles de ventas',
    'menu#9': 'Equipo',
    'menu#10': 'Documentos públicos',
    'menu#11': 'Probar versión MVP',

    'mailForm#1': 'Wrong email',
    'mailForm#2': 'sending ..',
    'mailForm#3': 'Already was or is not valid, try again',
    'mailForm#4': 'Your email has been sent successfully',
    'mailForm#5': 'an error occurred, try again',
    'mailForm#6': 'GDRP Сompliance',
    'mailForm#7': 'Personal data provided via Subscription form and KYC procedure will be collected in the full compliance with GDRP',
    'mailForm#8': 'The Data Protection Officer  of the project is  Mrs. Sofja Pevzner-Belositski. Contact details: dpo@cindx.io. Any data subject may, at any time, contact Data Protection Officer of directly with any request related to data protection.',
    'mailForm#9': 'Your personal data provided via Subscription form and KYC procedure will be shared to our partners:',
    'mailForm#10': 'ICO Promo',
    'mailForm#11': 'Privacy Policy',
    'mailForm#12': 'Sum & Substance',
    'mailForm#13': 'By default, the personal data provided by subscriber are kept by CINDX, ICO Promo and Sum & Substance for 5 years after registration of subscriber in the system',
    'mailForm#14': 'If you do not agree to this privacy policy, please do not use our site.',
    'mailForm#15': 'By using our site, you consent to the collection and use of information by us. Owing to the global nature of the internet infrastructure, the information you provide may be transferred in transit to countries outside the European Economic Area that do not have similar protections in place regarding your data and its use as set out in this policy.',
    'mailForm#16': 'However, we have taken the steps outlined above to try to improve the security of your information. By submitting your information you consent to these transfers',
    'mailForm#17': 'I agree to process my',
    'mailForm#18': 'personal data',
    'mailForm#19': 'Security Token Sale Starts with',
    'mailForm#20': '25% BONUS',
    'mailForm#21': 'Get it before everyone else does',
    'mailForm#22': 'Token sale starts in',
    'mailForm#23': 'Start from $1',
    'mailForm#24': '1$ later',
    'mailForm#25': 'Su correo electrónico',
    'mailForm#26': 'Apuntarse a la preventa',
    'mailForm#27': 'AGREE & SUBMIT',

    'progressBarSale#1': 'Bonos',
    'progressBarSale#2': 'en CINX',
    'progressBarSale#3': 'Preventa',
    'progressBarSale#4': 'Venta',
    'progressBarSale#5': 'Agosto 26',
    'progressBarSale#6': 'Sept 17',
    'progressBarSale#7': 'Oct 8',
    'progressBarSale#8': 'Oct 22',
    'progressBarSale#9': 'Nov 6',
    'progressBarSale#10': 'Nov 19',
    'progressBarSale#11': 'Dic 3',
    'progressBarSale#12': 'Dic 17',

    'cryptoAssetsManagement#1.1': 'CIDNX es un centro de gestión de criptoactivos. Solucionamos los problemas de los inversores,',
    'cryptoAssetsManagement#1.2': 'operadores y desarrolladores.',
    'cryptoAssetsManagement#2': 'CINDX.MARKETPLACE PARA INVERSORES',
    'cryptoAssetsManagement#3': 'No se preocupe por su conocimiento o experiencia. Nuestros expertos en operaciones con criptomonedas están aquí para ayudarle.',
    'cryptoAssetsManagement#4': 'Controle sus fondos: sus criptomonedas se mantienen en su cartera en todo momento.',
    'cryptoAssetsManagement#5': 'Solo pagará si obtiene beneficios; es decir, únicamente pagará comisiones si su cartera es rentable.',
    'cryptoAssetsManagement#6': 'Probar versión MVP',
    'cryptoAssetsManagement#7': 'CINDX.TERMINAL PARA OPERADORES',
    'cryptoAssetsManagement#8': 'Los buenos operadores pueden atraer capital con cero inversión en marketing.',
    'cryptoAssetsManagement#9': 'Le proporcionamos Terminal, App Store, Marketplace y otras herramientas avanzadas para ayudarle a operar con éxito.',
    'cryptoAssetsManagement#10': 'CINDX le ayuda a monetizar su reputación y sus conocimientos. Su historial de operaciones y su influencia son transparentes.',
    'cryptoAssetsManagement#11': 'CINDX.TALK, CINDX.HUB y CINDX.DAO',
    'cryptoAssetsManagement#12': 'CINDX.talk - una red social con recompensas para los contenidos útiles.',
    'cryptoAssetsManagement#13': 'CINDX.hub - los componentes incluyen un "gabinete de proveedores", así como un centro para tareas de prueba e integración de software de terceros.',
    'cryptoAssetsManagement#14': 'CINDX.dao - un componente que le permite implementar un sistema de votación para la comunidad basada en reglas de organización autónomas descentralizadas.',

    'teamLegal#1': 'CONTAMOS CON UN INCREÍBLE EQUIPO',
    'teamLegal#2': 'Y DEPARTAMENTO JURÍDICO',
    'teamLegal#3': 'CRYPTOCURRENCY EXCHANGE LICENSE',
    'teamLegal#4': 'FINANCIAL INSTITUTION LICENSE',
    'teamLegal#5': 'CRYPTO WALLET LICENSE',
    'teamLegal#6': 'DOCUMENTO TÉCNICO',
    'teamLegal#7': 'PRESENTACIÓN',
    'teamLegal#8': 'RESUMEN',
    'teamLegal#9': 'MODELO FINANCIERO',
    'teamLegal#10': 'DOCUMENTACIÓN LEGAL',

    'roadmap#1': 'Hoja de ruta',
    'roadmap#2': 'SCENARIO',
    'roadmap#3': 'We are building the base for the CINDX platform. At this step, the Minimum Viable Product (MVP) is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform.',
    'roadmap#4': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be  going through some alterations to add functionalities.  ',
    'roadmap#5': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services.      ',
    'roadmap#6': 'At this stage, the CINDX.market and CINDX.trade components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. ',
    'roadmap#7': 'CINDX.talk will have public and private channels. At this stage, the content will  be able to be  separated. ',
    'roadmap#8': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade is an extremely flexible system of order execution and risk management. The Vendor’s market will appear; however, at this point, the Vendor’s market will only contain applications developed by CINDX and its partners.  ',
    'roadmap#9': 'A tokenized rating system will be added in the final version of CINDX.talk, as well as a new type of product: “algorithmic trading”. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders.   ',
    'roadmap#10': 'We are building the base for the CINDX platform. At this step, the MVP is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform. ',
    'roadmap#11': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be going through some alterations to add functionalities.  ',
    'roadmap#12': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services. Another new component, CINDX.hub, will enable Vendors to develop applications that will analyze the market data that CINDX provides. ',
    'roadmap#13': 'At this stage, the CINDX.market and CINDX.trade components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. An SDK for developers will be released. This should simplify application development and implementation for CINDX.  ',
    'roadmap#14': 'CINDX.talk will have public and private channels. At this stage, the content will be able to be separated. CINDX.hub will integrate Github, which will simplify application development even more.',
    'roadmap#15': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade will be an extremely flexible system of order execution and risk management. CINDX.hub will have a full-scale editor for trading strategies with a testing system based on historical market data.',
    'roadmap#16': 'A tokenized rating system  CINDX.talk will be added in the final version of CINDX.talk. This will provide a system of assessment for CINDX community trading experts. “Algorithmic trading” will also be added. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders. A high-grade platform for a code audit will be created. ',
    'roadmap#17': 'We are building the base for the CINDX platform. At this step, the MVP is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform.',
    'roadmap#18': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be  going through some alterations to add functionalities. ',
    'roadmap#19': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services. Another new component,  CINDX.hub, will enable Vendors to develop applications that will analyze the market data that CINDX provides. The team will develop CINDX.dao, a component that acts as a system for the platform’s revenue distribution to its token holders.       ',
    'roadmap#20': 'At this stage, the CINDX.market and CINDX.trade  components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. An SDK for developers will be released. This should simplify application and implementation development for CINDX.  ',
    'roadmap#21': 'CINDX.talk will have public and private channels. At this stage the content can be separated. CINDX.hub will integrate Github which will simplify application development even more.',
    'roadmap#22': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade will be an extremely flexible system of order execution and risk management. CINDX.hub has a full-scale editor for trading strategies with a testing system based on historical market data. CINDX.dao will receive a voting system for token holders. ',
    'roadmap#23': 'A tokenized rating system CINDX.talk will be added in the final version of CINDX.talk. This will provide a system of assessment for CINDX community trading experts. “Algorithmic trading” will also be added. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders. A high-grade platform for a code audit will be created. ',

    'problemSolving#1': 'Tiempo ',
    'problemSolving#2': 'Confianza',
    'problemSolving#3': 'Incertidumbre',
    'problemSolving#4': 'Tengo dinero para invertir en criptoactivos, pero no tengo tiempo para investigar y contactar con operadores profesionales para gestionar mi cartera.',
    'problemSolving#5': 'Nunca me ha convencido la idea de poner mi dinero en manos de otros para obtener beneficios.',
    'problemSolving#6': 'La tecnología para operar con criptoactivos no es intuitiva. No sé cómo operar con mis monedas.',
    'problemSolving#7': 'CINDX ofrece acceso a operadores calificados y de confianza.',
    'problemSolving#8': 'En la plataforma de CINDX, sus fondos nunca salen de su cartera.',
    'problemSolving#9': 'Usted gana junto a los mejores operadores del mercado.',
    'problemSolving#10': 'Las valoraciones de los operadores de CINDX se basan en el éxito de su historial de operaciones. Elija rápidamente al operador que se ajuste a sus necesidades.',
    'problemSolving#11': 'Gracias a nuestro sistema descentralizado y nuestros contratos inteligentes, sus fondos se gestionan sin transferirse a operadores.',
    'problemSolving#12': 'Todos los inversores de CINDX tienen a su disposición a los mejores operadores del mercado para gestionar sus fondos.',
    'problemSolving#13': '¿Qué tipo de problemas soluciona CINDX??',
    'problemSolving#14': 'Probar versión MVP',

    'howCindxWorks#1': 'Inversores',
    'howCindxWorks#2': 'Operadores',
    'howCindxWorks#3': 'Proveedores',
    'howCindxWorks#4': 'aumentan sus beneficios gracias a las destrezas de gestión de carteras de los mejores operadores.',
    'howCindxWorks#5': 'ganan comisiones de los inversores que les siguen en base a sus resultados y su estrategia de operaciones.',
    'howCindxWorks#6': 'venden herramientas de operaciones avanzadas como bots y widgets financieros.',
    'howCindxWorks#7': 'recaudan comisiones y tasas de inscripción.',
    'howCindxWorks#8': 'Me registro en CINDX con criptoactivos con los que quiero operar.',
    'howCindxWorks#9': 'Me registro en CINDX con conocimientos financieros que beneficiarán a los inversores.',
    'howCindxWorks#10': 'Me registro en CINDX con aplicaciones financieras que ayudarán a los inversores.',
    'howCindxWorks#11': 'Nuestra misión es hacer que las operaciones sean fáciles, seguras y rentables.',
    'howCindxWorks#12': 'En resumen: cómo funciona CINDX',

    'marketAnalytics#1': 'Análisis del mercado',
    'marketAnalytics#2': 'AUM globales',
    'marketAnalytics#3': 'Inversión',
    'marketAnalytics#4': 'Aumento de capital',
    'marketAnalytics#5': 'Desde el 2000, el mercado global de gestión patrimonial ha crecido más de un 250 %.',
    'marketAnalytics#6': 'Esto se debe a las constantes mejoras de las herramientas de mercado y al desarrollo general de estructuras de mercado.',
    'marketAnalytics#7': 'A pesar del crecimiento explosivo del mercado de criptomonedas en el 2017, la industria sigue siendo muy joven.',
    'marketAnalytics#8': 'La capitalización del mercado total fue de 600 000 millones de dólares a finales de 2017, lo que representa tan solo un 1 % de la capitalización del mercado del sector de la gestión patrimonial.',
    'marketAnalytics#9': 'DOCUMENTO TÉCNICO',
    'marketAnalytics#10': 'PRESENTACIÓN',
    'marketAnalytics#11': 'RESUMEN',
    'marketAnalytics#12': 'MODELO FINANCIERO',
    'marketAnalytics#13': 'DOCUMENTACIÓN LEGAL',
    'marketAnalytics#14': 'Métricas generales',
    'marketAnalytics#15': '25 000 000 de carteras de posibles cadenas de',
    'marketAnalytics#16': 'bloques.',
    'marketAnalytics#17': '200 000 transacciones',
    'marketAnalytics#18': 'potenciales a diario.',
    'marketAnalytics#19': 'Más de 225 socios potenciales,',
    'marketAnalytics#20': 'con de 3000 a 5000 millones de dólares cada uno',

    'tokenSaleDetails#1': 'Asignación de tokens',
    'tokenSaleDetails#2': 'Equipo',
    'tokenSaleDetails#3': 'Primas',
    'tokenSaleDetails#4': 'Asesores',
    'tokenSaleDetails#5': 'Reserva',
    'tokenSaleDetails#6': 'Subvenciones comunitarias',
    'tokenSaleDetails#7': 'Respaldo de liquidez de tokens',
    'tokenSaleDetails#8': 'Disponible a la venta',
    'tokenSaleDetails#9': 'Nombre del token: CINX ',
    'tokenSaleDetails#10': 'Comienzo de la preventa de tokens: 26 de agosto de 2018',
    'tokenSaleDetails#11': 'Emisión total: 51 500 000 CINX ',
    'tokenSaleDetails#12': 'Precio por token: 1,00 $ = 1,00',
    'tokenSaleDetails#13': 'CINXO = 1,00 CINX',
    'tokenSaleDetails#14': 'Inversión mínima: 50 $ o cantidad equivalente',
    'tokenSaleDetails#15': 'DOCUMENTO TÉCNICO',
    'tokenSaleDetails#16': 'PRESENTACIÓN',
    'tokenSaleDetails#17': 'RESUMEN',
    'tokenSaleDetails#18': 'MODELO FINANCIERO',
    'tokenSaleDetails#19': 'DOCUMENTACIÓN LEGAL',
    'tokenSaleDetails#20': 'Uso de los fondos',
    'tokenSaleDetails#21': 'Marketing y relaciones públicas 21%',
    'tokenSaleDetails#22': 'Investigación y desarrollo 41%',
    'tokenSaleDetails#23': 'Operaciones 28%',
    'tokenSaleDetails#24': 'Gastos jurídicos 7%',
    'tokenSaleDetails#25': 'Bonificaciones de operadores 3%',
    'tokenSaleDetails#26': 'Ofertas de tokens',
    'tokenSaleDetails#27': 'Venta de tokens:',
    'tokenSaleDetails#28': 'Bonificaciones de preventa de tokens',
    'tokenSaleDetails#29': 'Agosto 26 - Septiembre 16 - 25% Bonos',
    'tokenSaleDetails#30': 'Septiembre 17 - Octubre 7 - 20% Bonos',
    'tokenSaleDetails#31': 'Bonificaciones de venta de tokens:',
    'tokenSaleDetails#32': 'Octubre 8 - Octubre 21 - 17% Bonos',
    'tokenSaleDetails#33': 'Octubre 22 - Noviembre 4 - 15% Bonos',
    'tokenSaleDetails#34': 'Noviembre 6 - Noviembre 18 - 13% Bonos',
    'tokenSaleDetails#35': 'Noviembre 19 - Diciembreci 2 - 10% Bonos',
    'tokenSaleDetails#36': 'Diciembre 3 - Diciembre 16 - 5% Bonos',
    'tokenSaleDetails#37': 'Diciembre 17 - Diciembre 26 - 0% Bonos',
    'tokenSaleDetails#38': 'Comprar tokens',
    'tokenSaleDetails#39': 'Detalles de la venta de tokens',
    'tokenSaleDetails#40': 'During the token sale, investors purchase utility tokens – options [CINXO], which give them the right to receive security tokens [CINX] in the future.',
    'tokenSaleDetails#41': 'Security tokens [CINX] will be issued and distributed following the prospect of emission published on the website of FSA of Estonia https://www.fi.ee/ and cindx.io after the end of the token sale, but no later than Q1 2019.',
    'tokenSaleDetails#42': 'The holder of [CINXO] tokens has the right but no obligation to exchange options for security tokens with a ratio of 1:1 after completing the KYC procedure with identification signature, address confirmation and supply of other documents (see the KYC diagram).',
    'tokenSaleDetails#43': 'Tokens [CINXO] grant the same rights as security tokens apart from the right to participate in revenue distribution with a lock-up and voting on the platform.',

    'legalSchedule#1': 'Planificación legal',
    'legalSchedule#2': 'LICENCIA OBTENIDA (FVR000110) PARA OFRECER SERVICIOS DE INTERCAMBIO DE DIVISAS VIRTUALES Y FIAT',
    'legalSchedule#3': 'CON REGISTRO DE MARCA COMERCIAL EN ESTONIA Y LA UE',
    'legalSchedule#4': 'LICENCIA FFA 000254 PARA OPERAR COMO INSTITUCIÓN FINANCIERA',
    'legalSchedule#5': 'LICENCIA FFA000254 OBTENIDA PARA OPERAR COMO INSTITUCIÓN FINANCIERA',
    'legalSchedule#6': 'Folleto elaborado conforme a las leyes de Estonia',
    'legalSchedule#7': 'LICENCIA DE LA FSA (autoridad de supervisión financiera de Estonia) SOLICITADA',
    'legalSchedule#8': 'LICENCIA OBTENIDA PARA OFRECER UN SERVICIO DE CARTERA DE DIVISAS SERVICIO',
    'legalSchedule#9': 'REGISTRADO SEGÚ LA EXENCIÓN D DE SEC',
    'legalSchedule#10': 'GESTOR DE DATOS PERSONALES NOMBRADO PARA CUMPLIR LOS REQUISITIOS DEL RGPD',
    'legalSchedule#11': 'LICENCIA DE LA FSA OBTENIDA',
    'legalSchedule#12': 'FOLLETO EU 809-2004 REGISTRADO',
    'legalSchedule#13': 'EMISIÓN DE TOKENS DE SEGURIDAD DE CINX',

    'feedbackProject#1': 'COMENTARIOS SOBRE NUESTRO PROYECTO',
    'feedbackProject#2': 'Val Jerdes',
    'feedbackProject#3': 'Director de productos',
    'feedbackProject#4': 'Val Jerdes, director de productos de CINDX, habla de los principales miembros del equipo y de cómo sus conocimientos y experiencia ayudarán a desarrollar el proyecto que puede cambiar las reglas del juego de las finanzas significativamente.',
    'feedbackProject#5': 'Denis Eskenazi',
    'feedbackProject#6': 'Director de marketing de productos',
    'feedbackProject#7': 'Denis Eskenazi, director de marketing de productos de CINDX, manifiesta por qué se unió a CINDX.',
    'feedbackProject#8': 'Philip Staehelin',
    'feedbackProject#9': 'Asesor',
    'feedbackProject#10': 'Philip Staehelin, asesor del proyecto de CINDX, explica cómo la revolución de las criptomonedas puede ayudar incluso a los inversores novatos y habla sobre la innovación que presenta el proyecto de CINDX para el mercado de los criptoactivos.',
    'feedbackProject#11': 'Andrzej Cichowlaz',
    'feedbackProject#12': 'Especialista en marketing',
    'feedbackProject#13': 'Andrzej Cichowlaz, director de marketing de CINDX, explica por qué confía en el éxito del proyecto.',
    'feedbackProject#14': 'Austin Kimm',
    'feedbackProject#15': 'Austin Kimm, asesor del proyecto de CINDX , habla de cómo CINDX hace que las operaciones de criptomonedas sean sencillas e inteligentes además de rentables.',
    'feedbackProject#16': 'Amarpreet Singh',
    'feedbackProject#17': 'Amarpreet Singh, asesor de CINDX, presenta el modo en que la plataforma de CINDX puede acortar las distancias entre inversores y operaciones.',
    'feedbackProject#18': 'Keith Teare',
    'feedbackProject#19': 'Keith Teare, asesor de CINDX, describe las ventajas de la plataforma de CINDX.',
    'feedbackProject#20': 'Mansur Rasulov',
    'feedbackProject#21': 'Jefe de comunidades',
    'feedbackProject#22': 'Mansur Rasulov, jefe de comunidades de CINDX, cuenta por qué decidió unirse al equipo de CINDX.',
    'feedbackProject#23': 'Sadie Hutton',
    'feedbackProject#24': 'Sadie Hutton, asesora de CINDX, explica en qué se diferencia la plataforma de CINDX de las demás plataformas de operaciones automatizadas.',
    'feedbackProject#25': 'Graham Doggart',
    'feedbackProject#26': 'Graham Doggart, asesor de CINDX, presenta las ventajas de la plataforma de CINDX.',
    'feedbackProject#27': 'Alina Vardanian',
    'feedbackProject#28': 'Gestora de contenidos',
    'feedbackProject#29': 'Alina Vardanian, gestora de contenidos de CINDX, nos explica el espíritu de equipo y lo que le gusta de su trabajo.',
    'feedbackProject#30': 'Bogdan Fiedur',
    'feedbackProject#31': 'Asesor de CINDX',
    'feedbackProject#32': 'Bogdan Fiedur, asesor de CINDX, expone las diferencias que existen entre el proyecto de CINDX y otros proyectos de ICO.',
    'feedbackProject#33': 'Jason King',
    'feedbackProject#34': 'Jason King, director comercial, explica los atractivos de CINDX y comenta las principales ventajas del proyecto.',

    'mediaNews#1': 'Medios',
    'mediaNews#2': 'Noticias',
    // Media
    'mediaNews#1_1': 'CINDX Aims to Democratize the Modern Financial System',
    'mediaNews#1_2': 'Even as investors in the cryptocurrency space recognize that they are at the forefront of a new financial revolution, adoption by the general populace is yet to occur. While 3rd parties are slowly entering the space in the form of hedge funds and other investors, very few individuals seem to have taken the step to invest in cryptocurrencies on their own.',
    'mediaNews#1_3': 'CINDX Announces Plans For ICO Pre-Sale Amidst Release Of Revolutionary Crypto Trading Hub That Allows Users To Follow Expert Traders',
    'mediaNews#1_4': 'CINDX takes its business seriously with particular attention and cares to legal matters and has taken great pains to ensure that CINDX is as compliant as possible with global regulations.',
    'mediaNews#1_5': 'How CINDX is Democratizing the Modern Financial System',
    'mediaNews#1_6': 'CINDX is a new platform that is making crypto trading easier, more secure, and more accessible. With this platform, it’s possible to have your funds traded without high fees or minimum investments, with the added security and transparency of blockchain technology.',
    'mediaNews#1_7': 'CINDX is making crypto trading easier, more secure, and more accessible.',
    'mediaNews#1_8': 'Cryptocurrency and blockchain technology have been slated as powerful tools capable of fueling a global financial revolution. There are myriad opportunities to invest in the crypto space, and yet, very few individuals have undertaken the steps necessary to invest.',
    'mediaNews#1_9': 'CINDX Announces Plans Release Of Revolutionary Crypto Trading Hub',
    'mediaNews#1_10': 'The CINDX platform creates a complete ecosystem for cryptocurrency trading that is favorable to all the participants of the market and offers solutions to existing pain points.',
    'mediaNews#1_11': 'CINDX Announces Plans For ICO Pre-Sale',
    'mediaNews#1_12': 'CINDX made headlines this week with the announcement that they will be opening their ICO Pre-Sale in late August after investors interest in the ICO peaks to new levels.',
    'mediaNews#1_13': 'CINDX Will Be Opening ICO Pre-Sale in late August',
    'mediaNews#1_14': 'The CINDX Crypto trading platform has a myriad of features and benefits that haven’t been seen in other platforms to date.',
    'mediaNews#1_15': '5 Tips from CINDX Crypto Assets Management Hub: How to Avoid Being Cheated',
    'mediaNews#1_16': 'The team behind the CINDX crypto assets management hub has created a helpful set of guidelines on how not to become victims of unfair play, so you can learn what should be primarily taken into account when evaluating ICOs before investing in them.',
    'mediaNews#1_17': 'CINDX Crypto Asset Management Hub Adopts Bancor Protocol',
    'mediaNews#1_18': 'CINDX is delighted to announce that a number of new integrations with top industry players are underway, each of which will make the life of the users of the platform easier and richer. These new integrations include the decision to adopt the Bancor protocol to provide continuous liquidity for the CINDX platform.',
    // News
    'mediaNews#2_1': 'CINDX meets Ian Balina',
    'mediaNews#2_2': 'CINDX pitch to the one of the TOP10 crypto gurus in the world in the Cryptobazar event.',
    'mediaNews#2_3': 'CINDX took part in Moscow ICO Summit 2018',
    'mediaNews#2_4': 'CINDX team introduced the project to the Russian crypto community during ICO Summit event.',
    'mediaNews#2_5': 'How CINDX is ensuring legal compliance',
    'mediaNews#2_6': 'Our company is registered in Estonia. Why? The answer is simple — the authorities of Estonia have created a strong and innovative legal infrastructure...',
    'mediaNews#2_7': 'Keith Teare Co-founder of Accelerated Digital Ventures and Founding Shareholder in TechCrunch',
    'mediaNews#2_8': 'We continue to introduce CINDX advisers, find out what they...',
    'mediaNews#2_9': 'Meet world\'s first financial crypto social network',
    'mediaNews#2_10': 'Every day our team takes one more step on the way to creation and start...',
    'mediaNews#2_11': 'Denis Eskenazi CINDX Product Marketing Director',
    'mediaNews#2_12': 'We continue to tell about the CINDX team and each team member’s professional experience. Please, read about Denis Eskenazi...',
    'mediaNews#2_13': 'CINDX crypto currency exchange license',
    'mediaNews#2_14': 'Our company in Estonia has received Crypto Currency Exchange License. This allows CINDX to provide fiat-to-crypto exchange services. This licence is issued...',
    'mediaNews#2_15': 'Austin Kimm Co-founder of Crypterium & CINDS Adviser',
    'mediaNews#2_16': 'We continue to introduce CINDX advisers, find out what they are proud...',
    'mediaNews#2_17': 'The strategic meeting of the international CINDX team',
    'mediaNews#2_18': 'Every day our team takes one more step on the way to creation and start of the CINDX platform. Our work...',
    'mediaNews#2_19': 'Artur Shamalov CINDX Investment Director',
    'mediaNews#2_20': 'We continue to introduce the CINDX team. Our next article is about Artur Shamalov, a skilled...',
    'mediaNews#2_21': 'The issuance of CINX tokens',
    'mediaNews#2_22': 'The issuance of CINX tokens will be carried out according to the license of The Estonian Financial Supervisory Authority (EFSA). What is a token...',
    'mediaNews#2_23': '"Amarpreet Singh Co-Founding Member of Malta Blockchain Association & CINDX adviser"',
    'mediaNews#2_24': 'We at CINDX are incredibly proud to present our advisers, tell the world about their achievements and why they have decided to become a part of the CINDX...',
    'mediaNews#2_25': 'CINDX meets Vangoo Capital Partners Fund',
    'mediaNews#2_26': 'Today we have welcomed Kevin Shang from Vangoo Capital Partners and his colleagues in our office. We have discussed business partnership opportunities in order to attract investors from the Asian region.',
    'mediaNews#2_27': '"Mofassair Hossain CINDX Chief Marketing Officer."',
    'mediaNews#2_28': 'We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly excited about...',
    'mediaNews#2_29': 'How CINDX ensures safety for its users - KYC',
    'mediaNews#2_30': 'Every crypto enthusiast knows that a KYC procedure is necessary in order to protect investors against fraudulent actions of the third...',
    'mediaNews#2_31': 'Philip Staehelin 25 Years of Consulting and Entrepreneurial Experience',
    'mediaNews#2_32': 'We continue our regular series of articles dedicated to introducing CINDX advisers. The next item is about Philip Staehelin.',
    'mediaNews#2_33': 'CINDX meets 9coin Digital Asses Exchange',
    'mediaNews#2_34': 'The CINDX team continues active work on building relationships with various international companies. One of the most important directions of business...',
    'mediaNews#2_35': 'Jason King Interim Chief Commercial Officer',
    'mediaNews#2_36': 'The core of any great project is always people who make the unique idea come true. We would like to tell about...',
    'mediaNews#2_37': 'CINDX Presents the project during RICLUB private investors meeting',
    'mediaNews#2_38': 'CINDX has successfully passed the due diligence procedure requested by RICLub and was one of the few projects...',
    'mediaNews#2_39': 'Sofja Pevzner CINDX Personal Data Officer',
    'mediaNews#2_40': 'We continue to introduce our team and tell about what inspires our colleagues to work with CINDX. Please read about...',
    'mediaNews#2_41': 'Tyler Sanford 8+ years digital marketing in Yelp, Zenefits',
    'mediaNews#2_42': 'We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become a part of the CINDX team. In this...',
    'mediaNews#2_43': 'CINDX - Key points to observe',
    'mediaNews#2_44': 'The CINDX project is a valuable business venture with the features that are critically relevant for its participants. In this article we talk about Strengths...',
    'mediaNews#2_45': 'Airat Shayhulov CINDX Head of Quantitative Research.',
    'mediaNews#2_46': 'In “TEAM” series of the articles, we tell about people who every day participates in the creation...',
    'mediaNews#2_47': 'CINDX license of the financial consultant',
    'mediaNews#2_48': 'CINDX has obtained a termless operating licence (the FFA 000254 license) that gives the right to operate as a financial institution...',
    'mediaNews#2_49': '"Graham Doggart 20 Years of Enterprise Development and Fintech Marketing Compliance"',
    'mediaNews#2_50': 'We continue our regular series of articles dedicated to introducing CINDX advisers. The next item...',
    'mediaNews#2_51': 'CINDX continues the roadshow in China!',
    'mediaNews#2_52': 'The CINDX team is glad to announce participation as a Golden Sponsor of Borderless Blockchain Technology Summit 2018, which...',
    'mediaNews#2_53': 'Ibraghim Haniev CINDX Tech Lead',
    'mediaNews#2_54': 'Get to know more about the CINDX team! The core of any great project is always people who make the unique ideas come true...',
    'mediaNews#2_55': 'Sadie Hutton 25 Years in Senior Management and Management Consulting',
    'mediaNews#2_56': 'Like any global project, we understand the importance of professional help and advice. We continue to tell the stories of...',
    'mediaNews#2_57': 'CINDX.talk - a service that will help people become wiser in taking financial decisions',
    'mediaNews#2_58': 'The current digital-world related to the crypto industry is getting crowded with mind-charming digital solutions...',
    'mediaNews#2_59': '"Val Jerdes CINDX Product Director"',
    'mediaNews#2_60': 'We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly...',
    'mediaNews#2_61': 'Bogdan Fiedur Blockchain and cryptocurrency expert, investor, entrepreneur',
    'mediaNews#2_62': 'We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become...',
    'mediaNews#2_63': 'Welcome to CINX Token Distribution – it’s not an ICO; it’s an STO',
    'mediaNews#2_64': 'In this article, we want to make it clear why CINDX chose to hold a Security Token Offering (STO) instead of an Initial...',
    'mediaNews#2_65': 'CINDX celebrates the “AA” Rating from Top ICO List Audit!',
    'mediaNews#2_66': 'The results of CINDX’s sincerity to make meaningful changes in people’s ambitions via a unique business model just got appreciated...',
    'mediaNews#2_67': 'CINDX Weekly digest (30.07.18 - 05.08.18)',
    'mediaNews#2_68': 'The CINDX team is very excited to share the results of our work for the last week 30.07.18 - 05.08.18!',
    'mediaNews#2_69': 'Virtual Currency Wallet Services',
    'mediaNews#2_70': 'CINDX believes that being fluent in legal issues and having a clean, confident and clear legal status is of utmost importance. At the moment, CINDX is going...',
    'mediaNews#2_71': 'How CINDX Influences Crypto Trading',
    'mediaNews#2_72': 'How to master the crypto market movements and turn them in one’s favor? This is where CINDX’s effective business model comes into play. Learn more about CINDX on our Medium!',
    'mediaNews#2_73': 'CINDX Weekly digest (06.08.18 - 12.08.18)',
    'mediaNews#2_74': 'CINDX continues its regular column - Weekly Digest. We are excited to share the recent achievements of our project! Enjoy your time reading!',
    'mediaNews#2_75': 'CINDX gets 5.0 rating on TrackICO!',
    'mediaNews#2_76': 'CINDX continues getting approval from the largest and the most credible rating services. The week has hardly passed after...',
    'mediaNews#2_77': '"David Gutierrez Investment Relations Officer"',
    'mediaNews#2_78': 'CINDX is very serious about taking people on crew and proud to introduce them. This article is dedicated to David Gutierrez, CINDX Investment Relations Officer',
    'mediaNews#2_79': 'ICObench gives 4.8 to CINDX',
    'mediaNews#2_80': 'The CINDX project has already gained the highest mark of  ‘AA’ from Top ICO List and got a 5.0 rating from TrackICO. Now, we are proud to share...',
    'mediaNews#2_81': 'Dip your Toe in Crypto',
    'mediaNews#2_82': 'It is never late to change your mind. It’s no surprise that Wall Street bankers change their minds in favour of crypto. Enjoy reading CINDX review on the current market situation!',
    'mediaNews#2_83': 'Yuriy Avdeev, CEO of the CINDX project',
    'mediaNews#2_84': 'Enjoy reading what inspired Yuriy Avdeev to create a project that will help all participants of the crypto market to be profitably engaged - CINDX.',
    'mediaNews#2_85': 'Weekly digest (13.08.18 - 19.08.18)',
    'mediaNews#2_86': 'CINDX continues its regular Weekly Digest column. We are excited to share our project’s progress and the most recent achievements! We are glad to remind you that CINDX security token Pre-sale starts this Sunday. Don\'t miss!',

    'teamAdvisersPartners#1': 'Equipo de más de 50 miembros',
    'teamAdvisersPartners#2': 'Asesores',
    'teamAdvisersPartners#3': 'Nuestros socios',
    // teamInfo
    'teamAdvisersPartners#4': 'Yuriy Avdeev',
    'teamAdvisersPartners#5': 'Director general',
    'teamAdvisersPartners#6': '13 años en emprendimiento',
    'teamAdvisersPartners#7': '9 empresas',
    'teamAdvisersPartners#8': '2 000 000 $ para gestión de criptoactivos',
    'teamAdvisersPartners#9': 'Val Jerdes',
    'teamAdvisersPartners#10': 'Director de productos',
    'teamAdvisersPartners#11': '20 años en emprendimiento',
    'teamAdvisersPartners#12': '3 salidas de éxito',
    'teamAdvisersPartners#13': 'Retornos cuadruplicados para carteras',
    'teamAdvisersPartners#14': 'Mofassair Hossain',
    'teamAdvisersPartners#15': 'Director de marketing',
    'teamAdvisersPartners#16': 'Inversor y asesor de más de 15 ICO',
    'teamAdvisersPartners#17': 'Asesor de alto nivel en ICO Bench',
    'teamAdvisersPartners#18': 'Miembro de la GBAP',
    'teamAdvisersPartners#19': 'Artur Shamalov',
    'teamAdvisersPartners#20': 'Director de inversiones',
    'teamAdvisersPartners#21': '15 años en emprendimiento',
    'teamAdvisersPartners#22': '5000 clientes de mixcart.ru',
    'teamAdvisersPartners#23': 'mail.ru invirtió en dc-daily.ru',
    'teamAdvisersPartners#24': 'Denis Eskenazi',
    'teamAdvisersPartners#25': 'Director de marketing de productos',
    'teamAdvisersPartners#26': '7 años en emprendimiento',
    'teamAdvisersPartners#27': '2 000 000 $ atraídos para clientes',
    'teamAdvisersPartners#28': '10 años en creación de marca',
    'teamAdvisersPartners#29': 'Ibraghim Haniev',
    'teamAdvisersPartners#30': 'Líder técnico',
    'teamAdvisersPartners#31': '6 años en emprendimiento',
    'teamAdvisersPartners#32': 'Más de 200 sitios desarrollados',
    'teamAdvisersPartners#33': 'Especialista en seguridad de la información',
    'teamAdvisersPartners#34': 'Airat Shaikhulov',
    'teamAdvisersPartners#35': 'Head of Quantitative Research',
    'teamAdvisersPartners#36': 'Dr of science at MSU',
    'teamAdvisersPartners#37': 'Aton-line navigator developer',
    'teamAdvisersPartners#38': 'Head of algorithmic trading',
    'teamAdvisersPartners#39': 'Sofja Pevzner',
    'teamAdvisersPartners#40': 'Director de datos personales',
    'teamAdvisersPartners#41': '5 años en emprendimiento',
    'teamAdvisersPartners#42': 'Permiso de la oficina de antiblanqueo de capitales de Estonia para operar',
    'teamAdvisersPartners#43': '8 años de experiencia laboral jurídica',
    'teamAdvisersPartners#44': 'Dave Gutierrez',
    'teamAdvisersPartners#45': 'Director de relaciones de inversión',
    'teamAdvisersPartners#46': '5 años en arrendamiento de aviones',
    'teamAdvisersPartners#47': '3 años en agencia de inversión',
    'teamAdvisersPartners#48': '2 años en inversiones extranjeras',
    'teamAdvisersPartners#49': 'Jelena Karzetskaja',
    'teamAdvisersPartners#50': 'Responsible de cumplimiento',
    'teamAdvisersPartners#51': 'cuenta con varias titulaciones en derecho',
    'teamAdvisersPartners#52': 'Práctica judicial desde 1997',
    'teamAdvisersPartners#53': 'Esferas legales: derecho internacional',
    'teamAdvisersPartners#54': 'Wang Dong',
    'teamAdvisersPartners#55': 'Especialista en el mercado chino de cadenas de bloques',
    'teamAdvisersPartners#56': '3 años en php/JavaScript',
    'teamAdvisersPartners#57': '5 años en SEO, SMM y compra de medios',
    'teamAdvisersPartners#58': '2 años en desarrollo de cadenas de bloques y venta de tokens en China',
    // advisers
    'teamAdvisersPartners#59': 'Keith Teare',
    'teamAdvisersPartners#60': 'Fundador y presidente ejecutivo de Accelerated Digital Ventures',
    'teamAdvisersPartners#61': 'Asesor para ICOBox, Crypterium, EnergiMine, etc.',
    'teamAdvisersPartners#62': 'Accionista fundador de TechCrunch',
    'teamAdvisersPartners#63': 'Soy el presidente ejecutivo y presidente del comité de inversiones de Accelerated Digital Ventures, una empresa del Reino Unido. Nací y me crié en el Reino Unido.',
    'teamAdvisersPartners#64': 'Anteriormente, fui fundador y socio de Archimedes Labs en Palo Alto (California). Me encanta trabajar con fundadores, equipos, diseñadores e ingenieros para crear productos, contar historias y hacerlas realidad.',
    'teamAdvisersPartners#65': 'He fundado y cofundado varias empresas desde principios de los 80. Algunas se vendieron con éxito y otras salieron al mercado en una OPV. Dos de mis empresas fueron unicornios, valoradas en más de mil millones de dólares.',
    'teamAdvisersPartners#66': 'Siempre me he centrado en las áreas de cambio. En la década de los 80, fueron las redes y las bases de datos. En la época de 1994 a 1998, fue el acceso a Internet. De 1998 a 2010 fueron los servicios y contenidos web, así como las aplicaciones móviles para el consumidor. Desde 2017, es la tecnología de cadenas de bloques. Carrera y proyectos: Tech Crunch, Accelerated Digital Ventures, cScape, EasyNet, Cyberia, RealNames, Venture Network, ICOBox, Crypterium, R/Block, Fluz, EnergiMine, Archimedes Labs y CINDX.',
    'teamAdvisersPartners#67': 'Austin Kimm',
    'teamAdvisersPartners#68': 'Director de servicios financieros internacionales',
    'teamAdvisersPartners#69': 'Más 30 años de experiencia en servicios financieros',
    'teamAdvisersPartners#70': 'Creación de empresas valoradas en 500 000 000 $',
    'teamAdvisersPartners#71': 'Director general experto en servicios financieros de eficacia demostrada con especial interés en la creación de negocios de seguros en mercados en desarrollo, donde he creado empresas con éxito valoradas actualmente en más de 500 000 000 $.',
    'teamAdvisersPartners#72': 'Más recientemente, he trabajado en Rusia durante 10 años y también he ocupado altos cargos ajenos a los seguros, como el de presidente general de Workle (la mayor plataforma de empleos comerciales de Internet), y una amplia variedad de puestos de nivel C en empresas emergentes del sector tecnofinanciero como Crypterium, el primer criptobanco digital del mundo. Carrera y proyectos:',
    'teamAdvisersPartners#73': 'Aviva, Commercial Union UK, Reinaissance Insurance, Kimm Health & Leisure Ltd, Workle, Crypterium, CryptoIndex y CINDX.',
    'teamAdvisersPartners#74': 'Philip Staehelin',
    'teamAdvisersPartners#75': '25 años de experiencia en asesoría y emprendimiento',
    'teamAdvisersPartners#76': 'Negocios de pagos alternativos de 500 000 000 $ bajo supervisión',
    'teamAdvisersPartners#77': 'Mentor de más de 200 empresas emergentes de 20 países',
    'teamAdvisersPartners#78': 'Soy innovador y líder con una combinación de optimismo contagioso y realismo pragmático. Encuentro oportunidades invisibles para los demás.',
    'teamAdvisersPartners#79': 'He potenciado mi capacidad para "ver las cosas de otra forma" y "hacer las cosas realidad" en corporaciones, asesorías y empresas emergentes, lo que me ha aportado nuevas y amplias perspectivas que sirven de base para nuevas ideas transformadoras.',
    'teamAdvisersPartners#80': 'Buscar soluciones para grandes desafíos es lo que me saca de la cama cada mañana. ',
    'teamAdvisersPartners#81': 'Carrera y proyectos: Roland Berger, Dot Glasses, Transparency International, StartupYard, Bethereum, Gjirafa Inc, Accenture y CINDX.',
    'teamAdvisersPartners#82': 'Amarpreet Singh',
    'teamAdvisersPartners#83': 'Asesor experto de Global Blockchain Foundation',
    'teamAdvisersPartners#84': 'Experiencia en Microsoft, The World Bank y Airbus',
    'teamAdvisersPartners#85': 'Miembro del consejo asesor de proyectos de cadenas de bloques',
    'teamAdvisersPartners#86': 'Entusiasta de la tecnología digital y profesional avezado con años de experiencia en el sector tecnológico, concretamente en operaciones, asesoría e innovación.',
    'teamAdvisersPartners#87': 'Especialista en servicios en la nube certificado (Microsoft y AWS). Conocido por su versatilidad y flexibilidad. Goza de excelentes destrezas analíticas, estratégicas y de liderazgo además de ser un compañero de primera.',
    'teamAdvisersPartners#88': 'Especialidades: asesoría tecnológica, operaciones, informática en la nube, tecnofinanzas, innovación, ERP, aprendizaje automático, gestión de cuentas, desarrollo de socios, desarrollo empresarial y estrategia.',
    'teamAdvisersPartners#89': 'Amarpreet Singh cuenta con una experiencia laboral y una formación muy diversificadas. Tiene tres títulos de máster y ha vivido, trabajado y estudiado en India, Singapur, Francia, China, Sudáfrica, Corea y Canadá.',
    'teamAdvisersPartners#90': 'Carrera y proyectos: Microsoft, The World Bank, Airbus, TokenAsia Platform, GOeurika y CINDX.',
    'teamAdvisersPartners#91': 'Tyler Sanford',
    'teamAdvisersPartners#92': '8 años de marketing digital en Yelp y Zenefits',
    'teamAdvisersPartners#93': '12 ICO con una recaudación de más de 225 000 000 $',
    'teamAdvisersPartners#94': 'Uno de los primeros operadores en adoptar la tecnología de cadenas de bloques',
    'teamAdvisersPartners#95': 'Crecer como atleta me brindó unas destrezas que he podido aplicar a mi carrera profesional y vida personal.',
    'teamAdvisersPartners#96': 'He tenido la gran suerte de ver los resultados de ir un paso más lejos y, además, he aprendido a lidiar con los altibajos inherentes a toda profesión.',
    'teamAdvisersPartners#97': 'Soy una persona muy motivada, y siempre tengo ganas de seguir ampliando mis conocimientos y talentos en todos los aspectos de los negocios.',
    'teamAdvisersPartners#98': 'Siempre dispuesto a aceptar nuevos desafíos, mi motivación se basa en superar los obstáculos para alcanzar mis objetivos.',
    'teamAdvisersPartners#99': 'Carrera y proyectos: IPG Holdings, DataBlockChain, TraXion by Puma Technologies, ELYSIAN, Etherinc, FTEC Foundation y CINDX.',
    // 'teamAdvisersPartners#100': 'Philip Staehelin',
    // 'teamAdvisersPartners#101': '25 years of consulting and entrepreneurial experience',
    // 'teamAdvisersPartners#102': '$500m alternative payments business under leadership',
    // 'teamAdvisersPartners#103': '200+ startups from 20 countries mentored',
    // 'teamAdvisersPartners#104': 'I\'m an innovator and a leader who blends contagious optimism with pragmatic realism. I find opportunity where others see none.',
    // 'teamAdvisersPartners#105': 'I\'ve leveraged my ability to "see things differently" and "make things happen" in corporate, consulting and start-up environments - all giving me broad new perspectives that provide fodder for new transformative ideas.',
    // 'teamAdvisersPartners#106': 'Finding solutions to hard challenges is what gets me out of bed in the morning.',
    // 'teamAdvisersPartners#107': 'Career and projects: BCG, Spectacler, Transparency International, StartupYard, Bethreum, Gjirafa Inc, Direct People, CINDX',
    // 'teamAdvisersPartners#108': 'Senior Adviser of Global Blockchain Foundation',
    // 'teamAdvisersPartners#109': 'Experience in Microsoft, The World Bank and Airbus',
    // 'teamAdvisersPartners#110': 'Advisery Board Member of Blockchain projects',
    // 'teamAdvisersPartners#111': 'Technology/Digital enthusiast and a seasoned professional with years of experience in Tech industry – operations, consulting and innovation.',
    // 'teamAdvisersPartners#112': 'He is a certified Cloud (Microsoft and AWS) specialist. Known for versatility and flexibility. Excellent analytic, strategic, leadership skills and a team player at its best.',
    // 'teamAdvisersPartners#113': 'Specialties: Technology Consulting, Operations, Cloud Computing, Fintech, Innovation, ERP, Machine Learning, Account Management, Partner Development, Business Development and Strategy',
    // 'teamAdvisersPartners#114': 'Amarpreet Singh has a very diversified work and educational background. He holds three Masters degrees and has lived/worked/studied in India, Singapore, France, China, South Africa, Korea, Canada.',
    // 'teamAdvisersPartners#115': 'Career and projects: Microsoft, The World Bank, Airbus, TokenAsia Platform, GOeurika, CINDX',
    // 'teamAdvisersPartners#116': 'Tyler Sanford',
    // 'teamAdvisersPartners#117': '8 Years Digital Marketing in Yelp and Zenefits',
    // 'teamAdvisersPartners#118': '12 ICO’s over $225M raised',
    // 'teamAdvisersPartners#119': 'Early adopter of blockchain',
    // 'teamAdvisersPartners#120': 'Growing up as an Athlete has given me a skill set that I\'ve been able to apply to my careers and personal life.',
    // 'teamAdvisersPartners#121': 'I have been very fortunate to see the results of going that extra mile, while learning to deal with the highs and lows that go along with all professional careers.',
    // 'teamAdvisersPartners#122': 'I\'m an extremely self-motivated individual, always looking to continue my growth of knowledge and talents in all aspects of business.',
    // 'teamAdvisersPartners#123': 'Always up for a challenge, my motivation comes from overcoming obstacles to reach my goals',
    // 'teamAdvisersPartners#124': 'Career and projects: IPG Holdings, DataBlockChain, TraXion by Puma Technologies, ELYSIAN, Etherinc, FTEC Foundation,  CINDX',
    'teamAdvisersPartners#125': 'Bogdan Fiedur',
    'teamAdvisersPartners#126': 'Experto, inversor y emprendedor en cadenas de bloques y criptomonedas',
    'teamAdvisersPartners#127': 'Cofundador de bitJob y presidente de Blockchainexperts.io',
    'teamAdvisersPartners#128': 'Asesor de ICO Advisor, experto de ICOBench',
    'teamAdvisersPartners#129': 'Bogdan Fiedur es desarrollador de contratos inteligentes, criptoinversor, empresario y presidente de http://blockchainexperts.io.',
    'teamAdvisersPartners#130': 'Cuenta con más de 20 años de experiencia en el sector de la informática, en la creación de sitios web de comercio electrónico, y lleva tres años trabajando en el desarrollo de las cadenas de bloques. También es asesor de ICO y ha trabajado con 20 ICO de éxito hasta la fecha.',
    'teamAdvisersPartners#131': 'Está muy involucrado en la organización de presentaciones y talleres sobre cadenas de bloques y programación de contratos inteligentes en su criptocomunidad local de Winnipeg. Bogdan está centrado actualmente en el sector de las cadenas de bloques y ofrece asesoramiento, servicios de consultoría y contactos a los expertos en la materia. Bogdan ha cofundado recientemente Bitjob, una plataforma de cadenas de bloques para autónomos dirigida a estudiantes, y ha participado en varios proyectos de ICO, como PayPie.com.',
    'teamAdvisersPartners#132': 'Carrera y proyectos: US Blockchain Association, Tuurnt, Trends Project, BiNeuro, Zichain, Graphen Tech, CyClean, Swachhcoin y CINDX.',
    'teamAdvisersPartners#133': 'Graham Doggart',
    'teamAdvisersPartners#134': '20 años de desarrollo empresarial y cumplimiento de marketing relativo a tecnofinanzas',
    'teamAdvisersPartners#135': 'Ejecución de campañas por valor de 100 000 000 $',
    'teamAdvisersPartners#136': 'Asesor en más de 10 proyectos de cadenas de bloques este año',
    'teamAdvisersPartners#137': 'Soy presidente de un proyecto de criptomonedas oculto además de cofundador y jefe de estrategia de Dynamic Abundance, una asesoría especializada en tecnología de cadenas de bloques y tecnofinanzas, desde 2012.',
    'teamAdvisersPartners#138': 'Me especializo en estructuras y paquetes de oferta de tokens, y he trabajado en numerosos proyectos de cadenas de bloques, criptomonedas e ICO a nivel internacional.',
    'teamAdvisersPartners#139': 'Llevo más de 20 años ofreciendo asesoramiento de gestión tecnológica, asesoría de cumplimiento jurídico y financiero, estrategias de desarrollo, relaciones con inversores, y diseño y autoría de materiales.',
    'teamAdvisersPartners#140': 'Carrera y proyectos: proyecto de criptomonedas oculto, Dynamic Abundance, ELYSIAN, Fox Trading FX, Profede, Worltdopoly y CINDX.',
    'teamAdvisersPartners#141': 'Sadie Hutton',
    'teamAdvisersPartners#142': '25 años en gestión de expertos y asesoría de gestión',
    'teamAdvisersPartners#143': 'Recaudaciones de fondos multimillonarias valoradas en 75 000 000 $',
    'teamAdvisersPartners#144': 'Asesor de ICO para ocho proyectos',
    'teamAdvisersPartners#145': 'Soy la fundadora de Dynamic Abundance, una consultoría de cadenas de bloques.',
    'teamAdvisersPartners#146': 'Soy partidaria del enfoque práctico y especialista en análisis de ICO, gestión de proyectos y todos los demás aspectos clave del proceso de ICO. Una de mis fortalezas es la gestión y el desarrollo empresarial, lo que me permite ver un proyecto de principio a fin.',
    'teamAdvisersPartners#147': 'Soy una solucionadora de problemas por naturaleza y todos los proyectos en los que participo me los tomo como un asunto personal. ¡Me gusta ganar! Con más de 20 años de experiencia en administración, he creado una red eficaz y ofrezco asesoramiento sobre finanzas, tecnología, ventas, marketing y control de calidad para proyectos de cadenas de bloques de alto nivel.',
    'teamAdvisersPartners#148': 'Carrera y proyectos: Dynamic Abundance, ELYSIAN, Worldopoly, Confidential ICO, Fox Trading FX, Profede, Market Digital y CINDX.',
    'teamAdvisersPartners#149': 'Jason King',
    'teamAdvisersPartners#150': '20 años de experiencia a nivel ejecutivo',
    'teamAdvisersPartners#151': 'Dirección de operaciones empresariales en 30 países',
    'teamAdvisersPartners#152': 'Responsable de estados de resultados de más de 500 000 000 $',
    'teamAdvisersPartners#153': 'Jason King lleva 20 trabajando como ejecutivo de tecnología, medios y telecomunicaciones, participando en negocios comerciales de estructura e intermediación, negociando ganancias, desarrollando mercados, y ayudando a organizaciones a alcanzar el éxito.',
    'teamAdvisersPartners#154': 'Muchos de estos desafíos me han permitido acceder a importantes puestos de reestructuración y reforma.',
    'teamAdvisersPartners#155': 'Hay que liderar formando a las personas y los equipos adecuados para alcanzar los objetivos más rentables.',
    'teamAdvisersPartners#156': 'Jason cuenta con amplia experiencia en distintas áreas como administración de empresas y operaciones, planificación estratégica y finanzas, criptomonedas, y cadenas de bloques.',
    'teamAdvisersPartners#157': 'Motti Peer',
    'teamAdvisersPartners#158': 'Cofundador de Blonde 2.0, agencia de relaciones públicas internacional galardonada',
    'teamAdvisersPartners#159': 'Fundador de varias empresas de los sectores de la seguridad y las finanzas.',
    'teamAdvisersPartners#160': 'Motti es uno de los pioneros en temas de relaciones públicas para cadenas de bloques y criptomonedas, empresas emergentes, y divisas virtuales.',
    'teamAdvisersPartners#161': 'Cuenta con muchos años de experiencia en gestión de capitales y fondos de cobertura y tiene un MBA en Finanzas y Marketing de la Universidad de Manchester. Es licenciado en Dirección de Empresas por la Fairleigh Dickinson University.',
    'teamAdvisersPartners#162': 'Es codirector general de Blonde 2.0, una agencia internacional de relaciones públicas galardonada y nombrada una de las empresas emergentes más influyentes e impulsoras por Forbes.',
    'teamAdvisersPartners#163': 'Como codirector de Blonde 2.0, se encarga de gestionar los aspectos de las relaciones públicas, así como de la gestión de estrategias y crisis. Con un equipo de 35 profesionales, Blonde 2.0 es una empresa pionera en temas de relaciones públicas para cadenas de bloques y criptomonedas, empresas emergentes, y divisas virtuales.',
    'teamAdvisersPartners#164': 'Leonard Grayver',
    'teamAdvisersPartners#165': 'Socio de Greenberg, Whitcombe & Takeuchi',
    'teamAdvisersPartners#166': 'Representante de más de 400 empresas emergentes',
    'teamAdvisersPartners#167': 'Recaudó más de 18 000 000 $ para esta empresa emergente cuando estudiaba Derecho en la universidad',
    'teamAdvisersPartners#168': 'Leonard Grayver nació en la URSS y se trasladó a EE. UU. con sus padres cuando era niño. Cuando aún estudiaba Derecho en la universidad, Leonard creó una empresa emergente y recaudó más de 18 000 000 $ para su financiación. La empresa no sobrevivió, pero, desde entonces, Leonard ha ayudado a más de 400 emergentes.',
    'teamAdvisersPartners#169': 'En total, Leonard cuenta con más de 10 años de experiencia en financiación de monedas virtuales, estructuración de fondos y diligencia debida (representando tanto a fondos como a sociedades limitadas). Su consejo para todos los emprendedores: no seguir las tendencias, sino los propios intereses.',
    'teamAdvisersPartners#170': 'Leonard ha establecido excelentes contactos profesionales con varios fondos de emprendimiento internacionales.',

    'joinTokenPreSale#1': 'Apuntarse a la preventa de tokens!',
    'joinTokenPreSale#2': 'Apuntarse a la preventa',
    'joinTokenPreSale#3': 'Probar versión MVP',
    'joinTokenPreSale#4': 'Oficina central',
    'joinTokenPreSale#5': 'Harjumaa, Erika 14,',
    'joinTokenPreSale#6': 'Talinn, 10416, Estonia',
    'joinTokenPreSale#7': 'Consultas de negocios | hello@cindx.io',
    'joinTokenPreSale#8': 'Nota legal',
    'joinTokenPreSale#9': 'Desarrollo y marketing',
    'joinTokenPreSale#10': 'Presnenskaya naberezhnaya, 8 building 1,',
    'joinTokenPreSale#11': 'Moscow, 123112, Russia',
    'joinTokenPreSale#12': 'Empleo | Únase a nuestro equipo |',
}

export default es