// Французкий
const fr = {
    'mainBlock#1': 'Rendre l\'investissement dans les cryptos',
    'mainBlock#2': 'Facile, Sécurisé et Rapide',
    'mainBlock#3': 'S\'inscrire à notre vente de jetons de sécurité',

    'icoInfo#1': 'Nous acceptons:',
    'icoInfo#2': 'Hard cap:',
    'icoInfo#3': 'Jalons soft cap:',
    'icoInfo#4': 'Les contrats d\'inscription sont signés avec',

    'menu#1': 'WHITEPAPER',
    'menu#2': 'PRESENTATION',
    'menu#3': 'ONE PAGER',
    'menu#4': 'FINANCIAL MODEL',
    'menu#5': 'LEGAL DOCS',
    'menu#6': 'EN',
    'menu#7': 'Produit',
    'menu#8': 'Détails de la vente',
    'menu#9': 'Équipe',
    'menu#10': 'Docs publics',
    'menu#11': 'Tester un MVP ',

    'mailForm#1': 'Wrong email',
    'mailForm#2': 'sending ..',
    'mailForm#3': 'Already was or is not valid, try again',
    'mailForm#4': 'Your email has been sent successfully',
    'mailForm#5': 'an error occurred, try again',
    'mailForm#6': 'GDRP Сompliance',
    'mailForm#7': 'Personal data provided via Subscription form and KYC procedure will be collected in the full compliance with GDRP',
    'mailForm#8': 'The Data Protection Officer  of the project is  Mrs. Sofja Pevzner-Belositski. Contact details: dpo@cindx.io. Any data subject may, at any time, contact Data Protection Officer of directly with any request related to data protection.',
    'mailForm#9': 'Your personal data provided via Subscription form and KYC procedure will be shared to our partners:',
    'mailForm#10': 'ICO Promo',
    'mailForm#11': 'Privacy Policy',
    'mailForm#12': 'Sum & Substance',
    'mailForm#13': 'By default, the personal data provided by subscriber are kept by CINDX, ICO Promo and Sum & Substance for 5 years after registration of subscriber in the system',
    'mailForm#14': 'If you do not agree to this privacy policy, please do not use our site.',
    'mailForm#15': 'By using our site, you consent to the collection and use of information by us. Owing to the global nature of the internet infrastructure, the information you provide may be transferred in transit to countries outside the European Economic Area that do not have similar protections in place regarding your data and its use as set out in this policy.',
    'mailForm#16': 'However, we have taken the steps outlined above to try to improve the security of your information. By submitting your information you consent to these transfers',
    'mailForm#17': 'I agree to process my',
    'mailForm#18': 'personal data',
    'mailForm#19': 'Vente de jetons de sécurité en direct',
    'mailForm#20': '25% BONUS',
    'mailForm#21': 'Obtenez-le avant les autres L\'offre expire dans',
    'mailForm#22': 'Token sale starts in',
    'mailForm#23': 'Start from $1',
    'mailForm#24': '1$ later',
    'mailForm#25': 'Votre adresse e-mail',
    'mailForm#26': 'S\'inscrire à la pré-vente ',
    'mailForm#27': 'AGREE & SUBMIT',

    'progressBarSale#1': 'Bonuses',
    'progressBarSale#2': 'in CINX',
    'progressBarSale#3': 'Pré-vente',
    'progressBarSale#4': 'Sale',
    'progressBarSale#5': 'Aug 26',
    'progressBarSale#6': 'Sep 17',
    'progressBarSale#7': 'Oct 8',
    'progressBarSale#8': 'Oct 22',
    'progressBarSale#9': 'Nov 6',
    'progressBarSale#10': 'Nov 19',
    'progressBarSale#11': 'Dec 3',
    'progressBarSale#12': 'Dec 17',

    'cryptoAssetsManagement#1.1': 'CIDNX est une plateforme de gestion d\'actifs crypto. Nous résolvons les problèmes des investisseurs,',
    'cryptoAssetsManagement#1.2': 'des traders et des développeurs',
    'cryptoAssetsManagement#2': 'CINDX.MARCHÉ POUR INVESTISSEURS',
    'cryptoAssetsManagement#3': 'Ne vous inquiétez pas de votre niveau de connaissance et d\'expérience – les experts en trading des cryptos sont là pour vous aider',
    'cryptoAssetsManagement#4': 'Contrôlez votre fonds crypto : vos crypto-monnaies sont conservées en permanence dans votre portefeuille',
    'cryptoAssetsManagement#5': 'Vous ne payez que si vous gagnez : des frais ne vous seront facturés que si votre portefeuille rapporte de l\'argent',
    'cryptoAssetsManagement#6': 'TESTER UN MVP',
    'cryptoAssetsManagement#7': 'CINDX.TERMINAL POUR LES TRADERS',
    'cryptoAssetsManagement#8': 'Si vous êtes un trader à succès, vous pouvez attirer des capitaux sans aucun investissement dans le marketing',
    'cryptoAssetsManagement#9': 'Nous vous fournissons un terminal, un App Store, une place de marché et d\'autres outils de pointe pour vous aider à réussir dans le trading',
    'cryptoAssetsManagement#10': 'CINDX aide à monétiser votre réputation et votre expertise. Votre historique de trading et votre influence sont visibles.',
    'cryptoAssetsManagement#11': 'CINDX.TALK, CINDX.HUB et CINDX.DAO',
    'cryptoAssetsManagement#12': 'CINDX.Talk - un réseau social avec une récompense pour le contenu utile',
    'cryptoAssetsManagement#13': 'CINDX.Hub - les composants comprennent un « compte vendeur » et une plateforme qui permet de tester et d\'intégrer des logiciels tiers ',
    'cryptoAssetsManagement#14': 'CINDX.dao - un composant qui vous permet de mettre en place un système de vote pour la communauté basé sur des règles d\'organisation autonome décentralisée',

    'teamLegal#1': 'NOUS DISPOSONS D\'UNE EXCELLENTE ÉQUIPE ET DU MEILLEUR',
    'teamLegal#2': 'CADRE ORGANISATIONNEL JURIDIQUE ET RÉGLEMENTAIRE DE SA CATÉGORIE.',
    'teamLegal#3': 'CRYPTOCURRENCY EXCHANGE LICENSE',
    'teamLegal#4': 'FINANCIAL INSTITUTION LICENSE',
    'teamLegal#5': 'CRYPTO WALLET LICENSE',
    'teamLegal#6': 'LIVRE BLANC',
    'teamLegal#7': 'PRÉSENTATION',
    'teamLegal#8': 'DOCUMENT D\'UNE PAGE',
    'teamLegal#9': 'MODÈLE FINANCIER',
    'teamLegal#10': 'DOCUMENTS JURIDIQUES',

    'roadmap#1': 'Feuille de route',
    'roadmap#2': 'Scénario',
    'roadmap#3': 'We are building the base for the CINDX platform. At this step, the Minimum Viable Product (MVP) is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform.',
    'roadmap#4': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be  going through some alterations to add functionalities.  ',
    'roadmap#5': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services.      ',
    'roadmap#6': 'At this stage, the CINDX.market and CINDX.trade components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. ',
    'roadmap#7': 'CINDX.talk will have public and private channels. At this stage, the content will  be able to be  separated. ',
    'roadmap#8': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade is an extremely flexible system of order execution and risk management. The Vendor’s market will appear; however, at this point, the Vendor’s market will only contain applications developed by CINDX and its partners.  ',
    'roadmap#9': 'A tokenized rating system will be added in the final version of CINDX.talk, as well as a new type of product: “algorithmic trading”. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders.   ',
    'roadmap#10': 'We are building the base for the CINDX platform. At this step, the MVP is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform. ',
    'roadmap#11': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be going through some alterations to add functionalities.  ',
    'roadmap#12': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services. Another new component, CINDX.hub, will enable Vendors to develop applications that will analyze the market data that CINDX provides. ',
    'roadmap#13': 'At this stage, the CINDX.market and CINDX.trade components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. An SDK for developers will be released. This should simplify application development and implementation for CINDX.  ',
    'roadmap#14': 'CINDX.talk will have public and private channels. At this stage, the content will be able to be separated. CINDX.hub will integrate Github, which will simplify application development even more.',
    'roadmap#15': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade will be an extremely flexible system of order execution and risk management. CINDX.hub will have a full-scale editor for trading strategies with a testing system based on historical market data.',
    'roadmap#16': 'A tokenized rating system  CINDX.talk will be added in the final version of CINDX.talk. This will provide a system of assessment for CINDX community trading experts. “Algorithmic trading” will also be added. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders. A high-grade platform for a code audit will be created. ',
    'roadmap#17': 'We are building the base for the CINDX platform. At this step, the MVP is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform.',
    'roadmap#18': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be  going through some alterations to add functionalities. ',
    'roadmap#19': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services. Another new component,  CINDX.hub, will enable Vendors to develop applications that will analyze the market data that CINDX provides. The team will develop CINDX.dao, a component that acts as a system for the platform’s revenue distribution to its token holders.       ',
    'roadmap#20': 'At this stage, the CINDX.market and CINDX.trade  components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. An SDK for developers will be released. This should simplify application and implementation development for CINDX.  ',
    'roadmap#21': 'CINDX.talk will have public and private channels. At this stage the content can be separated. CINDX.hub will integrate Github which will simplify application development even more.',
    'roadmap#22': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade will be an extremely flexible system of order execution and risk management. CINDX.hub has a full-scale editor for trading strategies with a testing system based on historical market data. CINDX.dao will receive a voting system for token holders. ',
    'roadmap#23': 'A tokenized rating system CINDX.talk will be added in the final version of CINDX.talk. This will provide a system of assessment for CINDX community trading experts. “Algorithmic trading” will also be added. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders. A high-grade platform for a code audit will be created. ',

    'problemSolving#1': 'Temps',
    'problemSolving#2': 'Confiance',
    'problemSolving#3': 'Incertitude',
    'problemSolving#4': 'J\'ai de l\'argent à investir dans le trading des cryptos, mais je n\'ai pas le temps de faire des recherches et de contacter des traders professionnels pour qu\'ils gèrent mon portefeuille',
    'problemSolving#5': 'Je me suis toujours senti mal à l\'aise à l\'idée de remettre mon argent à quelqu\'un d\'autre pour réaliser un profit',
    'problemSolving#6': 'La technologie utilisée dans le trading des cryptos n\'est pas conviviale. Je n\'arrive pas à comprendre comment échanger mes crypto-monnaies.',
    'problemSolving#7': 'CINDX fournit l\'accès à des traders notés et dignes de confiance ',
    'problemSolving#8': 'Sur la plateforme CINDX, vos fonds ne quittent jamais votre portefeuille',
    'problemSolving#9': 'Vous gagnez avec les meilleurs traders du marché',
    'problemSolving#10': 'Les traders sur CINDX sont notés en fonction de leur historique de réussite dans le trading. Choisissez rapidement le trader qui vous convient',
    'problemSolving#11': 'Notre système décentralisé et nos contrats intelligents permettent de gérer vos fonds sans qu\'ils ne soient transférés à un trader',
    'problemSolving#12': 'Chaque investisseur de CINDX a la possibilité de faire gérer ses fonds par les traders les plus performants du marché',
    'problemSolving#13': 'Quels types de problèmes CINDX peut résoudre?',
    'problemSolving#14': 'TESTER UN MVP ',

    'howCindxWorks#1': 'Investisseurs',
    'howCindxWorks#2': 'Traders',
    'howCindxWorks#3': 'Vendeurs',
    'howCindxWorks#4': 'Ils augmentent leurs gains en cryptos grâce aux compétences en gestion de portefeuille des meilleurs traders',
    'howCindxWorks#5': 'Ils gagnent des commissions auprès des investisseurs qui les suivent en fonction de leur performance et de leur stratégie de trading',
    'howCindxWorks#6': 'Ils vendent des outils de trading de pointe, tels que des robots de trading et des widgets d\'actualités.',
    'howCindxWorks#7': 'Elle perçoit les commissions et les frais d\'abonnement',
    'howCindxWorks#8': 'Je rejoins CINDX avec des actifs crypto que je souhaite faire trader',
    'howCindxWorks#9': 'Je rejoins CINDX avec une expertise en trading qui profitera aux investisseurs',
    'howCindxWorks#10': 'Je rejoins CINDX avec des applications de trading qui aideront les investisseurs',
    'howCindxWorks#11': 'Nous sommes là pour faciliter, sécuriser et rentabiliser le trading',
    'howCindxWorks#12': 'En bref, comment fonctionne CINDX?',

    'marketAnalytics#1': 'Analyse du marché',
    'marketAnalytics#2': 'AUM global',
    'marketAnalytics#3': 'Investissement',
    'marketAnalytics#4': 'Croissance du capital',
    'marketAnalytics#5': 'Depuis 2000, le marché mondial de la gestion de fortune a progressé de plus de 250 %.',
    'marketAnalytics#6': 'Ceci résulte de l\'amélioration constante des outils du marché et du développement général des structures de marché.',
    'marketAnalytics#7': 'Malgré la croissance explosive des crypto-monnaies en 2017, l\'industrie en est encore à ses balbutiements.',
    'marketAnalytics#8': 'La capitalisation boursière totale s\'élevait à 600 milliards de dollars à la fin de 2017, soit seulement 1 % de la capitalisation boursière totale de l\'industrie de la gestion de fortune.',
    'marketAnalytics#9': 'LIVRE BLANC',
    'marketAnalytics#10': 'PRÉSENTATION',
    'marketAnalytics#11': 'DOCUMENT D\'UNE PAGE',
    'marketAnalytics#12': 'MODÈLE FINANCIER',
    'marketAnalytics#13': 'DOCUMENTS JURIDIQUES',
    'marketAnalytics#14': 'Portée géographique',
    'marketAnalytics#15': '25 millions de portefeuilles',
    'marketAnalytics#16': 'de blockchain potentiels',
    'marketAnalytics#17': '200 000 transactions',
    'marketAnalytics#18': 'potentielles par jour',
    'marketAnalytics#19': 'Plus de 225 partenaires',
    'marketAnalytics#20': 'potentiels, chacun d\'une valeur de 3 à 5 milliards de dollars',

    'tokenSaleDetails#1': 'Attribution de jetons',
    'tokenSaleDetails#2': 'Équipe',
    'tokenSaleDetails#3': 'Prime',
    'tokenSaleDetails#4': 'Conseillers',
    'tokenSaleDetails#5': 'Réserve',
    'tokenSaleDetails#6': 'Subventions communautaires',
    'tokenSaleDetails#7': 'Appui en liquidités sous forme de jetons',
    'tokenSaleDetails#8': 'Disponible à la vente',
    'tokenSaleDetails#9': 'Nom du jeton : CINX',
    'tokenSaleDetails#10': 'Début de la pré-vente de jetons : 26/08/2018',
    'tokenSaleDetails#11': 'Émission totale : 51 500 000',
    'tokenSaleDetails#12': 'Prix du jeton : 1,00 $',
    'tokenSaleDetails#13': 'Investissement minimal:',
    'tokenSaleDetails#14': 'l\'équivalent de 50 $',
    'tokenSaleDetails#15': 'LIVRE BLANC',
    'tokenSaleDetails#16': 'PRÉSENTATION',
    'tokenSaleDetails#17': 'DOCUMENT D\'UNE PAGE',
    'tokenSaleDetails#18': 'MODÈLE FINANCIER',
    'tokenSaleDetails#19': 'DOCUMENTS JURIDIQUES',
    'tokenSaleDetails#20': 'Utilisation des bénéfices',
    'tokenSaleDetails#21': 'Marketing et RP 21%',
    'tokenSaleDetails#22': 'Recherche et développement 41%',
    'tokenSaleDetails#23': 'Opérations 28%',
    'tokenSaleDetails#24': 'Frais juridiques 7%',
    'tokenSaleDetails#25': 'Primes aux traders 3%',
    'tokenSaleDetails#26': 'Transactions de jetons',
    'tokenSaleDetails#27': 'Vente de jetons',
    'tokenSaleDetails#28': 'Prime de la pré-vente de jetons:',
    'tokenSaleDetails#29': 'Aug 26 - Sep 16 - 25% Bonus',
    'tokenSaleDetails#30': 'Sep 17 - Oct 7 - 20% Bonus',
    'tokenSaleDetails#31': 'Token Main Sale Bonuses:',
    'tokenSaleDetails#32': '8 oct. - 21 oct. - Prime de 17 %',
    'tokenSaleDetails#33': '22 oct. - 4 nov. - Prime de 15 %',
    'tokenSaleDetails#34': '6 nov. - 18 nov. - Prime de 13 %',
    'tokenSaleDetails#35': '19 nov. - 2 déc. - Prime de 10 % ',
    'tokenSaleDetails#36': '3 déc. - 16 déc. - Prime de 5 %',
    'tokenSaleDetails#37': '17 déc. - 26 déc. - Prime de 0 %',
    'tokenSaleDetails#38': 'Acheter des jetons',
    'tokenSaleDetails#39': 'Token Sale Details',
    'tokenSaleDetails#40': 'During the token sale, investors purchase utility tokens – options [CINXO], which give them the right to receive security tokens [CINX] in the future.',
    'tokenSaleDetails#41': 'Security tokens [CINX] will be issued and distributed following the prospect of emission published on the website of FSA of Estonia https://www.fi.ee/ and cindx.io after the end of the token sale, but no later than Q1 2019.',
    'tokenSaleDetails#42': 'The holder of [CINXO] tokens has the right but no obligation to exchange options for security tokens with a ratio of 1:1 after completing the KYC procedure with identification signature, address confirmation and supply of other documents (see the KYC diagram).',
    'tokenSaleDetails#43': 'Tokens [CINXO] grant the same rights as security tokens apart from the right to participate in revenue distribution with a lock-up and voting on the platform.',

    'legalSchedule#1': 'Calendrier juridique',
    'legalSchedule#2': 'OBTENTION DE LA LICENCE (FVR000110) POUR LA FOURNITURE DE L\'ÉCHANGE ENTRE LA MONNAIE VIRTUELLE ET LES SERVICES FIAT',
    'legalSchedule#3': 'DEMANDE D\'ENREGISTREMENT DE LA MARQUE EN ESTONIE ET DANS L\'UE',
    'legalSchedule#4': 'DE LA LICENCE FFA000254 POUR OPÉRER EN TANT QU\'INSTITUTION FINANCIÈRE',
    'legalSchedule#5': 'OBTENTION DE LA LICENCE FFA000254 POUR OPÉRER EN TANT QU\'INSTITUTION FINANCIÈRE',
    'legalSchedule#6': 'Prospectus élaboré conformément à la législation estonienne',
    'legalSchedule#7': 'LICENCE FSA DEMANDÉE (Autorité estonienne de surveillance financière)',
    'legalSchedule#8': 'OBTENTION DE LA LICENCE POUR LA FOURNITURE D\'UN SERVICE DE PORTEFEUILLE VIRTUEL',
    'legalSchedule#9': 'ENREGISTRÉ SOUS LE RÉGIME DE L\'EXEMPTION D DE LA SEC',
    'legalSchedule#10': 'NOMINATION D\'UN GESTIONNAIRE DE DONNÉES PERSONNELLES POUR RÉPONDRE AUX EXIGENCES DU RGDP',
    'legalSchedule#11': 'OBTENTION DE LA LICENCE FSA',
    'legalSchedule#12': 'ENREGISTREMENT DU PROSPECTUS EU 809-2004',
    'legalSchedule#13': 'ÉMISSION DES JETONS DE SÉCURITÉ CINX',

    'feedbackProject#1': 'COMMENTAIRES SUR NOS PROJETS',
    'feedbackProject#2': 'Val Jerdes',
    'feedbackProject#3': 'Directeur de produit',
    'feedbackProject#4': 'Val Jerdes, directeur de produit CINDX, parle des membres clés de l\'équipe et de la manière dont leur expertise aidera à développer le projet susceptible de changer de manière significative le jeu de la finance',
    'feedbackProject#5': 'Denis Eskenazi',
    'feedbackProject#6': 'Directeur du marketing produit',
    'feedbackProject#7': 'Denis Eskenazi, directeur du marketing produit chez CINDX, explique pourquoi il a rejoint cette entreprise',
    'feedbackProject#8': 'Philip Staehelin',
    'feedbackProject#9': 'Conseiller',
    'feedbackProject#10': 'Philip Staehelin, conseiller du projet CINDX, explique comment la révolution des cryto-devises peut aider même les investisseurs inexpérimentés et parle de la percée que le projet CINDX a préparé pour le marché des cryptos',
    'feedbackProject#11': 'Andrzej Cichowlaz',
    'feedbackProject#12': 'Spécialiste en marketing',
    'feedbackProject#13': 'Andrzej Cichowlaz, directeur marketing chez CINDX, explique pourquoi il croit en la réussite du projet',
    'feedbackProject#14': 'Austin Kimm',
    'feedbackProject#15': 'Austin Kimm, conseiller du projet CINDX, raconte comment CINDX rend simple et intelligent le trading des crypto-devises pour le profit',
    'feedbackProject#16': 'Amarpreet Singh',
    'feedbackProject#17': 'Amarpreet Singh, conseiller CINDX, explique comment la plateforme CINDX peut combler le fossé qui existe entre les investisseurs et les traders',
    'feedbackProject#18': 'Keith Teare',
    'feedbackProject#19': 'Keith Teare, conseiller CINDX, présente les avantages de la plateforme CINDX',
    'feedbackProject#20': 'Mansur Rasulov',
    'feedbackProject#21': 'Responsable communautaire',
    'feedbackProject#22': 'Mansur Rasulov, responsable communautaire chez CINDX, explique pourquoi il a décidé de faire partie de l\'équipe CINDX ',
    'feedbackProject#23': 'Sadie Hutton',
    'feedbackProject#24': 'Sadie Hutton, conseillère CINDX, explique en quoi la plateforme CINDX se distingue des autres plateformes de trading automatisées',
    'feedbackProject#25': 'Graham Doggart',
    'feedbackProject#26': 'Graham Doggart, conseiller CINDX, parle des points forts de la plateforme CINDX',
    'feedbackProject#27': 'Alina Vardanian',
    'feedbackProject#28': 'Gestionnaire de contenu',
    'feedbackProject#29': 'Alina Vardanian, gestionnaire du contenu chez CINDX, parle de l\'esprit d\'équipe et de ce qu\'elle aime dans son travail ',
    'feedbackProject#30': 'Bogdan Fiedur',
    'feedbackProject#31': 'Conseiller CINDX',
    'feedbackProject#32': 'Bogdan Fiedur, conseiller CINDX, explique en quoi le projet CINDX diffère des autres projets ICO',
    'feedbackProject#33': 'Jason King',
    'feedbackProject#34': 'Jason King, chef de la direction commerciale, explique ce qui l\'attire chez CINDX et parle des avantages cruciaux du projet',

    'mediaNews#1': 'Médias',
    'mediaNews#2': 'Actualités',
    // Médias
    'mediaNews#1_1': 'CINDX Aims to Democratize the Modern Financial System',
    'mediaNews#1_2': 'Even as investors in the cryptocurrency space recognize that they are at the forefront of a new financial revolution, adoption by the general populace is yet to occur. While 3rd parties are slowly entering the space in the form of hedge funds and other investors, very few individuals seem to have taken the step to invest in cryptocurrencies on their own.',
    'mediaNews#1_3': 'CINDX Announces Plans For ICO Pre-Sale Amidst Release Of Revolutionary Crypto Trading Hub That Allows Users To Follow Expert Traders',
    'mediaNews#1_4': 'CINDX takes its business seriously with particular attention and cares to legal matters and has taken great pains to ensure that CINDX is as compliant as possible with global regulations.',
    'mediaNews#1_5': 'How CINDX is Democratizing the Modern Financial System',
    'mediaNews#1_6': 'CINDX is a new platform that is making crypto trading easier, more secure, and more accessible. With this platform, it’s possible to have your funds traded without high fees or minimum investments, with the added security and transparency of blockchain technology.',
    'mediaNews#1_7': 'CINDX is making crypto trading easier, more secure, and more accessible.',
    'mediaNews#1_8': 'Cryptocurrency and blockchain technology have been slated as powerful tools capable of fueling a global financial revolution. There are myriad opportunities to invest in the crypto space, and yet, very few individuals have undertaken the steps necessary to invest.',
    'mediaNews#1_9': 'CINDX Announces Plans Release Of Revolutionary Crypto Trading Hub',
    'mediaNews#1_10': 'The CINDX platform creates a complete ecosystem for cryptocurrency trading that is favorable to all the participants of the market and offers solutions to existing pain points.',
    'mediaNews#1_11': 'CINDX Announces Plans For ICO Pre-Sale',
    'mediaNews#1_12': 'CINDX made headlines this week with the announcement that they will be opening their ICO Pre-Sale in late August after investors interest in the ICO peaks to new levels.',
    'mediaNews#1_13': 'CINDX Will Be Opening ICO Pre-Sale in late August',
    'mediaNews#1_14': 'The CINDX Crypto trading platform has a myriad of features and benefits that haven’t been seen in other platforms to date.',
    'mediaNews#1_15': '5 Tips from CINDX Crypto Assets Management Hub: How to Avoid Being Cheated',
    'mediaNews#1_16': 'The team behind the CINDX crypto assets management hub has created a helpful set of guidelines on how not to become victims of unfair play, so you can learn what should be primarily taken into account when evaluating ICOs before investing in them.',
    'mediaNews#1_17': 'CINDX Crypto Asset Management Hub Adopts Bancor Protocol',
    'mediaNews#1_18': 'CINDX is delighted to announce that a number of new integrations with top industry players are underway, each of which will make the life of the users of the platform easier and richer. These new integrations include the decision to adopt the Bancor protocol to provide continuous liquidity for the CINDX platform.',
    // News
    'mediaNews#2_1': 'CINDX meets Ian Balina',
    'mediaNews#2_2': 'CINDX pitch to the one of the TOP10 crypto gurus in the world in the Cryptobazar event.',
    'mediaNews#2_3': 'CINDX took part in Moscow ICO Summit 2018',
    'mediaNews#2_4': 'CINDX team introduced the project to the Russian crypto community during ICO Summit event.',
    'mediaNews#2_5': 'How CINDX is ensuring legal compliance',
    'mediaNews#2_6': 'Our company is registered in Estonia. Why? The answer is simple — the authorities of Estonia have created a strong and innovative legal infrastructure...',
    'mediaNews#2_7': 'Keith Teare Co-founder of Accelerated Digital Ventures and Founding Shareholder in TechCrunch',
    'mediaNews#2_8': 'We continue to introduce CINDX advisers, find out what they...',
    'mediaNews#2_9': 'Meet world\'s first financial crypto social network',
    'mediaNews#2_10': 'Every day our team takes one more step on the way to creation and start...',
    'mediaNews#2_11': 'Denis Eskenazi CINDX Product Marketing Director',
    'mediaNews#2_12': 'We continue to tell about the CINDX team and each team member’s professional experience. Please, read about Denis Eskenazi...',
    'mediaNews#2_13': 'CINDX crypto currency exchange license',
    'mediaNews#2_14': 'Our company in Estonia has received Crypto Currency Exchange License. This allows CINDX to provide fiat-to-crypto exchange services. This licence is issued...',
    'mediaNews#2_15': 'Austin Kimm Co-founder of Crypterium & CINDS Adviser',
    'mediaNews#2_16': 'We continue to introduce CINDX advisers, find out what they are proud...',
    'mediaNews#2_17': 'The strategic meeting of the international CINDX team',
    'mediaNews#2_18': 'Every day our team takes one more step on the way to creation and start of the CINDX platform. Our work...',
    'mediaNews#2_19': 'Artur Shamalov CINDX Investment Director',
    'mediaNews#2_20': 'We continue to introduce the CINDX team. Our next article is about Artur Shamalov, a skilled...',
    'mediaNews#2_21': 'The issuance of CINX tokens',
    'mediaNews#2_22': 'The issuance of CINX tokens will be carried out according to the license of The Estonian Financial Supervisory Authority (EFSA). What is a token...',
    'mediaNews#2_23': '"Amarpreet Singh Co-Founding Member of Malta Blockchain Association & CINDX adviser"',
    'mediaNews#2_24': 'We at CINDX are incredibly proud to present our advisers, tell the world about their achievements and why they have decided to become a part of the CINDX...',
    'mediaNews#2_25': 'CINDX meets Vangoo Capital Partners Fund',
    'mediaNews#2_26': 'Today we have welcomed Kevin Shang from Vangoo Capital Partners and his colleagues in our office. We have discussed business partnership opportunities in order to attract investors from the Asian region.',
    'mediaNews#2_27': '"Mofassair Hossain CINDX Chief Marketing Officer."',
    'mediaNews#2_28': 'We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly excited about...',
    'mediaNews#2_29': 'How CINDX ensures safety for its users - KYC',
    'mediaNews#2_30': 'Every crypto enthusiast knows that a KYC procedure is necessary in order to protect investors against fraudulent actions of the third...',
    'mediaNews#2_31': 'Philip Staehelin 25 Years of Consulting and Entrepreneurial Experience',
    'mediaNews#2_32': 'We continue our regular series of articles dedicated to introducing CINDX advisers. The next item is about Philip Staehelin.',
    'mediaNews#2_33': 'CINDX meets 9coin Digital Asses Exchange',
    'mediaNews#2_34': 'The CINDX team continues active work on building relationships with various international companies. One of the most important directions of business...',
    'mediaNews#2_35': 'Jason King Interim Chief Commercial Officer',
    'mediaNews#2_36': 'The core of any great project is always people who make the unique idea come true. We would like to tell about...',
    'mediaNews#2_37': 'CINDX Presents the project during RICLUB private investors meeting',
    'mediaNews#2_38': 'CINDX has successfully passed the due diligence procedure requested by RICLub and was one of the few projects...',
    'mediaNews#2_39': 'Sofja Pevzner CINDX Personal Data Officer',
    'mediaNews#2_40': 'We continue to introduce our team and tell about what inspires our colleagues to work with CINDX. Please read about...',
    'mediaNews#2_41': 'Tyler Sanford 8+ years digital marketing in Yelp, Zenefits',
    'mediaNews#2_42': 'We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become a part of the CINDX team. In this...',
    'mediaNews#2_43': 'CINDX - Key points to observe',
    'mediaNews#2_44': 'The CINDX project is a valuable business venture with the features that are critically relevant for its participants. In this article we talk about Strengths...',
    'mediaNews#2_45': 'Airat Shayhulov CINDX Head of Quantitative Research.',
    'mediaNews#2_46': 'In “TEAM” series of the articles, we tell about people who every day participates in the creation...',
    'mediaNews#2_47': 'CINDX license of the financial consultant',
    'mediaNews#2_48': 'CINDX has obtained a termless operating licence (the FFA 000254 license) that gives the right to operate as a financial institution...',
    'mediaNews#2_49': '"Graham Doggart 20 Years of Enterprise Development and Fintech Marketing Compliance"',
    'mediaNews#2_50': 'We continue our regular series of articles dedicated to introducing CINDX advisers. The next item...',
    'mediaNews#2_51': 'CINDX continues the roadshow in China!',
    'mediaNews#2_52': 'The CINDX team is glad to announce participation as a Golden Sponsor of Borderless Blockchain Technology Summit 2018, which...',
    'mediaNews#2_53': 'Ibraghim Haniev CINDX Tech Lead',
    'mediaNews#2_54': 'Get to know more about the CINDX team! The core of any great project is always people who make the unique ideas come true...',
    'mediaNews#2_55': 'Sadie Hutton 25 Years in Senior Management and Management Consulting',
    'mediaNews#2_56': 'Like any global project, we understand the importance of professional help and advice. We continue to tell the stories of...',
    'mediaNews#2_57': 'CINDX.talk - a service that will help people become wiser in taking financial decisions',
    'mediaNews#2_58': 'The current digital-world related to the crypto industry is getting crowded with mind-charming digital solutions...',
    'mediaNews#2_59': '"Val Jerdes CINDX Product Director"',
    'mediaNews#2_60': 'We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly...',
    'mediaNews#2_61': 'Bogdan Fiedur Blockchain and cryptocurrency expert, investor, entrepreneur',
    'mediaNews#2_62': 'We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become...',
    'mediaNews#2_63': 'Welcome to CINX Token Distribution – it’s not an ICO; it’s an STO',
    'mediaNews#2_64': 'In this article, we want to make it clear why CINDX chose to hold a Security Token Offering (STO) instead of an Initial...',
    'mediaNews#2_65': 'CINDX celebrates the “AA” Rating from Top ICO List Audit!',
    'mediaNews#2_66': 'The results of CINDX’s sincerity to make meaningful changes in people’s ambitions via a unique business model just got appreciated...',
    'mediaNews#2_67': 'CINDX Weekly digest (30.07.18 - 05.08.18)',
    'mediaNews#2_68': 'The CINDX team is very excited to share the results of our work for the last week 30.07.18 - 05.08.18!',
    'mediaNews#2_69': 'Virtual Currency Wallet Services',
    'mediaNews#2_70': 'CINDX believes that being fluent in legal issues and having a clean, confident and clear legal status is of utmost importance. At the moment, CINDX is going...',
    'mediaNews#2_71': 'How CINDX Influences Crypto Trading',
    'mediaNews#2_72': 'How to master the crypto market movements and turn them in one’s favor? This is where CINDX’s effective business model comes into play. Learn more about CINDX on our Medium!',
    'mediaNews#2_73': 'CINDX Weekly digest (06.08.18 - 12.08.18)',
    'mediaNews#2_74': 'CINDX continues its regular column - Weekly Digest. We are excited to share the recent achievements of our project! Enjoy your time reading!',
    'mediaNews#2_75': 'CINDX gets 5.0 rating on TrackICO!',
    'mediaNews#2_76': 'CINDX continues getting approval from the largest and the most credible rating services. The week has hardly passed after...',
    'mediaNews#2_77': '"David Gutierrez Investment Relations Officer"',
    'mediaNews#2_78': 'CINDX is very serious about taking people on crew and proud to introduce them. This article is dedicated to David Gutierrez, CINDX Investment Relations Officer',
    'mediaNews#2_79': 'ICObench gives 4.8 to CINDX',
    'mediaNews#2_80': 'The CINDX project has already gained the highest mark of  ‘AA’ from Top ICO List and got a 5.0 rating from TrackICO. Now, we are proud to share...',
    'mediaNews#2_81': 'Dip your Toe in Crypto',
    'mediaNews#2_82': 'It is never late to change your mind. It’s no surprise that Wall Street bankers change their minds in favour of crypto. Enjoy reading CINDX review on the current market situation!',
    'mediaNews#2_83': 'Yuriy Avdeev, CEO of the CINDX project',
    'mediaNews#2_84': 'Enjoy reading what inspired Yuriy Avdeev to create a project that will help all participants of the crypto market to be profitably engaged - CINDX.',
    'mediaNews#2_85': 'Weekly digest (13.08.18 - 19.08.18)',
    'mediaNews#2_86': 'CINDX continues its regular Weekly Digest column. We are excited to share our project’s progress and the most recent achievements! We are glad to remind you that CINDX security token Pre-sale starts this Sunday. Don\'t miss!',

    'teamAdvisersPartners#1': 'Équipe de plus de 50 personnes',
    'teamAdvisersPartners#2': 'Conseillers',
    'teamAdvisersPartners#3': 'Our Partners',
    // teamInfo
    'teamAdvisersPartners#4': 'Yuriy Avdeev',
    'teamAdvisersPartners#5': 'Président-directeur général',
    'teamAdvisersPartners#6': '13 ans d\'expérience en entrepreneuriat',
    'teamAdvisersPartners#7': '9 entreprises',
    'teamAdvisersPartners#8': '2 M$ pour la gestion des cryptos',
    'teamAdvisersPartners#9': 'Val Jerdes',
    'teamAdvisersPartners#10': 'Directeur de produit',
    'teamAdvisersPartners#11': '20 ans d\'expérience en entrepreneuriat',
    'teamAdvisersPartners#12': '3 sorties réussies',
    'teamAdvisersPartners#13': 'Rendements x4 pour les portefeuilles',
    'teamAdvisersPartners#14': 'Mofassair Hossain',
    'teamAdvisersPartners#15': 'Directeur du marketing',
    'teamAdvisersPartners#16': 'Investisseur et conseiller de 15+ ICO',
    'teamAdvisersPartners#17': 'Meilleur conseiller chez ICO Bench',
    'teamAdvisersPartners#18': 'Membre du PABG',
    'teamAdvisersPartners#19': 'Artur Shamalov',
    'teamAdvisersPartners#20': 'Directeur des investissements',
    'teamAdvisersPartners#21': '15 ans d\'expérience en entrepreneuriat',
    'teamAdvisersPartners#22': '5 000 clients de mixcart.ru',
    'teamAdvisersPartners#23': 'mail.ru a investi dans dc-daily.ru',
    'teamAdvisersPartners#24': 'Denis Eskenazi',
    'teamAdvisersPartners#25': 'Directeur du marketing produit',
    'teamAdvisersPartners#26': '7 ans d\'expérience en entrepreneuriat',
    'teamAdvisersPartners#27': '2 M$ attirés pour les clients',
    'teamAdvisersPartners#28': '10 ans dans la promotion de marques',
    'teamAdvisersPartners#29': 'Ibraghim Haniev',
    'teamAdvisersPartners#30': 'Lead technicien',
    'teamAdvisersPartners#31': '6 ans d\'expérience en entrepreneuriat',
    'teamAdvisersPartners#32': 'Plus de 200 sites développés',
    'teamAdvisersPartners#33': 'Focus sur la sécurité de l\'information',
    'teamAdvisersPartners#34': 'Airat Shaikhulov',
    'teamAdvisersPartners#35': 'Head of Quantitative Research',
    'teamAdvisersPartners#36': 'Dr of science at MSU',
    'teamAdvisersPartners#37': 'Aton-line navigator developer',
    'teamAdvisersPartners#38': 'Head of algorithmic trading',
    'teamAdvisersPartners#39': 'Sofja Pevzner',
    'teamAdvisersPartners#40': 'Responsable des données personnelles',
    'teamAdvisersPartners#41': '5 ans d\'expérience en entrepreneuriat',
    'teamAdvisersPartners#42': 'Autorisation du bureau estonien de lutte contre le blanchiment d\'argent (AML)',
    'teamAdvisersPartners#43': '8 ans d\'expérience dans le domaine juridique',
    'teamAdvisersPartners#44': 'Dave Gutierrez',
    'teamAdvisersPartners#45': 'Responsable des relations d\'investissement',
    'teamAdvisersPartners#46': '5 ans d\'expérience dans la location d\'avions',
    'teamAdvisersPartners#47': '3 ans d\'expérience en agence d\'investissement',
    'teamAdvisersPartners#48': '2 ans d\'expérience dans l\'investissement à l\'étranger',
    'teamAdvisersPartners#49': 'Jelena Karzetskaja',
    'teamAdvisersPartners#50': 'Responsable de la conformité',
    'teamAdvisersPartners#51': 'est titulaire de plusieurs diplômes en droit',
    'teamAdvisersPartners#52': 'dans le domaine judiciaire depuis 1997',
    'teamAdvisersPartners#53': 'sphères juridiques : droit international',
    'teamAdvisersPartners#54': 'Wang Dong',
    'teamAdvisersPartners#55': 'Spécialiste du marché chinois de la blockchain',
    'teamAdvisersPartners#56': '3 ans d\'expérience dans le php/JavaScript',
    'teamAdvisersPartners#57': '5 ans d\'expérience dans l\'achat SEO/SMM/médias',
    'teamAdvisersPartners#58': '2 ans d\'expérience dans le développement de la blockchain et la vente de jetons en Chine',
    // advisers
    'teamAdvisersPartners#59': 'Keith Teare',
    'teamAdvisersPartners#60': 'Fondateur et président exécutif d\'Accelerated Digital Ventures',
    'teamAdvisersPartners#61': 'Conseiller auprès d\'ICOBox, Crypterium, EnergiMine, etc.',
    'teamAdvisersPartners#62': 'Actionnaire fondateur de TechCrunch',
    'teamAdvisersPartners#63': 'Je suis directeur exécutif et président du comité d\'investissement d\'Accelerated Digital Ventures, une société britannique de capital-risque. Je suis né et j\'ai grandi au Royaume-Uni.',
    'teamAdvisersPartners#64': 'J\'ai auparavant été fondateur et associé chez Archimedes Labs à Palo Alto, Californie. J\'adore travailler avec les fondateurs, les équipes, les concepteurs et les ingénieurs pour créer des produits, raconter des histoires et les transformer en réalité. J\'ai fondé ou co-fondé de nombreuses entreprises depuis le début des années 1980. Certaines ont été vendues avec succès et d\'autres introduites en bourse.',
    'teamAdvisersPartners#65': 'Deux de mes entreprises étaient des licornes, qui ont été évaluées à plus d\'un milliard de dollars. J\'ai toujours mis l\'accent sur le moment où le changement se produit. Dans les années 1980, réseautage et bases de données. Au cours de la période 1994-1998, accès à Internet. De 1998 à 2010, services et contenus Web, applications mobiles grand public et depuis 2017 blockchain.',
    'teamAdvisersPartners#66': 'Carrière et projets : Tech Crunch, Accelerated Digital Ventures, cScape, EasyNet, Cyberia, RealNames, Venture Network, ICOBox, Crypterium, R/Block, Fluz, EnergiMine, Archimedes Labs et CINDX',
    'teamAdvisersPartners#67': 'Austin Kimm',
    'teamAdvisersPartners#68': 'PDG d\'International Financial Services',
    'teamAdvisersPartners#69': 'Plus de 30 ans d\'expérience dans les services financiers',
    'teamAdvisersPartners#70': 'Il a créé des entreprises d\'une valeur de 500 millions de dollars',
    'teamAdvisersPartners#71': 'PDG d\'une entreprise de services financiers éprouvée avec des résultats avérés, je mets un accent particulier sur la création d\'entreprises d\'assurance dans les marchés en développement où j\'ai fondé avec succès des entreprises avec une évaluation actuelle de plus de 500 millions de dollars.',
    'teamAdvisersPartners#72': 'Récemment en Russie (10 ans), ainsi que d\'autres postes de haute direction non liés à l\'assurance, y compris celui de PDG de Workle, la plus grande plateforme de vente sur Internet en Russie, et un large éventail de postes de niveau C dans les start-ups de fintech, dont Crypterium, la première banque de crypto-monnaie numérique au monde.',
    'teamAdvisersPartners#73': 'Carrière et projets : Aviva, Commercial Union UK, Reinaissance Insurance, Kimm Health & Leisure Ltd, Workle, Crypterium, CryptoIndex et CINDX',
    'teamAdvisersPartners#74': 'Philip Staehelin',
    'teamAdvisersPartners#75': '25 ans d\'expérience dans le conseil et l\'entreprenariat',
    'teamAdvisersPartners#76': '500 millions de dollars de paiements alternatifs sous la direction de l\'entreprise',
    'teamAdvisersPartners#77': 'Il a encadré plus de 200 start-ups dans 20 pays',
    'teamAdvisersPartners#78': 'Je suis un innovateur et un leader qui allie optimisme contagieux et réalisme pragmatique. Je trouve des opportunités là où les autres n\'en voient pas.',
    'teamAdvisersPartners#79': 'J\'ai su tirer parti de ma capacité à « voir les choses différemment » et à « faire avancer les choses » dans les environnements d\'entreprise, de conseil et de start-up. Tout cela m\'offre de nouvelles perspectives qui alimentent de nouvelles idées transformatrices.',
    'teamAdvisersPartners#80': 'Trouver des solutions à des problèmes difficiles, c\'est ce qui me motive à me lever le matin.',
    'teamAdvisersPartners#81': 'Carrière et projets : Roland Berger, Dot Glasses, Transparency International, StartupYard, Bethereum, Gjirafa Inc, Accenture et CINDX',
    'teamAdvisersPartners#82': 'Amarpreet Singh',
    'teamAdvisersPartners#83': 'Conseiller principal de la Global Blockchain Foundation',
    'teamAdvisersPartners#84': 'Expérience chez Microsoft, la Banque mondiale et Airbus',
    'teamAdvisersPartners#85': 'Membre du conseil consultatif des projets blockchain',
    'teamAdvisersPartners#86': 'Passionné de technologie/numérique et professionnel chevronné avec des années d\'expérience dans le secteur de la technologie – opérations, conseil et innovation.',
    'teamAdvisersPartners#87': 'Il est un spécialiste certifié du Cloud (Microsoft et AWS). Reconnu pour sa polyvalence et sa flexibilité. Il dispose d\'excellentes compétences analytiques, stratégiques, de leadership et d\'un esprit d\'équipe à son meilleur.',
    'teamAdvisersPartners#88': 'Spécialités : conseil en technologies, opérations, cloud computing, fintech, innovation, ERP, apprentissage automatique, gestion de comptes, développement de partenariats, développement commercial et stratégie.',
    'teamAdvisersPartners#89': 'En bref, Amarpreet Singh possède une expérience professionnelle et éducative très diversifiée. Il est titulaire de trois masters et a vécu/travaillé/étudié en Inde, à Singapour, en France, en Chine, en Afrique du Sud, en Corée et au Canada.',
    'teamAdvisersPartners#90': 'Carrière et projets : Microsoft, Banque mondiale, Airbus, TokenAsia Platform, GOeurika et CINDX',
    'teamAdvisersPartners#91': 'Tyler Sanford',
    'teamAdvisersPartners#92': '8 ans de marketing numérique chez Yelp et Zenefits',
    'teamAdvisersPartners#93': '12 ICO avec plus de 225 M$ levés',
    'teamAdvisersPartners#94': 'Parmi les premiers utilisateurs de la blockchain',
    'teamAdvisersPartners#95': 'Grandir comme athlète m\'a donné un ensemble de compétences que j\'ai pu appliquer à ma carrière et à ma vie privée.',
    'teamAdvisersPartners#96': 'J\'ai eu la chance de voir les résultats de ces efforts supplémentaires, tout en apprenant à composer avec les hauts et les bas qui accompagnent toute carrière professionnelle.',
    'teamAdvisersPartners#97': 'Je suis une personne extrêmement motivée, qui cherche toujours à continuer à développer ses connaissances et ses talents dans tous les domaines des affaires.',
    'teamAdvisersPartners#98': 'Toujours prêt à relever les défis, ma motivation vient du fait que je surmonte les obstacles pour atteindre mes objectifs.',
    'teamAdvisersPartners#99': 'Carrière et projets : IPG Holdings, DataBlockChain, TraXion de Puma Technologies, ELYSIAN, Etherinc, FTEC Foundation et CINDX',
    'teamAdvisersPartners#100': 'Philip Staehelin',
    'teamAdvisersPartners#101': '25 years of consulting and entrepreneurial experience',
    'teamAdvisersPartners#102': '$500m alternative payments business under leadership',
    'teamAdvisersPartners#103': '200+ startups from 20 countries mentored',
    'teamAdvisersPartners#104': 'I\'m an innovator and a leader who blends contagious optimism with pragmatic realism. I find opportunity where others see none.',
    'teamAdvisersPartners#105': 'I\'ve leveraged my ability to "see things differently" and "make things happen" in corporate, consulting and start-up environments - all giving me broad new perspectives that provide fodder for new transformative ideas.',
    'teamAdvisersPartners#106': 'Finding solutions to hard challenges is what gets me out of bed in the morning.',
    'teamAdvisersPartners#107': 'Career and projects: BCG, Spectacler, Transparency International, StartupYard, Bethreum, Gjirafa Inc, Direct People, CINDX',
    'teamAdvisersPartners#108': 'Senior Adviser of Global Blockchain Foundation',
    'teamAdvisersPartners#109': 'Experience in Microsoft, The World Bank and Airbus',
    'teamAdvisersPartners#110': 'Advisery Board Member of Blockchain projects',
    'teamAdvisersPartners#111': 'Technology/Digital enthusiast and a seasoned professional with years of experience in Tech industry – operations, consulting and innovation.',
    'teamAdvisersPartners#112': 'He is a certified Cloud (Microsoft and AWS) specialist. Known for versatility and flexibility. Excellent analytic, strategic, leadership skills and a team player at its best.',
    'teamAdvisersPartners#113': 'Specialties: Technology Consulting, Operations, Cloud Computing, Fintech, Innovation, ERP, Machine Learning, Account Management, Partner Development, Business Development and Strategy',
    'teamAdvisersPartners#114': 'Amarpreet Singh has a very diversified work and educational background. He holds three Masters degrees and has lived/worked/studied in India, Singapore, France, China, South Africa, Korea, Canada.',
    'teamAdvisersPartners#115': 'Career and projects: Microsoft, The World Bank, Airbus, TokenAsia Platform, GOeurika, CINDX',
    'teamAdvisersPartners#116': 'Tyler Sanford',
    'teamAdvisersPartners#117': '8 Years Digital Marketing in Yelp and Zenefits',
    'teamAdvisersPartners#118': '12 ICO’s over $225M raised',
    'teamAdvisersPartners#119': 'Early adopter of blockchain',
    'teamAdvisersPartners#120': 'Growing up as an Athlete has given me a skill set that I\'ve been able to apply to my careers and personal life.',
    'teamAdvisersPartners#121': 'I have been very fortunate to see the results of going that extra mile, while learning to deal with the highs and lows that go along with all professional careers.',
    'teamAdvisersPartners#122': 'I\'m an extremely self-motivated individual, always looking to continue my growth of knowledge and talents in all aspects of business.',
    'teamAdvisersPartners#123': 'Always up for a challenge, my motivation comes from overcoming obstacles to reach my goals',
    'teamAdvisersPartners#124': 'Career and projects: IPG Holdings, DataBlockChain, TraXion by Puma Technologies, ELYSIAN, Etherinc, FTEC Foundation,  CINDX',
    'teamAdvisersPartners#125': 'Bogdan Fiedur',
    'teamAdvisersPartners#126': 'Expert, investisseur, entrepreneur en blockchain et cryto-devises',
    'teamAdvisersPartners#127': 'Co-fondateur de bitJob et président de Blockchainexperts.io',
    'teamAdvisersPartners#128': 'Conseiller ICO, expert ICOBench',
    'teamAdvisersPartners#129': 'Bogdan Fiedur est un développeur de contrat intelligent, crypto-investisseur, entrepreneur et président de http://blockchainexperts.io . Il cumule plus de 20 ans d\'expérience en TI dans la création de sites Web pour le commerce électronique et participe au développement de la blockchain depuis ces 3 dernières années.',
    'teamAdvisersPartners#130': 'Il est également conseiller ICO et a travaillé à ce jour sur 20 ICO qui ont connu le succès. Il s’est beaucoup impliqué pour proposer des exposés et des ateliers sur la blockchain et la programmation de contrats intelligents dans sa communauté crypto locale de Winnipeg.',
    'teamAdvisersPartners#131': 'Bogdan se concentre à présent sur le secteur de la blockchain et fournit des services de conseil et de mise en relation avec les experts de la blockchain. Récemment, Bogdan a co-fondé « Bitjob », une plateforme de blockchain freelance pour étudiants et a participé à plusieurs projets ICO (par exemple, PayPie.com) en tant que membre de l\'équipe.',
    'teamAdvisersPartners#132': 'Carrière et projets : US Blockchain Association, Tuurnt, Trends Project, BiNeuro, Zichain, Graphen Tech, CyClean, Swachhcoin et CINDX',
    'teamAdvisersPartners#133': 'Graham Doggart',
    'teamAdvisersPartners#134': '20 ans d\'expérience dans le développement des entreprises, conformité au marketing de la fintech',
    'teamAdvisersPartners#135': 'Il a réalisé des campagnes d\'une valeur de 100 millions de dollars',
    'teamAdvisersPartners#136': 'Conseiller pour plus de 10 projets blockchain cette année',
    'teamAdvisersPartners#137': 'Je suis président du Stealth Cryptocurrency Project et co-fondateur et stratégiste en chef chez Dynamic Abundance, un service de conseil en matière de blockchain et de fintech depuis 2012.',
    'teamAdvisersPartners#138': 'e suis spécialisé dans la structuration et le packaging des offres de jetons et j\'ai travaillé sur de nombreux projets internationaux dans le domaine de la blockchain, de la crypto-devise et de l\'ICO.',
    'teamAdvisersPartners#139': 'Depuis plus de 20 ans, je fournis des services de conseil en gestion de la technologie, en conformité juridique et financière, des conseils en stratégies de croissance, en relations avec les investisseurs, ainsi que sur la conception et la paternité des documents.',
    'teamAdvisersPartners#140': 'Carrière et projets : Stealth Cryptocurrency Project, Dynamic Abundance, ELYSIAN, Fox Trading FX, Profede, Worltdopoly et CINDX',
    'teamAdvisersPartners#141': 'Sadie Hutton',
    'teamAdvisersPartners#142': '25 ans d\'expérience dans la direction d\'entreprise et le conseil en gestion',
    'teamAdvisersPartners#143': 'A collecté plusieurs millions de dollars avec des campagnes d\'une valeur de 75 millions de livres sterling',
    'teamAdvisersPartners#144': 'Conseillère ICO dans 8 projets',
    'teamAdvisersPartners#145': 'Je suis la fondatrice de Dynamic Abundance, un service de conseil en matière de blockchain.',
    'teamAdvisersPartners#146': 'Privilégiant une approche « pratique », je suis une spécialiste de l\'analyse ICO, de la gestion de projet, tous les aspects clés du processus ICO. Je dispose de compétences en gestion et développement d\'entreprise, ce qui me permet de voir un projet de la création à la livraison. Je suis une solutionneuse de problèmes par nature, et je prends à cœur tous les projets auxquels je participe. J\'aime gagner !',
    'teamAdvisersPartners#147': 'Totalisant plus de 20 ans d\'expérience en gestion, j\'ai bâti un réseau puissant, je conseille activement en finance, technologie, vente, marketing et assurance qualité pour des projets blockchain de haut niveau.',
    'teamAdvisersPartners#148': 'Carrière et projets : Dynamic Abundance, ELYSIAN, Worldopoly, Confidential ICO, Fox Trading FX, Profede, Market Digital et CINDX',
    'teamAdvisersPartners#149': 'Jason King',
    'teamAdvisersPartners#150': '20 ans d\'expérience en tant que cadre',
    'teamAdvisersPartners#151': 'Il a dirigé des opérations commerciales dans 30 pays',
    'teamAdvisersPartners#152': 'Responsable de plus de 500 millions de dollars en P&L',
    'teamAdvisersPartners#153': 'Pendant près de 20 ans, Jason King a été cadre dans le domaine de la technologie, des médias et des télécommunications.',
    'teamAdvisersPartners#154': 'Il a été impliqué dans la structuration et le courtage de transactions commerciales, la négociation de victoires, la création de marchés et le positionnement des organisations pour atteindre le succès.',
    'teamAdvisersPartners#155': 'Bon nombre de ces défis m\'ont amené à occuper avec succès des postes de restructuration et de redressement – diriger en formant les bonnes personnes et les bonnes équipes pour atteindre les objectifs les plus rentables.',
    'teamAdvisersPartners#156': 'Jason possède une vaste expérience dans différents domaines, notamment la gestion des opérations et des affaires, la planification stratégique, les finances, la crypto-monnaie et la blockchain.',
    'teamAdvisersPartners#157': 'Motti Peer',
    'teamAdvisersPartners#158': 'Co-fondateur de Blonde 2.0, agence de relations publiques mondiale primée',
    'teamAdvisersPartners#159': 'Fondateur de plusieurs sociétés dans le secteur de la sécurité et de la finance.',
    'teamAdvisersPartners#160': 'Motti est l\'un des principaux acteurs des relations publiques dans le secteur de la blockchain, des cryptos, des start-ups et des CR.',
    'teamAdvisersPartners#161': 'Motti a fondé plusieurs sociétés dans le secteur de la sécurité et de la finance. Il possède de nombreuses années d\'expérience en tant que gestionnaire de fonds et de fonds spéculatifs et détient un MBA en finance et marketing de l\'Université de Manchester et un BA en gestion des affaires de l\'Université Fairleigh Dickinson.',
    'teamAdvisersPartners#162': 'Il est co-PDG de Blonde 2.0, une agence internationale de relations publiques primée, également désignée comme l\'un des « Movers and Shakers » de la nation start-up sur Forbes. En tant que co-PDG de Blonde 2.0, il est responsable des aspects liés aux relations publiques, de la stratégie et de la gestion de crises.',
    'teamAdvisersPartners#163': 'Avec une équipe de 35 professionnels, Blonde 2.0 est l\'un des leaders des relations publiques dans le secteur de la blockchain, des cryptos, des start-ups et des CR.',
    'teamAdvisersPartners#164': 'Leonard Grayver',
    'teamAdvisersPartners#165': 'Partenaire chez Greenberg, Whitcombe & Takeuchi',
    'teamAdvisersPartners#166': 'A représenté de plus de 400 start-ups',
    'teamAdvisersPartners#167': 'Il a récolté plus de 18 millions de dollars pour sa start-up alors qu\'il était étudiant en droit',
    'teamAdvisersPartners#168': 'Leonard Grayver est né en URSS et a déménagé aux États-Unis avec ses parents lorsqu\'il était enfant. Pendant ses études de droit, Leonard a créé une start-up et a réussi à lever plus de 18 millions de dollars américains pour son financement.',
    'teamAdvisersPartners#169': 'La start-up n\'a pas survécu, mais depuis lors, il a aidé plus de 400 start-ups à se développer.',
    'teamAdvisersPartners#170': 'Leonard cumule plus de 10 ans d\'expérience dans le financement par capital-risque, la structuration de fonds et la diligence raisonnable (représentant à la fois des fonds et des sociétés en commandite). Son conseil à tous les entrepreneurs : « Ne suivez pas les tendances, mais suivez vos intérêts ».',

    'joinTokenPreSale#1': 'Join Token Pre-Sale now!',
    'joinTokenPreSale#2': 'JOIN PRE-SALE',
    'joinTokenPreSale#3': 'TEST MVP',
    'joinTokenPreSale#4': 'Head Office',
    'joinTokenPreSale#5': 'Harjumaa, Erika 14,',
    'joinTokenPreSale#6': 'Talinn, 10416, Estonia',
    'joinTokenPreSale#7': 'Business inquiries | hello@cindx.io',
    'joinTokenPreSale#8': 'Legal Disclaimer',
    'joinTokenPreSale#9': 'Development and Marketing',
    'joinTokenPreSale#10': 'Presnenskaya naberezhnaya, 8 building 1,',
    'joinTokenPreSale#11': 'Moscow, 123112, Russia',
    'joinTokenPreSale#12': 'Careers | Join our team',
}

export default fr