// Японский
const ja = {
    'mainBlock#1': '暗号通貨への投資を簡単・',
    'mainBlock#2': '安全・迅速に',
    'mainBlock#3': '当社のセキュリティトークンのプレセールにご参加ください',

    'icoInfo#1': '支払方法：',
    'icoInfo#2': 'ハードキャップ:',
    'icoInfo#3': 'ソフトキャップマイルストーン：',
    'icoInfo#4': 'リスティング契約は以下で成立します',

    'menu#1': 'ホワイトペーパー',
    'menu#2': 'プレゼンテーション',
    'menu#3': 'ワンシート概略資料',
    'menu#4': '財務モデル',
    'menu#5': '法的文書',
    'menu#6': 'JP',
    'menu#7': '製品',
    'menu#8': 'セール詳細',
    'menu#9': 'Tチーム',
    'menu#10': '公開文書',
    'menu#11': '公開文書',

    'mailForm#1': 'Wrong email',
    'mailForm#2': 'sending ..',
    'mailForm#3': 'Already was or is not valid, try again',
    'mailForm#4': 'Your email has been sent successfully',
    'mailForm#5': 'an error occurred, try again',
    'mailForm#6': 'GDRP Сompliance',
    'mailForm#7': 'Personal data provided via Subscription form and KYC procedure will be collected in the full compliance with GDRP',
    'mailForm#8': 'The Data Protection Officer  of the project is  Mrs. Sofja Pevzner-Belositski. Contact details: dpo@cindx.io. Any data subject may, at any time, contact Data Protection Officer of directly with any request related to data protection.',
    'mailForm#9': 'Your personal data provided via Subscription form and KYC procedure will be shared to our partners:',
    'mailForm#10': 'ICO Promo',
    'mailForm#11': 'Privacy Policy',
    'mailForm#12': 'Sum & Substance',
    'mailForm#13': 'By default, the personal data provided by subscriber are kept by CINDX, ICO Promo and Sum & Substance for 5 years after registration of subscriber in the system',
    'mailForm#14': 'If you do not agree to this privacy policy, please do not use our site.',
    'mailForm#15': 'By using our site, you consent to the collection and use of information by us. Owing to the global nature of the internet infrastructure, the information you provide may be transferred in transit to countries outside the European Economic Area that do not have similar protections in place regarding your data and its use as set out in this policy.',
    'mailForm#16': 'However, we have taken the steps outlined above to try to improve the security of your information. By submitting your information you consent to these transfers',
    'mailForm#17': 'I agree to process my',
    'mailForm#18': 'personal data',
    'mailForm#19': 'Security Token Sale Starts with',
    'mailForm#20': '20% BONUS',
    'mailForm#21': 'Get it before everyone else does',
    'mailForm#22': 'Token sale starts in',
    'mailForm#23': 'Start from $1',
    'mailForm#24': '$1 later',
    'mailForm#25': 'メールアドレス',
    'mailForm#26': 'プレセールに参加する',
    'mailForm#27': 'AGREE & SUBMIT',
    'mailForm#28': 'Get it before everyone else does Offer expires within',
    'mailForm#29': 'Want to get the latest news and upcoming offers?',

    'docPopup#1': '電子メール内のすべてのドキュメントを受信する',
    'docPopup#2': 'メールアドレスを入力',
    'docPopup#3': '私にドキュメントを送信',

    'progressBarSale#1': 'セールボーナス',
    'progressBarSale#2': 'CINXで',
    'progressBarSale#3': 'プレセール',
    'progressBarSale#4': '販売',
    'progressBarSale#5': '8月26日',
    'progressBarSale#6': '9月17日',
    'progressBarSale#7': '10月8日',
    'progressBarSale#8': '10月22日',
    'progressBarSale#9': '11月6日',
    'progressBarSale#10': '11月19日',
    'progressBarSale#11': '12月3日',
    'progressBarSale#12': '12月17日',

    'ourTopRatings#1': 'Our Top Ratings',

    'cryptoAssetsManagement#1.1': 'CIDNXは暗号資産管理ハブです。私たちは投資家・トレーダー・',
    'cryptoAssetsManagement#1.2': '開発者が抱える問題を解決します。',
    'cryptoAssetsManagement#2': '投資家のためのCINDXマーケットプレイス',
    'cryptoAssetsManagement#3': '知識や経験については心配無用です – 暗号通貨取引のエキスパートがお手伝いします。',
    'cryptoAssetsManagement#4': '暗号資金を管理： お客様のコインは常にウォレットで保管されます',
    'cryptoAssetsManagement#5': '支払は収益があるときだけ： 手数料は、お客様のポートフォリオが収益をあげているときだけです',
    'cryptoAssetsManagement#6': 'MVPを試してみる',
    'cryptoAssetsManagement#7': 'トレーダーのためのCINDXターミナル',
    'cryptoAssetsManagement#8': '優秀なトレーダーなら、何もマーケティングに投資することなく資金を集めることが可能です',
    'cryptoAssetsManagement#9': '取引で成功するために必要なターミナル、アプリストア、マーケットプレイスやその他の高度なツールを提供します ',
    'cryptoAssetsManagement#10': 'お客様の評判や専門性を収益化するのにCINDXは役立ちます。取引の実績や影響を目で見ることはできません。',
    'cryptoAssetsManagement#11': 'CINDXトーク、CINDXハブ、およびCINDX.DAO',
    'cryptoAssetsManagement#12': 'CINDXトーク - 役立つコンテンツで報酬が得られるソーシャルネットワーク',
    'cryptoAssetsManagement#13': 'CINDXハブ - その要素には、「ベンダーキャビネット」やテスト用ハブ、統合されたサードパーティ製ソフトウェアが含まれています',
    'cryptoAssetsManagement#14': 'CINDX.DAO - 自律分散型組織のルールに基づいたコミュニティの投票システムの実装を可能にする要素です',

    'teamLegal#1': '私たちには素晴らしいチームと法律専門家がついています',
    'teamLegal#2': '',
    'teamLegal#3': 'CRYPTOCURRENCY EXCHANGE LICENSE',
    'teamLegal#4': 'FINANCIAL INSTITUTION LICENSE',
    'teamLegal#5': 'CRYPTO WALLET LICENSE',
    'teamLegal#6': 'WHITEPAPER',
    'teamLegal#7': 'PRESENTATION',
    'teamLegal#8': 'ONE PAGER',
    'teamLegal#9': 'FINANCIAL MODEL',
    'teamLegal#10': 'LEGAL DOCS',

    'roadmap#1': 'ロードマップ',
    'roadmap#2': '百万ドルシナリオ',
    'roadmap#3': 'We are building the base for the CINDX platform. At this step, the Minimum Viable Product (MVP) is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform.',
    'roadmap#4': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be  going through some alterations to add functionalities.  ',
    'roadmap#5': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services.      ',
    'roadmap#6': 'At this stage, the CINDX.market and CINDX.trade components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. ',
    'roadmap#7': 'CINDX.talk will have public and private channels. At this stage, the content will  be able to be  separated. ',
    'roadmap#8': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade is an extremely flexible system of order execution and risk management. The Vendor’s market will appear; however, at this point, the Vendor’s market will only contain applications developed by CINDX and its partners.  ',
    'roadmap#9': 'A tokenized rating system will be added in the final version of CINDX.talk, as well as a new type of product: “algorithmic trading”. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders.   ',
    'roadmap#10': 'We are building the base for the CINDX platform. At this step, the MVP is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform. ',
    'roadmap#11': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be going through some alterations to add functionalities.  ',
    'roadmap#12': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services. Another new component, CINDX.hub, will enable Vendors to develop applications that will analyze the market data that CINDX provides. ',
    'roadmap#13': 'At this stage, the CINDX.market and CINDX.trade components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. An SDK for developers will be released. This should simplify application development and implementation for CINDX.  ',
    'roadmap#14': 'CINDX.talk will have public and private channels. At this stage, the content will be able to be separated. CINDX.hub will integrate Github, which will simplify application development even more.',
    'roadmap#15': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade will be an extremely flexible system of order execution and risk management. CINDX.hub will have a full-scale editor for trading strategies with a testing system based on historical market data.',
    'roadmap#16': 'A tokenized rating system  CINDX.talk will be added in the final version of CINDX.talk. This will provide a system of assessment for CINDX community trading experts. “Algorithmic trading” will also be added. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders. A high-grade platform for a code audit will be created. ',
    'roadmap#17': 'We are building the base for the CINDX platform. At this step, the MVP is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform.',
    'roadmap#18': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be  going through some alterations to add functionalities. ',
    'roadmap#19': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services. Another new component,  CINDX.hub, will enable Vendors to develop applications that will analyze the market data that CINDX provides. The team will develop CINDX.dao, a component that acts as a system for the platform’s revenue distribution to its token holders.       ',
    'roadmap#20': 'At this stage, the CINDX.market and CINDX.trade  components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. An SDK for developers will be released. This should simplify application and implementation development for CINDX.  ',
    'roadmap#21': 'CINDX.talk will have public and private channels. At this stage the content can be separated. CINDX.hub will integrate Github which will simplify application development even more.',
    'roadmap#22': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade will be an extremely flexible system of order execution and risk management. CINDX.hub has a full-scale editor for trading strategies with a testing system based on historical market data. CINDX.dao will receive a voting system for token holders. ',
    'roadmap#23': 'A tokenized rating system CINDX.talk will be added in the final version of CINDX.talk. This will provide a system of assessment for CINDX community trading experts. “Algorithmic trading” will also be added. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders. A high-grade platform for a code audit will be created. ',

    'problemSolving#1': '時間',
    'problemSolving#2': '信頼',
    'problemSolving#3': '不確実性',
    'problemSolving#4': '暗号通貨ゲームに使える資金はあるものの、自分のポートフォリオを管理するために研究したり、プロのトレーダーに連絡したりする時間がありません',
    'problemSolving#5': '今までずっと自分のお金の管理を他人に任せて収益をあげることを快く思っていませんでした',
    'problemSolving#6': '暗号通貨取引を取り巻くテクノロジーは、ユーザーにとって使いづらいものです。自分のコインをどう取引して良いのかわかりません',
    'problemSolving#7': 'CINDXは、評価された信頼できるトレーダーにアクセスを提供します',
    'problemSolving#8': 'CINDXプラットフォームなら、お客様の資金がウォレットから離れることはありません',
    'problemSolving#9': 'マーケットのトップトレーダーと共に収益をあげることができます',
    'problemSolving#10': 'CINDXのトレーダーは、自身の成功した取引実績に基づいて評価されます。ご自身に合ったトレーダーを選ぶだけです',
    'problemSolving#11': '当社の分散型システムとスマートコントラクトにより、資金をトレーダーへ転送することなく管理することができます',
    'problemSolving#12': 'CINDXのすべての投資家には、自身の資金をマーケットでも指折りのトップトレーダーに管理してもらえる機会があります',
    'problemSolving#13': 'CINDXはどのような問題を解決するのか？',
    'problemSolving#14': 'MVPを試してみる',

    'howCindxWorks#1': '投資家',
    'howCindxWorks#2': 'トレーダー',
    'howCindxWorks#3': 'ベンダー',
    'howCindxWorks#4': 'トップトレーダーのポートフォリオ管理スキルを活用して、暗号通貨による収益を増やします',
    'howCindxWorks#5': '自身のパフォーマンスとトレード戦略に基づいて、自分をフォローする投資家から手数料を受け取ります',
    'howCindxWorks#6': 'トレードボットやニュースウィジェットなどの高度なトレードツールを販売します.',
    'howCindxWorks#7': '手数料と購読料を徴収します',
    'howCindxWorks#8': '取引したい暗号資産でCINDXに参加します',
    'howCindxWorks#9': '投資家に利益をもたらす自身の専門知識でCINDXに参加します',
    'howCindxWorks#10': '投資家に役立つトレードアプリでCINDXに参加します',
    'howCindxWorks#11': '取引をより簡単、安全、かつ収益性のあるものにすることを目指しています',
    'howCindxWorks#12': 'CINDXの仕組みを簡単にご説明します',

    'marketAnalytics#1': 'マーケット分析',
    'marketAnalytics#2': '世界の運用資産残高（AUM)',
    'marketAnalytics#3': '投資',
    'marketAnalytics#4': '資本の成長',
    'marketAnalytics#5': '2000年以降、世界の資産管理市場は250%以上もの成長を見せています。',
    'marketAnalytics#6': 'これは市場ツールの継続的な改善と市場構造の全体的な発展がもたらした結果です。',
    'marketAnalytics#7': '2017年に爆発的に成長した暗号通貨市場ですが、業界は依然として未熟なままです。',
    'marketAnalytics#8': '2017年末の数字で合計時価総額は6,000億ドルにのぼりました — 資産管理業界の合計時価総額のたった1%です。',
    'marketAnalytics#9': 'ホワイトペーパー',
    'marketAnalytics#10': 'プレゼンテーション',
    'marketAnalytics#11': 'ワンシート概略資料',
    'marketAnalytics#12': '財務モデル',
    'marketAnalytics#13': '法的文書',
    'marketAnalytics#14': '参考データ',
    'marketAnalytics#15': '25百万の潜在ブロックチェーンウォレット',
    'marketAnalytics#16': '日次200,000回の潜在トランザクション',
    'marketAnalytics#17': '',
    'marketAnalytics#18': '',
    'marketAnalytics#19': '各30～50億ドルの潜在パートナーが225以上',
    'marketAnalytics#20': '',

    'tokenSaleDetails#1': 'トークン配分',
    'tokenSaleDetails#2': 'チーム',
    'tokenSaleDetails#3': 'バウンティ',
    'tokenSaleDetails#4': 'アドバイザー',
    'tokenSaleDetails#5': 'リザーブ',
    'tokenSaleDetails#6': 'コミュニティ助成',
    'tokenSaleDetails#7': 'トークン流動性サポート',
    'tokenSaleDetails#8': '販売可能数量',
    'tokenSaleDetails#9': 'トークン名：',
    'tokenSaleDetails#10': 'トークンプレセール開始： 2018年8月26日',
    'tokenSaleDetails#11': '総発行数：',
    'tokenSaleDetails#12': 'トークン価格：',
    'tokenSaleDetails#13': 'CINXO=1.00 CINX:',
    'tokenSaleDetails#14': '最低投資額： 50ドル相当',
    'tokenSaleDetails#15': 'ホワイトペーパー',
    'tokenSaleDetails#16': 'プレゼンテーション',
    'tokenSaleDetails#17': 'ワンシート概略資料',
    'tokenSaleDetails#18': '財務モデル',
    'tokenSaleDetails#19': '法的文書',
    'tokenSaleDetails#20': '収益の用途',
    'tokenSaleDetails#21': 'マーケティング＆広報 21%',
    'tokenSaleDetails#22': '研究開発 41%',
    'tokenSaleDetails#23': '運営 28%',
    'tokenSaleDetails#24': '法的費用 7%',
    'tokenSaleDetails#25': 'トレーダーボーナス 3%',
    'tokenSaleDetails#26': 'トークン販売',
    'tokenSaleDetails#27': 'トークンセール:',
    'tokenSaleDetails#28': 'トークンプレセールボーナス',
    'tokenSaleDetails#29': '8月26日〜9月16日 - のボーナス25％',
    'tokenSaleDetails#30': '9月17日〜10月7日 - のボーナス20％',
    'tokenSaleDetails#31': 'トークンメインセールボーナス:',
    'tokenSaleDetails#32': '10月8日～10月21日 - ボーナス17%',
    'tokenSaleDetails#33': '10月22日～11月4日 - ボーナス15%',
    'tokenSaleDetails#34': '11月5日～11月18日 - ボーナス13%',
    'tokenSaleDetails#35': '11月19日～12月2日 - ボーナス10%',
    'tokenSaleDetails#36': '12月3日～12月16日 - ボーナス5%',
    'tokenSaleDetails#37': '12月17日～12月26日 - ボーナス0%',
    'tokenSaleDetails#38': 'トークンを購入する',
    'tokenSaleDetails#39': 'トークンセール詳細',
    'tokenSaleDetails#40': 'During the token sale, investors purchase utility tokens – options [CINXO], which give them the right to receive security tokens [CINX] in the future.',
    'tokenSaleDetails#41': 'Security tokens [CINX] will be issued and distributed following the prospect of emission published on the website of FSA of Estonia https://www.fi.ee/ and cindx.io after the end of the token sale, but no later than Q1 2019.',
    'tokenSaleDetails#42': 'The holder of [CINXO] tokens has the right but no obligation to exchange options for security tokens with a ratio of 1:1 after completing the KYC procedure with identification signature, address confirmation and supply of other documents (see the KYC diagram).',
    'tokenSaleDetails#43': 'Tokens [CINXO] grant the same rights as security tokens apart from the right to participate in revenue distribution with a lock-up and voting on the platform.',

    'legalSchedule#1': '法手続きのスケジュール',
    'legalSchedule#2': '仮想通貨と法定通貨サービス間の取引を提供するためのライセンス（FVR000110）を取得',
    'legalSchedule#3': 'エストニアおよびEUにて商標登録を申請',
    'legalSchedule#4': '財務機関として運営するためのライセンスFFA 000254',
    'legalSchedule#5': '金融機関として業務を行うためのFFA000254ライセンスを取得',
    'legalSchedule#6': 'エストニアの法律に基づく目論見書を作成',
    'legalSchedule#7': 'FSAライセンスを申請（エストニア金融監督庁）',
    'legalSchedule#8': '仮想通貨ウォレットサービスを提供するためのライセンスを取得',
    'legalSchedule#9': 'SECの免除規定Dに登録',
    'legalSchedule#10': 'GDPR要件を満たすため、個人情報管理者を任命',
    'legalSchedule#11': 'FSAライセンスを取得',
    'legalSchedule#12': '発行したCINXセキュリティトークンのEU809-2004目論見書を登録',
    'legalSchedule#13': 'ISSUED CINX SECURITY TOKENS',

    'feedbackProject#1': 'プロジェクトへのフィードバック',
    'feedbackProject#2': 'Val Jerdes',
    'feedbackProject#3': 'プロダクトディレクター',
    'feedbackProject#4': 'CINDXプロダクトディレクターのVal Jerdes が、主要チームメンバーについて語り、著しく金融を変革する可能性を秘めたプロジェクトを作り上げるうえでどのように彼らの専門知識が役立つのかをご紹介します',
    'feedbackProject#5': 'Denis Eskenazi',
    'feedbackProject#6': 'プロダクトマーケティングディレクター',
    'feedbackProject#7': 'CINDXマーケティングディレクターのDenis Eskenaziが、なぜCINDXへ参加したのかをお話します',
    'feedbackProject#8': 'Philip Staehelin',
    'feedbackProject#9': 'アドバイザー',
    'feedbackProject#10': 'CINDXプロジェクトのアドバイザーであるPhilip Staehelinが、いかに暗号通貨革命が経験の浅い投資家にとって役立つかを語り、暗号通貨市場に特化したCINDXプロジェクトのブレイクスルーについてお話します',
    'feedbackProject#11': 'Andrzej Cichowlaz',
    'feedbackProject#12': 'マーケティングスペシャリスト',
    'feedbackProject#13': 'CINDXマーケティングマネージャーのAndrzej Cichowlazが、このプロジェクトの成功を信じる理由についてお話します',
    'feedbackProject#14': 'Austin Kimm',
    'feedbackProject#15': 'CINDXプロジェクトのアドバイザーであるAustin Kimmが、CINDXがどのようにしてシンプルかつスマートに利益をあげる暗号通貨取引を可能にするかについてお話します',
    'feedbackProject#16': 'Amarpreet Singh',
    'feedbackProject#17': 'CINDXアドバイザーのAmarpreet Singhが、CINDXプラットフォームがどのようにして投資家とトレーダー間に存在するギャップを埋めるかについてお話します',
    'feedbackProject#18': 'Keith Teare',
    'feedbackProject#19': 'CINDXアドバイザーのKeith TeareがCINDXプラットフォームの利点についてご紹介します',
    'feedbackProject#20': 'Mansur Rasulov',
    'feedbackProject#21': 'コミュニティ指導',
    'feedbackProject#22': 'CINDXコミュニティ指導担当のMansur Rasulovが、CINDXチームの一員になった理由をお話します',
    'feedbackProject#23': 'Sadie Hutton',
    'feedbackProject#24': 'CINDXアドバイザーのSadie Huttonが、CINDXプラットフォームが他の自動取引プラットフォームとどのように違っているかをご説明します',
    'feedbackProject#25': 'Graham Doggart',
    'feedbackProject#26': 'CINDXアドバイザーのGraham Doggartが、CINDXプラットフォームの強みをご紹介します',
    'feedbackProject#27': 'Alina Vardanian',
    'feedbackProject#28': 'コンテンツマネージャー',
    'feedbackProject#29': 'CINDXコンテンツマネージャーのAlina Vardanianが、チームの精神と彼女の強い仕事愛についてお話します',
    'feedbackProject#30': 'Bogdan Fiedur',
    'feedbackProject#31': 'CINDXアドバイザー',
    'feedbackProject#32': 'CINDXアドバイザーのBogdan Fiedur が、CINDXプロジェクトが他のICOプロジェクトとどのように違うかについて説明します',
    'feedbackProject#33': 'Jason King',
    'feedbackProject#34': 'チーフコマーシャルオフィサーのJason Kingが、何が彼をCINDXに惹きつけるのか、また本プロジェクトの重要な利点についてお話します',

    'mediaNews#1': 'メディア',
    'mediaNews#2': 'ニュース',
    // Media
    'mediaNews#1_1': 'CINDX Aims to Democratize the Modern Financial System',
    'mediaNews#1_2': 'Even as investors in the cryptocurrency space recognize that they are at the forefront of a new financial revolution, adoption by the general populace is yet to occur. While 3rd parties are slowly entering the space in the form of hedge funds and other investors, very few individuals seem to have taken the step to invest in cryptocurrencies on their own.',
    'mediaNews#1_3': 'CINDX Announces Plans For ICO Pre-Sale Amidst Release Of Revolutionary Crypto Trading Hub That Allows Users To Follow Expert Traders',
    'mediaNews#1_4': 'CINDX takes its business seriously with particular attention and cares to legal matters and has taken great pains to ensure that CINDX is as compliant as possible with global regulations.',
    'mediaNews#1_5': 'How CINDX is Democratizing the Modern Financial System',
    'mediaNews#1_6': 'CINDX is a new platform that is making crypto trading easier, more secure, and more accessible. With this platform, it’s possible to have your funds traded without high fees or minimum investments, with the added security and transparency of blockchain technology.',
    'mediaNews#1_7': 'CINDX is making crypto trading easier, more secure, and more accessible.',
    'mediaNews#1_8': 'Cryptocurrency and blockchain technology have been slated as powerful tools capable of fueling a global financial revolution. There are myriad opportunities to invest in the crypto space, and yet, very few individuals have undertaken the steps necessary to invest.',
    'mediaNews#1_9': 'CINDX Announces Plans Release Of Revolutionary Crypto Trading Hub',
    'mediaNews#1_10': 'The CINDX platform creates a complete ecosystem for cryptocurrency trading that is favorable to all the participants of the market and offers solutions to existing pain points.',
    'mediaNews#1_11': 'CINDX Announces Plans For ICO Pre-Sale',
    'mediaNews#1_12': 'CINDX made headlines this week with the announcement that they will be opening their ICO Pre-Sale in late August after investors interest in the ICO peaks to new levels.',
    'mediaNews#1_13': 'CINDX Will Be Opening ICO Pre-Sale in late August',
    'mediaNews#1_14': 'The CINDX Crypto trading platform has a myriad of features and benefits that haven’t been seen in other platforms to date.',
    'mediaNews#1_15': '5 Tips from CINDX Crypto Assets Management Hub: How to Avoid Being Cheated',
    'mediaNews#1_16': 'The team behind the CINDX crypto assets management hub has created a helpful set of guidelines on how not to become victims of unfair play, so you can learn what should be primarily taken into account when evaluating ICOs before investing in them.',
    'mediaNews#1_17': 'CINDX Crypto Asset Management Hub Adopts Bancor Protocol',
    'mediaNews#1_18': 'CINDX is delighted to announce that a number of new integrations with top industry players are underway, each of which will make the life of the users of the platform easier and richer. These new integrations include the decision to adopt the Bancor protocol to provide continuous liquidity for the CINDX platform.',
    // News
    'mediaNews#2_1': 'CINDX meets Ian Balina',
    'mediaNews#2_2': 'CINDX pitch to the one of the TOP10 crypto gurus in the world in the Cryptobazar event.',
    'mediaNews#2_3': 'CINDX took part in Moscow ICO Summit 2018',
    'mediaNews#2_4': 'CINDX team introduced the project to the Russian crypto community during ICO Summit event.',
    'mediaNews#2_5': 'How CINDX is ensuring legal compliance',
    'mediaNews#2_6': 'Our company is registered in Estonia. Why? The answer is simple — the authorities of Estonia have created a strong and innovative legal infrastructure...',
    'mediaNews#2_7': 'Keith Teare Co-founder of Accelerated Digital Ventures and Founding Shareholder in TechCrunch',
    'mediaNews#2_8': 'We continue to introduce CINDX advisers, find out what they...',
    'mediaNews#2_9': 'Meet world\'s first financial crypto social network',
    'mediaNews#2_10': 'Every day our team takes one more step on the way to creation and start...',
    'mediaNews#2_11': 'Denis Eskenazi CINDX Product Marketing Director',
    'mediaNews#2_12': 'We continue to tell about the CINDX team and each team member’s professional experience. Please, read about Denis Eskenazi...',
    'mediaNews#2_13': 'CINDX crypto currency exchange license',
    'mediaNews#2_14': 'Our company in Estonia has received Crypto Currency Exchange License. This allows CINDX to provide fiat-to-crypto exchange services. This licence is issued...',
    'mediaNews#2_15': 'Austin Kimm Co-founder of Crypterium & CINDS Adviser',
    'mediaNews#2_16': 'We continue to introduce CINDX advisers, find out what they are proud...',
    'mediaNews#2_17': 'The strategic meeting of the international CINDX team',
    'mediaNews#2_18': 'Every day our team takes one more step on the way to creation and start of the CINDX platform. Our work...',
    'mediaNews#2_19': 'Artur Shamalov CINDX Investment Director',
    'mediaNews#2_20': 'We continue to introduce the CINDX team. Our next article is about Artur Shamalov, a skilled...',
    'mediaNews#2_21': 'The issuance of CINX tokens',
    'mediaNews#2_22': 'The issuance of CINX tokens will be carried out according to the license of The Estonian Financial Supervisory Authority (EFSA). What is a token...',
    'mediaNews#2_23': '"Amarpreet Singh Co-Founding Member of Malta Blockchain Association & CINDX adviser"',
    'mediaNews#2_24': 'We at CINDX are incredibly proud to present our advisers, tell the world about their achievements and why they have decided to become a part of the CINDX...',
    'mediaNews#2_25': 'CINDX meets Vangoo Capital Partners Fund',
    'mediaNews#2_26': 'Today we have welcomed Kevin Shang from Vangoo Capital Partners and his colleagues in our office. We have discussed business partnership opportunities in order to attract investors from the Asian region.',
    'mediaNews#2_27': '"Mofassair Hossain CINDX Chief Marketing Officer."',
    'mediaNews#2_28': 'We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly excited about...',
    'mediaNews#2_29': 'How CINDX ensures safety for its users - KYC',
    'mediaNews#2_30': 'Every crypto enthusiast knows that a KYC procedure is necessary in order to protect investors against fraudulent actions of the third...',
    'mediaNews#2_31': 'Philip Staehelin 25 Years of Consulting and Entrepreneurial Experience',
    'mediaNews#2_32': 'We continue our regular series of articles dedicated to introducing CINDX advisers. The next item is about Philip Staehelin.',
    'mediaNews#2_33': 'CINDX meets 9coin Digital Asses Exchange',
    'mediaNews#2_34': 'The CINDX team continues active work on building relationships with various international companies. One of the most important directions of business...',
    'mediaNews#2_35': 'Jason King Interim Chief Commercial Officer',
    'mediaNews#2_36': 'The core of any great project is always people who make the unique idea come true. We would like to tell about...',
    'mediaNews#2_37': 'CINDX Presents the project during RICLUB private investors meeting',
    'mediaNews#2_38': 'CINDX has successfully passed the due diligence procedure requested by RICLub and was one of the few projects...',
    'mediaNews#2_39': 'Sofja Pevzner CINDX Personal Data Officer',
    'mediaNews#2_40': 'We continue to introduce our team and tell about what inspires our colleagues to work with CINDX. Please read about...',
    'mediaNews#2_41': 'Tyler Sanford 8+ years digital marketing in Yelp, Zenefits',
    'mediaNews#2_42': 'We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become a part of the CINDX team. In this...',
    'mediaNews#2_43': 'CINDX - Key points to observe',
    'mediaNews#2_44': 'The CINDX project is a valuable business venture with the features that are critically relevant for its participants. In this article we talk about Strengths...',
    'mediaNews#2_45': 'Airat Shayhulov CINDX Head of Quantitative Research.',
    'mediaNews#2_46': 'In “TEAM” series of the articles, we tell about people who every day participates in the creation...',
    'mediaNews#2_47': 'CINDX license of the financial consultant',
    'mediaNews#2_48': 'CINDX has obtained a termless operating licence (the FFA 000254 license) that gives the right to operate as a financial institution...',
    'mediaNews#2_49': '"Graham Doggart 20 Years of Enterprise Development and Fintech Marketing Compliance"',
    'mediaNews#2_50': 'We continue our regular series of articles dedicated to introducing CINDX advisers. The next item...',
    'mediaNews#2_51': 'CINDX continues the roadshow in China!',
    'mediaNews#2_52': 'The CINDX team is glad to announce participation as a Golden Sponsor of Borderless Blockchain Technology Summit 2018, which...',
    'mediaNews#2_53': 'Ibraghim Haniev CINDX Tech Lead',
    'mediaNews#2_54': 'Get to know more about the CINDX team! The core of any great project is always people who make the unique ideas come true...',
    'mediaNews#2_55': 'Sadie Hutton 25 Years in Senior Management and Management Consulting',
    'mediaNews#2_56': 'Like any global project, we understand the importance of professional help and advice. We continue to tell the stories of...',
    'mediaNews#2_57': 'CINDX.talk - a service that will help people become wiser in taking financial decisions',
    'mediaNews#2_58': 'The current digital-world related to the crypto industry is getting crowded with mind-charming digital solutions...',
    'mediaNews#2_59': '"Val Jerdes CINDX Product Director"',
    'mediaNews#2_60': 'We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly...',
    'mediaNews#2_61': 'Bogdan Fiedur Blockchain and cryptocurrency expert, investor, entrepreneur',
    'mediaNews#2_62': 'We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become...',
    'mediaNews#2_63': 'Welcome to CINX Token Distribution – it’s not an ICO; it’s an STO',
    'mediaNews#2_64': 'In this article, we want to make it clear why CINDX chose to hold a Security Token Offering (STO) instead of an Initial...',
    'mediaNews#2_65': 'CINDX celebrates the “AA” Rating from Top ICO List Audit!',
    'mediaNews#2_66': 'The results of CINDX’s sincerity to make meaningful changes in people’s ambitions via a unique business model just got appreciated...',
    'mediaNews#2_67': 'CINDX Weekly digest (30.07.18 - 05.08.18)',
    'mediaNews#2_68': 'The CINDX team is very excited to share the results of our work for the last week 30.07.18 - 05.08.18!',
    'mediaNews#2_69': 'Virtual Currency Wallet Services',
    'mediaNews#2_70': 'CINDX believes that being fluent in legal issues and having a clean, confident and clear legal status is of utmost importance. At the moment, CINDX is going...',
    'mediaNews#2_71': 'How CINDX Influences Crypto Trading',
    'mediaNews#2_72': 'How to master the crypto market movements and turn them in one’s favor? This is where CINDX’s effective business model comes into play. Learn more about CINDX on our Medium!',
    'mediaNews#2_73': 'CINDX Weekly digest (06.08.18 - 12.08.18)',
    'mediaNews#2_74': 'CINDX continues its regular column - Weekly Digest. We are excited to share the recent achievements of our project! Enjoy your time reading!',
    'mediaNews#2_75': 'CINDX gets 5.0 rating on TrackICO!',
    'mediaNews#2_76': 'CINDX continues getting approval from the largest and the most credible rating services. The week has hardly passed after...',
    'mediaNews#2_77': '"David Gutierrez Investment Relations Officer"',
    'mediaNews#2_78': 'CINDX is very serious about taking people on crew and proud to introduce them. This article is dedicated to David Gutierrez, CINDX Investment Relations Officer',
    'mediaNews#2_79': 'ICObench gives 4.8 to CINDX',
    'mediaNews#2_80': 'The CINDX project has already gained the highest mark of  ‘AA’ from Top ICO List and got a 5.0 rating from TrackICO. Now, we are proud to share...',
    'mediaNews#2_81': 'Dip your Toe in Crypto',
    'mediaNews#2_82': 'It is never late to change your mind. It’s no surprise that Wall Street bankers change their minds in favour of crypto. Enjoy reading CINDX review on the current market situation!',
    'mediaNews#2_83': 'Yuriy Avdeev, CEO of the CINDX project',
    'mediaNews#2_84': 'Enjoy reading what inspired Yuriy Avdeev to create a project that will help all participants of the crypto market to be profitably engaged - CINDX.',
    'mediaNews#2_85': 'Weekly digest (13.08.18 - 19.08.18)',
    'mediaNews#2_86': 'CINDX continues its regular Weekly Digest column. We are excited to share our project’s progress and the most recent achievements! We are glad to remind you that CINDX security token Pre-sale starts this Sunday. Don\'t miss!',



    'socialMedia#1': 'For more information, follow us on social media:',

    'teamAdvisersPartners#1': '50名以上のメンバーから成るチーム',
    'teamAdvisersPartners#2': 'アドバイザー',
    'teamAdvisersPartners#3': '当社のパートナー',
    // teamInfo
    'teamAdvisersPartners#4': 'Yuriy Avdeev',
    'teamAdvisersPartners#5': 'チーフエグゼクティブオフィサ',
    'teamAdvisersPartners#6': '13年の起業経験',
    'teamAdvisersPartners#7': 'ベンチャー9社',
    'teamAdvisersPartners#8': '暗号通貨管理で2百万ドル',
    'teamAdvisersPartners#9': 'Val Jerdes',
    'teamAdvisersPartners#10': 'プロダクトディレクター',
    'teamAdvisersPartners#11': '20年の起業経験',
    'teamAdvisersPartners#12': '3社の売却に成功',
    'teamAdvisersPartners#13': 'ポートフォリオで4倍のリターン',
    'teamAdvisersPartners#14': 'Mofassair Hossain',
    'teamAdvisersPartners#15': 'チーフマーケティングオフィサー',
    'teamAdvisersPartners#16': '15以上のICOで投資家およびアドバイザー',
    'teamAdvisersPartners#17': 'ICO Benchでトップアドバイザー',
    'teamAdvisersPartners#18': 'GBAPメンバー',
    'teamAdvisersPartners#19': 'Artur Shamalov',
    'teamAdvisersPartners#20': '投資ディレクター',
    'teamAdvisersPartners#21': '15年の起業経験',
    'teamAdvisersPartners#22': 'mixcart.ruでのクライアント数は5,000人',
    'teamAdvisersPartners#23': 'mail.ru で dc-daily.ruに投資',
    'teamAdvisersPartners#24': 'Denis Eskenazi',
    'teamAdvisersPartners#25': 'プロダクトマーケティングディレクター',
    'teamAdvisersPartners#26': '7年の起業経験',
    'teamAdvisersPartners#27': 'クライアントに2百万ドルを集めた実績あり',
    'teamAdvisersPartners#28': '10年のブランド戦略経験',
    'teamAdvisersPartners#29': 'Ibraghim Haniev',
    'teamAdvisersPartners#30': 'テックリード',
    'teamAdvisersPartners#31': '6年の起業経験',
    'teamAdvisersPartners#32': '200以上ものサイトを開発',
    'teamAdvisersPartners#33': '情報セキュリティに焦点をおく',
    'teamAdvisersPartners#34': 'Airat Shaikhulov',
    'teamAdvisersPartners#35': 'Head of Quantitative Research',
    'teamAdvisersPartners#36': 'Dr of science at MSU',
    'teamAdvisersPartners#37': 'Aton-line navigator developer',
    'teamAdvisersPartners#38': 'Head of algorithmic trading',
    'teamAdvisersPartners#39': 'Sofja Pevzner',
    'teamAdvisersPartners#40': '個人情報管理者',
    'teamAdvisersPartners#41': '5年の起業経験',
    'teamAdvisersPartners#42': 'エストニアのAMLオフィス運営許可',
    'teamAdvisersPartners#43': '8年の法律業務経験',
    'teamAdvisersPartners#44': 'Dave Gutierrez',
    'teamAdvisersPartners#45': '投資家向け広報担当',
    'teamAdvisersPartners#46': '5年の航空機リース業経験',
    'teamAdvisersPartners#47': '投資会社で3年の経験あり',
    'teamAdvisersPartners#48': '2年の 海外投資経験',
    'teamAdvisersPartners#49': 'Jelena Karzetskaja',
    'teamAdvisersPartners#50': 'コンプライアンスオフィサー',
    'teamAdvisersPartners#51': '法律関連で複数の学位を取得',
    'teamAdvisersPartners#52': '1997年より司法実務に就く',
    'teamAdvisersPartners#53': '法律分野： 国際法',
    'teamAdvisersPartners#54': 'Wang Dong',
    'teamAdvisersPartners#55': '中国ブロックチェーン市場専門家',
    'teamAdvisersPartners#56': 'php/JavaScriptで3年の経験',
    'teamAdvisersPartners#57': '5年のSEO/SMM/メディアバイヤー経験',
    'teamAdvisersPartners#58': '中国にて2年のブロックチェーン開発とトークン販売の経験を持つ',
    // advisers
    'teamAdvisersPartners#59': 'Keith Teare',
    'teamAdvisersPartners#60': 'Accelerated Digital Ventures の創業者および取締役会長',
    'teamAdvisersPartners#61': 'ICOBox、Crypterium、EnergiMine などのアドバイザー',
    'teamAdvisersPartners#62': 'TechCrunch創業当初からの株主',
    'teamAdvisersPartners#63': 'イギリスのベンチャー企業、Accelerated Digital Ventures の取締役会長および投資委員会を務めています。私は生まれも育ちもイギリスです。前職は、カリフォルニア州パロアルトにあるArchimedes Labs の創業者兼パートナーでした。',
    'teamAdvisersPartners#64': '創業者たち、チーム、デザイナー、エンジニアと共に製品づくりをしたり、語り合ったり、それらを現実のもにすることが好きでした。',
    'teamAdvisersPartners#65': '1980年代の前半ごろから多くの企業の創業に創業者または共同創業者として携わってきました。そのいくつかは売却もしくは株式公開に成功しました。私の会社のうち2つはユニコーン企業となり、10億ドル以上の値が付きました。私は常に物事の変化に焦点をあててきました。80年代はネットワークとデータベースです。1994～1998年はインターネットアクセス。1998～2010年はウェブサービスとコンテンツ、モバイル消費者向けアプリ。そして2017年からはブロックチェーンです。',
    'teamAdvisersPartners#66': '経歴およびプロジェクト： Tech Crunch、Accelerated Digital Ventures、cScape、EasyNet、Cyberia、RealNames、Venture Network、ICOBox、Crypterium、R/Block、Fluz、EnergiMine、Archimedes Labs そして CINDX',
    'teamAdvisersPartners#67': 'Austin Kimm',
    'teamAdvisersPartners#68': 'International Financial Services のCEO',
    'teamAdvisersPartners#69': '金融サービスで30年以上もの経験',
    'teamAdvisersPartners#70': 'Created companies with a worth of $500m',
    'teamAdvisersPartners#71': '経験豊かな実績により、私が時価500百万ドルを超える企業づくりに成功した発展途上の市場で、保険事業の構築に重点を置くことを金融サービスのCEOに証明しました。',
    'teamAdvisersPartners#72': 'ごく最近のロシア（10年）では、ロシア最大のインターネット販売雇用プラットフォーム「Workle」のCEOを含む、保険以外の上級管理職者や、世界初の暗号通貨銀行Crypteriumを始めとする幅広いフィンテックスタートアップの経営幹部などです。',
    'teamAdvisersPartners#73': ' 経歴およびプロジェクト： Aviva、Commercial Union UK、Reinaissance Insurance、Kimm Health & Leisure Ltd、Workle、Crypterium、CryptoIndex、CINDX',
    'teamAdvisersPartners#74': 'Philip Staehelin',
    'teamAdvisersPartners#75': '25年ものコンサルティングおよび起業経験',
    'teamAdvisersPartners#76': '500百万ドル代替決済ビジネスの経営に携わる',
    'teamAdvisersPartners#77': '20か国で200以上ものスタートアップを指導',
    'teamAdvisersPartners#78': '私は革新者であり、伝染する楽観主義と実用的な現実主義を融合するリーダーです。他人が気づかないところにチャンスを見出します。',
    'teamAdvisersPartners#79': '企業・コンサルティング・スタートアップの現場で、「物を別の方向から見る」能力と「実現する」力を活用してきました。そうした現場は斬新なアイデアのネタとなる広い視野を提供してくれます。',
    'teamAdvisersPartners#80': '難問を解決するソリューションを見つけることこそ、私を朝ベッドから起き上がらせる原動力です。',
    'teamAdvisersPartners#81': '経歴およびプロジェクト： Roland Berger、Dot Glasses、Transparency International、StartupYard、Bethereum、Gjirafa Inc、Accenture、CINDX',
    'teamAdvisersPartners#82': 'Amarpreet Singh',
    'teamAdvisersPartners#83': 'Global Blockchain Foundation のシニアアドバイザー',
    'teamAdvisersPartners#84': 'Microsoft、The World Bank および Airbus での経験あり',
    'teamAdvisersPartners#85': '複数のブロックチェーンプロジェクトで諮問委員会のメンバーに就任',
    'teamAdvisersPartners#86': 'テクノロジー＆デジタル愛好家、 オペレーション・コンサルティング・イノベーションなどテクノロジー業界で長年の経験を持つベテラン専門家。 彼はクラウド（Microsoft および AWS）の認定スペシャリストです。',
    'teamAdvisersPartners#87': '彼はクラウド（Microsoft および AWS）の認定スペシャリストです。汎用性と柔軟性に優れています。優秀な分析力、戦略、リーダーシップのスキルを備え、チームプレーに長けています。',
    'teamAdvisersPartners#88': '専門分野： テクノロジーコンサルティング、オペレーション、クラウドコンピューティング、フィンテック、イノベーション、ERP、マシン学習、アカウント管理、パートナー開発、ビジネス開発および戦略。Amarpreet Singhは、職歴および学歴ともに幅広い経歴の持ち主です。',
    'teamAdvisersPartners#89': '3つの修士号を取得しており、インド・シンガポール・フランス・中国・南アフリカ・韓国・カナダにて在住・勤務・勉強していました。',
    'teamAdvisersPartners#90': '経歴およびプロジェクト： Microsoft、The World Bank、Airbus、TokenAsia Platform、GOeurika、CINDX',
    'teamAdvisersPartners#91': 'Tyler Sanford',
    'teamAdvisersPartners#92': 'Yelp および Zenefits にて8年のデジタルマーケティング経験',
    'teamAdvisersPartners#93': '12のICOで225百万ドル以上を集めた',
    'teamAdvisersPartners#94': 'ブロックチェーンの早期導入者',
    'teamAdvisersPartners#95': '自分の経歴および人生で活用したスキルは、アスリートとして育った経験からくるものです。',
    'teamAdvisersPartners#96': 'どんな仕事にも浮き沈みがあることを学びつつ、もうひとがんばりしたときの結果を見られた自分はとても恵まれています。',
    'teamAdvisersPartners#97': '自分は自発的な人間で、常にビジネスのあらゆる側面で知識を伸ばそうとします。',
    'teamAdvisersPartners#98': 'チャレンジ精神にあふれ、目標に向かって障害を乗り越えることからモチベーションを得ています。',
    'teamAdvisersPartners#99': '経歴およびプロジェクト： IPG Holdings、DataBlockChain、TraXion by Puma Technologies、ELYSIAN、Etherinc、FTEC Foundation、CINDX',
    'teamAdvisersPartners#100': 'Philip Staehelin',
    'teamAdvisersPartners#101': '25 years of consulting and entrepreneurial experience',
    'teamAdvisersPartners#102': '$500m alternative payments business under leadership',
    'teamAdvisersPartners#103': '200+ startups from 20 countries mentored',
    'teamAdvisersPartners#104': '',
    'teamAdvisersPartners#105': '',
    'teamAdvisersPartners#106': '',
    'teamAdvisersPartners#107': '',
    'teamAdvisersPartners#108': 'Senior Adviser of Global Blockchain Foundation',
    'teamAdvisersPartners#109': 'Experience in Microsoft, The World Bank and Airbus',
    'teamAdvisersPartners#110': 'Advisery Board Member of Blockchain projects',
    'teamAdvisersPartners#111': 'Technology/Digital enthusiast and a seasoned professional with years of experience in Tech industry – operations, consulting and innovation.',
    'teamAdvisersPartners#112': 'He is a certified Cloud (Microsoft and AWS) specialist. Known for versatility and flexibility. Excellent analytic, strategic, leadership skills and a team player at its best.',
    'teamAdvisersPartners#113': 'Specialties: Technology Consulting, Operations, Cloud Computing, Fintech, Innovation, ERP, Machine Learning, Account Management, Partner Development, Business Development and Strategy',
    'teamAdvisersPartners#114': 'Amarpreet Singh has a very diversified work and educational background. He holds three Masters degrees and has lived/worked/studied in India, Singapore, France, China, South Africa, Korea, Canada.',
    'teamAdvisersPartners#115': 'Career and projects: Microsoft, The World Bank, Airbus, TokenAsia Platform, GOeurika, CINDX',
    'teamAdvisersPartners#116': 'Tyler Sanford',
    'teamAdvisersPartners#117': '8 Years Digital Marketing in Yelp and Zenefits',
    'teamAdvisersPartners#118': '12 ICO’s over $225M raised',
    'teamAdvisersPartners#119': 'Early adopter of blockchain',
    'teamAdvisersPartners#120': 'Growing up as an Athlete has given me a skill set that I\'ve been able to apply to my careers and personal life.',
    'teamAdvisersPartners#121': 'I have been very fortunate to see the results of going that extra mile, while learning to deal with the highs and lows that go along with all professional careers.',
    'teamAdvisersPartners#122': 'I\'m an extremely self-motivated individual, always looking to continue my growth of knowledge and talents in all aspects of business.',
    'teamAdvisersPartners#123': 'Always up for a challenge, my motivation comes from overcoming obstacles to reach my goals',
    'teamAdvisersPartners#124': 'Career and projects: IPG Holdings, DataBlockChain, TraXion by Puma Technologies, ELYSIAN, Etherinc, FTEC Foundation,  CINDX',
    'teamAdvisersPartners#125': 'Bogdan Fiedur',
    'teamAdvisersPartners#126': 'ブロックチェーンおよび暗号通貨の専門家・投資家・起業家',
    'teamAdvisersPartners#127': 'bitJob の共同創業者およびBlockchainexperts.io の社長',
    'teamAdvisersPartners#128': 'ICOアドバイザー、ICOBenchエキスパート',
    'teamAdvisersPartners#129': 'Bogdan Fiedur はスマートコントラクト開発者・暗号通貨投資家・起業家、そしてhttp://blockchainexperts.io の社長という顔を持ちます。',
    'teamAdvisersPartners#130': 'eコマースウェブサイト構築で20年以上ものIT経験を持ち、ここ3年はブロックチェーン開発に関わっています。また、今日まで20もの成功しているICOでICOアドバイザーを務めており、',
    'teamAdvisersPartners#131': 'Winnipeg のローカル暗号通貨コミュニティでプレゼンテーションやブロックチェーン＆スマートコントラクトプログラムのワークショップ提供に深く関わっています。 現在 Bogdan はブロックチェーン業界に重点を置き、ブロックチェーンエキスパートにアドバイス、コンサルティングサービス、人脈などを提供しています。 最近では学生向けのフリーランサーブロックチェーンプラットフォームを共同で創業し、',
    'teamAdvisersPartners#132': 'PayPie.comを始めとするいくつかのICOプロジェクトのチームに加わっています。 経歴およびプロジェクト： US Blockchain Association、Tuurnt、Trends Project、BiNeuro、Zichain、Graphen Tech、CyClean、Swachhcoin、CINDX',
    'teamAdvisersPartners#133': 'Graham Doggart',
    'teamAdvisersPartners#134': '20年の企業開発、フィンテックマーケティングコンプライアンス',
    'teamAdvisersPartners#135': '100百万ドル相当のキャンペーンを実施',
    'teamAdvisersPartners#136': '本年10以上ものブロックチェーンプロジェクトでアドバイザーに就任',
    'teamAdvisersPartners#137': '私はStealth Cryptocurrency Project の会長であり、2012年からブロックチェーン＆フィンテックのアドバイザリーとして活動しているDynamic Abundance の共同創業者および戦略担当のトップに立っています。',
    'teamAdvisersPartners#138': 'トークン提供の構成とパッケージングが専門で、国際的に数多くのブロックチェーン、暗号通貨、ICOプロジェクトに関わってきました。',
    'teamAdvisersPartners#139': '20年以上、技術マネジメントのコンサルタントや法律・金融コンプライアンスのアドバイス、成長戦略、投資家向け広報、そして自ら材料のデザインや作成なども手掛けてきました。',
    'teamAdvisersPartners#140': '経歴およびプロジェクト： Stealth Cryptocurrency Project、Dynamic Abundance、ELYSIAN、Fox Trading FX、Profede、Worltdopoly、CINDX',
    'teamAdvisersPartners#141': 'Sadie Hutton',
    'teamAdvisersPartners#142': 'シニアマネジメントおよびマネジメントコンサルタントで25年の経験あり',
    'teamAdvisersPartners#143': '75百万ポンド相当のキャンペーンで数百万ドルの資金調達',
    'teamAdvisersPartners#144': '8つのプロジェクトでICOアドバイザーに就任',
    'teamAdvisersPartners#145': '私はブロックチェーンアドバイザリーであるDynamic Abundance の創業者です。「実践的」なアプローチを好みます。',
    'teamAdvisersPartners#146': 'ICO分析、プロジェクトマネジメント、ICOプロセスのあらゆる側面における専門家です。ビジネスの経営と成長を得意とし、プロジェクトの始まりから終わりまでを見届けます。',
    'teamAdvisersPartners#147': '生まれながらにして問題の解決屋で、すべてのプロジェクトには個人的にか関わります。勝つことが好きなのです！20年以上もの経営経験で確固たるネットワークを築き上げてきました。高度なブロックチェーンプロジェクトで、財務・技術・販売・マーケティング・品質管理などのアドバイスを活発に行ってきました。',
    'teamAdvisersPartners#148': '経歴およびプロジェクト： Dynamic Abundance、ELYSIAN、Worldopoly、Confidential ICO、Fox Trading FX、Profede、Market Digital、CINDX',
    'teamAdvisersPartners#149': 'Jason King',
    'teamAdvisersPartners#150': '20年もの取締役経験',
    'teamAdvisersPartners#151': '30か国で事業を運営',
    'teamAdvisersPartners#152': '500百万ドルの損益を担っています',
    'teamAdvisersPartners#153': 'Jason King は約20年間テクノロジー・メディア・電気通信で重役を務め、商取引の構築やブローカー業、交渉の成功、市場開拓、成功に向けた組織のポジショニングに携わってきました。',
    'teamAdvisersPartners#154': '交渉の成功、市場開拓、成功に向けた組織のポジショニングに携わってきました。',
    'teamAdvisersPartners#155': '適確な人材とチームを作り最も収益性の高いゴールを達成することで、これらのチャレンジの多くは、自分を優秀な再構築および方向転換の役へと導きました。',
    'teamAdvisersPartners#156': 'Jason はビジネス運営と経営、戦略的プランニングおよび財務、暗号通貨とブロックチェーン業界を含む多くの分野で幅広い経験を持っています。',
    'teamAdvisersPartners#157': 'Motti Peer',
    'teamAdvisersPartners#158': '受賞歴のある世界的に有名なPR企業、Blonde 2.0 の共同創業者',
    'teamAdvisersPartners#159': 'セキュリティおよび金融分野で様々な企業を創業',
    'teamAdvisersPartners#160': 'Motti はブロックチェーンや暗号通貨のPR・スタートアップ・ベンチャーキャピタルをけん引しています',
    'teamAdvisersPartners#161': 'セキュリティおよび金融分野で様々な企業を創業しました。金融ヘッジファンドマネージャーとして長年の経験があり、金融とマーケティングのMBAをマンチェスター大学から取得し、経営学の学士号をフェアリー・ディキンソン大学より取得しています。',
    'teamAdvisersPartners#162': '歴のあるPR会社で「業界の有力スタートアップ」としてフォーブス誌に掲載された Blonde 2.0 の共同CEOです。Blonde 2.0 の共同CEOとして、戦略や危機管理だけでなく、広報面の指示も担っています。',
    'teamAdvisersPartners#163': '35名の専門家チームで、Blonde 2.0はブロックチェーンや暗号通貨のPR・スタートアップ・ベンチャーキャピタルをけん引しています',
    'teamAdvisersPartners#164': 'Leonard Grayver',
    'teamAdvisersPartners#165': 'Greenberg、Whitcombe および Takeuchi のパートナー',
    'teamAdvisersPartners#166': '400以上ものスタートアップで代表を務めた',
    'teamAdvisersPartners#167': '彼はロースクール時代に18百万米ドルもの資金を自身のスタートアップのために集めました',
    'teamAdvisersPartners#168': 'Leonard Grayver はソ連で生まれ、幼少期に両親とともにアメリカへ移住しました。Leonard はロースクール時代に始めたスタートアップで、18百万米ドルの資金調達に成功しました。',
    'teamAdvisersPartners#169': 'そのスタートアップが生き残ることはありませんでしたが、それ以降 Leonard は 400以上ものスタートアップを支援してきました。',
    'teamAdvisersPartners#170': '総じて言えることは、Leonard にはベンチャーキャピタルの資金調達・ファンド構築・デュー・デリジェンス（ファンドと出資者の両方を代表）で10年以上もの経験があります。 すべての起業家に対する彼のアドバイスは、「トレンドを追いかけずに自分の興味を追いかけろ」です。Leonard には様々な海外ベンチャーファンドとの強力な繋がりがあります。',

    'joinTokenPreSale#1': 'トークンプレセールに参加する',
    'joinTokenPreSale#2': 'プレセールに参加する',
    'joinTokenPreSale#3': 'MVPを試してみる ',
    'joinTokenPreSale#4': '本社',
    'joinTokenPreSale#5': 'Harjumaa, Erika 14,',
    'joinTokenPreSale#6': 'Talinn, 10416, Estonia',
    'joinTokenPreSale#7': 'ビジネスに関するお問合せ | hello@cindx.io',
    'joinTokenPreSale#8': 'Legal Disclaimer',
    'joinTokenPreSale#9': '開発とマーケティング',
    'joinTokenPreSale#10': 'Presnenskaya naberezhnaya, 8 building 1,',
    'joinTokenPreSale#11': 'Moscow, 123112, Russia',
    'joinTokenPreSale#12': '採用情報 | チームの一員に |',
    'joinTokenPreSale#13': 'Follow us:'
}

export default ja