// Португальский
const pt = {
    'mainBlock#1': 'Fazemos com que o investimento em criptomoedas seja',
    'mainBlock#2': 'Fácil, Seguro e Rápido',
    'mainBlock#3': 'Junte-se à nossa pré-venda de tokens segura',

    'icoInfo#1': 'Aceitamos:',
    'icoInfo#2': 'Limite total:',
    'icoInfo#3': 'Marcos por etapa:',
    'icoInfo#4': 'Os Contratos de Serviço são assinados com',

    'menu#1': 'WHITEPAPER',
    'menu#2': 'APRESENTAÇÃO',
    'menu#3': 'FOLHETO',
    'menu#4': 'MODELO FINANCEIRO',
    'menu#5': 'DOCUMENTAÇÃO LEGAL',
    'menu#6': 'EN',
    'menu#7': 'Produto',
    'menu#8': 'Detalhes das vendas',
    'menu#9': 'Equipa',
    'menu#10': 'Documentação pública',
    'menu#11': 'Testar MVP',

    'mailForm#1': 'Wrong email',
    'mailForm#2': 'sending ..',
    'mailForm#3': 'Already was or is not valid, try again',
    'mailForm#4': 'Your email has been sent successfully',
    'mailForm#5': 'an error occurred, try again',
    'mailForm#6': 'GDRP Сompliance',
    'mailForm#7': 'Personal data provided via Subscription form and KYC procedure will be collected in the full compliance with GDRP',
    'mailForm#8': 'The Data Protection Officer  of the project is  Mrs. Sofja Pevzner-Belositski. Contact details: dpo@cindx.io. Any data subject may, at any time, contact Data Protection Officer of directly with any request related to data protection.',
    'mailForm#9': 'Your personal data provided via Subscription form and KYC procedure will be shared to our partners:',
    'mailForm#10': 'ICO Promo',
    'mailForm#11': 'Privacy Policy',
    'mailForm#12': 'Sum & Substance',
    'mailForm#13': 'By default, the personal data provided by subscriber are kept by CINDX, ICO Promo and Sum & Substance for 5 years after registration of subscriber in the system',
    'mailForm#14': 'If you do not agree to this privacy policy, please do not use our site.',
    'mailForm#15': 'By using our site, you consent to the collection and use of information by us. Owing to the global nature of the internet infrastructure, the information you provide may be transferred in transit to countries outside the European Economic Area that do not have similar protections in place regarding your data and its use as set out in this policy.',
    'mailForm#16': 'However, we have taken the steps outlined above to try to improve the security of your information. By submitting your information you consent to these transfers',
    'mailForm#17': 'I agree to process my',
    'mailForm#18': 'personal data',
    'mailForm#19': 'Venda de tokens segura e em direto',
    'mailForm#20': '25% BONUS',
    'mailForm#21': 'Agarre a oportunidade antes dos outros A oferta expira em',
    'mailForm#22': 'Token sale starts in',
    'mailForm#23': 'Start from $1',
    'mailForm#24': '$1 later',
    'mailForm#25': 'O seu e-mail',
    'mailForm#26': 'Aderir à Pré-venda',
    'mailForm#27': 'AGREE & SUBMIT',

    'progressBarSale#1':  'Bónus de venda',
    'progressBarSale#2':  'em CINX',
    'progressBarSale#3':  'Pré-venda',
    'progressBarSale#4':  'Venda',
    'progressBarSale#5':  '26 Agosto',
    'progressBarSale#6':  '17 Setembro',
    'progressBarSale#7':  '8 Outubro',
    'progressBarSale#8':  '22 Outubro',
    'progressBarSale#9':  '6 Novembro',
    'progressBarSale#10': '19 Novembro',
    'progressBarSale#11': '3 Dezembro',
    'progressBarSale#12': '17 Dezembro',

    'cryptoAssetsManagement#1.1': 'A CIDNX é uma plataforma de gestão de ativos de criptomoedas. Resolvemos os problemas de investidores, negociadores e programadores,',
    'cryptoAssetsManagement#1.2': 'traders and developers',
    'cryptoAssetsManagement#2': 'CINDX.MARKETPLACE PARA INVESTIDORES',
    'cryptoAssetsManagement#3': 'Não se preocupe com os seus conhecimentos e experiência – os especialistas em negociação com criptomoedas estão aqui para o ajudar',
    'cryptoAssetsManagement#4': 'Controle os seus fundos de criptomoedas: as suas moedas são mantidas na sua carteira em todos os momentos',
    'cryptoAssetsManagement#5': 'Só paga se ganhar: serão cobradas taxas apenas se o seu portfólio obtiver lucros',
    'cryptoAssetsManagement#6': 'TEST MVP',
    'cryptoAssetsManagement#7': 'CINDX.TERMINAL PARA NEGOCIADORES',
    'cryptoAssetsManagement#8': 'Se é um negociador de sucesso, pode atrair capital com zero de investimento em marketing',
    'cryptoAssetsManagement#9': 'Nós fornecemos um Terminal, App Store, o mercado e outras ferramentas avançadas que vão ajudá-lo a ter sucesso na negociação.',
    'cryptoAssetsManagement#10': 'A CINDX ajuda a rentabilizar a sua reputação e a sua experiência. O seu historial na negociação e a sua influência são transparentes.',
    'cryptoAssetsManagement#11': 'CINDX.TALK, CINDX.HUB e CINDX.DAO',
    'cryptoAssetsManagement#12': 'CINDX.Talk - uma rede social com recompensas baseadas em conteúdos úteis',
    'cryptoAssetsManagement#13': 'CINDX.Hub - os componentes incluem um "gabinete para o fornecedor", assim como uma plataforma para testar e integrar software de terceiros',
    'cryptoAssetsManagement#14': 'CINDX.dao - um componente que lhe permite implementar um sistema de votação para a comunidade, baseado em regras organizacionais, descentralizadas e autónomas',

    'teamLegal#1': 'TAMBÉM TEMOS UMA GRANDE EQUIPA E REGULAMENTAÇÃO JURÍDICA',
    'teamLegal#2': 'Legal and Regulatory Organizational Framework',
    'teamLegal#3': 'CRYPTOCURRENCY EXCHANGE LICENSE',
    'teamLegal#4': 'FINANCIAL INSTITUTION LICENSE',
    'teamLegal#5': 'CRYPTO WALLET LICENSE',
    'teamLegal#6': 'WHITEPAPER',
    'teamLegal#7': 'APRESENTAÇÃO',
    'teamLegal#8': 'FOLHETO',
    'teamLegal#9': 'MODELO FINANCEIRO',
    'teamLegal#10': 'DOCUMENTAÇÃO LEGAL',

    'roadmap#1': 'Roadmap',
    'roadmap#2': 'CENÁRIO',
    'roadmap#3': 'We are building the base for the CINDX platform. At this step, the Minimum Viable Product (MVP) is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform.',
    'roadmap#4': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be  going through some alterations to add functionalities.  ',
    'roadmap#5': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services.      ',
    'roadmap#6': 'At this stage, the CINDX.market and CINDX.trade components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. ',
    'roadmap#7': 'CINDX.talk will have public and private channels. At this stage, the content will  be able to be  separated. ',
    'roadmap#8': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade is an extremely flexible system of order execution and risk management. The Vendor’s market will appear; however, at this point, the Vendor’s market will only contain applications developed by CINDX and its partners.  ',
    'roadmap#9': 'A tokenized rating system will be added in the final version of CINDX.talk, as well as a new type of product: “algorithmic trading”. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders.   ',
    'roadmap#10': 'We are building the base for the CINDX platform. At this step, the MVP is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform. ',
    'roadmap#11': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be going through some alterations to add functionalities.  ',
    'roadmap#12': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services. Another new component, CINDX.hub, will enable Vendors to develop applications that will analyze the market data that CINDX provides. ',
    'roadmap#13': 'At this stage, the CINDX.market and CINDX.trade components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. An SDK for developers will be released. This should simplify application development and implementation for CINDX.  ',
    'roadmap#14': 'CINDX.talk will have public and private channels. At this stage, the content will be able to be separated. CINDX.hub will integrate Github, which will simplify application development even more.',
    'roadmap#15': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade will be an extremely flexible system of order execution and risk management. CINDX.hub will have a full-scale editor for trading strategies with a testing system based on historical market data.',
    'roadmap#16': 'A tokenized rating system  CINDX.talk will be added in the final version of CINDX.talk. This will provide a system of assessment for CINDX community trading experts. “Algorithmic trading” will also be added. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders. A high-grade platform for a code audit will be created. ',
    'roadmap#17': 'We are building the base for the CINDX platform. At this step, the MVP is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform.',
    'roadmap#18': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be  going through some alterations to add functionalities. ',
    'roadmap#19': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services. Another new component,  CINDX.hub, will enable Vendors to develop applications that will analyze the market data that CINDX provides. The team will develop CINDX.dao, a component that acts as a system for the platform’s revenue distribution to its token holders.       ',
    'roadmap#20': 'At this stage, the CINDX.market and CINDX.trade  components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. An SDK for developers will be released. This should simplify application and implementation development for CINDX.  ',
    'roadmap#21': 'CINDX.talk will have public and private channels. At this stage the content can be separated. CINDX.hub will integrate Github which will simplify application development even more.',
    'roadmap#22': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade will be an extremely flexible system of order execution and risk management. CINDX.hub has a full-scale editor for trading strategies with a testing system based on historical market data. CINDX.dao will receive a voting system for token holders. ',
    'roadmap#23': 'A tokenized rating system CINDX.talk will be added in the final version of CINDX.talk. This will provide a system of assessment for CINDX community trading experts. “Algorithmic trading” will also be added. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders. A high-grade platform for a code audit will be created. ',

    'problemSolving#1': 'Tempo',
    'problemSolving#2': 'Confiança',
    'problemSolving#3': 'Incerteza',
    'problemSolving#4': 'Tenho algum dinheiro para investir na área das criptomoedas, mas não tenho tempo para fazer pesquisas nem para contactar negociadores profissionais que possam gerir o meu portfólio',
    'problemSolving#5': 'Nunca gostei da ideia de entregar o meu dinheiro a outra pessoa com o objetivo de fazer lucros',
    'problemSolving#6': 'A tecnologia que rodeia a negociação com criptomoedas não é fácil de compreender Não consigo perceber como faço para negociar com as minhas moedas',
    'problemSolving#7': 'A CINDX fornece acesso a operadores bem cotados e dignos de confiança',
    'problemSolving#8': 'Na plataforma CINDX, os seus fundos nunca saem da sua carteira',
    'problemSolving#9': 'Obtém ganhos juntamente com os melhores negociadores do mercado',
    'problemSolving#10': 'Os negociadores registados na CINDX são classificados de acordo com o seu histórico de sucessos em negociações. Escolha rapidamente o negociador que se adapta a si',
    'problemSolving#11': 'Os nosso sistema descentralizado e os contratos inteligentes permitem que os seus fundos sejam geridos sem a necessidade de transferi-los para um negociador',
    'problemSolving#12': 'Cada investidor registado na CINDX tem a oportunidade de ter os seus fundos geridos pelos negociadores mais bem-sucedidos do mercado',
    'problemSolving#13': 'Quais são os problemas que a CINDX resolve?',
    'problemSolving#14': 'Teste MVP',

    'howCindxWorks#1': 'Investidores',
    'howCindxWorks#2': 'Negociadores',
    'howCindxWorks#3': 'Fornecedores',
    'howCindxWorks#4': 'aumentam os seus ganhos com criptomoedas através da gestão do seu portfólio efetuada pelos melhores negociadores',
    'howCindxWorks#5': 'ganham comissões dos seus investidores, que os seguem consoante o seu desempenho e estratégia negocial',
    'howCindxWorks#6': 'vendem ferramentas avançadas para negociação, como robôs de negociação e widgets de notícias.',
    'howCindxWorks#7': 'recolhe comissões e taxas de subscrição',
    'howCindxWorks#8': 'Vou juntar-me à CINDX com fundos de criptomoedas que pretendo que sejam negociados',
    'howCindxWorks#9': 'Vou juntar-me à CINDX com a experiência na negociação que vai beneficiar os investidores',
    'howCindxWorks#10': 'Vou juntar-me à CINDX com aplicações para negociação que vão ajudar os investidores',
    'howCindxWorks#11': 'Estamos aqui para tornar a negociação mais fácil, segura e rentável',
    'howCindxWorks#12': 'Resumo: Como funciona a CINDX',

    'marketAnalytics#1': 'Análises de Mercado',
    'marketAnalytics#2': 'ASG Globais',
    'marketAnalytics#3': 'Investimento',
    'marketAnalytics#4': 'Structure of investment',
    'marketAnalytics#5': 'Desde 2000, o mercado global de gestão de capitais cresceu mais de 250%.',
    'marketAnalytics#6': 'Isto é o resultado de melhorias constantes nas ferramentas de mercado, assim como o desenvolvimento geral de estruturas de mercado.',
    'marketAnalytics#7': 'Apesar do crescimento explosivo do mercado de criptomoedas em 2017, este setor ainda está a dar os primeiros passos.',
    'marketAnalytics#8': 'A capitalização de mercado total era de 600 mil milhões $, no final de 2017 — apenas 1% da capitalização de mercado do total do setor da gestão de capitais.',
    'marketAnalytics#9': 'WHITEPAPER',
    'marketAnalytics#10': 'APRESENTAÇÃO',
    'marketAnalytics#11': 'FOLHETO',
    'marketAnalytics#12': 'MODELO FINANCEIRO',
    'marketAnalytics#13': 'DOCUMENTAÇÃO LEGAL',
    'marketAnalytics#14': 'Geographic Scope',
    'marketAnalytics#15': '25 milhões de potenciais',
    'marketAnalytics#16': 'carteiras de blockchain',
    'marketAnalytics#17': '200.000 potenciais',
    'marketAnalytics#18': 'transações diariamente',
    'marketAnalytics#19': 'Mais de 225 potenciais',
    'marketAnalytics#20': 'parceiros, cada um com 3 a 5 mil milhões $',

    'tokenSaleDetails#1': 'Operações dos tokens',
    'tokenSaleDetails#2': 'Equipa',
    'tokenSaleDetails#3': 'Prémios',
    'tokenSaleDetails#4': 'Consultores',
    'tokenSaleDetails#5': 'Reserva',
    'tokenSaleDetails#6': 'Incentivos na comunidade',
    'tokenSaleDetails#7': 'Suporte à liquidez de tokens',
    'tokenSaleDetails#8': 'Disponíveis para venda',
    'tokenSaleDetails#9': 'Nome do token: CINX',
    'tokenSaleDetails#10': 'Início da Pré-venda de tokens:',
    'tokenSaleDetails#11': 'Emissão total:',
    'tokenSaleDetails#12': 'Preço por token: 1,00 $',
    'tokenSaleDetails#13': 'Investimento mínimo:',
    'tokenSaleDetails#14': 'equivalente a 50 $',
    'tokenSaleDetails#15': 'WHITEPAPER',
    'tokenSaleDetails#16': 'APRESENTAÇÃO',
    'tokenSaleDetails#17': 'FOLHETO',
    'tokenSaleDetails#18': 'MODELO FINANCEIRO',
    'tokenSaleDetails#19': 'DOCUMENTAÇÃO LEGAL',
    'tokenSaleDetails#20': 'Utilização de receitas',
    'tokenSaleDetails#21': 'Marketing e RP 21%',
    'tokenSaleDetails#22': 'Pesquisa e desenvolvimento 41%',
    'tokenSaleDetails#23': 'Operações 28%',
    'tokenSaleDetails#24': 'Despesas legais 7%',
    'tokenSaleDetails#25': 'Bónus para negociadores 3%',
    'tokenSaleDetails#26': 'Operações dos tokens',
    'tokenSaleDetails#27': 'Venda de tokens:',
    'tokenSaleDetails#28': 'Bónus na Pré-venda de tokens:',
    'tokenSaleDetails#29': 'Aug 26 - Sep 16 - 25% Bonus',
    'tokenSaleDetails#30': 'Sep 17 - Oct 7 - 20% Bonus',
    'tokenSaleDetails#31': 'Bónus na venda principal de tokens:',
    'tokenSaleDetails#32': '8 de out. - 21 de out. - 17% de bónus',
    'tokenSaleDetails#33': '22 de out. - 4 de nov. - 15% de bónus',
    'tokenSaleDetails#34': '5 de nov. - 18 de nov. - 13% de bónus',
    'tokenSaleDetails#35': '19 de nov. - 2 de dez. - 10% de bónus',
    'tokenSaleDetails#36': '3 de dez. - 16 de dez. - 5% de bónus',
    'tokenSaleDetails#37': '17 de dez. - 26 de dez. - 0% de bónus',
    'tokenSaleDetails#38': 'Comprar Tokens',
    'tokenSaleDetails#39': 'Detalhes da Venda de Tokens',
    'tokenSaleDetails#40': 'During the token sale, investors purchase utility tokens – options [CINXO], which give them the right to receive security tokens [CINX] in the future.',
    'tokenSaleDetails#41': 'Security tokens [CINX] will be issued and distributed following the prospect of emission published on the website of FSA of Estonia https://www.fi.ee/ and cindx.io after the end of the token sale, but no later than Q1 2019.',
    'tokenSaleDetails#42': 'The holder of [CINXO] tokens has the right but no obligation to exchange options for security tokens with a ratio of 1:1 after completing the KYC procedure with identification signature, address confirmation and supply of other documents (see the KYC diagram).',
    'tokenSaleDetails#43': 'Tokens [CINXO] grant the same rights as security tokens apart from the right to participate in revenue distribution with a lock-up and voting on the platform.',

    'legalSchedule#1': 'Calendário Legal',
    'legalSchedule#2': 'RECEBIDA LICENÇA (FVR000110) PARA PERMITIR CÂMBIO ENTRE MOEDA VIRTUAL E SERVIÇOS FIAT',
    'legalSchedule#3': 'INSCRIÇÃO PARA REGISTO DE MARCA COMERCIAL NA ESTÓNIA E UE',
    'legalSchedule#4': 'LICENÇA FFA000254 PARA OPERAÇÃO COMO INSTITUIÇÃO FINANCEIRA',
    'legalSchedule#5': 'RECEBIDA LICENÇA FFA000254 PARA OPERAÇÃO COMO INSTITUIÇÃO FINANCEIRA',
    'legalSchedule#6': 'Criado o Prospeto de acordo com a lei da Estónia',
    'legalSchedule#7': 'OBTIDA A LICENÇA FSA (Autoridade Supervisora Financeira da Estónia)',
    'legalSchedule#8': 'RECEBIDA LICENÇA PARA FORNECER UM SERVIÇO DE CARTEIRA DE MOEDA VIRTUAL',
    'legalSchedule#9': 'REGISTADA SEGUNDO REGULAMENTO D NA SEC',
    'legalSchedule#10': 'NOMEADO GESTOR DE DADOS PESSOAIS PARA CUMPRIR OS REQUISITOS DO RGPD',
    'legalSchedule#11': 'RECEBIDA LICENÇA FSA',
    'legalSchedule#12': 'REGISTADO O PROSPETO UE 809-2004',
    'legalSchedule#13': 'EMISSÃO DE TOKENS DE SEGURANÇA CINX',

    'feedbackProject#1': 'COMENTÁRIOS SOBRE O NOSSO PROJETO',
    'feedbackProject#2': 'Val Jerdes',
    'feedbackProject#3': 'Diretor de Produto',
    'feedbackProject#4': 'Val Jerdes, Diretor de Produto da CINDX, fala sobre os principais membros da equipa e como a sua experiência irá ajudar a desenvolver o projeto que pode mudar, de forma significativa, o setor do investimento',
    'feedbackProject#5': 'Denis Eskenazi',
    'feedbackProject#6': 'Diretor de Marketing de Produto',
    'feedbackProject#7': 'Denis Eskenazi, Diretor de Marketing de Produto da CINDX, explica as razões que o levaram a juntar-se à CINDX',
    'feedbackProject#8': 'Philip Staehelin',
    'feedbackProject#9': 'Consultor',
    'feedbackProject#10': 'Philip Staehelin, Consultor do projeto CINDX, explica como a revolução das criptomoedas pode ajudar até os investidores mais inexperientes e também fala sobre as inovações que o projeto CINDX preparou para o mercado das criptomoedas',
    'feedbackProject#11': 'Andrzej Cichowlaz',
    'feedbackProject#12': 'Especialista em Marketing',
    'feedbackProject#13': 'Andrzej Cichowlaz, Gestor de Marketing da CINDX, fala sobre o que o levou a acreditar no sucesso do projeto',
    'feedbackProject#14': 'Austin Kimm',
    'feedbackProject#15': 'Austin Kimm, Consultor do projeto CINDX, conta-nos como a CINDX possibilita a obtenção de lucro com a negociação de criptomoedas, de forma simples e inteligente ',
    'feedbackProject#16': 'Amarpreet Singh',
    'feedbackProject#17': 'Amarpreet Singh, Consultor da CINDX, explica como a plataforma CINDX pode fazer a ponte entre os investidores e os negociadores',
    'feedbackProject#18': 'Keith Teare',
    'feedbackProject#19': 'Keith Teare, Consultor da CINDX, descreve as vantagens da plataforma CINDX',
    'feedbackProject#20': 'Mansur Rasulov',
    'feedbackProject#21': 'Responsável de Comunidade',
    'feedbackProject#22': 'Mansur Rasulov, Responsável de Média da CINDX, explica o que o levou a fazer parte da equipa da CINDX',
    'feedbackProject#23': 'Sadie Hutton',
    'feedbackProject#24': 'Sadie Hutton, Consultora da CINDX, explica como a plataforma CINDX é diferente de outras plataformas de negociação automatizadas',
    'feedbackProject#25': 'Graham Doggart',
    'feedbackProject#26': 'Graham Doggart, Consultor da CINDX, fala sobre os pontos fortes da plataforma CINDX',
    'feedbackProject#27': 'Alina Vardanian',
    'feedbackProject#28': 'Gestora de Conteúdos',
    'feedbackProject#29': 'Alina Vardanian, Gestora de Conteúdos da CINDX, fala sobre o espírito de equipa e porque adora o seu trabalho',
    'feedbackProject#30': 'Bogdan Fiedur',
    'feedbackProject#31': 'Consultor CINDX',
    'feedbackProject#32': 'Bogdan Fiedur, Consultor da CINDX, explica o que separa o projeto CINDX dos outros projetos de ICO',
    'feedbackProject#33': 'Jason King',
    'feedbackProject#34': 'Jason King, Diretor Comercial, explica o que o atraiu para a CINDX e fala sobre as vantagens cruciais do projeto',

    'mediaNews#1': 'Média',
    'mediaNews#2': 'Notícias',
    // Media
    'mediaNews#1_1': 'CINDX Aims to Democratize the Modern Financial System',
    'mediaNews#1_2': 'Even as investors in the cryptocurrency space recognize that they are at the forefront of a new financial revolution, adoption by the general populace is yet to occur. While 3rd parties are slowly entering the space in the form of hedge funds and other investors, very few individuals seem to have taken the step to invest in cryptocurrencies on their own.',
    'mediaNews#1_3': 'CINDX Announces Plans For ICO Pre-Sale Amidst Release Of Revolutionary Crypto Trading Hub That Allows Users To Follow Expert Traders',
    'mediaNews#1_4': 'CINDX takes its business seriously with particular attention and cares to legal matters and has taken great pains to ensure that CINDX is as compliant as possible with global regulations.',
    'mediaNews#1_5': 'How CINDX is Democratizing the Modern Financial System',
    'mediaNews#1_6': 'CINDX is a new platform that is making crypto trading easier, more secure, and more accessible. With this platform, it’s possible to have your funds traded without high fees or minimum investments, with the added security and transparency of blockchain technology.',
    'mediaNews#1_7': 'CINDX is making crypto trading easier, more secure, and more accessible.',
    'mediaNews#1_8': 'Cryptocurrency and blockchain technology have been slated as powerful tools capable of fueling a global financial revolution. There are myriad opportunities to invest in the crypto space, and yet, very few individuals have undertaken the steps necessary to invest.',
    'mediaNews#1_9': 'CINDX Announces Plans Release Of Revolutionary Crypto Trading Hub',
    'mediaNews#1_10': 'The CINDX platform creates a complete ecosystem for cryptocurrency trading that is favorable to all the participants of the market and offers solutions to existing pain points.',
    'mediaNews#1_11': 'CINDX Announces Plans For ICO Pre-Sale',
    'mediaNews#1_12': 'CINDX made headlines this week with the announcement that they will be opening their ICO Pre-Sale in late August after investors interest in the ICO peaks to new levels.',
    'mediaNews#1_13': 'CINDX Will Be Opening ICO Pre-Sale in late August',
    'mediaNews#1_14': 'The CINDX Crypto trading platform has a myriad of features and benefits that haven’t been seen in other platforms to date.',
    'mediaNews#1_15': '5 Tips from CINDX Crypto Assets Management Hub: How to Avoid Being Cheated',
    'mediaNews#1_16': 'The team behind the CINDX crypto assets management hub has created a helpful set of guidelines on how not to become victims of unfair play, so you can learn what should be primarily taken into account when evaluating ICOs before investing in them.',
    'mediaNews#1_17': 'CINDX Crypto Asset Management Hub Adopts Bancor Protocol',
    'mediaNews#1_18': 'CINDX is delighted to announce that a number of new integrations with top industry players are underway, each of which will make the life of the users of the platform easier and richer. These new integrations include the decision to adopt the Bancor protocol to provide continuous liquidity for the CINDX platform.',
    // News
    'mediaNews#2_1': 'CINDX meets Ian Balina',
    'mediaNews#2_2': 'CINDX pitch to the one of the TOP10 crypto gurus in the world in the Cryptobazar event.',
    'mediaNews#2_3': 'CINDX took part in Moscow ICO Summit 2018',
    'mediaNews#2_4': 'CINDX team introduced the project to the Russian crypto community during ICO Summit event.',
    'mediaNews#2_5': 'How CINDX is ensuring legal compliance',
    'mediaNews#2_6': 'Our company is registered in Estonia. Why? The answer is simple — the authorities of Estonia have created a strong and innovative legal infrastructure...',
    'mediaNews#2_7': 'Keith Teare Co-founder of Accelerated Digital Ventures and Founding Shareholder in TechCrunch',
    'mediaNews#2_8': 'We continue to introduce CINDX advisers, find out what they...',
    'mediaNews#2_9': 'Meet world\'s first financial crypto social network',
    'mediaNews#2_10': 'Every day our team takes one more step on the way to creation and start...',
    'mediaNews#2_11': 'Denis Eskenazi CINDX Product Marketing Director',
    'mediaNews#2_12': 'We continue to tell about the CINDX team and each team member’s professional experience. Please, read about Denis Eskenazi...',
    'mediaNews#2_13': 'CINDX crypto currency exchange license',
    'mediaNews#2_14': 'Our company in Estonia has received Crypto Currency Exchange License. This allows CINDX to provide fiat-to-crypto exchange services. This licence is issued...',
    'mediaNews#2_15': 'Austin Kimm Co-founder of Crypterium & CINDS Adviser',
    'mediaNews#2_16': 'We continue to introduce CINDX advisers, find out what they are proud...',
    'mediaNews#2_17': 'The strategic meeting of the international CINDX team',
    'mediaNews#2_18': 'Every day our team takes one more step on the way to creation and start of the CINDX platform. Our work...',
    'mediaNews#2_19': 'Artur Shamalov CINDX Investment Director',
    'mediaNews#2_20': 'We continue to introduce the CINDX team. Our next article is about Artur Shamalov, a skilled...',
    'mediaNews#2_21': 'The issuance of CINX tokens',
    'mediaNews#2_22': 'The issuance of CINX tokens will be carried out according to the license of The Estonian Financial Supervisory Authority (EFSA). What is a token...',
    'mediaNews#2_23': '"Amarpreet Singh Co-Founding Member of Malta Blockchain Association & CINDX adviser"',
    'mediaNews#2_24': 'We at CINDX are incredibly proud to present our advisers, tell the world about their achievements and why they have decided to become a part of the CINDX...',
    'mediaNews#2_25': 'CINDX meets Vangoo Capital Partners Fund',
    'mediaNews#2_26': 'Today we have welcomed Kevin Shang from Vangoo Capital Partners and his colleagues in our office. We have discussed business partnership opportunities in order to attract investors from the Asian region.',
    'mediaNews#2_27': '"Mofassair Hossain CINDX Chief Marketing Officer."',
    'mediaNews#2_28': 'We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly excited about...',
    'mediaNews#2_29': 'How CINDX ensures safety for its users - KYC',
    'mediaNews#2_30': 'Every crypto enthusiast knows that a KYC procedure is necessary in order to protect investors against fraudulent actions of the third...',
    'mediaNews#2_31': 'Philip Staehelin 25 Years of Consulting and Entrepreneurial Experience',
    'mediaNews#2_32': 'We continue our regular series of articles dedicated to introducing CINDX advisers. The next item is about Philip Staehelin.',
    'mediaNews#2_33': 'CINDX meets 9coin Digital Asses Exchange',
    'mediaNews#2_34': 'The CINDX team continues active work on building relationships with various international companies. One of the most important directions of business...',
    'mediaNews#2_35': 'Jason King Interim Chief Commercial Officer',
    'mediaNews#2_36': 'The core of any great project is always people who make the unique idea come true. We would like to tell about...',
    'mediaNews#2_37': 'CINDX Presents the project during RICLUB private investors meeting',
    'mediaNews#2_38': 'CINDX has successfully passed the due diligence procedure requested by RICLub and was one of the few projects...',
    'mediaNews#2_39': 'Sofja Pevzner CINDX Personal Data Officer',
    'mediaNews#2_40': 'We continue to introduce our team and tell about what inspires our colleagues to work with CINDX. Please read about...',
    'mediaNews#2_41': 'Tyler Sanford 8+ years digital marketing in Yelp, Zenefits',
    'mediaNews#2_42': 'We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become a part of the CINDX team. In this...',
    'mediaNews#2_43': 'CINDX - Key points to observe',
    'mediaNews#2_44': 'The CINDX project is a valuable business venture with the features that are critically relevant for its participants. In this article we talk about Strengths...',
    'mediaNews#2_45': 'Airat Shayhulov CINDX Head of Quantitative Research.',
    'mediaNews#2_46': 'In “TEAM” series of the articles, we tell about people who every day participates in the creation...',
    'mediaNews#2_47': 'CINDX license of the financial consultant',
    'mediaNews#2_48': 'CINDX has obtained a termless operating licence (the FFA 000254 license) that gives the right to operate as a financial institution...',
    'mediaNews#2_49': '"Graham Doggart 20 Years of Enterprise Development and Fintech Marketing Compliance"',
    'mediaNews#2_50': 'We continue our regular series of articles dedicated to introducing CINDX advisers. The next item...',
    'mediaNews#2_51': 'CINDX continues the roadshow in China!',
    'mediaNews#2_52': 'The CINDX team is glad to announce participation as a Golden Sponsor of Borderless Blockchain Technology Summit 2018, which...',
    'mediaNews#2_53': 'Ibraghim Haniev CINDX Tech Lead',
    'mediaNews#2_54': 'Get to know more about the CINDX team! The core of any great project is always people who make the unique ideas come true...',
    'mediaNews#2_55': 'Sadie Hutton 25 Years in Senior Management and Management Consulting',
    'mediaNews#2_56': 'Like any global project, we understand the importance of professional help and advice. We continue to tell the stories of...',
    'mediaNews#2_57': 'CINDX.talk - a service that will help people become wiser in taking financial decisions',
    'mediaNews#2_58': 'The current digital-world related to the crypto industry is getting crowded with mind-charming digital solutions...',
    'mediaNews#2_59': '"Val Jerdes CINDX Product Director"',
    'mediaNews#2_60': 'We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly...',
    'mediaNews#2_61': 'Bogdan Fiedur Blockchain and cryptocurrency expert, investor, entrepreneur',
    'mediaNews#2_62': 'We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become...',
    'mediaNews#2_63': 'Welcome to CINX Token Distribution – it’s not an ICO; it’s an STO',
    'mediaNews#2_64': 'In this article, we want to make it clear why CINDX chose to hold a Security Token Offering (STO) instead of an Initial...',
    'mediaNews#2_65': 'CINDX celebrates the “AA” Rating from Top ICO List Audit!',
    'mediaNews#2_66': 'The results of CINDX’s sincerity to make meaningful changes in people’s ambitions via a unique business model just got appreciated...',
    'mediaNews#2_67': 'CINDX Weekly digest (30.07.18 - 05.08.18)',
    'mediaNews#2_68': 'The CINDX team is very excited to share the results of our work for the last week 30.07.18 - 05.08.18!',
    'mediaNews#2_69': 'Virtual Currency Wallet Services',
    'mediaNews#2_70': 'CINDX believes that being fluent in legal issues and having a clean, confident and clear legal status is of utmost importance. At the moment, CINDX is going...',
    'mediaNews#2_71': 'How CINDX Influences Crypto Trading',
    'mediaNews#2_72': 'How to master the crypto market movements and turn them in one’s favor? This is where CINDX’s effective business model comes into play. Learn more about CINDX on our Medium!',
    'mediaNews#2_73': 'CINDX Weekly digest (06.08.18 - 12.08.18)',
    'mediaNews#2_74': 'CINDX continues its regular column - Weekly Digest. We are excited to share the recent achievements of our project! Enjoy your time reading!',
    'mediaNews#2_75': 'CINDX gets 5.0 rating on TrackICO!',
    'mediaNews#2_76': 'CINDX continues getting approval from the largest and the most credible rating services. The week has hardly passed after...',
    'mediaNews#2_77': '"David Gutierrez Investment Relations Officer"',
    'mediaNews#2_78': 'CINDX is very serious about taking people on crew and proud to introduce them. This article is dedicated to David Gutierrez, CINDX Investment Relations Officer',
    'mediaNews#2_79': 'ICObench gives 4.8 to CINDX',
    'mediaNews#2_80': 'The CINDX project has already gained the highest mark of  ‘AA’ from Top ICO List and got a 5.0 rating from TrackICO. Now, we are proud to share...',
    'mediaNews#2_81': 'Dip your Toe in Crypto',
    'mediaNews#2_82': 'It is never late to change your mind. It’s no surprise that Wall Street bankers change their minds in favour of crypto. Enjoy reading CINDX review on the current market situation!',
    'mediaNews#2_83': 'Yuriy Avdeev, CEO of the CINDX project',
    'mediaNews#2_84': 'Enjoy reading what inspired Yuriy Avdeev to create a project that will help all participants of the crypto market to be profitably engaged - CINDX.',
    'mediaNews#2_85': 'Weekly digest (13.08.18 - 19.08.18)',
    'mediaNews#2_86': 'CINDX continues its regular Weekly Digest column. We are excited to share our project’s progress and the most recent achievements! We are glad to remind you that CINDX security token Pre-sale starts this Sunday. Don\'t miss!',

    'teamAdvisersPartners#1': 'Equipa com +50 membros',
    'teamAdvisersPartners#2': 'Consultores',
    'teamAdvisersPartners#3': 'Os nossos Parceiros',
    // teamInfo
    'teamAdvisersPartners#4': 'Yuriy Avdeev',
    'teamAdvisersPartners#5': 'Diretor Executivo',
    'teamAdvisersPartners#6': '13 anos em empreendedorismo',
    'teamAdvisersPartners#7': '9 participações em capital de risco',
    'teamAdvisersPartners#8': '2 milhões $ em gestão de criptomoedas',
    'teamAdvisersPartners#9': 'Val Jerdes',
    'teamAdvisersPartners#10': 'Diretor de Produto',
    'teamAdvisersPartners#11': '20 anos em empreendedorismo',
    'teamAdvisersPartners#12': '3 lançamentos bem-sucedidos',
    'teamAdvisersPartners#13': 'Retorno de 4x para portfólios',
    'teamAdvisersPartners#14': 'Mofassair Hossain',
    'teamAdvisersPartners#15': 'Diretor de Marketing',
    'teamAdvisersPartners#16': 'Investidor e Consultor em mais de 15 ICO',
    'teamAdvisersPartners#17': 'Consultor de topo em ICO Bench',
    'teamAdvisersPartners#18': 'Membro GBAP',
    'teamAdvisersPartners#19': 'Artur Shamalov',
    'teamAdvisersPartners#20': 'Diretor de Investimentos',
    'teamAdvisersPartners#21': '15 anos em empreendedorismo',
    'teamAdvisersPartners#22': '5000 clientes em mixcart.ru',
    'teamAdvisersPartners#23': 'mail.ru investiu em dc-daily.ru',
    'teamAdvisersPartners#24': 'Denis Eskenazi',
    'teamAdvisersPartners#25': 'Diretor de Marketing de Produto',
    'teamAdvisersPartners#26': '7 anos em empreendedorismo',
    'teamAdvisersPartners#27': '2 milhões $ atraídos para os clientes',
    'teamAdvisersPartners#28': '10 anos em gestão de marcas',
    'teamAdvisersPartners#29': 'Ibraghim Haniev',
    'teamAdvisersPartners#30': 'Responsável Técnico',
    'teamAdvisersPartners#31': '6 anos em empreendedorismo',
    'teamAdvisersPartners#32': '+200 websites desenvolvidos',
    'teamAdvisersPartners#33': 'Experiência em Segurança da Informação',
    'teamAdvisersPartners#34': 'Airat Shaikhulov',
    'teamAdvisersPartners#35': 'Head of Quantitative Research',
    'teamAdvisersPartners#36': 'Dr of science at MSU',
    'teamAdvisersPartners#37': 'Aton-line navigator developer',
    'teamAdvisersPartners#38': 'Head of algorithmic trading',
    'teamAdvisersPartners#39': 'Sofja Pevzner',
    'teamAdvisersPartners#40': 'Responsável de Dados Pessoais',
    'teamAdvisersPartners#41': '5 anos em empreendedorismo',
    'teamAdvisersPartners#42': 'Autorização emitida pelo gabinete de BC da Estónia',
    'teamAdvisersPartners#43': '8 anos de experiência jurídica',
    'teamAdvisersPartners#44': 'Dave Gutierrez',
    'teamAdvisersPartners#45': 'Responsável de Relações de Investimentos',
    'teamAdvisersPartners#46': '5 anos no leasing de aeronaves',
    'teamAdvisersPartners#47': '3 anos em aconselhamento de investimento',
    'teamAdvisersPartners#48': '2 anos em investimento no estrangeiro',
    'teamAdvisersPartners#49': 'Jelena Karzetskaja',
    'teamAdvisersPartners#50': 'Responsável de Conformidade',
    'teamAdvisersPartners#51': 'detém vários cursos em direito',
    'teamAdvisersPartners#52': 'Experiência jurídica desde 1997',
    'teamAdvisersPartners#53': 'Esferas legais: lei internacional',
    'teamAdvisersPartners#54': 'Wang Dong',
    'teamAdvisersPartners#55': 'Especialista no mercado de Blockchain chinês',
    'teamAdvisersPartners#56': '3 anos em php/JavaScript',
    'teamAdvisersPartners#57': '5 anos em SEO/SMM/meios de média',
    'teamAdvisersPartners#58': '2 anos no desenvolvimento de Blockchain e venda de tokens na China',
    // Consultores
    'teamAdvisersPartners#59': 'Keith Teare',
    'teamAdvisersPartners#60': 'Fundador e Presidente Executivo da Accelerated Digital Ventures',
    'teamAdvisersPartners#61': 'Consultor para a ICOBox, Crypterium, EnergiMine, etc.',
    'teamAdvisersPartners#62': 'Fundador e acionista da TechCrunch',
    'teamAdvisersPartners#63': 'Sou o Presidente Executivo e Presidente do Comité de Investimento na Accelerated Digital Ventures - uma empresa de capital de risco no Reino Unido. Sou nascido e criado no Reino Unido.',
    'teamAdvisersPartners#64': 'Anteriormente, fui fundador e sócio na Archimedes Labs em Palo Alto, na Califórnia. Adoro trabalhar com fundadores, equipas, designers e engenheiros para criar produtos, contar histórias e transformá-los em realidade. Fui fundador e cofundador de muitas empresas, no início dos anos 80. Algumas foram vendidas com sucesso, outras sujeitas a OPA.',
    'teamAdvisersPartners#65': 'Duas das minhas empresas eram "unicórnios" - avaliadas por outros em mais de mil milhões $. Sempre me foquei no ponto de mudança. Nos anos 80, redes e bases de dados. No período entre 1994 e 1998, acesso à Internet. Entre 1998 e 2010 foram os Serviços e Conteúdos de Internet, Aplicações de Consumo Móveis. Desde 2017, a área de Blockchain.',
    'teamAdvisersPartners#66': 'Carreira e projetos: TechCrunch, Accelerated Digital Ventures, cScape, EasyNet, Cyberia, RealNames, Venture Network, ICOBox, Crypterium, R/Block, Fluz, EnergiMine, Archimedes Labs e CINDX',
    'teamAdvisersPartners#67': 'Austin Kimm',
    'teamAdvisersPartners#68': 'Diretor Executivo na International Financial Services',
    'teamAdvisersPartners#69': '+30 anos de experiência em serviços financeiros',
    'teamAdvisersPartners#70': 'Criou empresas com um valor de 500 milhões $',
    'teamAdvisersPartners#71': 'Diretor Executivo experiente com resultados provados em serviços financeiros, com enfoque particular na criação de negócios de seguros em mercados em desenvolvimento, onde criei empresas de sucesso com uma avaliação atual superior a 500 milhões $',
    'teamAdvisersPartners#72': ' A experiência mais recente é na Rússia (10 anos), assim como outros cargos na gestão sénior em áreas não afetas aos seguros, incluindo Diretor Executivo da maior plataforma de emprego digital da Rússia, a Workle, e uma grande variedade de cargos de nível C em startups de fintech, incluindo o Crypterium, o primeiro criptobanco digital do mundo.',
    'teamAdvisersPartners#73': 'Carreira e projetos: Aviva, Commercial Union UK, Reinaissance Insurance, Kimm Health & Leisure Ltd, Workle, Crypterium, CryptoIndex, CINDX',
    'teamAdvisersPartners#74': 'Philip Staehelin',
    'teamAdvisersPartners#75': '25 anos de experiência em consultoria em empreendedorismo',
    'teamAdvisersPartners#76': '500 milhões $ em negócios de pagamento alternativos sob liderança',
    'teamAdvisersPartners#77': 'Mentor de +200 startups de 20 países',
    'teamAdvisersPartners#78': 'Sou um inovador e um líder que mistura o otimismo contagiante com o realismo pragmático. Encontro a oportunidade onde niguém a vê.',
    'teamAdvisersPartners#79': 'Consegui alavancar a minha capacidade de "ver as coisas de forma diferente" e "fazer acontecer coisas" em ambientes empresariais, de consultoria e de startups - tudo isto proporciona novas perspetivas alargadas que alimentam novas ideias transformadoras.',
    'teamAdvisersPartners#80': 'Encontrar soluções para desafios complicados é o que me motiva a sair da cama todos os dias.',
    'teamAdvisersPartners#81': 'Carreira e projetos: Roland Berger, Dot Glasses, Transparency International, StartupYard, Bethereum, Gjirafa Inc, Accenture, CINDX',
    'teamAdvisersPartners#82': 'Amarpreet Singh',
    'teamAdvisersPartners#83': 'Consultor Sénior na Global Blockchain Foundation',
    'teamAdvisersPartners#84': 'Experiência na Microsoft, The World Bank e Airbus',
    'teamAdvisersPartners#85': 'Membro de Conselho Consultor de projetos de Blockchain',
    'teamAdvisersPartners#86': 'Entusiasta de Tecnologia/Digital e profissional maduro com anos de experiência no setor da Tecnologia, nas áreas de operações, consultoria e inovação.',
    'teamAdvisersPartners#87': 'É um especialista em Cloud certificado (Microsoft e AWS). Conhecido pela sua versatilidade e flexibilidade. Excelentes capacidades de análise, estratégia e liderança - um jogador de equipa no seu melhor.',
    'teamAdvisersPartners#88': 'Especialidades: Consultoria em Tecnologia, Operações, Computação em Cloud, Fintech, Inovação, ERP, Machine Learning, Gestão de Contas, Desenvolvimento de Parcerias, Desenvolvimento de Negócios e Estratégia.',
    'teamAdvisersPartners#89': 'Amarpreet Singh possui um trabalho muito diversificado, assim como uma vasta formação académica. Possui três Mestrados e viveu/trabalhou/estudou na Índia, Singapura, França, China, África do Sul, Coreia e Canadá.',
    'teamAdvisersPartners#90': 'Carreira e projetos: Microsoft, The World Bank, Airbus, TokenAsia Platform, GOeurika, CINDX',
    'teamAdvisersPartners#91': 'Tyler Sanford',
    'teamAdvisersPartners#92': '8 anos em Marketing Digital na Yelp and Zenefits',
    'teamAdvisersPartners#93': '12 ICO, mais de 225 milhões $ angariados',
    'teamAdvisersPartners#94': 'Utilizador pioneiro de Blockchain',
    'teamAdvisersPartners#95': 'Crescer como atleta deu-me capacidades que consegui aplicar às minhas carreiras e vida pessoal.',
    'teamAdvisersPartners#96': 'Tive a felicidade de ver os resultados que advêm daquele esforço suplementar, enquanto aprendo a lidar com os altos e baixos que acompanham todas as carreiras pessoais.',
    'teamAdvisersPartners#97': 'Sou um indivíduo com uma grande auto-motivação, sempre à procura de continuar o meu crescimento de conhecimentos e talentos, em todos os aspetos dos negócios.',
    'teamAdvisersPartners#98': 'Sempre pronto para um desafio, a minha motivação tem origem na superação de obstáculos com vista a alcançar os meus objetivos.',
    'teamAdvisersPartners#99': 'Carreira e projetos: IPG Holdings, DataBlockChain, TraXion by Puma Technologies, ELYSIAN, Etherinc, FTEC Foundation, CINDX',
    'teamAdvisersPartners#100': 'Philip Staehelin',
    'teamAdvisersPartners#101': '25 anos de experiência em consultoria em empreendedorismo',
    'teamAdvisersPartners#102': '500 milhões $ em negócios de pagamento alternativos sob liderança',
    'teamAdvisersPartners#103': 'Mentor de +200 startups de 20 países',
    'teamAdvisersPartners#104': 'Sou um inovador e um líder que mistura o otimismo contagiante com o realismo pragmático. Encontro a oportunidade onde niguém a vê.',
    'teamAdvisersPartners#105': 'Consegui alavancar a minha capacidade de "ver as coisas de forma diferente" e "fazer acontecer coisas" em ambientes empresariais, de consultoria e de startups - tudo isto proporciona novas perspetivas alargadas que alimentam novas ideias transformadoras.',
    'teamAdvisersPartners#106': 'Encontrar soluções para desafios complicados é o que me motiva a sair da cama todos os dias.',
    'teamAdvisersPartners#107': 'Carreira e projetos: Roland Berger, Dot Glasses, Transparency International, StartupYard, Bethereum, Gjirafa Inc, Accenture, CINDX',
    'teamAdvisersPartners#108': 'Senior Adviser of Global Blockchain Foundation',
    'teamAdvisersPartners#109': 'Experience in Microsoft, The World Bank and Airbus',
    'teamAdvisersPartners#110': 'Advisery Board Member of Blockchain projects',
    'teamAdvisersPartners#111': 'Technology/Digital enthusiast and a seasoned professional with years of experience in Tech industry – operations, consulting and innovation.',
    'teamAdvisersPartners#112': 'He is a certified Cloud (Microsoft and AWS) specialist. Known for versatility and flexibility. Excellent analytic, strategic, leadership skills and a team player at its best.',
    'teamAdvisersPartners#113': 'Specialties: Technology Consulting, Operations, Cloud Computing, Fintech, Innovation, ERP, Machine Learning, Account Management, Partner Development, Business Development and Strategy',
    'teamAdvisersPartners#114': 'Amarpreet Singh has a very diversified work and educational background. He holds three Masters degrees and has lived/worked/studied in India, Singapore, France, China, South Africa, Korea, Canada.',
    'teamAdvisersPartners#115': 'Career and projects: Microsoft, The World Bank, Airbus, TokenAsia Platform, GOeurika, CINDX',
    'teamAdvisersPartners#116': 'Tyler Sanford',
    'teamAdvisersPartners#117': '8 anos em Marketing Digital na Yelp and Zenefits',
    'teamAdvisersPartners#118': '12 ICO, mais de 225 milhões $ angariados',
    'teamAdvisersPartners#119': 'Utilizador pioneiro de Blockchain',
    'teamAdvisersPartners#120': 'Crescer como atleta deu-me capacidades que consegui aplicar às minhas carreiras e vida pessoal.',
    'teamAdvisersPartners#121': 'Tive a felicidade de ver os resultados que advêm daquele esforço suplementar, enquanto aprendo a lidar com os altos e baixos que acompanham todas as carreiras pessoais.',
    'teamAdvisersPartners#122': 'Sou um indivíduo com uma grande auto-motivação, sempre à procura de continuar o meu crescimento de conhecimentos e talentos, em todos os aspetos dos negócios.',
    'teamAdvisersPartners#123': 'Sempre pronto para um desafio, a minha motivação tem origem na superação de obstáculos com vista a alcançar os meus objetivos.',
    'teamAdvisersPartners#124': 'Carreira e projetos: IPG Holdings, DataBlockChain, TraXion by Puma Technologies, ELYSIAN, Etherinc, FTEC Foundation, CINDX',
    'teamAdvisersPartners#125': 'Bogdan Fiedur',
    'teamAdvisersPartners#126': 'Especialista, investidor e empreendedor em Blockchain e criptomoedas',
    'teamAdvisersPartners#127': 'Cofundador da bitJob e Presidente da Blockchainexperts.io',
    'teamAdvisersPartners#128': 'Consultor de ICO, Especialista da ICOBench',
    'teamAdvisersPartners#129': 'Bogdan Fiedur é um criador de contratos inteligentes, criptoinvestidor, empreendedor e Presidente da http://blockchainexperts.io. Ele tem mais de 20 anos de experiência de TI na construção de websites de comércio eletrónico e está envolvido no desenvolvimento de Blockchain desde há 3 anos.',
    'teamAdvisersPartners#130': 'Bogdan é também um consultor de ICO, que trabalhou com 20 ICO de sucesso até à data, e está profundamente envolvido na oferta de apresentações e formações sobre Blockchain e programação de contratos inteligentes na sua criptocomunidade local de Winnipeg.',
    'teamAdvisersPartners#131': 'Agora está focado no setor de Blockchain e oferece aconselhamento, serviços de consultoria e ligações a especialistas de Blockchain. Mais recentemente, Bogdan foi cofundador da "Bitjob", uma plataforma independente de Blockchain para estudantes, e participou em vários projetos de ICO como membro de equipa, como o PayPie.com.',
    'teamAdvisersPartners#132': 'Carreira e projetos: US Blockchain Association, Tuurnt, Trends Project, BiNeuro, Zichain, Graphen Tech, CyClean, Swachhcoin, CINDX',
    'teamAdvisersPartners#133': 'Graham Doggart',
    'teamAdvisersPartners#134': '20 anos no desenvolvimento de empresas, conformidade em marketing de fintech',
    'teamAdvisersPartners#135': 'Executou campanhas com um valor de 100 milhões $',
    'teamAdvisersPartners#136': 'Consultor em +10 projetos de Blockchain este ano',
    'teamAdvisersPartners#137': 'Sou o Presidente de um projeto Stealth Cryptocurrency Project e cofundador, além de Responsável de Estratégia, na Dynamic Abundance, uma consultora de Blockchain e Fintech, desde 2012.',
    'teamAdvisersPartners#138': 'A minha especialidade é a estruturação e criação de pacotes de ofertas de tokens, e trabalhei com vários projetos internacionais de Blockchain, criptomoedas e ICO.',
    'teamAdvisersPartners#139': 'Durante mais de 20 anos, forneci consultadoria de gestão de tecnologias, aconselhamento de conformidade jurídica e financeira, estratégias de crescimento, assim como o design e autoria de materiais.',
    'teamAdvisersPartners#140': 'Carreira e projetos: Stealth Cryptocurrency Project, Dynamic Abundance, ELYSIAN, Fox Trading FX, Profede, Worltdopoly, CINDX',
    'teamAdvisersPartners#141': 'Sadie Hutton',
    'teamAdvisersPartners#142': '25 anos em gestão sénior e consultoria de gestão',
    'teamAdvisersPartners#143': 'Angariadora de milhões, com campanhas a superar os 75 milhões £',
    'teamAdvisersPartners#144': 'Consultora em 8 projetos de ICO',
    'teamAdvisersPartners#145': 'Sou a fundadora da Dynamic Abundance, uma consultora de Blockchain.',
    'teamAdvisersPartners#146': 'Preferindo uma abordagem de "meter as mãos na massa", sou especialista em análises de ICO, gestão de projetos e todos os aspetos principais do processo de ICO. Possuo competências em gestão e crescimento de negócios, o que me permite acompanhar um projeto desde o nascimento ao lançamento. Gosto de resolver problemas por natureza e assumo pessoalmente todos os projetos em que me envolvo. Gosto de ganhar!',
    'teamAdvisersPartners#147': 'Com mais de 20 anos de experiência em gestão, construí uma rede poderosa, faço aconselhamento ativo nas áreas financeira, tecnológica, vendas, marketing e garantia de qualidade para projetos de Blockchain de alto nível.',
    'teamAdvisersPartners#148': 'Carreira e projetos: Dynamic Abundance, ELYSIAN, Worldopoly, Confidential ICO, Fox Trading FX, Profede, Market Digital, CINDX',
    'teamAdvisersPartners#149': 'Jason King',
    'teamAdvisersPartners#150': '20 anos de experiência executiva',
    'teamAdvisersPartners#151': 'Liderou operações empresariais em 30 países',
    'teamAdvisersPartners#152': 'Responsável por 500 milhões $ L&P',
    'teamAdvisersPartners#153': 'Durante mais de 20 anos, Jason King tem sido um executivo da área da tecnologia, média e telecomunicações, envolvido na estruturação e mediação de acordos comerciais, negociando vitórias, construindo mercados e posicionando organizações para o sucesso.',
    'teamAdvisersPartners#154': 'Muitos destes desafios levaram-me a restruturações de sucesso e cargos de recuperação - a liderança deve construir as equipas certas para alcançar os objetivos mais rentáveis.',
    'teamAdvisersPartners#155': 'Jason possui uma vasta experiência em diferentes campos, incluindo Gestão de Negócios e Operações, Planeamento Estratégico e Financeiro, assim como o setor das criptomoedas e Blockchain.',
    'teamAdvisersPartners#156': 'Jason has either worked or has led business directly in over 30 countries and has previously held commercial P&L responsibilities in the $500M-$1B range.',
    'teamAdvisersPartners#157': 'Motti Peer',
    'teamAdvisersPartners#158': 'Cofundador da Blonde 2.0, agência de RP global premiada',
    'teamAdvisersPartners#159': 'Fundador de várias empresas, nos setores da segurança e financeiro.',
    'teamAdvisersPartners#160': 'Motti é uma das principais forças de RP para Blockchain, criptomoedas, startups e capitais de risco',
    'teamAdvisersPartners#161': 'Motti fundou várias empresas, nos setores da segurança e financeiro. Ele possui muitos anos de experiência como gestor de ativos monetários e fundos de risco, além de possuir um MBA em Finança e Marketing pela Universidade de Manchester, e também um Bacharelato em Gestão de Empresas BA pela Universidade Fairleigh Dickinson.',
    'teamAdvisersPartners#162': 'É Codiretor Executivo da Blonde 2.0, uma agência de RP global premiada, também descrita como uma startup que faz "Mexer e Agitar" a nação pela Forbes. Como Codiretor Executivo da Blonde 2.0, ele é responsável pelo tratamento dos aspetos de Relações Públicas, juntamente com as áreas de estratégia e gestão de crises.',
    'teamAdvisersPartners#163': 'Com uma equipa de 35 profissionais, a Blonde 2.0 é uma das principais forças de RP para Blockchain, criptomoedas, startups e capitais de risco.',
    'teamAdvisersPartners#164': 'Leonard Grayver',
    'teamAdvisersPartners#165': 'Sócio na Greenberg, Whitcombe & Takeuchi',
    'teamAdvisersPartners#166': 'Representou mais de 400 startups',
    'teamAdvisersPartners#167': 'Angariou mais de 18 milhões USD para a sua startup, quando era estudante de direito',
    'teamAdvisersPartners#168': 'Leonard Grayver nasceu na antiga URSS e mudou-se para os EUA com os seus pais, ainda em criança. Enquanto frequentava a faculdade de direito, Leonard criou uma startup e angariou mais de 18 milhões $ para financiamento.',
    'teamAdvisersPartners#169': 'A startup não sobreviveu, mas desde então Leonard ajudou mais de 400 startups.',
    'teamAdvisersPartners#170': 'No geral, Leonard tem mais de 10 anos de experiência com financiamento de capitais de risco, estruturação de fundos e diligência prévia (representando ambas as partes). O seu conselho a todos os empreededores; não sigam tendências, sigam os seus interesses.',

    'joinTokenPreSale#1': 'Junte-se à Pré-venda de Tokens!',
    'joinTokenPreSale#2': 'Aderir à Pré-venda',
    'joinTokenPreSale#3': 'Teste MVP ',
    'joinTokenPreSale#4': 'Sede',
    'joinTokenPreSale#5': 'Harjumaa, Erika 14,',
    'joinTokenPreSale#6': 'Talinn, 10416, Estonia',
    'joinTokenPreSale#7': 'Questões empresariais | hello@cindx.io',
    'joinTokenPreSale#8': 'Legal Disclaimer',
    'joinTokenPreSale#9': 'Desenvolvimento e Marketing',
    'joinTokenPreSale#10': 'Presnenskaya naberezhnaya, 8 building 1,',
    'joinTokenPreSale#11': 'Moscow, 123112, Russia',
    'joinTokenPreSale#12': 'Carreiras | Junte-se à nossa equipa |',
}

export default pt