// Турецкий
const tr = {
    'mainBlock#1': `Kripto döviz yatırımları artık`,
    'mainBlock#2': `Basit, Güvenli ve Hızlı.`,
    'mainBlock#3': `Token Varlıkları Satışımıza Katılın`,

    'icoInfo#1': `Kabul ettiklerimiz:`,
    'icoInfo#2': `Sabit Limit:`,
    'icoInfo#3': `Esnek Limit:`,
    'icoInfo#4': `Listeleme Anlaşmalarını İmzalanan Taraf:`,

    'menu#1': `TANITIM`,
    'menu#2': `SUNUM`,
    'menu#3': `BROŞÜR`,
    'menu#4': `FİNANSAL MODEL`,
    'menu#5': `YASAL BELGELER`,
    'menu#6': `TR`,
    'menu#7': `Ürün`,
    'menu#8': `Satış Bilgileri`,
    'menu#9': `Ekip`,
    'menu#10': `Resmi Belgeler`,
    'menu#11': `MVP'yi Test Edin`,

    'mailForm#1': `Yanlış Email`,
    'mailForm#2': `gönderiliyor ..`,
    'mailForm#3': `Bu işlem geçerli değil veya zaten geçerliydi, yeniden deneyin`,
    'mailForm#4': `Epostanız başarıyla gönderildi`,
    'mailForm#5': `bir hata oluştu, yeniden deneyin`,
    'mailForm#6': `GDPR Uyumluluğu`,
    'mailForm#7': `Üyelik formu ve MTB prosedürü ile bize ilettiğiniz kişisel veriler, GDRP ile tam uyumlu bir şekilde toplanacaktır.`,
    'mailForm#8': `Bu projenin Veri Koruma Görevlisi, Bayan Sofja Pevzner-Belositski'dir. İletişim bilgileri: dpo@cindx.io. Verileri toplanmış herhangi bir kişi, herhangi bir zamanda, veri koruma ile ilgili herhangi bir talebi hakkında doğrudan Veri Koruma Sorumlusu ile iletişime geçebilir.`,
    'mailForm#9': `Üyelik formu ve MTB prosedürü ile bize ilettiğiniz kişisel verileriniz, ortaklarımızla paylaşılacaktır:`,
    'mailForm#10': `ICO Promosyonu`,
    'mailForm#11': `Gizlilik Politikası`,
    'mailForm#12': `Sum & Substance`,
    'mailForm#13': `Varsayılan olarak, üyelerin sağladığı kişisel veriler, sisteme kayıt olmalarının ardından 5 yıl süreyle CINDX, ICO Promo ve Sum & Substance tarafından saklanır.`,
    'mailForm#14': `Bu gizlilik politikasını kabul etmiyorsanız, lütfen sitemizi kullanmayın.`,
    'mailForm#15': `Sitemizi kullanarak, tarafımıza kişisel bilgilerinizi toplamak ve kullanmak için izin vermiş sayılırsınız. İnternet altyapısının küresel niteliği nedeniyle, sağladığınız bilgiler, verilerinizle ilgili benzer korumalara ve bu politikada belirtilen kullanım amaçlarına sahip olmayan Avrupa Ekonomik Alanı dışındaki ülkelere de aktarılabilir.`,
    'mailForm#16': `Ancak, bilgilerinizin güvenliğini artırmak için yukarıda belirtilen tedbirleri alıyoruz. Bize bilgilerinizi göndererek bu transferlere izin vermiş sayılırsınız.`,
    'mailForm#17': `Kişisel bilgilerimin işlenmesine`,
    'mailForm#18': `izin veriyorum`,
    'mailForm#19': `Menkul Kıymet Jetonu satışı, şununla başlıyor:`,
    'mailForm#20': `25% BONUS`,
    'mailForm#21': `Herkesten önce edinin Teklifin kalan süresi:`,
    'mailForm#22': `Token satışı başlıyor`,
    'mailForm#23': `$1’dan başla`,
    'mailForm#24': `$1’dan sonra`,
    'mailForm#25': `E-posta adresiniz`,
    'mailForm#26': `Ön Satışa Katılın`,
    'mailForm#27': `KABUL & GÖNDER`,

    'progressBarSale#1': `CINX`,
    'progressBarSale#2': `içinde Bonuslar`,
    'progressBarSale#3': `Ön Satış`,
    'progressBarSale#4': `Satış`,
    'progressBarSale#5': `Ağustos 26`,
    'progressBarSale#6': `Eylül 17`,
    'progressBarSale#7': `Ekim 8`,
    'progressBarSale#8': `Ekim 22`,
    'progressBarSale#9': `Kasım 6`,
    'progressBarSale#10': `Kasım 19`,
    'progressBarSale#11': `Aralık 3`,
    'progressBarSale#12': `Aralık 17`,

    'cryptoAssetsManagement#1.1': `CINDX bir Kripto Varlık Yönetim Merkezidir.`,
    'cryptoAssetsManagement#1.2': `Yatırımcıların, borsacıların ve geliştiricilerin sorunlarına çözüm getiriyoruz.`,
    'cryptoAssetsManagement#2': `YATIRIMCILAR İÇİN CINDX.MARKETPLACE`,
    'cryptoAssetsManagement#3': `Bilgi ve deneyiminiz konusunda endişeye kapılmayın; kripto yatırım uzmanları size yardımcı olmak için buradalar`,
    'cryptoAssetsManagement#4': `Kripto fonlarınızın kontrol altında tutun; koinleriniz her daim cüzdanınızda tutulur`,
    'cryptoAssetsManagement#5': `Sadece kazanırsanız ödeme yapın; yalnızca portföyünüzden kazanç sağladığınız takdirde ücret ödersiniz`,
    'cryptoAssetsManagement#6': `MVP'yi Test Edin`,
    'cryptoAssetsManagement#7': `BORSACILAR İÇİN CINDX.TERMINAL `,
    'cryptoAssetsManagement#8': `Başarılı bir yatırımcıysanız, pazarlama ve satış için herhangi bir yatırımda bulunmadan sermaye toplayabilirsiniz`,
    'cryptoAssetsManagement#9': `Yatırımlarda başarılı olmanız için size bir Terminal, Uygulama Merkezi, pazar ve farklı niteliklere sahip olan gelişmiş araçlar sunuyoruz`,
    'cryptoAssetsManagement#10': `CINDX sayesinde itibarınızı ve uzmanlığınızı kazanca dönüştürebilirsiniz. Yatırım geçmişiniz ve etkiniz şeffaf bir şekilde paylaşılır. `,
    'cryptoAssetsManagement#11': `CINDX.TALK, CINDX.HUB & CINDX.DAO`,
    'cryptoAssetsManagement#12': `CINDX.talk - Kullanışlı içeriklerin ödüllendirildiği bir sosyal ağ`,
    'cryptoAssetsManagement#13': `CINDX.hub - Merkezimizdeki araçlar arasında "sağlayıcı kabini" özelliğinin yanı sıra, üçüncü taraf yazılımlarını test edip entegre edebileceğiniz bir alan da bulunuyor`,
    'cryptoAssetsManagement#14': `CINDX.dao - Merkezsizleştirilmiş, otonom organizasyon kuralları çerçevesinde camia tarafından oylanmak için uygulamaya koyabileceğiniz bir bileşen`,

    'teamLegal#1': `AYRICA HARİKA BİR EKİBİMİZ VE HUKUK DANIŞMANLARIMIZ DA VAR`,
    'teamLegal#2': `HUKUK DANIŞMANLARIMIZ DA VAR`,
    'teamLegal#3': `KRİPTO PARA BİRİMİ TAKAS LİSANSI`,
    'teamLegal#4': `FİNANSAL KURUM LİSANSI`,
    'teamLegal#5': `KRİPTO CÜZDAN LİSANSI`,
    'teamLegal#6': `TANITIM`,
    'teamLegal#7': `SUNUM`,
    'teamLegal#8': `BROŞÜR`,
    'teamLegal#9': `FİNANSAL MODEL`,
    'teamLegal#10': `YASAL BELGELER`,

    'roadmap#1': `Yol Haritası`,
    'roadmap#2': `SENARYO`,
    'roadmap#3': `İlk olarak CINDX platformu için bir temel oluşturuyoruz. Bu aşamada, Minimum Kullanılabilir Ürün geliştiriliyor. MKÜ, takas ve çoğaltma protokolüne erişim sağlayacak. Kaynaklarımızın büyük bir kısmı, platformun ölçeklenebilirliğine ve güvenliğine ayrılmıştır.`,
    'roadmap#4': `Platformun CINDX.alpha sürümü, bir blokzinciri mimarisi ve akıllı sözleşmeler için temel bir yerleşim sistemi içerir. CINDX.market ve CINDX.trade bileşenleri de ek işlevler kazanıp bazı değişikliklerden geçer.`,
    'roadmap#5': `CINDX.alpha sürümündeki blokzinciri mimarisine dayanarak, kullanıcıların iletişim kurmalarını ve faydalı içerikler öğrenip ödül kazanmalarını sağlayan CINDX.talk bileşenini ekliyoruz. Piyasa bilgisini analiz etmek ve bunu üçüncü taraf hizmetlerine sunmak için, platformun CINDX.core bileşenine bir analitik modül eklenecektir.`,
    'roadmap#6': `Bu aşamada, CINDX.market ve CINDX.trade bileşenlerini ekliyoruz. Yöneticiler endeks bazlı ürünler ekleyebilir ve terminal esnek bir risk yönetimi sistemi ile entegre olur.`,
    'roadmap#7': `CINDX.talk, herkese açık ve özel iletişim kanallarına sahip olur. Bu aşamada, içerikler birbirinden ayrılabilir.`,
    'roadmap#8': `Bu aşamada platform büyük oranda güncellenir. Kullanıcılar kripto para birimleri ile fiat para birimlerini depolayıp takas edebilmeye başlar. CINDX.trade, sipariş yürütme ve risk yönetiminin için son derece esnek bir sistem kullanmaya başlar. Pazaryeri devreye alınır ancak bu aşamada sadece CINDX ve iş ortakları tarafından geliştirilen uygulamalara yer verilir.`,
    'roadmap#9': `CINDX.talk son sürümüne jeton bazlı bir puanlama sistemi eklenir. Ayrıca yeni bir ürün türü olan “Algoritmik ticaret” ve takas ile çoklu takas siparişleri arasında otomatik arbitraj işlevi eklenecektir.`,
    'roadmap#10': `İlk olarak CINDX platformu için bir temel oluşturuyoruz. Bu aşamada, Minimum Kullanılabilir Ürün geliştiriliyor. MKÜ, takas ve çoğaltma protokolüne erişim sağlayacak. Kaynaklarımızın büyük bir kısmı, platformun ölçeklenebilirliğine ve güvenliğine ayrılmıştır.`,
    'roadmap#11': `Platformun CINDX.alpha sürümü, bir blokzinciri mimarisi ve akıllı sözleşmeler için temel bir yerleşim sistemi içerir. CINDX.market ve CINDX.trade bileşenleri de ek işlevler kazanıp bazı değişikliklerden geçer.`,
    'roadmap#12': `CINDX.alpha sürümündeki blokzinciri mimarisine dayanarak, kullanıcıların iletişim kurmalarını ve faydalı içerikler öğrenip ödül kazanmalarını sağlayan CINDX.talk bileşenini ekliyoruz. Piyasa bilgisini analiz etmek ve bunu üçüncü taraf hizmetlerine sunmak için, platformun CINDX.core bileşenine bir analitik modül eklenecektir. Yeni bir CINDX.hub bileşeni, CINDX'in sağladığı piyasa verilerini analiz etmek için uygulama geliştirmeyi sağlar.`,
    'roadmap#13': `Bu aşamada, CINDX.market ve CINDX.trade bileşenlerini ekliyoruz. Yöneticiler endeks bazlı ürünler ekleyebilir ve terminal esnek bir risk yönetimi sistemi ile entegre olur. Geliştiriciler için, CINDX üzerinde uygulama geliştirmeyi kolaylaştıracak bir UGK yayımlanır.`,
    'roadmap#14': `CINDX.talk, herkese açık ve özel iletişim kanallarına sahip olur. Bu aşamada, içerik türleri birbirlerinden ayırt edilebilir. CINDX.hub, uygulama geliştirmeyi daha da kolaylaştıran bir Github entegrasyonuna sahip olur.`,
    'roadmap#15': `Bu aşamada platform büyük oranda güncellenir. Kullanıcılar kripto para birimleri ile fiat para birimlerini depolayıp takas edebilmeye başlar. CINDX.trade, sipariş yürütme ve risk yönetiminin için son derece esnek bir sistem kullanmaya başlar. Pazaryeri devreye alınır ancak bu aşamada sadece CINDX ve iş ortakları tarafından geliştirilen uygulamalara yer verilir. CINDX.hub, tarihsel piyasa verilerine dayanan bir test sistemi ile ticaret stratejileri geliştirmek için tam ölçekli bir editöre sahip olur.`,
    'roadmap#16': `CINDX.talk son sürümüne jeton bazlı bir puanlama sistemi eklenir. Ayrıca yeni bir ürün türü olan “Algoritmik ticaret” ve takas ile çoklu takas siparişleri arasında otomatik arbitraj işlevi eklenecektir. Kod denetimi için üst düzey bir platform ve CINDX.talk'da jeton bazlı derecelendirmeye dayalı topluluk uzman değerlendirmesi oluşturulur.`,
    'roadmap#17': `İlk olarak CINDX platformu için bir temel oluşturuyoruz. Bu aşamada, Minimum Kullanılabilir Ürün geliştiriliyor. MKÜ, takas ve çoğaltma protokolüne erişim sağlayacak. Kaynaklarımızın büyük bir kısmı, platformun ölçeklenebilirliğine ve güvenliğine ayrılmıştır.`,
    'roadmap#18': `Platformun CINDX.alpha sürümü, bir blokzinciri mimarisi ve akıllı sözleşmeler için temel bir yerleşim sistemi içerir. CINDX.market ve CINDX.trade bileşenleri de ek işlevler kazanıp bazı değişikliklerden geçer.`,
    'roadmap#19': `CINDX.alpha sürümündeki blokzinciri mimarisine dayanarak, kullanıcıların iletişim kurmalarını ve faydalı içerikler öğrenip ödül kazanmalarını sağlayan CINDX.talk bileşenini ekliyoruz. Piyasa bilgisini analiz etmek ve bunu üçüncü taraf hizmetlerine sunmak için, platformun CINDX.core bileşenine bir analitik modül eklenecektir. Yeni bir CINDX.hub bileşeni, CINDX'in sağladığı piyasa verilerini analiz etmek için uygulama geliştirmeyi sağlar. Ekip, jeton sahiplerine platformun gelirini dağıtacak bir sistem olan CINDX.dao bileşenini geliştirir.`,
    'roadmap#20': `Bu aşamada, CINDX.market ve CINDX.trade bileşenlerini ekliyoruz. Yöneticiler endeks bazlı ürünler ekleyebilir ve terminal esnek bir risk yönetimi sistemi ile entegre olur. Geliştiriciler için, CINDX üzerinde uygulama geliştirmeyi kolaylaştıracak bir UGK yayımlanır.`,
    'roadmap#21': `CINDX.talk, herkese açık ve özel iletişim kanallarına sahip olur. Bu aşamada, içerik türleri birbirlerinden ayırt edilebilir. CINDX.hub, uygulama geliştirmeyi daha da kolaylaştıran bir Github entegrasyonuna sahip olur.`,
    'roadmap#22': `Bu aşamada platform büyük oranda güncellenir. Kullanıcılar kripto para birimleri ile fiat para birimlerini depolayıp takas edebilmeye başlar. CINDX.trade, sipariş yürütme ve risk yönetiminin için son derece esnek bir sistem kullanmaya başlar. Pazaryeri devreye alınır ancak bu aşamada sadece CINDX ve iş ortakları tarafından geliştirilen uygulamalara yer verilir. CINDX.hub, tarihsel piyasa verilerine dayanan bir test sistemi ile ticaret stratejileri geliştirmek için tam ölçekli bir editöre sahip olur. CINDX.dao, jeton sahipleri için bir oy kullanma sistemi elde eder.`,
    'roadmap#23': `CINDX.talk son sürümüne jeton bazlı bir puanlama sistemi eklenir. Ayrıca yeni bir ürün türü olan “Algoritmik ticaret” ve takas ile çoklu takas siparişleri arasında otomatik arbitraj işlevi eklenecektir. Kod denetimi için üst düzey bir platform ve CINDX.talk'da jeton bazlı derecelendirmeye dayalı topluluk uzman değerlendirmesi oluşturulur. CINDX.dao, CINDX’in daha da merkezsiz hale gelmesi için bir delege sistemi sunmaya başlar.`,

    'problemSolving#1': `Zaman`,
    'problemSolving#2': `Güven`,
    'problemSolving#3': `Belirsizlik`,
    'problemSolving#4': `Kripto dövizlere biraz sermaye yatırdım ama portföyümü yönetebilecek profesyonel yatırımcı aramak ve iletişim kurmak için zamanım yok.`,
    'problemSolving#5': `Kâr yapsın diye sermayemi başkasına teslim etme fikri hiçbir zaman ilgimi çekmedi.`,
    'problemSolving#6': `Kripto yatırımları için mevcut olan teknoloji kullanıcı dostu değil. Koinlerimle nasıl yatırım yapacağımı bilemiyorum`,
    'problemSolving#7': `CINDX sayesinde güvenilir ve puanlanmış yatırımcılara ulaşabilirsiniz`,
    'problemSolving#8': `CINDX platformunda fonlarınız hiçbir zaman cüzdanınızdan çıkmaz`,
    'problemSolving#9': `Piyasadaki en iyi yatırımcılarla beraber kazanç sağlıyor olursunuz`,
    'problemSolving#10': `CINDX platformundaki yatırımcılar, yatırım geçmişlerindeki başarı doğrultusunda puanlandırılırlar. Sizin için en doğru yatırımcıyı çabucak seçin`,
    'problemSolving#11': `Merkezsizleştirilmiş sistemimiz ve akıllı kontratlarımız sayesinde, sermayeniz, herhangi bir yatırımcıya transfer edilmesine gerek kalmadan yönetiliyor olacak.`,
    'problemSolving#12': `CINDX platformundaki her yatırımcı, sermayesinin piyasalardaki en başarılı yatırımcılar tarafından yönetilmesi fırsatına sahip olur.`,
    'problemSolving#13': `CINDX ne tür sorunlara çözüm getiriyor?`,
    'problemSolving#14': `MVP'yi Test Edin`,

    'howCindxWorks#1': `Yatırımcılar`,
    'howCindxWorks#2': `Borsacılar`,
    'howCindxWorks#3': `Sağlayıcılar`,
    'howCindxWorks#4': `en başarılı yatırımcıların portföy yönetimi becerilerinden yararlanarak, kripto dünyasındaki kazançlarını arttırırlar`,
    'howCindxWorks#5': `performansları ve yatırım stratejileri doğrultusunda onları takip eden yatırımcılardan komisyon kazanırlar`,
    'howCindxWorks#6': `yatırım botları ve haber araçları gibi gelişmiş yatırım araçları satarlar`,
    'howCindxWorks#7': `komisyon ve abonelik ücretleri kazanırlar`,
    'howCindxWorks#8': `CINDXe yatırımlarda kullanmak istediğim kripto varlıklarla katılıyorum`,
    'howCindxWorks#9': `CINDXe yatırımcılara sunacağım yatırım uzmanlığıyla katılıyorum`,
    'howCindxWorks#10': `CINDXe yatırımcılara yardımcı olacak yatırım uygulamalarıyla katılıyorum`,
    'howCindxWorks#11': `Yatırımları kolay, güvenli ve kârlı hâle getirmek için buradayız`,
    'howCindxWorks#12': `Kısa Bilgi: CINDX Nasıl Çalışır?`,

    'marketAnalytics#1': `Piyasa İstatistikleri`,
    'marketAnalytics#2': `Global Yönetilen Varlıklar (AUM)`,
    'marketAnalytics#3': `Yatırım`,
    'marketAnalytics#4': `Yatırımın Yapısı`,
    'marketAnalytics#5': `Global varlık yönetimi piyasası, 2000 yılından bu yana %250'nin üzerinde büyüme gösterdi.`,
    'marketAnalytics#6': `Bunun, piyasalardaki araçların iyileşmesi ve piyasa yapısının genel olarak gelişmesinden kaynaklandığını söylemek yanlış olmaz.`,
    'marketAnalytics#7': `Kripto döviz piyasasının 2017 yılında yaşadığı patlamaya rağmen, sektör hâlâ daha çok bakirdir.`,
    'marketAnalytics#8': `2017 yılının sonunda 600 milyar dolar olan toplam piyasa değeri, varlık yönetimi sektörünün toplam piyasa değerinin sadece %1'ine tekabül ediyor.`,
    'marketAnalytics#9': `TANITIM`,
    'marketAnalytics#10': `SUNUM`,
    'marketAnalytics#11': `BROŞÜR`,
    'marketAnalytics#12': `FİNANSAL MODEL`,
    'marketAnalytics#13': `YASAL BELGELER`,
    'marketAnalytics#14': `Genel Rakamlar`,
    'marketAnalytics#15': `25 milyon potansiyel blok zinciri`,
    'marketAnalytics#16': `cüzdanı`,
    'marketAnalytics#17': `200.000 potansiyel`,
    'marketAnalytics#18': `günlük işlem`,
    'marketAnalytics#19': `3-5 milyar dolarlık değere sahip,`,
    'marketAnalytics#20': `225'in üzerinde potansiyel ortak`,

    'tokenSaleDetails#1': `Token Dağıtımı`,
    'tokenSaleDetails#2': `Ekip`,
    'tokenSaleDetails#3': `İkramiye`,
    'tokenSaleDetails#4': `Danışmanlar`,
    'tokenSaleDetails#5': `Rezerv`,
    'tokenSaleDetails#6': `Camia Hibesi`,
    'tokenSaleDetails#7': `Token Likidite Desteği`,
    'tokenSaleDetails#8': `Satışa Açık Miktar`,
    'tokenSaleDetails#9': `Token Adı:`,
    'tokenSaleDetails#10': `Token Ön Satışı başlangıcı:`,
    'tokenSaleDetails#11': `Toplam İhraç:`,
    'tokenSaleDetails#12': `Token Fiyatı:`,
    'tokenSaleDetails#13': `Minimum Yatırım:`,
    'tokenSaleDetails#14': `50$'a eşdeğer`,
    'tokenSaleDetails#15': `TANITIM`,
    'tokenSaleDetails#16': `SUNUM`,
    'tokenSaleDetails#17': `BROŞÜR`,
    'tokenSaleDetails#18': `FİNANSAL MODEL`,
    'tokenSaleDetails#19': `YASAL BELGELER`,
    'tokenSaleDetails#20': `Gelir Kullanımı`,
    'tokenSaleDetails#21': `Pazarlama ve Hİ 21%`,
    'tokenSaleDetails#22': `Araştırma ve Geliştirme 41%`,
    'tokenSaleDetails#23': `Operasyon 28%`,
    'tokenSaleDetails#24': `Hukuki giderler 7%`,
    'tokenSaleDetails#25': `Yatırımcı bonusları 3%`,
    'tokenSaleDetails#26': `Token Bilgileri`,
    'tokenSaleDetails#27': `Token Satışı:`,
    'tokenSaleDetails#28': `Token Ön Satış Bonusları:`,
    'tokenSaleDetails#29': `26 Ağustos-16 Eylül -% 25 Bonus`,
    'tokenSaleDetails#30': `17 Eylül - 7 Ekim -% 20 Bonus`,
    'tokenSaleDetails#31': `Token Ana Satış Bonusları`,
    'tokenSaleDetails#32': `8 Eki - 21 Eki - %17 Bonus`,
    'tokenSaleDetails#33': `22 Eki - 4 Kas - %15 Bonus`,
    'tokenSaleDetails#34': `5 Kas - 18 Kas - %13 Bonus`,
    'tokenSaleDetails#35': `19 Kas - 2 Ara - %10 Bonus`,
    'tokenSaleDetails#36': `3 Ara - 16 Ara - %5 Bonus`,
    'tokenSaleDetails#37': `17 Ara - 26 Ara - %0 Bonus`,
    'tokenSaleDetails#38': `Token Al`,
    'tokenSaleDetails#39': `Token Satışı Bilgileri`,
    'tokenSaleDetails#40': `Jeton satışı sırasında, yatırımcılar, gelecekte [CINX] jetonu alma hakkı veren [CINXO] hizmet jetonları satın alırlar.`,
    'tokenSaleDetails#41': `Menkul kıymet jetonu olan [CINX], Emisyon İzni alınmasının ardından piyasaya sürülecektir. (Jeton satışının sona ermesinden sonra Estonya'nın https://www.fi.ee/ adresindeki MDM web sitesinde ve cindx.io adresinde yayınlanacak ve 2019’un ilk çeyreğinden önce gerçekleşecektir.)`,
    'tokenSaleDetails#42': `[CINXO] jetonlarının sahibi; imza teyidi, adres teyidi ve diğer belgelerin temin edilmesi ile MTB prosedürü tamamlandıktan sonra elindeki jetonları 1: 1 oranında menkul kıymet jetonları ile değiştirme hakkına sahiptir ancak bu bir yükümlülük değildir (bkz. CINDX MTB Şeması).`,
    'tokenSaleDetails#43': `[CINXO] jetonları, gelir dağıtımına katılma ve platformda oy kullanma hakkı dışında, menkul kıymet jetonları ile aynı hakları verir.`,

    'legalSchedule#1': `Hukuki Takvim`,
    'legalSchedule#2': `SANAL DÖVİZ VE YASAL DÖVİZLER ARASINDA BORSA OLUŞTURMAK İÇİN LİSANS (FVR000110) ALINDI`,
    'legalSchedule#3': `ESTONYA VE AB'DE TİCARİ MARKA KAYIT BAŞVURUSUNDA BULUNULDU`,
    'legalSchedule#5': `FİNANSAL KURULUŞ FAALİYETLERİNDE BULUNMAK İÇİN LİSANS FFA000254 ALINDI`,
    'legalSchedule#6': `Estonaya yasalarına uygun olarak Prospektüs oluşturuldu`,
    'legalSchedule#7': `FSA LİSANSI ALINDI (Estonya Finansal Denetim Kurumu)`,
    'legalSchedule#8': `SANAL DÖVİZ CÜZDANI HİZMETİ SUNMAK İÇİN LİSANS ALINDI`,
    'legalSchedule#9': `SEC'TE D TÜRÜ MUAFİYET KAYDI YAPILDI`,
    'legalSchedule#10': `GDPR KOŞULLARINI SAĞLAMAK AMACIYLA KİŞİSEL VERİ YÖNETİCİSİ ATANDI`,
    'legalSchedule#11': `FSA LİSANSI ALINDI`,
    'legalSchedule#12': `EU 809-2004 PROSPEKTÜSÜNE KAYIT OLUNDU`,
    'legalSchedule#13': `CINX TOKEN VARLIKLARI İHRAÇ EDİLDİ`,

    'feedbackProject#1': `PROJE GERİ BİLDİRİMLERİMİZ`,
    'feedbackProject#2': `Val Jerdes`,
    'feedbackProject#3': `Ürün Direktörü`,
    'feedbackProject#4': `CINDX Ürün Direktörü Val Jerdes, ekibin başlıca üyelerinden ve ekibe kattıkları uzmanlık sayesinde, finans dünyasını ciddi ölçüde değiştirebilecek bu projenin nasıl geliştiğinden bahsediyor`,
    'feedbackProject#5': `Denis Eskenazi`,
    'feedbackProject#6': `Ürün Pazarlama Direktörü`,
    'feedbackProject#7': `CINDX Ürün Pazarlama Direktörü Denis Eskenazi, CINDX projesine nasıl katıldığını anlatıyor`,
    'feedbackProject#8': `Philip Staehelin`,
    'feedbackProject#9': `Danışman`,
    'feedbackProject#10': `CINDX projesinin Danışmanı Philip Staehelin, kripto döviz devriminin en deneyimsiz yatırımcılara bile nasıl katkılar sağlayabileceğini ve CINDX projesinin kripto döviz piyasasında yaratmaya hazırlandığı devrimi anlatıyor`,
    'feedbackProject#11': `Andrzej Cichowlaz`,
    'feedbackProject#12': `Pazarlama Uzmanı`,
    'feedbackProject#13': `CINDX Pazarlama Müdürü Andrzej Cichowlaz, projenin başarılı olacağına nasıl bu kadar inandığını açıklıyor`,
    'feedbackProject#14': `Austin Kimm`,
    'feedbackProject#15': `CINDX projesinin Danışmanı Austin Kimm, CINFX projesi sayesinde kâr amaçlı kripto döviz yatırımlarının nasıl basit ve akıllı bir yönteme dönüştüğünü anlatıyor`,
    'feedbackProject#16': `Amarpreet Singh`,
    'feedbackProject#17': `CINDX Danışmanı Amarpreet Singh, CINDX'in nasıl yatırımcılar ile borsacılar arasında bir köprü görevi görebileceğini açıklıyor`,
    'feedbackProject#18': `Keith Teare`,
    'feedbackProject#19': `CINDX Danışmanı Keith Teare, CINDX platformunun avantajlarını sayıyor`,
    'feedbackProject#20': `Mansur Rasulov`,
    'feedbackProject#21': `Camia Lideri`,
    'feedbackProject#22': `CINDX Camia Lideri Mansur Rasulov, CINDX ekibinin bir üyesi olmaya nasıl karar verdiğini anlatıyor`,
    'feedbackProject#23': `Sadie Hutton`,
    'feedbackProject#24': `CINDX Danışmanı Sadie Hutton, CINDX platformunun diğer otomatik yatırım platformlarıyla kıyaslandığında nasıl farklara sahip olduğunu anlatıyor`,
    'feedbackProject#25': `Graham Doggart`,
    'feedbackProject#26': `CINDX Danışmanı Graham Doggart, CINDX platformunun sunduğu eşsiz avantajları açıklıyor`,
    'feedbackProject#27': `Alina Vardanian`,
    'feedbackProject#28': `İçerik Yöneticisi`,
    'feedbackProject#29': `CINDX İçerik Yöneticisi Alina Vardanian, ekip ruhundan ve işiyle ilgili en çok neleri sevdiğinden bahsediyor`,
    'feedbackProject#30': `Bogdan Fiedur`,
    'feedbackProject#31': `CINDX Danışmanı`,
    'feedbackProject#32': `CINDX Danışmanı Bogdan Fiedur,  CINDX projesinin diğer ICO projelerinden hangi konularda farklı olduğuna açıklık getiriyor`,
    'feedbackProject#33': `Jason King`,
    'feedbackProject#34': `Ticaret Kurulu Başkanı Jason King, CINDX'te en çok ilgisini çeken şeyin ne olduğunu ve bu projenin sunduğu önemli faydaları anlatıyor`,

    'mediaNews#1': `Medya`,
    'mediaNews#2': `Haberler`,
    // Media
    'mediaNews#1_1': `CINDX Aims to Democratize the Modern Financial System`,
    'mediaNews#1_2': `Even as investors in the cryptocurrency space recognize that they are at the forefront of a new financial revolution, adoption by the general populace is yet to occur. While 3rd parties are slowly entering the space in the form of hedge funds and other investors, very few individuals seem to have taken the step to invest in cryptocurrencies on their own.`,
    'mediaNews#1_3': `CINDX Announces Plans For ICO Pre-Sale Amidst Release Of Revolutionary Crypto Trading Hub That Allows Users To Follow Expert Traders`,
    'mediaNews#1_4': `CINDX takes its business seriously with particular attention and cares to legal matters and has taken great pains to ensure that CINDX is as compliant as possible with global regulations.`,
    'mediaNews#1_5': `How CINDX is Democratizing the Modern Financial System`,
    'mediaNews#1_6': `CINDX is a new platform that is making crypto trading easier, more secure, and more accessible. With this platform, it’s possible to have your funds traded without high fees or minimum investments, with the added security and transparency of blockchain technology.`,
    'mediaNews#1_7': `CINDX is making crypto trading easier, more secure, and more accessible.`,
    'mediaNews#1_8': `Cryptocurrency and blockchain technology have been slated as powerful tools capable of fueling a global financial revolution. There are myriad opportunities to invest in the crypto space, and yet, very few individuals have undertaken the steps necessary to invest.`,
    'mediaNews#1_9': `CINDX Announces Plans Release Of Revolutionary Crypto Trading Hub`,
    'mediaNews#1_10': `The CINDX platform creates a complete ecosystem for cryptocurrency trading that is favorable to all the participants of the market and offers solutions to existing pain points.`,
    'mediaNews#1_11': `CINDX Announces Plans For ICO Pre-Sale`,
    'mediaNews#1_12': `CINDX made headlines this week with the announcement that they will be opening their ICO Pre-Sale in late August after investors interest in the ICO peaks to new levels.`,
    'mediaNews#1_13': `CINDX Will Be Opening ICO Pre-Sale in late August`,
    'mediaNews#1_14': `The CINDX Crypto trading platform has a myriad of features and benefits that haven’t been seen in other platforms to date.`,
    'mediaNews#1_15': `5 Tips from CINDX Crypto Assets Management Hub: How to Avoid Being Cheated`,
    'mediaNews#1_16': `The team behind the CINDX crypto assets management hub has created a helpful set of guidelines on how not to become victims of unfair play, so you can learn what should be primarily taken into account when evaluating ICOs before investing in them.`,
    'mediaNews#1_17': `CINDX Crypto Asset Management Hub Adopts Bancor Protocol`,
    'mediaNews#1_18': `CINDX is delighted to announce that a number of new integrations with top industry players are underway, each of which will make the life of the users of the platform easier and richer. These new integrations include the decision to adopt the Bancor protocol to provide continuous liquidity for the CINDX platform.`,
    // News
    'mediaNews#2_1': `CINDX meets Ian Balina`,
    'mediaNews#2_2': `CINDX pitch to the one of the TOP10 crypto gurus in the world in the Cryptobazar event.`,
    'mediaNews#2_3': `CINDX took part in Moscow ICO Summit 2018`,
    'mediaNews#2_4': `CINDX team introduced the project to the Russian crypto community during ICO Summit event.`,
    'mediaNews#2_5': `How CINDX is ensuring legal compliance`,
    'mediaNews#2_6': `Our company is registered in Estonia. Why? The answer is simple — the authorities of Estonia have created a strong and innovative legal infrastructure...`,
    'mediaNews#2_7': `Keith Teare Co-founder of Accelerated Digital Ventures and Founding Shareholder in TechCrunch`,
    'mediaNews#2_8': `We continue to introduce CINDX advisers, find out what they...`,
    'mediaNews#2_9': `Meet world's first financial crypto social network`,
    'mediaNews#2_10': `Every day our team takes one more step on the way to creation and start...`,
    'mediaNews#2_11': `Denis Eskenazi CINDX Product Marketing Director`,
    'mediaNews#2_12': `We continue to tell about the CINDX team and each team member’s professional experience. Please, read about Denis Eskenazi...`,
    'mediaNews#2_13': `CINDX crypto currency exchange license`,
    'mediaNews#2_14': `Our company in Estonia has received Crypto Currency Exchange License. This allows CINDX to provide fiat-to-crypto exchange services. This licence is issued...`,
    'mediaNews#2_15': `Austin Kimm Co-founder of Crypterium & CINDS Adviser`,
    'mediaNews#2_16': `We continue to introduce CINDX advisers, find out what they are proud...`,
    'mediaNews#2_17': `The strategic meeting of the international CINDX team`,
    'mediaNews#2_18': `Every day our team takes one more step on the way to creation and start of the CINDX platform. Our work...`,
    'mediaNews#2_19': `Artur Shamalov CINDX Investment Director`,
    'mediaNews#2_20': `We continue to introduce the CINDX team. Our next article is about Artur Shamalov, a skilled...`,
    'mediaNews#2_21': `The issuance of CINX tokens`,
    'mediaNews#2_22': `The issuance of CINX tokens will be carried out according to the license of The Estonian Financial Supervisory Authority (EFSA). What is a token...`,
    'mediaNews#2_23': `"Amarpreet Singh Co-Founding Member of Malta Blockchain Association & CINDX adviser"`,
    'mediaNews#2_24': `We at CINDX are incredibly proud to present our advisers, tell the world about their achievements and why they have decided to become a part of the CINDX...`,
    'mediaNews#2_25': `CINDX meets Vangoo Capital Partners Fund`,
    'mediaNews#2_26': `Today we have welcomed Kevin Shang from Vangoo Capital Partners and his colleagues in our office. We have discussed business partnership opportunities in order to attract investors from the Asian region.`,
    'mediaNews#2_27': `"Mofassair Hossain CINDX Chief Marketing Officer."`,
    'mediaNews#2_28': `We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly excited about...`,
    'mediaNews#2_29': `How CINDX ensures safety for its users - KYC`,
    'mediaNews#2_30': `Every crypto enthusiast knows that a KYC procedure is necessary in order to protect investors against fraudulent actions of the third...`,
    'mediaNews#2_31': `Philip Staehelin 25 Years of Consulting and Entrepreneurial Experience`,
    'mediaNews#2_32': `We continue our regular series of articles dedicated to introducing CINDX advisers. The next item is about Philip Staehelin.`,
    'mediaNews#2_33': `CINDX meets 9coin Digital Asses Exchange`,
    'mediaNews#2_34': `The CINDX team continues active work on building relationships with various international companies. One of the most important directions of business...`,
    'mediaNews#2_35': `Jason King Interim Chief Commercial Officer`,
    'mediaNews#2_36': `The core of any great project is always people who make the unique idea come true. We would like to tell about...`,
    'mediaNews#2_37': `CINDX Presents the project during RICLUB private investors meeting`,
    'mediaNews#2_38': `CINDX has successfully passed the due diligence procedure requested by RICLub and was one of the few projects...`,
    'mediaNews#2_39': `Sofja Pevzner CINDX Personal Data Officer`,
    'mediaNews#2_40': `We continue to introduce our team and tell about what inspires our colleagues to work with CINDX. Please read about...`,
    'mediaNews#2_41': `Tyler Sanford 8+ years digital marketing in Yelp, Zenefits`,
    'mediaNews#2_42': `We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become a part of the CINDX team. In this...`,
    'mediaNews#2_43': `CINDX - Key points to observe`,
    'mediaNews#2_44': `The CINDX project is a valuable business venture with the features that are critically relevant for its participants. In this article we talk about Strengths...`,
    'mediaNews#2_45': `Airat Shayhulov CINDX Head of Quantitative Research.`,
    'mediaNews#2_46': `In “TEAM” series of the articles, we tell about people who every day participates in the creation...`,
    'mediaNews#2_47': `CINDX license of the financial consultant`,
    'mediaNews#2_48': `CINDX has obtained a termless operating licence (the FFA 000254 license) that gives the right to operate as a financial institution...`,
    'mediaNews#2_49': `"Graham Doggart 20 Years of Enterprise Development and Fintech Marketing Compliance"`,
    'mediaNews#2_50': `We continue our regular series of articles dedicated to introducing CINDX advisers. The next item...`,
    'mediaNews#2_51': `CINDX continues the roadshow in China!`,
    'mediaNews#2_52': `The CINDX team is glad to announce participation as a Golden Sponsor of Borderless Blockchain Technology Summit 2018, which...`,
    'mediaNews#2_53': `Ibraghim Haniev CINDX Tech Lead`,
    'mediaNews#2_54': `Get to know more about the CINDX team! The core of any great project is always people who make the unique ideas come true...`,
    'mediaNews#2_55': `Sadie Hutton 25 Years in Senior Management and Management Consulting`,
    'mediaNews#2_56': `Like any global project, we understand the importance of professional help and advice. We continue to tell the stories of...`,
    'mediaNews#2_57': `CINDX.talk - a service that will help people become wiser in taking financial decisions`,
    'mediaNews#2_58': `The current digital-world related to the crypto industry is getting crowded with mind-charming digital solutions...`,
    'mediaNews#2_59': `"Val Jerdes CINDX Product Director"`,
    'mediaNews#2_60': `We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly...`,
    'mediaNews#2_61': `Bogdan Fiedur Blockchain and cryptocurrency expert, investor, entrepreneur`,
    'mediaNews#2_62': `We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become...`,
    'mediaNews#2_63': `Welcome to CINX Token Distribution – it’s not an ICO; it’s an STO`,
    'mediaNews#2_64': `In this article, we want to make it clear why CINDX chose to hold a Security Token Offering (STO) instead of an Initial...`,
    'mediaNews#2_65': `CINDX celebrates the “AA” Rating from Top ICO List Audit!`,
    'mediaNews#2_66': `The results of CINDX’s sincerity to make meaningful changes in people’s ambitions via a unique business model just got appreciated...`,
    'mediaNews#2_67': `CINDX Weekly digest (30.07.18 - 05.08.18)`,
    'mediaNews#2_68': `The CINDX team is very excited to share the results of our work for the last week 30.07.18 - 05.08.18!`,
    'mediaNews#2_69': `Virtual Currency Wallet Services`,
    'mediaNews#2_70': `CINDX believes that being fluent in legal issues and having a clean, confident and clear legal status is of utmost importance. At the moment, CINDX is going...`,
    'mediaNews#2_71': `How CINDX Influences Crypto Trading`,
    'mediaNews#2_72': `How to master the crypto market movements and turn them in one’s favor? This is where CINDX’s effective business model comes into play. Learn more about CINDX on our Medium!`,
    'mediaNews#2_73': `CINDX Weekly digest (06.08.18 - 12.08.18)`,
    'mediaNews#2_74': `CINDX continues its regular column - Weekly Digest. We are excited to share the recent achievements of our project! Enjoy your time reading!`,
    'mediaNews#2_75': `CINDX gets 5.0 rating on TrackICO!`,
    'mediaNews#2_76': `CINDX continues getting approval from the largest and the most credible rating services. The week has hardly passed after...`,
    'mediaNews#2_77': `"David Gutierrez Investment Relations Officer"`,
    'mediaNews#2_78': `CINDX is very serious about taking people on crew and proud to introduce them. This article is dedicated to David Gutierrez, CINDX Investment Relations Officer`,
    'mediaNews#2_79': `ICObench gives 4.8 to CINDX`,
    'mediaNews#2_80': `The CINDX project has already gained the highest mark of  ‘AA’ from Top ICO List and got a 5.0 rating from TrackICO. Now, we are proud to share...`,
    'mediaNews#2_81': `Dip your Toe in Crypto`,
    'mediaNews#2_82': `It is never late to change your mind. It’s no surprise that Wall Street bankers change their minds in favour of crypto. Enjoy reading CINDX review on the current market situation!`,
    'mediaNews#2_83': `Yuriy Avdeev, CEO of the CINDX project`,
    'mediaNews#2_84': `Enjoy reading what inspired Yuriy Avdeev to create a project that will help all participants of the crypto market to be profitably engaged - CINDX.`,
    'mediaNews#2_85': `Weekly digest (13.08.18 - 19.08.18)`,
    'mediaNews#2_86': `CINDX continues its regular Weekly Digest column. We are excited to share our project’s progress and the most recent achievements! We are glad to remind you that CINDX security token Pre-sale starts this Sunday. Don\'t miss!`,

    'teamAdvisersPartners#1': `50'den fazla üyeye sahip ekip`,
    'teamAdvisersPartners#2': `Danışmanlar`,
    'teamAdvisersPartners#3': `Ortaklarımız`,
    // teamInfo
    'teamAdvisersPartners#4': `Yuriy Avdeev`,
    'teamAdvisersPartners#5': `Yönetim Kurulu Başkanı`,
    'teamAdvisersPartners#6': `13 yıllık girişimcilik deneyimi`,
    'teamAdvisersPartners#7': `9 girişim`,
    'teamAdvisersPartners#8': `2 milyon dolarlık kripto döviz yönetim deneyimi`,
    'teamAdvisersPartners#9': `Val Jerdes`,
    'teamAdvisersPartners#10': `Ürün Direktörü`,
    'teamAdvisersPartners#11': `20 yıllık girişimcilik deneyimi`,
    'teamAdvisersPartners#12': `3 başarılı satış`,
    'teamAdvisersPartners#13': `Portföylerde 4 kat getiri`,
    'teamAdvisersPartners#14': `Mofassair Hossain`,
    'teamAdvisersPartners#15': `Pazarlama Kurulu Başkanı`,
    'teamAdvisersPartners#16': `15'ten Fazla ICO'nun Yatırımcısı ve Danışmanı`,
    'teamAdvisersPartners#17': `ICO Bench'te Başdanışman`,
    'teamAdvisersPartners#18': `GBAP Üyesi`,
    'teamAdvisersPartners#19': `Artur Shamalov`,
    'teamAdvisersPartners#20': `Yatırım Direktörü`,
    'teamAdvisersPartners#21': `15 yıllık girişimcilik deneyimi`,
    'teamAdvisersPartners#22': `Mixcart.ru'da 5.000 müşteri`,
    'teamAdvisersPartners#23': `mail.ru yatırımlı dc-daily.ru`,
    'teamAdvisersPartners#24': `Denis Eskenazi`,
    'teamAdvisersPartners#25': `Ürün Pazarlama Direktörü`,
    'teamAdvisersPartners#26': `7 yıllık girişimcilik deneyimi`,
    'teamAdvisersPartners#27': `Müşteriler için 2 milyon dolarlık sermaye toplama`,
    'teamAdvisersPartners#28': `10 yıllık marka yönetim deneyimi`,
    'teamAdvisersPartners#29': `Ibraghim Haniev`,
    'teamAdvisersPartners#30': `Teknoloji Müdürü`,
    'teamAdvisersPartners#31': `6 yıllık girişimcilik deneyimi`,
    'teamAdvisersPartners#32': `200'ün üzerinde site geliştirmesi`,
    'teamAdvisersPartners#33': `Bilgi Güvenliği odaklı`,
    'teamAdvisersPartners#34': `Airat Shaikhulov`,
    'teamAdvisersPartners#35': `Niceliksel Araştırmalar Müdürü`,
    'teamAdvisersPartners#36': `MS Üniversitesinde Bilim Doktoru`,
    'teamAdvisersPartners#37': `Aton-line navigatörü geliştiricisi`,
    'teamAdvisersPartners#38': `Algoritmik takas sorumlu müdürü`,
    'teamAdvisersPartners#39': `Sofja Pevzner`,
    'teamAdvisersPartners#40': `Kişisel Veri Temsilcisi`,
    'teamAdvisersPartners#41': `5 yıllık girişimcilik deneyimi`,
    'teamAdvisersPartners#42': `Estonya KPAÖ kurumundan çalışma izni`,
    'teamAdvisersPartners#43': `8 yıllık hukuk işleri deneyimi`,
    'teamAdvisersPartners#44': `Dave Gutierrez`,
    'teamAdvisersPartners#45': `Yatırımcı İlişkileri Temsilcisi`,
    'teamAdvisersPartners#46': `5 yıllık hava taşıtı kiralama deneyimi`,
    'teamAdvisersPartners#47': `3 yıllık Yatırım Ajansı deneyimi`,
    'teamAdvisersPartners#48': `2 yıllık yurt dışı yatırım deneyimi`,
    'teamAdvisersPartners#49': `Jelena Karzetskaja`,
    'teamAdvisersPartners#50': `Uyumluluk Temsilcisi`,
    'teamAdvisersPartners#51': `hukuk alanında çeşitli diplomalara sahip`,
    'teamAdvisersPartners#52': `1997 yılından beri yargı organı deneyimi`,
    'teamAdvisersPartners#53': `yasal konular: uluslararası hukuk`,
    'teamAdvisersPartners#54': `Wang Dong`,
    'teamAdvisersPartners#55': `Çin Blok Zinciri Piyasası Uzmanı`,
    'teamAdvisersPartners#56': `3 yıllık PHP/JavaScript deneyimi`,
    'teamAdvisersPartners#57': `5 yıllık SEO/SMM/medya satın alma deneyimi`,
    'teamAdvisersPartners#58': `2 yıllık Blok Zinciri geliştirme ve Çin'de token satışı deneyimi`,
    // advisers
    'teamAdvisersPartners#59': `Keith Teare`,
    'teamAdvisersPartners#60': `Accelerated Digital Ventures Kurucusu ve Yönetim Kurulu Başkanı`,
    'teamAdvisersPartners#61': `ICOBox, Crypterium, EnergiMine, vb. şirketlerinin danışmanı`,
    'teamAdvisersPartners#62': `TechCrunch'ın kurucu hissedarı`,
    'teamAdvisersPartners#63': `Birleşik Krallık merkezli bir Girişim Şirketi olan Accelerated Digital Ventures firmasında Yönetim Kurulu Başkanı ve Yatırım Komitesi Başkanıyım.`,
    'teamAdvisersPartners#64': `Birleşik Krallık'ta doğdum ve büyüdüm. Daha öncesinde Kaliforniya'nın Palo Alto bölgesinde Archimedes Labs şirketinin kurucusu ve ortağıyım. Ürünler yaratmak, hikâyeler anlatmak ve bunları gerçeğe dönüştürmek için kurucular, ekipler, tasarımcılar ve mühendislerle çalışmaktan keyif alıyorum.`,
    'teamAdvisersPartners#65': `1980'li yıllarından beri sayısız şirketi bizzat kurdum veya kuruluşuna ortaklık ettim. Şirketlerimden ikisi "Unicorn" (tek boynuzlu at) olarak nitelendirildi ve insanlar tarafından 1 milyar doların üzerinde değer biçildi. Hayatım boyunca hep değişimin yaşandığı noktaya odaklandım. 1980'lerdeki ağ kurulumları ve veri tabanları. 1994-1998 arasında İnternet Erişimi. 1998-2010 yılları arasında İnternet Hizmetleri ve İçerik, Mobil Tüketici Uygulamaları ve 2017 yılından bu yana Blok Zinciri.`,
    'teamAdvisersPartners#66': `Kariyer ve projeler: Tech Crunch, Accelerated Digital Ventures, cScape, EasyNet, Cyberia, RealNames, Venture Network, ICOBox, Crypterium, R/Block, Fluz, EnergiMine, Archimedes Labs ve CINDX`,
    'teamAdvisersPartners#67': `Austin Kimm`,
    'teamAdvisersPartners#68': `Uluslararası Finans Hizmetleri CEO'su`,
    'teamAdvisersPartners#69': `30 yılı aşkın finans hizmetleri deneyimi`,
    'teamAdvisersPartners#70': `Değeri 500 milyon dolara ulaşan şirketler kurma`,
    'teamAdvisersPartners#71': `Tecrübesi, aldığı sonuçlarla kanıtlanmış olan bir finans hizmetleri CEO'su olarak gelişmekte olan pazarlarda sigorta şirketleri kurmaya odaklanmış durumdayım. Bugüne kadar kurmuş olduğum şirketlerin güncel değeri 500 milyon doların üzerindedir. Yakın zamanda Rusya'da (10 yıl) sigorta sektörü harici kıdemli yönetim pozisyonlarında bulundum.`,
    'teamAdvisersPartners#72': `Bunlar arasında Rusya'nın en büyük İnternet satış istihdam platformu Workle'nin CEO'luğu ve dünyanın ilk dijital kripto bankası Crypterium da dâhil olmak üzere, çok sayıda fintech girişiminde C seviyesinde pozisyon da bulunuyor.`,
    'teamAdvisersPartners#73': `Kariyer ve projeler: Aviva, Commercial Union UK, Reinaissance Insurance, Kimm Health & Leisure Ltd, Workle, Crypterium, CryptoIndex, CINDX`,
    'teamAdvisersPartners#74': `Philip Staehelin`,
    'teamAdvisersPartners#75': `25 yıllık danışmanlık ve girişimcilik deneyimi`,
    'teamAdvisersPartners#76': `Liderliğindeki işletmelerde 500 milyon dolar değerinde alternatif ödeme yöntemi kullanımı`,
    'teamAdvisersPartners#77': `20 ülkede 200'den fazla startup şirkete mentorluk`,
    'teamAdvisersPartners#78': `Bulaşıcı iyimserliği pragmatik gerçekçilikle birleştiren bir lider ve yenilikçiyim. Kimsenin görmediği yerlerdeki fırsatları görüyorum.`,
    'teamAdvisersPartners#79': `"Farklı görme" ve "gerçekleştirme" becerilerimi kurumsal, danışmanlık ve girişimcilik alanlarında kullanarak yeni ve dönüşüm odaklı fikirler üretebileceğim yeni perspektifler kazandım.`,
    'teamAdvisersPartners#80': `Sabahları yataktan fırlayarak uyanmamı sağlayan şey, zorlu konularda çözüm üretme isteğimdir.`,
    'teamAdvisersPartners#81': `Kariyer ve projeler: Roland Berger, Dot Glasses, Transparency International, StartupYard, Bethereum, Gjirafa Inc, Accenture, CINDX`,
    'teamAdvisersPartners#82': `Amarpreet Singh`,
    'teamAdvisersPartners#83': `Global Blok Zinciri Kuruluşunda Kıdemli Danışman`,
    'teamAdvisersPartners#84': `Microsoft, Dünya Bankası ve Airbus deneyimi`,
    'teamAdvisersPartners#85': `Blok Zinciri projelerinde Yönetim Kurulu Danışman Üyesi`,
    'teamAdvisersPartners#86': `Teknoloji sektöründe operasyon, danışmanlık ve yenilikçilik gibi alanlarda yılların deneyimine sahip bir profesyonel ve Teknoloji/Dijitalleşme hayranı.`,
    'teamAdvisersPartners#87': `Microsoft ve AWS sertifikalı bir Bulut Bilişim uzmanı. Çok yönlülüğü ve esnekliğiyle tanınıyor. Mükemmel analitik, stratejik ve liderlik becerilerinin yanı sıra harika bir takım oyuncusu.`,
    'teamAdvisersPartners#88': `Uzmanlık alanları: Teknoloji Danışmanlığı, Operasyon, Bulut Bilişim, Fintech, Yenilik, ERP, Yapay Zeka Öğrenimi, Hesap Yönetimi, Ortaklık Kurulumu, İş Geliştirme ve Strateji Amarpreet Singh epey geniş bir yelpazeye uzanan bir iş ve eğitim geçmişine sahip.`,
    'teamAdvisersPartners#89': `Üç alanda Yüksek Lisans sahibi ve Hindistan, Singapur, Fransa, Çin, Güney Afrika, Kore ve Kanada gibi farklı yerlerde yaşadı, çalıştı ve eğitim aldı.`,
    'teamAdvisersPartners#90': `Kariyer ve projeleri: Microsoft, Dünya Bankası, Airbus, TokenAsia Platformu, GOeurika, CINDX`,
    'teamAdvisersPartners#91': `Tyler Sanford`,
    'teamAdvisersPartners#92': `Yelp ve Zenefits'te 8 Yıllık Dijital Pazarlama Deneyimi`,
    'teamAdvisersPartners#93': `Toplam 225 milyon doların üzerinde sermaye topladığı 12 ICO`,
    'teamAdvisersPartners#94': `Blok zincirini kullanıma sokan ilk kişilerden birin`,
    'teamAdvisersPartners#95': `Sporcu olarak yetişmek, hem kariyerimde hem de kişisel yaşamımda kullanabileceğim bir dizi becerilere sahip olmamı sağladı.`,
    'teamAdvisersPartners#96': `Herkesten biraz daha fazla gayret sarf etmemin sonucu olarak, her profesyonel kariyerde karşılaşılan düşüş ve yükselişlerle başa çıkmayı öğrenme fırsatına sahip olduğumu görecek kadar şanslıyım.`,
    'teamAdvisersPartners#97': `Tamamen kendi kendine motive olan bir insan olarak her daim sahip olduğum bilgi dağarcığını büyütme ve ticaretin her alanında yeteneklerimi geliştirmeye odaklanıyorum.`,
    'teamAdvisersPartners#98': `Her daim zorluklarla başa çıkmaya hazırım ve motivasyonumu, hedeflerime ulaşmak için zorlukları aşma fikrinden alıyorum.`,
    'teamAdvisersPartners#99': `Kariyer ve projeler: IPG Holdings, DataBlockChain, TraXion by Puma Technologies, ELYSIAN, Etherinc, FTEC Foundation, CINDX`,
    'teamAdvisersPartners#125': `Bogdan Fiedur`,
    'teamAdvisersPartners#126': `Blok zinciri ve kripto döviz uzmanı, yatırımcı, girişimci`,
    'teamAdvisersPartners#127': `bitJob Kurucu Ortağı ve Blockchainexperts.io Başkanı`,
    'teamAdvisersPartners#128': `ICO Danışmanı, ICOBench Uzmanı`,
    'teamAdvisersPartners#129': `Bogdan Fiedur bir akıllı kontrat geliştiricisi, kripto yatırımcısı, girişimci ve http://blockchainexperts.io platformunun başkanı. 20 yılı aşkın BT deneyiminde sayısız e-ticaret sitesi kurdu ve son 3 yılını blok zinciri geliştirmeye adadı.`,
    'teamAdvisersPartners#130': `Bunun yanı sıra, bugüne kadar birbirinden başarılı 20 ICO projesine danışmanlık yaptı ve yaşadığı yer olan Winnipeg'deki yerel kripto camiasına blok zinciri ve akıllı kontrat yazılımları konusunda sunumlar yapmaya ve workshop'lar düzenlemeye kendini adadı`,
    'teamAdvisersPartners#131': `Bogdan artık tamamen Blok Zinciri sektörüne odaklanmış durumda ve Blok Zinciri uzmanlarına danışmanlık hizmetleri ve ağ desteği veriyor.`,
    'teamAdvisersPartners#132': `Bogdan'ın en son projesi, öğrenciler için blok zinciri tabanlı bir freelance platformu olan 'Bitjob' sitesinin kurucu ortağıydı ve PayPie.com gibi çeşitli ICO projelerine ekip üyesi olarak katıldı. Kariyer ve projeler: ABD Blok Zinciri Birliği, Tuurnt, Trends Project, BiNeuro, Zichain, Graphen Tech, CyClean, Swachhcoin, CINDX`,
    'teamAdvisersPartners#133': `Graham Doggart`,
    'teamAdvisersPartners#134': `20 yıllık girişim geliştirme, fintech pazarlama ve uyumluluk deneyimi`,
    'teamAdvisersPartners#135': `Değeri 100 milyon doları aşan kampanya yönetimi`,
    'teamAdvisersPartners#136': `Bu yıl içerisinde 10'un üzerinde blok zinciri projesinde danışmanlık`,
    'teamAdvisersPartners#137': `Stealth Kripto Döviz Projesinin yönetim kurulu başkanı ve kurucu ortağı olmamın yanı sıra, 2012 yılında kurulan bir Blok Zinciri ve Fintech Danışmanlık şirketi olan Dynamic Abundance'ın baş stratejistiyim. Uzmanlık alanım, token ihraçlarını yapılandırma ve paketleme.`,
    'teamAdvisersPartners#138': `Bugüne kadar uluslararası alanda sayısız blok zinciri, kripto döviz ve ICO projesinde çalıştım.`,
    'teamAdvisersPartners#139': `20 yılı aşkın bir süredir teknoloji yönetimi danışmanlığı, hukuki ve finansal uyumluluk danışmanlığı, büyüme stratejileri, yatırımcı ilişkileri ve tasarım ve yazarlık materyalleri üzerinde çalışıyorum.`,
    'teamAdvisersPartners#140': `Kariyer ve projeler: Stealth Kripto Döviz Projesi, Dynamic Abundance, ELYSIAN, Fox Trading FX, Profede, Worltdopoly, CINDX`,
    'teamAdvisersPartners#141': `Sadie Hutton`,
    'teamAdvisersPartners#142': `25 yıllık kıdemli yönetim ve yönetici danışmanlığı deneyimi`,
    'teamAdvisersPartners#143': `Değeri 75 milyon paunda ulaşan kampanyalarla milyon dolarlık sermaye toplama`,
    'teamAdvisersPartners#144': `8 projenin ICO Danışmanı`,
    'teamAdvisersPartners#145': `Bir blok zinciri danışmanlık kuruluşu olan Dynamic Abundance'nin kurucusuyum.`,
    'teamAdvisersPartners#146': `İşlerle bizzat ilgilenmeyi tercih eden birisi olarak, ICO analizi ve proje yönetimi gibi ICO sürecinin en önemli aşamalarında uzmanlaştım. İş yönetimi ve büyütme becerilerim sayesinde bir projeyi başlangıcından ihracına kadar her aşamasında ilerletmeyi hedefliyorum.`,
    'teamAdvisersPartners#147': `Yapısal olarak çözüm üretmeye odaklıyım ve ilgilendiğim her projeyi kişisel projem olarak görüyorum. Kazanmayı seviyorum! 20 yılı aşkın yönetim deneyimim sayesinde büyük bir ağ oluşturdum ve aktif olarak yüksek seviyeli blok zinciri projelerinde finans, teknoloji, satış, pazarlama ve kalite güvencesi danışmanlığı yapıyorum.`,
    'teamAdvisersPartners#148': `Kariyer ve projeler: Dynamic Abundance, ELYSIAN, Worldopoly, Confidential ICO, Fox Trading FX, Profede, Market Digital, CINDX`,
    'teamAdvisersPartners#149': `Jason King`,
    'teamAdvisersPartners#150': `20 yıllık yönetim deneyimi`,
    'teamAdvisersPartners#151': `30 ülkede şirket faaliyetleri yürütme deneyimi`,
    'teamAdvisersPartners#152': `500 milyon dolar değerindeki K/Z'den sorumlu`,
    'teamAdvisersPartners#153': `Jason King, 20 yıla yakın bir süredir teknoloji, medya ve telekomünikasyon yöneticisi olarak kurumsal anlaşmaları yapılandırma ve tedarik etme, kazançlı pazarlıklar yapma, pazarlar oluşturma ve organizasyonları başarılı olacak şekilde konumlandırma üzerine çalışıyor.`,
    'teamAdvisersPartners#154': `Bu zorlukların büyük bir kısmı, beni birbirinden başarılı yeniden yapılandırma ve işleri tersine çevirme pozisyonlarına taşıdı.`,
    'teamAdvisersPartners#155': `En kârlı hedeflere ulaşmak için doğru insanlardan oluşan doğru ekipler kurmanın gerekli olduğuna inanıyorum.`,
    'teamAdvisersPartners#156': `Jason; Şirket ve Operasyon Yönetimi, Stratejik Planlama ve Finans, Kripto Döviz ve Blok Zinciri sektörü gibi çeşitli alanlarda kapsamlı tecrübelere sahip.`,
    'teamAdvisersPartners#157': `Motti Peer`,
    'teamAdvisersPartners#158': `Ödüllü global PR ajansı Blonde 2.0'ın kurucu ortağı`,
    'teamAdvisersPartners#159': `Güvenlik ve finans sektörlerinde çeşitli şirketlerin kurucusu.`,
    'teamAdvisersPartners#160': `Motti, Blockchain ve Crypto için PR, startups, VCs'nin önde gelen güçlerinden biridir.`,
    'teamAdvisersPartners#161': `Motti, güvenlik ve finans sektörlerinde çeşitli şirketler kurdu. Sermaye ve yatırım fonu yöneticisi olarak yılların deneyimine sahip olan Motti, Manchester Üniversitesinden Finans ve Pazarlama alanında Yüksek Lisans ve Fairleigh Dickinson Üniversitesinden İş Yönetimi alanında Lisans sahibi.`,
    'teamAdvisersPartners#162': `Ödüllü bir global PR ajansı olan ve Forbes tarafından girişim dünyasında "Yeri Yerinden Oynatan" (Movers and Shakers) markalarından biri olarak seçilen Blonde 2.0 markasının Eş CEO'su. Blonde 2.0 markasının Eş CEO'su olarak Halka İlişkiler konularının yanı sıra strateji ve kriz yönetiminden de sorumlu.`,
    'teamAdvisersPartners#163': `35 profesyonelden oluşan bir ekibe sahip olan Blonde 2.0 markası, Blok Zinciri ve Kripto sektörlerinde startuplar ve VC'ler için önde gelen PR uzmanlarından biri.`,
    'teamAdvisersPartners#164': `Leonard Grayver`,
    'teamAdvisersPartners#165': `Greenberg, Whitcombe ve Takeuchi'de Ortak`,
    'teamAdvisersPartners#166': `400'den fazla startup temsil etme deneyimi`,
    'teamAdvisersPartners#167': `Hukuk fakültesinde öğrenciyken startup şirketi için 18 milyon USD'nin üzerinde sermaye topladı`,
    'teamAdvisersPartners#168': `Leonard Grayver, SSCB'de doğdu ve çocukken ailesiyle birlikte ABD'ye yerleşti. Leonard, Hukuk fakültesinde öğrenciyken bir girişim kurdu ve başarılı bir şekilde 18 milyon USD'nin üzerinde finansman topladı.`,
    'teamAdvisersPartners#169': `Girişimi en nihayetinde başarıya ulaşamadı ama Leonard, 400'ün üzerinde startup'a yardımcı oldu.`,
    'teamAdvisersPartners#170': `Genel olarak Leonard'ın Girişim Fonu finansmanı, fon yapılandırması ve durum analizi alanlarında 10 yılı aşkın deneyimi bulunuyor ve hem fonları hem de sınırlı ortakları temsil ediyor. Girişimcilere en büyük tavsiyesi trendleri değil, merak ettikleri şeyleri takip etmeleri. Leonard, çeşitli uluslararası girişim sermayeleriyle güçlü profesyonel bağlantılar kurmayı başardı.`,

    'joinTokenPreSale#1': `Token Ön Satışına Katılın!`,
    'joinTokenPreSale#2': `Ön Satışa Katılın`,
    'joinTokenPreSale#3': `MVP'yi Test Edin `,
    'joinTokenPreSale#4': `Merkez Ofis `,
    'joinTokenPreSale#5': `Harjumaa, Erika 14,`,
    'joinTokenPreSale#6': `Talinn, 10416, Estonia`,
    'joinTokenPreSale#7': `Ticari Konular | hello@cindx.io`,
    'joinTokenPreSale#8': `Yasal Uyarı`,
    'joinTokenPreSale#9': `Geliştirme ve Pazarlama`,
    'joinTokenPreSale#10': `Presnenskaya naberezhnaya, 8 building 1,`,
    'joinTokenPreSale#11': `Moscow, 123112, Russia`,
    'joinTokenPreSale#12': `Kariyer | Ekibimize Katılın |`,
}

export default tr