// Вьетнамский
const vi = {
    'mainBlock#1': 'Giúp việc đầu tư tiền điện tử',
    'mainBlock#2': 'dễ dàng, an toàn và nhanh chóng.',
    'mainBlock#3': 'Tham gia đợt bán token chứng khoán của chúng tôi',

    'icoInfo#1': 'Chúng tôi đồng ý:',
    'icoInfo#2': 'Vốn cứng:',
    'icoInfo#3': 'Mốc vốn mềm:',
    'icoInfo#4': 'Liệt kê các thỏa thuận được ký với',

    'menu#1': 'SÁCH TRẮNG',
    'menu#2': 'BẢN TRÌNH BÀY',
    'menu#3': 'TÀI LIỆU MỘT TRANG ',
    'menu#4': 'MÔ HÌNH TÀI CHÍNH',
    'menu#5': 'TÀI LIỆU PHÁP LÝ',
    'menu#6': 'EN',
    'menu#7': 'Sản phẩm',
    'menu#8': 'Chi tiết bán',
    'menu#9': 'Nhóm',
    'menu#10': 'Tài liệu công khai',
    'menu#11': 'Kiểm tra MVP',

    'mailForm#1': 'Wrong email',
    'mailForm#2': 'sending ..',
    'mailForm#3': 'Already was or is not valid, try again',
    'mailForm#4': 'Your email has been sent successfully',
    'mailForm#5': 'an error occurred, try again',
    'mailForm#6': 'GDRP Сompliance',
    'mailForm#7': 'Personal data provided via Subscription form and KYC procedure will be collected in the full compliance with GDRP',
    'mailForm#8': 'The Data Protection Officer  of the project is  Mrs. Sofja Pevzner-Belositski. Contact details: dpo@cindx.io. Any data subject may, at any time, contact Data Protection Officer of directly with any request related to data protection.',
    'mailForm#9': 'Your personal data provided via Subscription form and KYC procedure will be shared to our partners:',
    'mailForm#10': 'ICO Promo',
    'mailForm#11': 'Privacy Policy',
    'mailForm#12': 'Sum & Substance',
    'mailForm#13': 'By default, the personal data provided by subscriber are kept by CINDX, ICO Promo and Sum & Substance for 5 years after registration of subscriber in the system',
    'mailForm#14': 'If you do not agree to this privacy policy, please do not use our site.',
    'mailForm#15': 'By using our site, you consent to the collection and use of information by us. Owing to the global nature of the internet infrastructure, the information you provide may be transferred in transit to countries outside the European Economic Area that do not have similar protections in place regarding your data and its use as set out in this policy.',
    'mailForm#16': 'However, we have taken the steps outlined above to try to improve the security of your information. By submitting your information you consent to these transfers',
    'mailForm#17': 'I agree to process my',
    'mailForm#18': 'personal data',
    'mailForm#19': 'Security Token Sale Starts with',
    'mailForm#20': '20% BONUS',
    'mailForm#21': 'Nhận token trước những người khác Ưu đãi hết hạn trong',
    'mailForm#22': 'Token sale starts in',
    'mailForm#23': 'Start from $1',
    'mailForm#24': '$1 later',
    'mailForm#25': 'Email của bạn',
    'mailForm#26': 'Tham gia đợt bán trước',
    'mailForm#27': 'AGREE & SUBMIT',
    'mailForm#28': 'Get it before everyone else does Offer expires within',
    'mailForm#29': 'Want to get the latest news and upcoming offers?',

    'docPopup#1': 'Nhận tất cả các tài liệu trong email của bạn',
    'docPopup#2': 'Nhập email của bạn',
    'docPopup#3': 'Gửi cho tôi Docs',

    'progressBarSale#1': 'Bonuses',
    'progressBarSale#2': 'in CINX',
    'progressBarSale#3': 'Pre-Sale',
    'progressBarSale#4': 'Sale',
    'progressBarSale#5': 'Aug 26',
    'progressBarSale#6': 'Sep 17',
    'progressBarSale#7': 'Oct 8',
    'progressBarSale#8': 'Oct 22',
    'progressBarSale#9': 'Nov 6',
    'progressBarSale#10': 'Nov 19',
    'progressBarSale#11': 'Dec 3',
    'progressBarSale#12': 'Dec 17',

    'ourTopRatings#1': 'Our Top Ratings',

    'cryptoAssetsManagement#1.1': 'CIDNX là Trung tâm quản lý tài sản điện tử. Chúng tôi giải quyết các vấn đề của nhà đầu tư,',
    'cryptoAssetsManagement#1.2': 'nhà giao dịch và nhà phát triển',
    'cryptoAssetsManagement#2': 'CINDX.MARKETPLACE CHO NHÀ ĐẦU TƯ',
    'cryptoAssetsManagement#3': 'Bạn không cần phải lo lắng về kiến thức và kinh nghiệm của mình - các chuyên gia về giao dịch tiền điện tử luôn sẵn sàng hỗ trợ bạn',
    'cryptoAssetsManagement#4': 'Kiểm soát quỹ tiền điện tử của bạn: tiền luôn ở trong ví của bạn',
    'cryptoAssetsManagement#5': 'Chỉ trả phí nếu bạn kiếm được tiền: bạn chỉ phải trả phí nếu danh mục đầu tư của bạn sinh lời',
    'cryptoAssetsManagement#6': 'TEST MVP',
    'cryptoAssetsManagement#7': 'CINDX.TERMINAL CHO NHÀ GIAO DỊCH',
    'cryptoAssetsManagement#8': 'Nếu bạn là nhà giao dịch thành công, bạn có thể thu hút vốn mà không mất tiền đầu tư vào tiếp thị',
    'cryptoAssetsManagement#9': 'Chúng tôi cung cấp cho bạn Thiết bị đầu cuối, Cửa hàng ứng dụng, thị trường và các công cụ nâng cao khác để giúp bạn giao dịch thành công',
    'cryptoAssetsManagement#10': 'CINDX giúp bạn kiếm tiền từ danh tiếng và chuyên môn của mình. Lịch sử giao dịch và ảnh hưởng của bạn rất rõ ràng',
    'cryptoAssetsManagement#11': 'CINDX.TALK, CINDX.HUB & CINDX.DAO',
    'cryptoAssetsManagement#12': 'CINDX.Talk - mạng xã hội trao thưởng cho nội dung hữu ích',
    'cryptoAssetsManagement#13': 'CINDX.Hub - các thành phần bao gồm "tủ của nhà cung cấp", cũng như trung tâm thử nghiệm và tích hợp phần mềm của bên thứ ba',
    'cryptoAssetsManagement#14': 'CINDX.dao - thành phần cho phép bạn thực hiện hệ thống bỏ phiếu cho cộng đồng dựa trên các quy tắc tổ chức tự quản phi tập trung',

    'teamLegal#1': 'CHÚNG TÔI CÓ MỘT ĐỘI NGŨ TUYỆT VỜI VÀ',
    'teamLegal#2': 'Legal and Regulatory Organizational Framework',
    'teamLegal#3': 'CRYPTOCURRENCY EXCHANGE LICENSE',
    'teamLegal#4': 'FINANCIAL INSTITUTION LICENSE',
    'teamLegal#5': 'CRYPTO WALLET LICENSE',
    'teamLegal#6': 'SÁCH TRẮNG',
    'teamLegal#7': 'BẢN TRÌNH BÀY',
    'teamLegal#8': 'TÀI LIỆU MỘT TRANG ',
    'teamLegal#9': 'MÔ HÌNH TÀI CHÍNH',
    'teamLegal#10': 'TÀI LIỆU PHÁP LÝ',

    'roadmap#1': 'Lộ trình',
    'roadmap#2': 'SCENARIO',
    'roadmap#3': 'We are building the base for the CINDX platform. At this step, the Minimum Viable Product (MVP) is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform.',
    'roadmap#4': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be  going through some alterations to add functionalities.  ',
    'roadmap#5': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services.      ',
    'roadmap#6': 'At this stage, the CINDX.market and CINDX.trade components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. ',
    'roadmap#7': 'CINDX.talk will have public and private channels. At this stage, the content will  be able to be  separated. ',
    'roadmap#8': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade is an extremely flexible system of order execution and risk management. The Vendor’s market will appear; however, at this point, the Vendor’s market will only contain applications developed by CINDX and its partners.  ',
    'roadmap#9': 'A tokenized rating system will be added in the final version of CINDX.talk, as well as a new type of product: “algorithmic trading”. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders.   ',
    'roadmap#10': 'We are building the base for the CINDX platform. At this step, the MVP is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform. ',
    'roadmap#11': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be going through some alterations to add functionalities.  ',
    'roadmap#12': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services. Another new component, CINDX.hub, will enable Vendors to develop applications that will analyze the market data that CINDX provides. ',
    'roadmap#13': 'At this stage, the CINDX.market and CINDX.trade components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. An SDK for developers will be released. This should simplify application development and implementation for CINDX.  ',
    'roadmap#14': 'CINDX.talk will have public and private channels. At this stage, the content will be able to be separated. CINDX.hub will integrate Github, which will simplify application development even more.',
    'roadmap#15': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade will be an extremely flexible system of order execution and risk management. CINDX.hub will have a full-scale editor for trading strategies with a testing system based on historical market data.',
    'roadmap#16': 'A tokenized rating system  CINDX.talk will be added in the final version of CINDX.talk. This will provide a system of assessment for CINDX community trading experts. “Algorithmic trading” will also be added. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders. A high-grade platform for a code audit will be created. ',
    'roadmap#17': 'We are building the base for the CINDX platform. At this step, the MVP is developed. The MVP allows an access to exchanges and replication protocol. A large portion of our resources is allocated to the scalability and security of the platform.',
    'roadmap#18': 'The CINDX.alpha version of the platform will be released. This includes a blockchain architecture and a basic system of settlement via smart contracts. The CINDX.market and CINDX.trade components will be  going through some alterations to add functionalities. ',
    'roadmap#19': 'Based on the blockchain architecture of the CINDX.alpha version, we will produce the CINDX.talk component. This will allow users to communicate, learn and earn with useful content. Additionally, an analytical module will be added to the CINDX.core component of the platform to analyze the market information and present it to the third-party services. Another new component,  CINDX.hub, will enable Vendors to develop applications that will analyze the market data that CINDX provides. The team will develop CINDX.dao, a component that acts as a system for the platform’s revenue distribution to its token holders.       ',
    'roadmap#20': 'At this stage, the CINDX.market and CINDX.trade  components will be added. Managers can create index-based products, and the trading terminal is integrated with a flexible setting of risk management. An SDK for developers will be released. This should simplify application and implementation development for CINDX.  ',
    'roadmap#21': 'CINDX.talk will have public and private channels. At this stage the content can be separated. CINDX.hub will integrate Github which will simplify application development even more.',
    'roadmap#22': 'There will be a big update for the platform at this stage: users will be able to store and exchange cryptocurrencies and fiat. CINDX.trade will be an extremely flexible system of order execution and risk management. CINDX.hub has a full-scale editor for trading strategies with a testing system based on historical market data. CINDX.dao will receive a voting system for token holders. ',
    'roadmap#23': 'A tokenized rating system CINDX.talk will be added in the final version of CINDX.talk. This will provide a system of assessment for CINDX community trading experts. “Algorithmic trading” will also be added. We will also add an automatic arbitrage function that will operate between exchanges and multi-exchange orders. A high-grade platform for a code audit will be created. ',

    'problemSolving#1': 'Thời gian',
    'problemSolving#2': 'Trust',
    'problemSolving#3': 'Tính không chắc chắn',
    'problemSolving#4': 'Tôi có ít tiền để đầu tư vào tiền điện tử, nhưng không có thời gian để nghiên cứu và liên hệ với các nhà giao dịch chuyên nghiệp để quản lý danh mục đầu tư của tôi',
    'problemSolving#5': 'Tôi luôn cảm thấy không thoải mái với ý tưởng trao tiền cho người khác để kiếm lời',
    'problemSolving#6': 'Công nghệ xung quanh giao dịch tiền diện tử không thân thiện với người dùng. Tôi không thể tìm ra cách giao dịch đồng tiền của mình',
    'problemSolving#7': 'CINDX cho phép bạn tiếp cận các nhà giao dịch đã được đánh giá và đáng tin cậy',
    'problemSolving#8': 'Trên nền tảng CINDX, tiền không bao giờ rời khỏi ví của bạn',
    'problemSolving#9': 'Bạn kiếm tiền cùng với các nhà giao dịch tốt nhất trên thị trường',
    'problemSolving#10': 'Các nhà giao dịch trên CINDX được đánh giá theo lịch sử giao dịch thành công của họ. Chọn nhanh nhà giao dịch phù hợp với bạn',
    'problemSolving#11': 'Hệ thống phi tập trung và hợp đồng thông minh của chúng tôi cho phép quỹ vốn của bạn được quản lý mà không bị chuyển sang một nhà giao dịch',
    'problemSolving#12': 'Mỗi nhà đầu tư trong CINDX đều có cơ hội được các nhà giao dịch thành công nhất trên thị trường quản lý quỹ vốn cho họ',
    'problemSolving#13': 'CINDX giải quyết những vấn đề gì?',
    'problemSolving#14': 'TEST MVP',

    'howCindxWorks#1': 'Nhà đầu tư',
    'howCindxWorks#2': 'Nhà giao dịch',
    'howCindxWorks#3': 'Nhà cung cấp',
    'howCindxWorks#4': 'tăng thu nhập từ tiền điện tử bằng kỹ năng quản lý danh mục đầu tư của các nhà giao dịch hàng đầu',
    'howCindxWorks#5': 'kiếm tiền hoa hồng từ các nhà đầu tư, theo dõi họ dựa trên hiệu suất và chiến lược giao dịch của họ',
    'howCindxWorks#6': 'bán các công cụ giao dịch nâng cao, như chương trình giao dịch và tiện ích tin tức.',
    'howCindxWorks#7': 'nhận tiền hoa hồng và phí đăng ký',
    'howCindxWorks#8': 'Tôi tham gia CINDX với tài sản điện tử mà tôi muốn được giao dịch',
    'howCindxWorks#9': 'Tôi tham gia CINDX với chuyên môn giao dịch sẽ mang lại lợi ích cho nhà đầu tư',
    'howCindxWorks#10': 'Tôi tham gia CINDX với ứng dụng giao dịch sẽ giúp ích cho nhà đầu tư',
    'howCindxWorks#11': 'Chúng tôi giúp việc giao dịch trở nên dễ dàng, an toàn và sinh lời',
    'howCindxWorks#12': 'Tóm tắt: Cách thức hoạt động của CINDXs',

    'marketAnalytics#1': 'Phân tích thị trường',
    'marketAnalytics#2': 'AUM toàn cầu',
    'marketAnalytics#3': 'Đầu tư',
    'marketAnalytics#4': 'Structure of investment',
    'marketAnalytics#5': 'Từ năm 2000, thị trường quản lý tài sản toàn cầu đã tăng hơn 250%.',
    'marketAnalytics#6': 'Đây là kết quả của việc cải tiến liên tục công cụ thị trường và sự phát triển chung của cấu trúc thị trường.',
    'marketAnalytics#7': 'Mặc dù thị trường tiền điện tử tăng trưởng bùng nổ trong năm 2017, nhưng ngành công nghiệp này vẫn còn trong giai đoạn trứng nước.',
    'marketAnalytics#8': 'Tổng giá trị vốn hóa thị trường là 600 tỷ đô la vào cuối năm 2017 - chỉ bằng 1% tổng giá trị vốn hóa thị trường của ngành quản lý tài sản.',
    'marketAnalytics#9': 'SÁCH TRẮNG',
    'marketAnalytics#10': 'BẢN TRÌNH BÀY',
    'marketAnalytics#11': 'ONE PAGER',
    'marketAnalytics#12': 'MÔ HÌNH TÀI CHÍNH',
    'marketAnalytics#13': 'TÀI LIỆU PHÁP LÝ',
    'marketAnalytics#14': 'Geographic Scope',
    'marketAnalytics#15': '25 triệu tiềm năng',
    'marketAnalytics#16': 'ví blockchain',
    'marketAnalytics#17': '200.000 giao dịch tiềm',
    'marketAnalytics#18': 'năng mỗi ngày',
    'marketAnalytics#19': 'Hơn 225 đối tác tiềm năng,',
    'marketAnalytics#20': 'mỗi đối tác có 3-5 tỷ đô la',

    'tokenSaleDetails#1': 'Phân bổ token',
    'tokenSaleDetails#2': 'Nhóm',
    'tokenSaleDetails#3': 'Bounty',
    'tokenSaleDetails#4': 'Cố vấn',
    'tokenSaleDetails#5': 'Dự trữ',
    'tokenSaleDetails#6': 'Tài trợ cộng đồng',
    'tokenSaleDetails#7': 'Hỗ trợ thanh khoản token',
    'tokenSaleDetails#8': 'Có sẵn để bán',
    'tokenSaleDetails#9': 'Tên token: CINX',
    'tokenSaleDetails#10': 'Đợt bán trước token bắt đầu vào:',
    'tokenSaleDetails#11': 'Tổng lượng phát hành:',
    'tokenSaleDetails#12': 'Giá mỗi token: 1 đô la',
    'tokenSaleDetails#13': 'Số tiền đầu tư tối thiểu:',
    'tokenSaleDetails#14': 'tương đương 50 đô la',
    'tokenSaleDetails#15': 'SÁCH TRẮNG',
    'tokenSaleDetails#16': 'BẢN TRÌNH BÀY',
    'tokenSaleDetails#17': 'TÀI LIỆU MỘT TRANG',
    'tokenSaleDetails#18': 'MÔ HÌNH TÀI CHÍNH',
    'tokenSaleDetails#19': 'TÀI LIỆU PHÁP LÝ',
    'tokenSaleDetails#20': 'Sử dụng tiền thu được',
    'tokenSaleDetails#21': 'Tiếp thị và PR 21%',
    'tokenSaleDetails#22': 'Nghiên cứu và phát triển 41%',
    'tokenSaleDetails#23': 'Hoạt động 28%',
    'tokenSaleDetails#24': 'Chi phí pháp lý 7%',
    'tokenSaleDetails#25': 'Tiền thưởng của nhà giao dịch 3%',
    'tokenSaleDetails#26': 'Token Deals',
    'tokenSaleDetails#27': 'Token Sale:',
    'tokenSaleDetails#28': 'Tiền thưởng bán Token',
    'tokenSaleDetails#29': 'Aug 26 - Sep 16 - 25% Bonus',
    'tokenSaleDetails#30': 'Sep 17 - Oct 7 - 20% Bonus',
    'tokenSaleDetails#31': 'Tiền thưởng bán chính token:',
    'tokenSaleDetails#32': '8 tháng 10 - 21 tháng 10 - Tiền thưởng 17%',
    'tokenSaleDetails#33': '22 tháng 10 - 4 tháng 11 - Tiền thưởng 15%',
    'tokenSaleDetails#34': '5 tháng 11 - 18 tháng 11 - Tiền thưởng 13%',
    'tokenSaleDetails#35': '19 tháng 11 - 2 tháng 12 - Tiền thưởng 10%',
    'tokenSaleDetails#36': '3 tháng 12 - 16 tháng 12 - Tiền thưởng 5%',
    'tokenSaleDetails#37': '17 tháng 12 - 26 tháng 12 - Tiền thưởng 0%',
    'tokenSaleDetails#38': 'Mua token',
    'tokenSaleDetails#39': 'Chi tiết bán token',
    'tokenSaleDetails#40': 'During the token sale, investors purchase utility tokens – options [CINXO], which give them the right to receive security tokens [CINX] in the future.',
    'tokenSaleDetails#41': 'Security tokens [CINX] will be issued and distributed following the prospect of emission published on the website of FSA of Estonia https://www.fi.ee/ and cindx.io after the end of the token sale, but no later than Q1 2019.',
    'tokenSaleDetails#42': 'The holder of [CINXO] tokens has the right but no obligation to exchange options for security tokens with a ratio of 1:1 after completing the KYC procedure with identification signature, address confirmation and supply of other documents (see the KYC diagram).',
    'tokenSaleDetails#43': 'Tokens [CINXO] grant the same rights as security tokens apart from the right to participate in revenue distribution with a lock-up and voting on the platform.',

    'legalSchedule#1': 'Lịch trình pháp lý',
    'legalSchedule#2': 'ĐÃ NHẬN ĐƯỢC GIẤY PHÉP (FVR000110) CUNG CẤP TRAO ĐỔI GIỮA TIỀN ẢO VÀ DỊCH VỤ FIAT',
    'legalSchedule#3': 'ÁP DỤNG CHO ĐĂNG KÝ THƯƠNG HIỆU Ở ESTONIA VÀ CHÂU ÂU',
    'legalSchedule#4': 'GIẤY PHÉP FFA000254 ĐỂ HOẠT ĐỘNG NHƯ MỘT TỔ CHỨC TÀI CHÍNH',
    'legalSchedule#5': 'ĐÃ NHẬN ĐƯỢC GIẤY PHÉP FFA000254 ĐỂ HOẠT ĐỘNG NHƯ MỘT TỔ CHỨC TÀI CHÍNH',
    'legalSchedule#6': 'Triển khai Bản cáo bạch phù hợp với luật Estonia',
    'legalSchedule#7': 'ĐÃ NHẬN ĐƯỢC GIẤY PHÉP FSA (Cơ quan giám sát tài chính Estonia)',
    'legalSchedule#8': 'ĐÃ NHẬN ĐƯỢC GIẤY PHÉP ĐỂ CUNG CẤP DỊCH VỤ VÍ TIỀN ẢO',
    'legalSchedule#9': 'ĐĂNG KÝ THEO MỤC MIỄN TRỪ D TẠI SEC',
    'legalSchedule#10': 'ĐÃ CHỈ ĐỊNH NHÀ QUẢN LÝ DỮ LIỆU CÁ NHÂN ĐỂ ĐÁP ỨNG YÊU CẦU GDPR',
    'legalSchedule#11': 'ĐÃ NHẬN ĐƯỢC GIẤY PHÉP FSA',
    'legalSchedule#12': 'ĐÃ ĐĂNG KÝ BẢN CÁO BẠCH EU 809-2004',
    'legalSchedule#13': 'ĐÃ CẤP TOKEN BẢO MẬT CINX',

    'feedbackProject#1': 'PHẢN HỒI VỀ DỰ ÁN CỦA CHÚNG TÔI',
    'feedbackProject#2': 'Val Jerdes',
    'feedbackProject#3': 'Giám đốc sản phẩm',
    'feedbackProject#4': 'Val Jerdes, Giám đốc sản phẩm CINDX nói về các thành viên chủ chốt trong nhóm và cách chuyên môn của họ giúp phát triển dự án mà có thể thay đổi cuộc chơi tài chính một cách đáng kể',
    'feedbackProject#5': 'Denis Eskenazi',
    'feedbackProject#6': 'Giám đốc tiếp thị sản phẩm',
    'feedbackProject#7': 'Denis Eskenazi, Giám đốc tiếp thị sản phẩm CINDX giải thích lý do tham gia CINDX',
    'feedbackProject#8': 'Philip Staehelin',
    'feedbackProject#9': 'Cố vấn',
    'feedbackProject#10': 'Philip Staehelin, Cố vấn dự án CINDX, giải thích cách cuộc cách mạng tiền điện tử có thể giúp cả những nhà đầu tư thiếu kinh nghiệm và nói về bước đột phá mà dự án CINDX đã chuẩn bị cho thị trường tiền điện tử',
    'feedbackProject#11': 'Andrzej Cichowlaz',
    'feedbackProject#12': 'Chuyên gia tiếp thị',
    'feedbackProject#13': 'Andrzej Cichowlaz, Giám đốc tiếp thị CINDX cho biết lý do anh tin tưởng vào sự thành công của dự án',
    'feedbackProject#14': 'Austin Kimm',
    'feedbackProject#15': 'Austin Kimm, Cố vấn dự án CINDX nói về cách CINDX giúp việc giao dịch tiền điện tử có lợi nhuận trở nên đơn giản và thông minh',
    'feedbackProject#16': 'Amarpreet Singh',
    'feedbackProject#17': 'Amarpreet Singh, Cố vấn CINDX giải thích cách nền tảng CINDX có thể thu hẹp khoảng cách giữa nhà đầu tư và nhà giao dịch',
    'feedbackProject#18': 'Keith Teare',
    'feedbackProject#19': 'Keith Teare, Cố vấn CINDX mô tả các ưu điểm của nền tảng CINDX',
    'feedbackProject#20': 'Mansur Rasulov',
    'feedbackProject#21': 'Trưởng nhóm cộng đồng',
    'feedbackProject#22': 'Mansur Rasulov, Trưởng nhóm cộng đồng CINDX giải thích lý do anh quyết định trở thành thành viên của nhóm CINDX',
    'feedbackProject#23': 'Sadie Hutton',
    'feedbackProject#24': 'Sadie Hutton, Cố vấn CINDX giải thích cách nền tảng CINDX khác với nền tảng giao dịch tự động khác',
    'feedbackProject#25': 'Graham Doggart',
    'feedbackProject#26': 'Graham Doggart, Cố vấn CINDX nói về những điểm mạnh của nền tảng CINDX',
    'feedbackProject#27': 'Alina Vardanian',
    'feedbackProject#28': 'Giám đốc nội dung',
    'feedbackProject#29': 'Alina Vardanian, Giám đốc nội dung CINDX nói về tinh thần làm việc nhóm và lý do cô yêu thích công việc của mình',
    'feedbackProject#30': 'Bogdan Fiedur',
    'feedbackProject#31': 'Cố vấn CINDX',
    'feedbackProject#32': 'Bogdan Fiedur, Cố vấn CINDX, giải thích cách dự án CINDX khác với các dự án ICO khác',
    'feedbackProject#33': 'Jason King',
    'feedbackProject#34': 'Jason King, Giám đốc thương mại, giải thích lý do thu hút anh đến CINDX và nói về những lợi thế quan trọng của dự án',

    'mediaNews#1': 'Truyền thông',
    'mediaNews#2': 'Tin tức',
    // Media
    'mediaNews#1_1': 'CINDX Aims to Democratize the Modern Financial System',
    'mediaNews#1_2': 'Even as investors in the cryptocurrency space recognize that they are at the forefront of a new financial revolution, adoption by the general populace is yet to occur. While 3rd parties are slowly entering the space in the form of hedge funds and other investors, very few individuals seem to have taken the step to invest in cryptocurrencies on their own.',
    'mediaNews#1_3': 'CINDX Announces Plans For ICO Pre-Sale Amidst Release Of Revolutionary Crypto Trading Hub That Allows Users To Follow Expert Traders',
    'mediaNews#1_4': 'CINDX takes its business seriously with particular attention and cares to legal matters and has taken great pains to ensure that CINDX is as compliant as possible with global regulations.',
    'mediaNews#1_5': 'How CINDX is Democratizing the Modern Financial System',
    'mediaNews#1_6': 'CINDX is a new platform that is making crypto trading easier, more secure, and more accessible. With this platform, it’s possible to have your funds traded without high fees or minimum investments, with the added security and transparency of blockchain technology.',
    'mediaNews#1_7': 'CINDX is making crypto trading easier, more secure, and more accessible.',
    'mediaNews#1_8': 'Cryptocurrency and blockchain technology have been slated as powerful tools capable of fueling a global financial revolution. There are myriad opportunities to invest in the crypto space, and yet, very few individuals have undertaken the steps necessary to invest.',
    'mediaNews#1_9': 'CINDX Announces Plans Release Of Revolutionary Crypto Trading Hub',
    'mediaNews#1_10': 'The CINDX platform creates a complete ecosystem for cryptocurrency trading that is favorable to all the participants of the market and offers solutions to existing pain points.',
    'mediaNews#1_11': 'CINDX Announces Plans For ICO Pre-Sale',
    'mediaNews#1_12': 'CINDX made headlines this week with the announcement that they will be opening their ICO Pre-Sale in late August after investors interest in the ICO peaks to new levels.',
    'mediaNews#1_13': 'CINDX Will Be Opening ICO Pre-Sale in late August',
    'mediaNews#1_14': 'The CINDX Crypto trading platform has a myriad of features and benefits that haven’t been seen in other platforms to date.',
    'mediaNews#1_15': '5 Tips from CINDX Crypto Assets Management Hub: How to Avoid Being Cheated',
    'mediaNews#1_16': 'The team behind the CINDX crypto assets management hub has created a helpful set of guidelines on how not to become victims of unfair play, so you can learn what should be primarily taken into account when evaluating ICOs before investing in them.',
    'mediaNews#1_17': 'CINDX Crypto Asset Management Hub Adopts Bancor Protocol',
    'mediaNews#1_18': 'CINDX is delighted to announce that a number of new integrations with top industry players are underway, each of which will make the life of the users of the platform easier and richer. These new integrations include the decision to adopt the Bancor protocol to provide continuous liquidity for the CINDX platform.',
    // News
    'mediaNews#2_1': 'CINDX meets Ian Balina',
    'mediaNews#2_2': 'CINDX pitch to the one of the TOP10 crypto gurus in the world in the Cryptobazar event.',
    'mediaNews#2_3': 'CINDX took part in Moscow ICO Summit 2018',
    'mediaNews#2_4': 'CINDX team introduced the project to the Russian crypto community during ICO Summit event.',
    'mediaNews#2_5': 'How CINDX is ensuring legal compliance',
    'mediaNews#2_6': 'Our company is registered in Estonia. Why? The answer is simple — the authorities of Estonia have created a strong and innovative legal infrastructure...',
    'mediaNews#2_7': 'Keith Teare Co-founder of Accelerated Digital Ventures and Founding Shareholder in TechCrunch',
    'mediaNews#2_8': 'We continue to introduce CINDX advisers, find out what they...',
    'mediaNews#2_9': 'Meet world\'s first financial crypto social network',
    'mediaNews#2_10': 'Every day our team takes one more step on the way to creation and start...',
    'mediaNews#2_11': 'Denis Eskenazi CINDX Product Marketing Director',
    'mediaNews#2_12': 'We continue to tell about the CINDX team and each team member’s professional experience. Please, read about Denis Eskenazi...',
    'mediaNews#2_13': 'CINDX crypto currency exchange license',
    'mediaNews#2_14': 'Our company in Estonia has received Crypto Currency Exchange License. This allows CINDX to provide fiat-to-crypto exchange services. This licence is issued...',
    'mediaNews#2_15': 'Austin Kimm Co-founder of Crypterium & CINDS Adviser',
    'mediaNews#2_16': 'We continue to introduce CINDX advisers, find out what they are proud...',
    'mediaNews#2_17': 'The strategic meeting of the international CINDX team',
    'mediaNews#2_18': 'Every day our team takes one more step on the way to creation and start of the CINDX platform. Our work...',
    'mediaNews#2_19': 'Artur Shamalov CINDX Investment Director',
    'mediaNews#2_20': 'We continue to introduce the CINDX team. Our next article is about Artur Shamalov, a skilled...',
    'mediaNews#2_21': 'The issuance of CINX tokens',
    'mediaNews#2_22': 'The issuance of CINX tokens will be carried out according to the license of The Estonian Financial Supervisory Authority (EFSA). What is a token...',
    'mediaNews#2_23': '"Amarpreet Singh Co-Founding Member of Malta Blockchain Association & CINDX adviser"',
    'mediaNews#2_24': 'We at CINDX are incredibly proud to present our advisers, tell the world about their achievements and why they have decided to become a part of the CINDX...',
    'mediaNews#2_25': 'CINDX meets Vangoo Capital Partners Fund',
    'mediaNews#2_26': 'Today we have welcomed Kevin Shang from Vangoo Capital Partners and his colleagues in our office. We have discussed business partnership opportunities in order to attract investors from the Asian region.',
    'mediaNews#2_27': '"Mofassair Hossain CINDX Chief Marketing Officer."',
    'mediaNews#2_28': 'We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly excited about...',
    'mediaNews#2_29': 'How CINDX ensures safety for its users - KYC',
    'mediaNews#2_30': 'Every crypto enthusiast knows that a KYC procedure is necessary in order to protect investors against fraudulent actions of the third...',
    'mediaNews#2_31': 'Philip Staehelin 25 Years of Consulting and Entrepreneurial Experience',
    'mediaNews#2_32': 'We continue our regular series of articles dedicated to introducing CINDX advisers. The next item is about Philip Staehelin.',
    'mediaNews#2_33': 'CINDX meets 9coin Digital Asses Exchange',
    'mediaNews#2_34': 'The CINDX team continues active work on building relationships with various international companies. One of the most important directions of business...',
    'mediaNews#2_35': 'Jason King Interim Chief Commercial Officer',
    'mediaNews#2_36': 'The core of any great project is always people who make the unique idea come true. We would like to tell about...',
    'mediaNews#2_37': 'CINDX Presents the project during RICLUB private investors meeting',
    'mediaNews#2_38': 'CINDX has successfully passed the due diligence procedure requested by RICLub and was one of the few projects...',
    'mediaNews#2_39': 'Sofja Pevzner CINDX Personal Data Officer',
    'mediaNews#2_40': 'We continue to introduce our team and tell about what inspires our colleagues to work with CINDX. Please read about...',
    'mediaNews#2_41': 'Tyler Sanford 8+ years digital marketing in Yelp, Zenefits',
    'mediaNews#2_42': 'We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become a part of the CINDX team. In this...',
    'mediaNews#2_43': 'CINDX - Key points to observe',
    'mediaNews#2_44': 'The CINDX project is a valuable business venture with the features that are critically relevant for its participants. In this article we talk about Strengths...',
    'mediaNews#2_45': 'Airat Shayhulov CINDX Head of Quantitative Research.',
    'mediaNews#2_46': 'In “TEAM” series of the articles, we tell about people who every day participates in the creation...',
    'mediaNews#2_47': 'CINDX license of the financial consultant',
    'mediaNews#2_48': 'CINDX has obtained a termless operating licence (the FFA 000254 license) that gives the right to operate as a financial institution...',
    'mediaNews#2_49': '"Graham Doggart 20 Years of Enterprise Development and Fintech Marketing Compliance"',
    'mediaNews#2_50': 'We continue our regular series of articles dedicated to introducing CINDX advisers. The next item...',
    'mediaNews#2_51': 'CINDX continues the roadshow in China!',
    'mediaNews#2_52': 'The CINDX team is glad to announce participation as a Golden Sponsor of Borderless Blockchain Technology Summit 2018, which...',
    'mediaNews#2_53': 'Ibraghim Haniev CINDX Tech Lead',
    'mediaNews#2_54': 'Get to know more about the CINDX team! The core of any great project is always people who make the unique ideas come true...',
    'mediaNews#2_55': 'Sadie Hutton 25 Years in Senior Management and Management Consulting',
    'mediaNews#2_56': 'Like any global project, we understand the importance of professional help and advice. We continue to tell the stories of...',
    'mediaNews#2_57': 'CINDX.talk - a service that will help people become wiser in taking financial decisions',
    'mediaNews#2_58': 'The current digital-world related to the crypto industry is getting crowded with mind-charming digital solutions...',
    'mediaNews#2_59': '"Val Jerdes CINDX Product Director"',
    'mediaNews#2_60': 'We continue to introduce the CINDX team, explore each team member’s point of view, find out what our team members are particularly...',
    'mediaNews#2_61': 'Bogdan Fiedur Blockchain and cryptocurrency expert, investor, entrepreneur',
    'mediaNews#2_62': 'We continue to introduce CINDX advisers, find out what they are proud of and why they have decided to become...',
    'mediaNews#2_63': 'Welcome to CINX Token Distribution – it’s not an ICO; it’s an STO',
    'mediaNews#2_64': 'In this article, we want to make it clear why CINDX chose to hold a Security Token Offering (STO) instead of an Initial...',
    'mediaNews#2_65': 'CINDX celebrates the “AA” Rating from Top ICO List Audit!',
    'mediaNews#2_66': 'The results of CINDX’s sincerity to make meaningful changes in people’s ambitions via a unique business model just got appreciated...',
    'mediaNews#2_67': 'CINDX Weekly digest (30.07.18 - 05.08.18)',
    'mediaNews#2_68': 'The CINDX team is very excited to share the results of our work for the last week 30.07.18 - 05.08.18!',
    'mediaNews#2_69': 'Virtual Currency Wallet Services',
    'mediaNews#2_70': 'CINDX believes that being fluent in legal issues and having a clean, confident and clear legal status is of utmost importance. At the moment, CINDX is going...',
    'mediaNews#2_71': 'How CINDX Influences Crypto Trading',
    'mediaNews#2_72': 'How to master the crypto market movements and turn them in one’s favor? This is where CINDX’s effective business model comes into play. Learn more about CINDX on our Medium!',
    'mediaNews#2_73': 'CINDX Weekly digest (06.08.18 - 12.08.18)',
    'mediaNews#2_74': 'CINDX continues its regular column - Weekly Digest. We are excited to share the recent achievements of our project! Enjoy your time reading!',
    'mediaNews#2_75': 'CINDX gets 5.0 rating on TrackICO!',
    'mediaNews#2_76': 'CINDX continues getting approval from the largest and the most credible rating services. The week has hardly passed after...',
    'mediaNews#2_77': '"David Gutierrez Investment Relations Officer"',
    'mediaNews#2_78': 'CINDX is very serious about taking people on crew and proud to introduce them. This article is dedicated to David Gutierrez, CINDX Investment Relations Officer',
    'mediaNews#2_79': 'ICObench gives 4.8 to CINDX',
    'mediaNews#2_80': 'The CINDX project has already gained the highest mark of  ‘AA’ from Top ICO List and got a 5.0 rating from TrackICO. Now, we are proud to share...',
    'mediaNews#2_81': 'Dip your Toe in Crypto',
    'mediaNews#2_82': 'It is never late to change your mind. It’s no surprise that Wall Street bankers change their minds in favour of crypto. Enjoy reading CINDX review on the current market situation!',
    'mediaNews#2_83': 'Yuriy Avdeev, CEO of the CINDX project',
    'mediaNews#2_84': 'Enjoy reading what inspired Yuriy Avdeev to create a project that will help all participants of the crypto market to be profitably engaged - CINDX.',
    'mediaNews#2_85': 'Weekly digest (13.08.18 - 19.08.18)',
    'mediaNews#2_86': 'CINDX continues its regular Weekly Digest column. We are excited to share our project’s progress and the most recent achievements! We are glad to remind you that CINDX security token Pre-sale starts this Sunday. Don\'t miss!',



    'socialMedia#1': 'For more information, follow us on social media:',

    'teamAdvisersPartners#1': 'Đội ngũ hơn 50 thành viên',
    'teamAdvisersPartners#2': 'Advisers',
    'teamAdvisersPartners#3': 'Our Partners',
    // teamInfo
    'teamAdvisersPartners#4': 'Yuriy Avdeev',
    'teamAdvisersPartners#5': 'Giám đốc điều hành',
    'teamAdvisersPartners#6': '13 năm kinh nghiệm trong lĩnh vực kinh doanh',
    'teamAdvisersPartners#7': '9 liên doanh',
    'teamAdvisersPartners#8': '2 triệu đô la cho quản lý tiền điện tử',
    'teamAdvisersPartners#9': 'Val Jerdes',
    'teamAdvisersPartners#10': 'Giám đốc sản phẩm',
    'teamAdvisersPartners#11': '20 năm kinh nghiệm trong lĩnh vực kinh doanh',
    'teamAdvisersPartners#12': '3 lần rút lui thành công',
    'teamAdvisersPartners#13': 'Tăng doanh thu cho danh mục đầu tư lên 4 lần',
    'teamAdvisersPartners#14': 'Mofassair Hossain',
    'teamAdvisersPartners#15': 'Giám đốc tiếp thị',
    'teamAdvisersPartners#16': 'Nhà đầu tư và Cố vấn của hơn 15 dự án ICO',
    'teamAdvisersPartners#17': 'Cố vấn hàng đầu tại ICO Bench',
    'teamAdvisersPartners#18': 'Thành viên GBAP',
    'teamAdvisersPartners#19': 'Artur Shamalov',
    'teamAdvisersPartners#20': 'Giám đốc đầu tư',
    'teamAdvisersPartners#21': '15 năm kinh nghiệm trong lĩnh vực kinh doanh',
    'teamAdvisersPartners#22': '5000 khách hàng mixcart.ru',
    'teamAdvisersPartners#23': 'mail.ru được đầu tư ở dc-daily.ru',
    'teamAdvisersPartners#24': 'Denis Eskenazi',
    'teamAdvisersPartners#25': 'Giám đốc tiếp thị sản phẩm',
    'teamAdvisersPartners#26': '7 năm kinh nghiệm trong lĩnh vực kinh doanh',
    'teamAdvisersPartners#27': 'Đã thu hút 2 triệu đô la cho khách hàng',
    'teamAdvisersPartners#28': '10 năm kinh nghiệm trong lĩnh vực xây dựng thương hiệu',
    'teamAdvisersPartners#29': 'Ibraghim Haniev',
    'teamAdvisersPartners#30': 'Trưởng phòng công nghệ',
    'teamAdvisersPartners#31': '6 năm kinh nghiệm trong lĩnh vực kinh doanh',
    'teamAdvisersPartners#32': 'Đã phát triển hơn 200 trang web',
    'teamAdvisersPartners#33': 'Tập trung vào bảo mật thông tin',
    'teamAdvisersPartners#34': 'Airat Shaikhulov',
    'teamAdvisersPartners#35': 'Head of Quantitative Research',
    'teamAdvisersPartners#36': 'Dr of science at MSU',
    'teamAdvisersPartners#37': 'Aton-line navigator developer',
    'teamAdvisersPartners#38': 'Head of algorithmic trading',
    'teamAdvisersPartners#39': 'Sofja Pevzner',
    'teamAdvisersPartners#40': 'Giám đốc dữ liệu cá nhân',
    'teamAdvisersPartners#41': '5 năm kinh nghiệm trong lĩnh vực kinh doanh',
    'teamAdvisersPartners#42': 'Giấy phép hoạt động của văn phòng AML Estonia',
    'teamAdvisersPartners#43': '8 năm kinh nghiệm trong lĩnh vực pháp lý',
    'teamAdvisersPartners#44': 'Dave Gutierrez',
    'teamAdvisersPartners#45': 'Giám đốc quan hệ đầu tư',
    'teamAdvisersPartners#46': '5 năm kinh nghiệm trong lĩnh vực cho thuê máy bay',
    'teamAdvisersPartners#47': '3 năm kinh nghiệm trong Tổ chức đầu tư',
    'teamAdvisersPartners#48': '2 năm kinh nghiệm trong lĩnh vực đầu tư ra nước ngoài',
    'teamAdvisersPartners#49': 'Jelena Karzetskaja',
    'teamAdvisersPartners#50': 'Nhân viên tuân thủ',
    'teamAdvisersPartners#51': 'có nhiều bằng cấp về luật',
    'teamAdvisersPartners#52': 'thực hành tư pháp từ năm 1997',
    'teamAdvisersPartners#53': 'lĩnh vực pháp lý: luật quốc tế',
    'teamAdvisersPartners#54': 'Wang Dong',
    'teamAdvisersPartners#55': 'Chuyên gia trong thị trường blockchain Trung Quốc',
    'teamAdvisersPartners#56': '3 năm kinh nghiệm về php/JavaScript',
    'teamAdvisersPartners#57': '5 năm kinh nghiệm trong lĩnh vực mua phương tiện truyền thông/SEO/SMM',
    'teamAdvisersPartners#58': '2 năm kinh nghiệm về phát triển Blockchain và bán token tại Trung Quốc',
    // advisers
    'teamAdvisersPartners#59': 'Keith Teare',
    'teamAdvisersPartners#60': 'Người sáng lập kiêm Chủ tịch điều hành tại Accelerated Digital Ventures',
    'teamAdvisersPartners#61': 'Cố vấn cho ICOBox, Crypterium, EnergiMine, v.v.',
    'teamAdvisersPartners#62': 'Cổ đông sáng lập của TechCrunch',
    'teamAdvisersPartners#63': 'Tôi là Chủ tịch điều hành kiêm Chủ tịch ủy ban đầu tư tại Accelerated Digital Ventures - Công ty liên doanh của Anh.  Tôi sinh ra và lớn lên ở Anh.',
    'teamAdvisersPartners#64': 'Trước đây tôi là người sáng lập và là thành viên của Archimedes Labs ở Palo Alto, California. Tôi thích làm việc với những nhà sáng lập, các nhóm, nhà thiết kế và kỹ sư để tạo ra sản phẩm, kể chuyện và biến chúng thành hiện thực. Tôi đã thành lập hoặc đồng sáng lập nhiều công ty từ đầu những năm 1980. Một số công ty đã được bán thành công, những công ty khác đã phát hành chứng khoán lần đầu tiên ra công chúng (IPO).',
    'teamAdvisersPartners#65': 'Hai công ty của tôi là Unicorns - được định giá hơn 1 tỷ đô la. Tôi luôn tập trung vào điểm mà thay đổi đang diễn ra. Trong mạng và cơ sở dữ liệu của năm 1980. Trong giai đoạn 1994-1998, Truy cập Internet. Từ 1998-2010 - Dịch vụ Web và nội dung, Ứng dụng người dùng di động và từ năm 2017 là Blockchain.',
    'teamAdvisersPartners#66': 'Sự nghiệp và các dự án: Tech Crunch, Accelerated Digital Ventures, cScape, EasyNet, Cyberia, RealNames, Venture Network, ICOBox, Crypterium, R/Block, Fluz, EnergiMine, Archimedes Labs and CINDX',
    'teamAdvisersPartners#67': 'Austin Kimm',
    'teamAdvisersPartners#68': 'Giám đốc điều hành dịch vụ tài chính quốc tế',
    'teamAdvisersPartners#69': 'Hơn 30 năm kinh nghiệm trong ngành dịch vụ tài chính',
    'teamAdvisersPartners#70': 'Thành lập các công ty trị giá 500 triệu đô la',
    'teamAdvisersPartners#71': 'Kết quả kinh nghiệm được chứng minh với vị trí CEO trong dịch vụ tài chính với trọng tâm đặc biệt là xây dựng các doanh nghiệp bảo hiểm tại các thị trường đang phát triển nơi tôi đã xây dựng thành công các công ty với mức định giá hiện tại vượt quá 500 triệu đô la. Gần đây nhất là ở Nga (10 năm), cũng như các vai trò quản lý cấp cao trong lĩnh vực phi bảo hiểm khác, bao gồm vị trí CEO cho nền tảng việc làm bán hàng Internet lớn nhất của Nga, Workle và một loạt công ty khởi nghiệp công nghệ tài chính vị trí cấp C bao gồm Crypterium, ngân hàng tiền điện tử đầu tiên trên thế giới.',
    'teamAdvisersPartners#72': 'Gần đây nhất là ở Nga (10 năm), cũng như các vai trò quản lý cấp cao trong lĩnh vực phi bảo hiểm khác, bao gồm vị trí CEO cho nền tảng việc làm bán hàng Internet lớn nhất của Nga, Workle và một loạt công ty khởi nghiệp công nghệ tài chính vị trí cấp C bao gồm Crypterium, ngân hàng tiền điện tử đầu tiên trên thế giới.',
    'teamAdvisersPartners#73': 'Sự nghiệp và các dự án: Aviva, Commercial Union UK, Reinaissance Insurance, Kimm Health & Leisure Ltd, Workle, Crypterium, CryptoIndex, CINDX',
    'teamAdvisersPartners#74': 'Philip Staehelin',
    'teamAdvisersPartners#75': '25 năm kinh nghiệm trong lĩnh vực tư vấn và kinh doanh',
    'teamAdvisersPartners#76': 'Quản lý hoạt động kinh doanh thanh toán thay thế trị giá 500 triệu đô la',
    'teamAdvisersPartners#77': 'Tư vấn cho hơn 200 công ty khởi nghiệp từ 20 quốc gia',
    'teamAdvisersPartners#78': 'Tôi là một nhà sáng tạo và một nhà lãnh đạo pha trộn giữa sự lạc quan lan tỏa với chủ nghĩa hiện thực thực dụng. Tôi tìm thấy cơ hội mà người khác không thấy.',
    'teamAdvisersPartners#79': 'Tôi đã tận dụng khả năng "nhìn mọi thứ khác biệt" và "làm cho mọi thứ xảy ra" trong môi trường doanh nghiệp, tư vấn và khởi nghiệp - tất cả đều mang lại cho tôi những quan điểm mới rộng lớn cung cấp nguồn lực cho những ý tưởng biến đổi mới.',
    'teamAdvisersPartners#80': 'Tìm giải pháp cho những thử thách khó khăn là điều hối thúc tôi ra khỏi giường vào buổi sáng.',
    'teamAdvisersPartners#81': 'Sự nghiệp và các dự án: Roland Berger, Dot Glasses, Transparency International, StartupYard, Bethereum, Gjirafa Inc, Accenture, CINDX',
    'teamAdvisersPartners#82': 'Amarpreet Singh',
    'teamAdvisersPartners#83': 'Cố vấn cấp cao của Quỹ blockchain toàn cầu',
    'teamAdvisersPartners#84': 'Kinh nghiệm làm việc ở Microsoft, The World Bank và Airbus',
    'teamAdvisersPartners#85': 'Thành viên của các dự án Blockchain',
    'teamAdvisersPartners#86': 'Người đam mê Công nghệ/kỹ thuật số và một chuyên gia dày dạn kinh nghiệm trong ngành Công nghệ - trong hoạt động, tư vấn và đổi mới.',
    'teamAdvisersPartners#87': 'Anh là chuyên gia về Đám mây (Microsoft và AWS) được chứng nhận. Được biết đến với tính linh hoạt và linh động. Kỹ năng phân tích, chiến lược, khả năng lãnh đạo tuyệt vời và là thành viên nhóm làm việc hết sức mình.',
    'teamAdvisersPartners#88': 'Chuyên ngành: Tư vấn công nghệ, Hoạt động, Điện toán đám mây, Công nghệ tài chính, Đổi mới, ERP, Máy học (Machine Learning), Quản lý tài khoản, Phát triển đối tác, Chiến lược và phát triển kinh doanh',
    'teamAdvisersPartners#89': 'Amarpreet Singh có nền tảng giáo dục và công việc rất đa dạng.  Anh có ba bằng Thạc sĩ và đã sống/làm việc/học tập tại Ấn Độ, Singapore, Pháp, Trung Quốc, Nam Phi, Hàn Quốc, Canada.',
    'teamAdvisersPartners#90': 'Sự nghiệp và các dự án: Microsoft, The World Bank, Airbus, TokenAsia Platform, GOeurika, CINDX',
    'teamAdvisersPartners#91': 'Tyler Sanford',
    'teamAdvisersPartners#92': '8 năm kinh nghiệm trong lĩnh vực tiếp thị kỹ thuật số ở Yelp và Zenefits',
    'teamAdvisersPartners#93': 'Huy động được hơn 225 triệu đô la cho 12 ICO',
    'teamAdvisersPartners#94': 'Người sớm áp dụng blockchain',
    'teamAdvisersPartners#95': 'Việc lớn lên là Vận động viên đã cho tôi một bộ kỹ năng mà tôi có thể áp dụng vào trong nghề nghiệp và cuộc sống cá nhân.',
    'teamAdvisersPartners#96': 'Tôi đã rất may mắn khi thấy kết quả của việc nỗ lực làm việc vượt bậc, học cách ứng phó với những thăng trầm trong sự nghiệp làm việc chuyên nghiệp.',
    'teamAdvisersPartners#97': 'Tôi là một cá nhân cực kỳ năng động, luôn mong muốn tiếp tục phát triển kiến thức và tài năng trong mọi khía cạnh kinh doanh.',
    'teamAdvisersPartners#98': 'Luôn sẵn sàng đương đầu với thách thức, động lực của tôi đến từ việc vượt qua những trở ngại để đạt được mục tiêu.',
    'teamAdvisersPartners#99': 'Sự nghiệp và các dự án: IPG Holdings, DataBlockChain, TraXion by Puma Technologies, ELYSIAN, Etherinc, FTEC Foundation, CINDX',
    'teamAdvisersPartners#100': 'Philip Staehelin',
    'teamAdvisersPartners#101': '25 years of consulting and entrepreneurial experience',
    'teamAdvisersPartners#102': '$500m alternative payments business under leadership',
    'teamAdvisersPartners#103': '200+ startups from 20 countries mentored',
    'teamAdvisersPartners#104': 'I\'m an innovator and a leader who blends contagious optimism with pragmatic realism. I find opportunity where others see none.',
    'teamAdvisersPartners#105': 'I\'ve leveraged my ability to "see things differently" and "make things happen" in corporate, consulting and start-up environments - all giving me broad new perspectives that provide fodder for new transformative ideas.',
    'teamAdvisersPartners#106': 'Finding solutions to hard challenges is what gets me out of bed in the morning.',
    'teamAdvisersPartners#107': 'Career and projects: BCG, Spectacler, Transparency International, StartupYard, Bethreum, Gjirafa Inc, Direct People, CINDX',
    'teamAdvisersPartners#108': 'Senior Adviser of Global Blockchain Foundation',
    'teamAdvisersPartners#109': 'Experience in Microsoft, The World Bank and Airbus',
    'teamAdvisersPartners#110': 'Advisery Board Member of Blockchain projects',
    'teamAdvisersPartners#111': 'Technology/Digital enthusiast and a seasoned professional with years of experience in Tech industry – operations, consulting and innovation.',
    'teamAdvisersPartners#112': 'He is a certified Cloud (Microsoft and AWS) specialist. Known for versatility and flexibility. Excellent analytic, strategic, leadership skills and a team player at its best.',
    'teamAdvisersPartners#113': 'Specialties: Technology Consulting, Operations, Cloud Computing, Fintech, Innovation, ERP, Machine Learning, Account Management, Partner Development, Business Development and Strategy',
    'teamAdvisersPartners#114': 'Amarpreet Singh has a very diversified work and educational background. He holds three Masters degrees and has lived/worked/studied in India, Singapore, France, China, South Africa, Korea, Canada.',
    'teamAdvisersPartners#115': 'Career and projects: Microsoft, The World Bank, Airbus, TokenAsia Platform, GOeurika, CINDX',
    'teamAdvisersPartners#116': 'Tyler Sanford',
    'teamAdvisersPartners#117': '8 Years Digital Marketing in Yelp and Zenefits',
    'teamAdvisersPartners#118': '12 ICO’s over $225M raised',
    'teamAdvisersPartners#119': 'Early adopter of blockchain',
    'teamAdvisersPartners#120': 'Growing up as an Athlete has given me a skill set that I\'ve been able to apply to my careers and personal life.',
    'teamAdvisersPartners#121': 'I have been very fortunate to see the results of going that extra mile, while learning to deal with the highs and lows that go along with all professional careers.',
    'teamAdvisersPartners#122': 'I\'m an extremely self-motivated individual, always looking to continue my growth of knowledge and talents in all aspects of business.',
    'teamAdvisersPartners#123': 'Always up for a challenge, my motivation comes from overcoming obstacles to reach my goals',
    'teamAdvisersPartners#124': 'Career and projects: IPG Holdings, DataBlockChain, TraXion by Puma Technologies, ELYSIAN, Etherinc, FTEC Foundation,  CINDX',
    'teamAdvisersPartners#125': 'Bogdan Fiedur',
    'teamAdvisersPartners#126': 'Chuyên gia nhà đầu tư, doanh nhân về blockchain và tiền điện tử',
    'teamAdvisersPartners#127': 'Đồng sáng lập bitJob và Chủ tịch Blockchainexperts.io',
    'teamAdvisersPartners#128': 'Cố vấn ICO, Chuyên gia ICOBench',
    'teamAdvisersPartners#129': 'Bogdan Fiedur là một nhà phát triển hợp đồng thông minh, nhà đầu tư tiền điện tử, doanh nhân và Chủ tịch của http://blockchainexperts.io. Ông có hơn 20 năm kinh nghiệm về CNTT trong việc xây dựng các trang web thương mại điện tử và đã tham gia vào phát triển blockchain trong suốt 3 năm qua.',
    'teamAdvisersPartners#130': 'Ông cũng là một cố vấn ICO làm việc với 20 ICO thành công cho đến nay và tích cực tham gia vào việc cung cấp các bài thuyết trình và hội thảo về lập trình blockchain và hợp đồng thông minh trong cộng đồng tiền điện tử địa phương của ông ở Winnipeg.',
    'teamAdvisersPartners#131': 'Bogdan bây giờ tập trung vào ngành công nghiệp Blockchain và cung cấp lời khuyên, dịch vụ tư vấn và kết nối với các chuyên gia Blockchain. Gần đây nhất Bogdan đã đồng sáng lập \'Bitjob\', một nền tảng blockchain miễn phí cho sinh viên và tham gia vào một số dự án ICO với tư cách là một thành viên trong nhóm. ví dụ. PayPie.com.',
    'teamAdvisersPartners#132': 'Sự nghiệp và các dự án: US Blockchain Association, Tuurnt, Dự án Trends, BiNeuro, Zichain, Graphen Tech, CyClean, Swachhcoin, CINDX',
    'teamAdvisersPartners#133': 'Graham Doggart',
    'teamAdvisersPartners#134': '20 năm kinh nghiệm về phát triển doanh nghiệp, tuân thủ tiếp thị công nghệ tài chính ',
    'teamAdvisersPartners#135': 'Thực hiện các chiến dịch trị giá 100 triệu đô la',
    'teamAdvisersPartners#136': 'Cố vấn cho hơn 10 dự án blockchain trong năm nay',
    'teamAdvisersPartners#137': 'Tôi là chủ tịch của dự án Stealth Cryptocurrency và là người đồng sáng lập kiêm nhà chiến lược chính tại Dynamic Abundance, một Cố vấn về Blockchain và Công nghệ tài chính từ năm 2012.',
    'teamAdvisersPartners#138': 'Tôi chuyên về cấu trúc và đóng gói các dịch vụ token và đã làm việc với nhiều dự án blockchain, tiền điện tử và ICO quốc tế.',
    'teamAdvisersPartners#139': 'Trong hơn 20 năm, tôi đã cung cấp tư vấn quản lý công nghệ, tư vấn tuân thủ pháp lý và tài chính, chiến lược tăng trưởng, quan hệ nhà đầu tư, cũng như thiết kế và tác giả tài liệu.',
    'teamAdvisersPartners#140': 'Sự nghiệp và các dự án: Dự án Stealth Cryptocurrency, Dynamic Abundance, ELYSIAN, Fox Trading FX, Profede, Worltdopoly, CINDX',
    'teamAdvisersPartners#141': 'Sadie Hutton',
    'teamAdvisersPartners#142': '25 năm kinh nghiệm làm quản lý cấp cao và tư vấn quản lý',
    'teamAdvisersPartners#143': 'Huy động được hàng triệu đô la với các chiến dịch trị giá 75 triệu bảng',
    'teamAdvisersPartners#144': 'Cố vấn ICO của 8 dự án',
    'teamAdvisersPartners#145': 'Tôi là người sáng lập Dynamic Abundance, một cố vấn blockchain.',
    'teamAdvisersPartners#146': 'Tôi là người đề xuất phương pháp tiếp cận “thực hành”, chuyên gia về phân tích ICO, quản lý dự án, tất cả các khía cạnh quan trọng của quy trình ICO. Tôi có nhiều kinh nghiệm trong quản lý kinh doanh và tăng trưởng, công việc cho phép tôi giám sát một dự án từ khi hình thành đến khi ra sản phẩm. Tôi là người giải quyết vấn đề một cách tự nhiên và tôi dồn hết tâm huyết vào bất kỳ dự án mà tôi tham gia. Tôi thích chiến thắng!',
    'teamAdvisersPartners#147': 'Trong hơn 20 năm, tôi đã cung cấp tư vấn quản lý công nghệ, tư vấn tuân thủ pháp lý và tài chính, chiến lược tăng trưởng, quan hệ nhà đầu tư, cũng như thiết kế và tác giả tài liệu.',
    'teamAdvisersPartners#148': 'Sự nghiệp và các dự án: Dự án Stealth Cryptocurrency, Dynamic Abundance, ELYSIAN, Fox Trading FX, Profede, Worltdopoly, CINDX',
    'teamAdvisersPartners#149': 'Jason King',
    'teamAdvisersPartners#150': '20 năm kinh nghiệm quản lý cấp cao',
    'teamAdvisersPartners#151': 'Quản lý hoạt động kinh doanh tại 30 quốc gia',
    'teamAdvisersPartners#152': 'Điều hành P&L trị giá hơn 500 triệu đô la',
    'teamAdvisersPartners#153': 'Trong gần 20 năm, Jason King là một nhà quản lý cấp cao về công nghệ, truyền thông và viễn thông tham gia vào việc cấu trúc và môi giới các giao dịch thương mại, thương lượng thành công, xây dựng thị trường và định vị tổ chức để thành công.',
    'teamAdvisersPartners#154': 'Nhiều thách thức trong số này đã giúp tôi thành công trong vai trò tái cấu trúc và xoay vòng - dẫn đầu bằng cách xây dựng đúng người và nhóm để đạt được các mục tiêu sinh lợi nhiều nhất.',
    'teamAdvisersPartners#155': 'Jason có nhiều kinh nghiệm trong các lĩnh vực khác nhau bao gồm Quản trị kinh doanh và hoạt động, Lập kế hoạch chiến lược và tài chính, ngành công nghiệp Tiền điện tử và Blockchain.',
    'teamAdvisersPartners#156': 'Jason has either worked or has led business directly in over 30 countries and has previously held commercial P&L responsibilities in the $500M-$1B range.',
    'teamAdvisersPartners#157': 'Motti Peer',
    'teamAdvisersPartners#158': 'Đồng sáng lập Blonde 2.0, công ty PR toàn cầu từng được trao giải thưởng',
    'teamAdvisersPartners#159': 'Nhà sáng lập nhiều công ty khác nhau trong lĩnh vực an ninh và tài chính.',
    'teamAdvisersPartners#160': 'Motti là một trong những chuyên gia hàng đầu về PR cho Blockchain và Tiền điện tử, khởi nghiệp, VC.',
    'teamAdvisersPartners#161': 'Motti đã thành lập nhiều công ty khác nhau trong lĩnh vực an ninh và tài chính. Ông có nhiều năm kinh nghiệm làm quản lý tiền và quản lý quỹ đầu tư, ông có bằng Thạc sỹ Quản trị Kinh doanh về Tài chính và Tiếp thị của Đại học Manchester và bằng Cử nhân Quản trị Kinh doanh của Đại học Fairleigh Dickinson.',
    'teamAdvisersPartners#162': 'Ông là đồng Giám đốc điều hành của Blonde 2.0, một tổ chức PR toàn cầu từng đoạt giải thưởng cũng được đặt tên là "Movers and Shakers" của chương trình quốc gia khởi nghiệp trên Forbes. Là đồng CEO của Blonde 2.0, ông chịu trách nhiệm xử lý các khía cạnh Quan hệ công chúng, cùng với quản lý chiến lược và khủng hoảng.',
    'teamAdvisersPartners#163': 'Với đội ngũ 35 chuyên gia, Blonde 2.0 là một trong những lực lượng hàng đầu về PR cho Blockchain và Tiền điện tử, các công ty khởi nghiệp, VC.',
    'teamAdvisersPartners#164': 'Leonard Grayver',
    'teamAdvisersPartners#165': 'Đối tác tại Greenberg, Whitcombe & Takeuchi',
    'teamAdvisersPartners#166': 'Đại diện cho hơn 400 công ty khởi nghiệp',
    'teamAdvisersPartners#167': 'Huy động được hơn 18 triệu USD cho công ty khởi nghiệp của mình khi còn là sinh viên trường Luật  ',
    'teamAdvisersPartners#168': 'Leonard Grayver sinh ra tại Liên Xô, chuyển đến sống tại Mỹ cùng cha mẹ từ nhỏ.  Khi học ở trường Luật, Leonard đã thành lập một công ty khởi nghiệp và đã huy động thành công hơn 18 triệu đô la tiền tài trợ.',
    'teamAdvisersPartners#169': 'Công ty này đã không còn tồn tại nhưng kể từ đó Leonard đã giúp hơn 400 công ty khởi nghiệp ',
    'teamAdvisersPartners#170': 'Nhìn chung Leonard có hơn 10 năm kinh nghiệm về tài chính VC, cấu trúc quỹ, thẩm định (đại diện cho cả quỹ và LP). Lời khuyên của ông cho tất cả các doanh nhân - không chạy theo xu hướng, hãy theo đuổi sở thích của bạn.Leonard đã thiết lập các kết nối chuyên nghiệp mạnh mẽ với nhiều quỹ đầu tư mạo hiểm quốc tế khác nhau.',

    'joinTokenPreSale#1': 'Join Token Pre-Sale now!',
    'joinTokenPreSale#2': 'JOIN PRE-SALE',
    'joinTokenPreSale#3': 'TEST MVP',
    'joinTokenPreSale#4': 'Head Office',
    'joinTokenPreSale#5': 'Harjumaa, Erika 14,',
    'joinTokenPreSale#6': 'Talinn, 10416, Estonia',
    'joinTokenPreSale#7': 'Business inquiries | hello@cindx.io',
    'joinTokenPreSale#8': 'Legal Disclaimer',
    'joinTokenPreSale#9': 'Development and Marketing',
    'joinTokenPreSale#10': 'Presnenskaya naberezhnaya, 8 building 1,',
    'joinTokenPreSale#11': 'Moscow, 123112, Russia',
    'joinTokenPreSale#12': 'Careers | Join our team',
    'joinTokenPreSale#13': 'Follow us:'
}

export default vi